// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "Version",
    "tagline": "Éditeur VibeCoding de nouvelle génération",
    "checkForUpdates": "Rechercher des mises à jour",
    "releaseNotes": "Notes de version",
    "reportIssue": "Signaler un problème",
    "website": "Site web",
    "github": "GitHub",
    "wechatGroupTitle": "Scannez pour rejoindre le groupe WeChat"
  }
};

export default about;
