// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
const app = {
  "app": {
    "title": "ccgui",
    "subtitle": "Orchestrez des agents dans vos projets locaux."
  }
};

export default app;
