// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
const approval = {
  "approval": {
    "approve": "Approuver",
    "deny": "Refuser",
    "approveAll": "Tout approuver",
    "denyAll": "Tout refuser",
    "reviewRequest": "Réviser la demande",
    "approvalNeeded": "Approbation requise",
    "pendingBadge": "Approbation en attente",
    "reviewBeforeApply": "Révisez cette demande avant que le pont local ne l'exécute.",
    "inputRequested": "Saisie demandée",
    "fileChanges": "Modifications de fichiers",
    "commandExecution": "Exécution de commande",
    "genericApproval": "Approbation",
    "toolLabel": "Outil",
    "filePathLabel": "Chemin du fichier",
    "commandLabel": "Commande",
    "noteLabel": "Note",
    "none": "Aucun",
    "noExtraDetails": "Aucun détail supplémentaire.",
    "decline": "Refuser",
    "close": "Fermer",
    "approveTurnBatch": "Tout approuver dans ce lot ({{count}})",
    "allowCommandsStartWith": "Autoriser les commandes commençant par {{prefix}}",
    "alwaysAllow": "Toujours autoriser",
    "approveEnter": "Approuver (Entrée)",
    "remainingRequests": "{{count}} autre(s) demande(s) d'approbation en attente",
    "applyingApprovedFileChange": "Application de la modification de fichier approuvée",
    "resumingAfterApproval": "Approuvé. Application locale de la modification et reprise de Claude...",
    "userInputRequested": "Saisie utilisateur demandée",
    "requestOf": "Demande {{current}} sur {{total}}",
    "typeAnswerOptional": "Saisissez votre réponse (facultatif)",
    "addNotesOptional": "Ajouter des notes (facultatif)",
    "noQuestionsProvided": "Aucune question fournie.",
    "showSecret": "Afficher",
    "hideSecret": "Masquer",
    "submitFailed": "Échec de l'envoi. Veuillez réessayer.",
    "submit": "Envoyer",
    "dismiss": "Fermer",
    "dismissUserInputRequest": "Fermer cette carte de question",
    "collapseUserInputRequest": "Réduire cette carte de question sans l'ignorer",
    "collapsedUserInputRequest": "Carte de question réduite",
    "expandUserInputRequest": "Développer",
    "skipUserInputRequest": "Ignorer cette question et continuer",
    "skipAndContinue": "Ignorer cette question",
    "submitted": "Envoyé",
    "noAnswerProvided": "(Aucune réponse fournie)",
    "noDisplayableAnswer": "(Aucune réponse affichable)",
    "userInputSubmittedBanner": "[Saisie utilisateur envoyée]"
  }
};

export default approval;
