// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {
  "askUserQuestion": {
    "title": "Claude a une question pour vous",
    "progress": "Question {{current}} / {{total}}",
    "timeoutWarning": "Veuillez répondre rapidement. Cette boîte de dialogue se fermera automatiquement dans {{seconds}} secondes",
    "collapse": "Réduire",
    "expand": "Développer",
    "clickToAnswer": "Cliquez pour répondre",
    "questionTab": "Question {{index}}",
    "cancel": "Annuler",
    "back": "Retour",
    "next": "Suivant",
    "submit": "Envoyer",
    "otherOption": "Autre",
    "otherOptionDesc": "Saisir une réponse personnalisée",
    "customInputPlaceholder": "Saisissez votre réponse...",
    "multiSelectHint": "Vous pouvez sélectionner plusieurs options"
  }
};

export default askUserQuestion;
