// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
const browserAgent = {
  "browserAgent": {
    "dock": {
      "description": "Lisez d'abord les informations clés de la page, puis activez progressivement la navigation et les actions sur les éléments.",
      "disabled": "Désactivé",
      "statusDisconnected": "Déconnecté",
      "statusLoading": "Chargement",
      "statusReady": "Lisible",
      "statusClosed": "Fermé",
      "statusNeedsAttention": "Attention requise",
      "statusPreparing": "Préparation",
      "emptyUrl": "Saisissez une URL de page à ouvrir.",
      "blockedUrl": "Cette URL est bloquée par la politique de Browser Agent.",
      "opened": "Browser Agent a ouvert un onglet de navigateur.",
      "closed": "Onglet de Browser Agent fermé.",
      "busy": "En cours",
      "open": "Ouvrir",
      "enable": "Activer",
      "enabled": "Browser Agent activé.",
      "tabs": "Onglets du navigateur",
      "newTab": "Nouvel onglet de navigateur",
      "openDock": "Navigateur",
      "panelTitle": "Dock du navigateur",
      "panelKicker": "Ouvrez une page ici, puis attachez son contexte à l'IA si nécessaire.",
      "noWorkspace": "Sélectionnez un espace de travail avant d'ouvrir le Dock du navigateur.",
      "noPage": "Ouvrez une page http/https autorisée pour lancer la fenêtre de Browser Agent.",
      "rendering": "Rendu de la page dans la fenêtre de Browser Agent...",
      "windowOpened": "La page est ouverte dans une fenêtre distincte de Browser Agent.",
      "closePanel": "Fermer le Dock du navigateur",
      "close": "Fermer la session de Browser Agent",
      "info": "Afficher les détails de Browser Agent",
      "footnote": "Le MVP ne stocke pas le DOM brut, les cookies, les en-têtes ni les secrets de page."
    },
    "composer": {
      "attach": "Attacher le contexte du navigateur",
      "attaching": "Attachement du contexte du navigateur...",
      "attached": "Contexte du navigateur attaché",
      "visibleSnapshot": "Capture de la page visible du navigateur",
      "selectedElement": "Élément de page sélectionné",
      "selectedElementCount": "{{count}} éléments de page sélectionnés",
      "selectedElementFacts": "Informations de l'élément de page sélectionné",
      "selectedElementMore": "{{count}} éléments de plus",
      "selectorHint": "Sélecteur {{selector}}",
      "noRawApi": "Pas de données brutes d'API",
      "remove": "Supprimer",
      "refresh": "Actualiser le contexte du navigateur",
      "fresh": "prêt",
      "stale": "actualiser",
      "expired": "expiré",
      "degraded": "dégradé",
      "unsupported": "non pris en charge",
      "showDetails": "Afficher les détails de la capture",
      "hideDetails": "Masquer les détails",
      "countSummary": "Nombre d'éléments de la page",
      "headingCount": "Titres {{count}}",
      "linkCount": "Liens {{count}}",
      "buttonCount": "Boutons {{count}}",
      "formCount": "Formulaires {{count}}",
      "readableBlockCount": "Blocs lisibles {{count}}",
      "visualEvidenceCount": "Indices visuels {{count}}",
      "counts": "Titres {{headings}} · liens {{links}} · boutons {{buttons}} · formulaires {{forms}} · blocs lisibles {{readableBlocks}} · indices visuels {{visualEvidence}} · candidats de code {{candidates}}",
      "primaryContent": "Contenu principal",
      "readableBlocks": "Blocs lisibles {{count}}",
      "visualEvidence": "Indices visuels {{count}}",
      "codeCandidates": "Candidats de code {{count}}",
      "privacy": "{{redacted}} type(s) de rédaction, {{omitted}} type(s) de source sensible omis.",
      "noSession": "Aucune session de Browser Agent active. Ouvrez d'abord une page dans le Dock du navigateur."
    }
  }
};

export default browserAgent;
