// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {"debug":{"title":"Débogage","copyLogs":"Copier les journaux","clearLogs":"Effacer les journaux","noLogs":"Aucun journal de débogage","copy":"Copier","clear":"Effacer","noDebugEventsYet":"Aucun événement de débogage pour l'instant."}};

export default debug;
