// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
const home = {
  "home": {
    "welcome": "Bienvenue",
    "subtitle": "Que souhaitez-vous créer aujourd'hui ?",
    "latestActivity": "Conversations récentes",
    "noActivity": "Aucune conversation récente",
    "latestAgents": "Derniers agents",
    "agentReplied": "L'agent a répondu.",
    "running": "En cours",
    "loadingAgents": "Chargement des agents",
    "noAgentActivity": "Aucune activité d'agent pour le moment",
    "startThreadToSee": "Démarrez un fil pour voir ici les dernières réponses.",
    "openProject": "Ajouter un projet",
    "addWorkspace": "Ajouter un projet",
    "usageSnapshot": "Aperçu de l'utilisation",
    "refreshUsage": "Actualiser l'utilisation",
    "workspace": "Espace de travail",
    "allWorkspaces": "Tous les espaces de travail",
    "view": "Vue",
    "tokens": "Tokens",
    "time": "Temps",
    "last7Days": "7 derniers jours",
    "last30Days": "30 derniers jours",
    "cacheHitRate": "Taux de succès du cache",
    "peakDay": "Jour de pointe",
    "agentTime": "temps d'agent",
    "runs": "exécutions",
    "avg": "Moy.",
    "total": "Total",
    "day": "jour",
    "noUsageData": "Aucune donnée d'utilisation pour le moment",
    "runCodexSession": "Lancez une session Codex pour commencer à suivre l'utilisation locale.",
    "topModels": "Meilleurs modèles",
    "noModelsYet": "Aucun modèle pour le moment",
    "updated": "Mis à jour"
  }
};

export default home;
