// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {
  "layout": {
    "resizeGitHistoryPanel": "Redimensionner le panneau d'historique Git",
    "resizeSidebar": "Redimensionner la barre latérale",
    "resizeRightPanel": "Redimensionner le panneau droit",
    "resizeEditorSplit": "Redimensionner la division de l'éditeur",
    "resizeNoteCardsSplit": "Redimensionner la division conversation/notes",
    "resizePlanPanel": "Redimensionner le panneau de plan",
    "resizeRuntimeConsole": "Redimensionner la console d'exécution",
    "resizeProjects": "Redimensionner les projets"
  }
};

export default layout;
