// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
const menu = {
  "menu": {
    "about": "À propos de {{appName}}",
    "checkForUpdates": "Vérifier les mises à jour…",
    "settings": "Paramètres…",
    "file": "Fichier",
    "newAgent": "Nouvel Agent",
    "newWorktreeAgent": "Nouvel Agent Worktree",
    "newCloneAgent": "Nouvel Agent cloné",
    "newWindow": "Nouvelle fenêtre",
    "addWorkspace": "Ajouter un espace de travail…",
    "closeWindow": "Fermer la fenêtre",
    "quit": "Quitter",
    "edit": "Édition",
    "composer": "Composeur",
    "cycleModel": "Changer de modèle",
    "cycleAccessMode": "Changer de mode d'accès",
    "cycleReasoningMode": "Changer de mode de raisonnement",
    "cycleCollaborationMode": "Changer de mode de collaboration",
    "view": "Affichage",
    "toggleProjectsSidebar": "Basculer la barre latérale des projets",
    "toggleGitSidebar": "Basculer la barre latérale droite",
    "toggleGlobalSearch": "Basculer la recherche globale",
    "toggleDebugPanel": "Basculer le panneau de débogage",
    "toggleTerminal": "Basculer le terminal",
    "toggleDevtools": "Basculer les outils de développement",
    "nextAgent": "Agent suivant",
    "previousAgent": "Agent précédent",
    "nextWorkspace": "Espace de travail suivant",
    "previousWorkspace": "Espace de travail précédent",
    "toggleFullScreen": "Basculer le plein écran",
    "window": "Fenêtre",
    "minimize": "Réduire",
    "maximize": "Agrandir",
    "reloadWindow": "Recharger la fenêtre",
    "help": "Aide"
  }
};

export default menu;
