// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {
  "modes": {
    "selectMode": "Sélectionner le mode",
    "default": {
      "label": "Mode par défaut",
      "tooltip": "Comportement d'autorisation standard",
      "description": "Nécessite une confirmation manuelle pour chaque opération, adapté à une utilisation prudente"
    },
    "plan": {
      "label": "Mode plan",
      "tooltip": "Mode plan - analyse en lecture seule",
      "description": "Utilise uniquement des outils en lecture seule, génère un plan pour approbation de l'utilisateur"
    },
    "acceptEdits": {
      "label": "Mode agent",
      "tooltip": "Accepter automatiquement les modifications de fichiers",
      "description": "Accepte automatiquement la création/modification de fichiers, réduisant les étapes de confirmation"
    },
    "bypassPermissions": {
      "label": "Mode auto",
      "tooltip": "Contourner toutes les vérifications d'autorisation",
      "description": "Entièrement automatisé, contourne toutes les vérifications d'autorisation [À utiliser avec prudence]"
    }
  }
};

export default modes;
