// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Sélectionner le modèle",
    "addModel": "Ajouter un modèle",
    "refreshConfig": "Actualiser la configuration",
    "refreshingConfig": "Actualisation...",
    "refreshConfigFailed": "Échec de l'actualisation : {{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "Dernier modèle de codage agentique de pointe."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Modèle de codage agentique équilibré pour le travail quotidien."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Modèle de codage agentique rapide et abordable."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Modèle de pointe pour le codage complexe, la recherche et le travail concret."
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "Modèle performant pour le codage quotidien."
      }
    }
  }
};

export default models;
