// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {"panels":{"radar":"Radar","git":"Git","files":"Fichiers","search":"Recherche","notes":"Notes","memory":"Mémoire","projectMap":"Carte du projet","intentCanvas":"Canevas d'intention","activity":"Activité","prompts":"Prompts"}};

export default panels;
