// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {"reasoning":{"title":"Sélectionner la profondeur de raisonnement","default":"Par défaut","claudeDefault":"Par défaut","defaultDescription":"Utiliser le comportement de raisonnement par défaut du moteur","low":{"label":"Faible","description":"Réponses rapides avec raisonnement de base"},"medium":{"label":"Moyen","description":"Réflexion équilibrée (par défaut)"},"high":{"label":"Élevé","description":"Raisonnement approfondi pour les tâches complexes"},"xhigh":{"label":"Très élevé","description":"Profondeur de raisonnement très élevée"},"max":{"label":"Maximum","description":"Profondeur de raisonnement maximale"},"ultra":{"label":"Ultra","description":"Raisonnement maximal avec délégation automatique des tâches"}}};

export default reasoning;
