// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
const rewind = {
  "rewind": {
    "title": "Restaurer les fichiers à un état précédent",
    "tooltip": "Restaurer",
    "label": "Restaurer",
    "tooltipFull": "Restaurer les fichiers à leur état lors de ce message",
    "notAvailable": "La restauration n'est pas disponible dans cette session",
    "noEligibleMessage": "Aucun message utilisateur restaurable n'a été trouvé.",
    "selectPrompt": "Sélectionnez une cible de restauration (1-{{count}}) :",
    "invalidSelection": "Sélection de restauration invalide.",
    "confirmPrompt": "Créer un nouveau fil à partir de ce message ?\n\"{{preview}}\"",
    "dialogTitle": "Confirmer la restauration {{engine}}",
    "dialogDescription": "Cliquer sur restaurer maintenant ouvre d'abord uniquement cette boîte de dialogue de confirmation. La restauration ne s'exécute qu'après votre confirmation explicite.",
    "targetSectionTitle": "Point de départ de la restauration",
    "targetMessageLabel": "Cette restauration reviendra en arrière à partir de ce message utilisateur",
    "impactSectionTitle": "Ce qui sera supprimé",
    "impactUserMessages": "Messages utilisateur supprimés",
    "impactAssistantMessages": "Réponses de l'assistant supprimées",
    "impactToolCalls": "Appels d'outils supprimés",
    "impactFiles": "Fichiers concernés",
    "impactSummary": "Après confirmation, l'historique linéaire actuel reviendra en arrière à partir de ce message utilisateur. Cela inclut ce message utilisateur ainsi que toutes les réponses ultérieures de l'assistant, les appels d'outils et les modifications associées.",
    "impactFollowUp": "Si des fichiers sont listés ci-dessous, leurs modifications ont eu lieu dans le segment d'historique qui sera restauré. Vérifiez-les avant de confirmer.",
    "workspaceRestoreSectionTitle": "Stratégie des fichiers de l'espace de travail",
    "modeMessagesAndFilesLabel": "Restaurer messages + fichiers",
    "modeMessagesAndFilesHint": "Restaurer l'historique de la conversation et rétablir ensemble les modifications de fichiers associées de l'espace de travail.",
    "modeMessagesOnlyLabel": "Messages uniquement",
    "modeMessagesOnlyHint": "Restaurer uniquement l'historique de la conversation et laisser intacts les fichiers actuels de l'espace de travail.",
    "modeFilesOnlyLabel": "Fichiers uniquement",
    "modeFilesOnlyHint": "Rétablir uniquement les fichiers associés et conserver inchangé l'historique actuel de la conversation.",
    "filesSectionTitle": "Fichiers affectés",
    "filesRailTitle": "Fichiers",
    "filesEmpty": "Aucune modification de fichier n'a été détectée dans le segment d'historique restauré.",
    "filesHint": "Il s'agit d'un résumé frontend au mieux des modifications de fichiers détectées, afin que vous puissiez confirmer l'étendue de l'impact avant de continuer.",
    "diffEmpty": "Aucun aperçu de diff n'est disponible pour ce fichier. Vous pouvez toujours examiner d'autres fichiers ou ouvrir le panneau de diff principal.",
    "openDiffAction": "Ouvrir dans le panneau de diff",
    "storeAction": "Stocker les modifications",
    "storeActionBusy": "Stockage...",
    "storeUnavailable": "Le contexte de restauration actuel ne contient pas assez d'informations de session pour stocker les modifications.",
    "storeFailed": "Échec du stockage des modifications.",
    "storeRevealFailed": "Échec de l'ouverture du répertoire des modifications stockées.",
    "storeRevealAction": "Ouvrir le dossier",
    "storeSuccessTitle": "{{count}} fichier(s) stocké(s) et instantané de manifeste réutilisable généré.",
    "storeSuccessPrefix": "Enregistré dans : ",
    "confirmAction": "Confirmer la restauration",
    "confirmActionBusy": "Restauration...",
    "failed": "Échec de la restauration de la conversation."
  }
};

export default rewind;
