// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "Rechercher des fichiers, kanban, fils, messages, skills, commandes...",
    "placeholderFiltered": "Rechercher {{content}}...",
    "inputAria": "Champ de recherche",
    "scope": "Portée",
    "content": "Contenu",
    "current": "Actuel",
    "global": "Global",
    "currentWorkspace": "Espace de travail actuel",
    "allWorkspaces": "Tous les espaces de travail",
    "noResults": "Aucun résultat",
    "noResultsHint": "Essayez des mots-clés du chemin de fichier, du titre de tâche, du titre de fil, du texte de message, du nom de skill ou du nom de commande.",
    "fileIndexLoading": "Complétion de l’index des fichiers…",
    "fileIndexPartial": "L’index des fichiers est incomplet ; certains fichiers peuvent manquer.",
    "fileIndexError": "Échec du chargement de l’index. Rouvrez la recherche pour réessayer.",
    "navigate": "Naviguer",
    "open": "Ouvrir",
    "close": "Fermer",
    "projectTag": "Projet",
    "typeTag": "Type",
    "sourceTag": "Source",
    "locationTag": "Emplacement",
    "typeAction": "Action",
    "typeFile": "Fichier",
    "typeKanban": "Kanban",
    "typeThread": "Fil",
    "typeMessage": "Message",
    "typeHistory": "Historique",
    "typeSkill": "Skill",
    "typeCommand": "Commande",
    "sourceActions": "Actions de l’application",
    "sourceFiles": "Index des fichiers",
    "sourceKanban": "Données Kanban",
    "sourceThreads": "Titres des fils",
    "sourceMessages": "Contenu des messages",
    "sourceHistory": "Historique de saisie",
    "sourceSkills": "Liste des skills",
    "sourceCommands": "Liste des commandes",
    "contentAll": "Tout",
    "contentActions": "Actions",
    "contentFiles": "Fichiers",
    "contentKanban": "Kanban",
    "contentThreads": "Fils",
    "contentMessages": "Messages",
    "contentHistory": "Historique",
    "contentSkills": "Skills",
    "contentCommands": "Commandes"
  }
};

export default searchPalette;
