// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
const statusPanel = {
  "statusPanel": {
    "tabTodos": "Tâches",
    "tabSubagents": "Sous-agents",
    "tabAgents": "Agents",
    "tabCheckpoint": "Résultat",
    "tabPlan": "Plan",
    "tabCommands": "Commandes",
    "files": "fichiers",
    "emptyTodos": "Aucune tâche",
    "emptySubagents": "Aucun sous-agent",
    "emptyFileChanges": "Aucune modification de fichier",
    "emptyCommands": "Aucune commande",
    "emptyPlan": "Aucun plan",
    "planGenerating": "Génération du plan...",
    "planSwitchHint": "Passez en mode Plan pour voir le plan",
    "expand": "Développer le panneau d'état",
    "collapse": "Réduire le panneau d'état",
    "label": "État",
    "policy": {
      "title": "Audit des règles",
      "count": "{{count}} décision(s)",
      "noReason": "{{policy}} n'a fourni aucune raison",
      "verdict": {
        "running": "En cours",
        "blocked": "Bloqué",
        "needs_review": "À examiner",
        "ready": "Prêt",
        "no_contribution": "Ignoré"
      },
      "corePolicy": {
        "blocked": "Les règles principales ont détecté un risque bloquant.",
        "running": "Les règles principales ont détecté un travail en cours.",
        "ready": "Les règles principales ont jugé les preuves actuelles prêtes.",
        "needsReview": "Les règles principales nécessitent un examen."
      },
      "lintValidationPolicy": {
        "pass": "Lint réussi.",
        "fail": "Le lint a échoué et nécessite un examen.",
        "running": "Le lint est en cours.",
        "notRun": "Le lint n'a pas été exécuté."
      },
      "typecheckValidationPolicy": {
        "pass": "Vérification de types réussie.",
        "fail": "La vérification de types a échoué et nécessite un examen.",
        "running": "La vérification de types est en cours.",
        "notRun": "La vérification de types n'a pas été exécutée."
      },
      "testsValidationPolicy": {
        "pass": "Tests réussis.",
        "fail": "Les tests ont échoué et nécessitent un examen.",
        "running": "Les tests sont en cours.",
        "notRun": "Les tests n'ont pas été exécutés."
      },
      "openspecGovernancePolicy": {
        "pass": "La preuve de gouvernance OpenSpec est à jour.",
        "warn": "La preuve de gouvernance OpenSpec comporte des avertissements consultatifs.",
        "fail": "La preuve de gouvernance OpenSpec nécessite un examen.",
        "unknown": "La preuve de gouvernance OpenSpec est indisponible ou incomplète."
      },
      "largeFileGovernancePolicy": {
        "pass": "La preuve de gouvernance des gros fichiers est à jour.",
        "warn": "La preuve de gouvernance des gros fichiers comporte des avertissements consultatifs.",
        "fail": "La preuve de gouvernance des gros fichiers nécessite un examen.",
        "unknown": "La preuve de gouvernance des gros fichiers est indisponible ou incomplète."
      },
      "heavyTestNoiseGovernancePolicy": {
        "pass": "La preuve de bruit de tests lourds est à jour.",
        "warn": "La preuve de bruit de tests lourds comporte des avertissements consultatifs.",
        "fail": "La preuve de bruit de tests lourds nécessite un examen.",
        "unknown": "La preuve de bruit de tests lourds est indisponible ou incomplète."
      },
      "realtimeHarnessGovernancePolicy": {
        "pass": "La preuve du harnais temps réel est à jour.",
        "warn": "La preuve du harnais temps réel comporte des avertissements consultatifs.",
        "fail": "La preuve du harnais temps réel nécessite un examen.",
        "unknown": "La preuve du harnais temps réel est indisponible ou incomplète."
      },
      "capabilityMismatchGovernancePolicy": {
        "pass": "La preuve de capacité du moteur est à jour.",
        "warn": "La preuve de capacité du moteur comporte des avertissements consultatifs.",
        "fail": "La preuve de capacité du moteur nécessite un examen.",
        "unknown": "La preuve de capacité du moteur est indisponible ou incomplète."
      },
      "engineRuntimeGovernancePolicy": {
        "pass": "La preuve du contrat runtime du moteur est à jour.",
        "warn": "La preuve du contrat runtime du moteur comporte des avertissements consultatifs.",
        "fail": "La preuve du contrat runtime du moteur nécessite un examen.",
        "unknown": "La preuve du contrat runtime du moteur est indisponible ou incomplète."
      },
      "costBudgetGovernancePolicy": {
        "pass": "La preuve de budget de coût est à jour.",
        "warn": "La preuve de budget de coût comporte des avertissements consultatifs.",
        "fail": "La preuve de budget de coût nécessite un examen.",
        "unknown": "La preuve de budget de coût est indisponible ou incomplète."
      }
    },
    "audit": {
      "title": "Justification de la décision",
      "expandLabel": "{{count}} décision(s) de règle",
      "empty": "Aucune décision de règle",
      "reasonUnavailable": "{{policy}} n'a fourni aucune raison",
      "sourceUnavailable": "Aucune source",
      "enforcement": {
        "advisory": "Consultatif",
        "blocking": "Bloquant",
        "informational": "Info"
      }
    },
    "governance": {
      "title": "Preuve de gouvernance",
      "loading": "Lecture des preuves...",
      "empty": "Aucune preuve de gouvernance",
      "count": "{{count}} élément(s) de preuve · {{needsAction}} à traiter",
      "group": {
        "needs_action": "À traiter · {{count}}",
        "watch": "À surveiller · {{count}}",
        "passed": "Réussi · {{count}}"
      },
      "meta": {
        "source": "Source : {{source}}",
        "artifact": "Artefact : {{path}}",
        "action": "Action : résoudre {{reason}}"
      },
      "status": {
        "pass": "Réussi",
        "warn": "Avertissement",
        "fail": "Échec",
        "unknown": "Inconnu"
      }
    },
    "cost": {
      "title": "Coût / Budget",
      "session": "Session",
      "engine": "Moteur",
      "model": "Modèle",
      "sessionId": "ID de session",
      "tokens": "Tokens",
      "tokenBreakdownLabel": "Détail de l'utilisation des Tokens",
      "known": "Tarification correspondante",
      "partial": "Estimation partielle",
      "unknownModel": "Modèle inconnu",
      "pricingSource": "Source de tarification : {{source}} · {{date}}",
      "historyDegraded": "L'historique des coûts continue en mémoire car les écritures dans localStorage ont échoué.",
      "accumulated": {
        "session": "Session {{amount}}",
        "today": "Aujourd'hui {{amount}}",
        "month": "Mois {{amount}}"
      },
      "degraded": {
        "pricing-unavailable": "Aucune tarification traçable n'est disponible pour {{engine}}/{{model}} ; le coût n'est pas silencieusement considéré comme nul.",
        "pricing-stale": "La donnée de tarification est périmée ; ce coût est donné à titre indicatif uniquement.",
        "usage-unavailable": "Aucune utilisation de Tokens n'est disponible pour la projection des coûts.",
        "block-level-cost-unsupported": "Le coût au niveau du bloc n'est pas pris en charge dans cette version.",
        "unknown": "La projection des coûts est dégradée."
      }
    },
    "budget": {
      "unconfigured": "Le budget n'est pas configuré. Ceci est un guide, non l'échec d'un contrôle de budget.",
      "unsetShort": "Budget non défini",
      "barLabel": "Progression de l'utilisation du budget",
      "progress": "{{amount}} / {{limit}}",
      "threshold": {
        "info": "Seuil d'info atteint : {{amount}} / {{threshold}}",
        "warn": "Seuil d'avertissement atteint : {{amount}} / {{threshold}}",
        "block": "Seuil de blocage atteint : {{amount}} / {{threshold}}. Cette capacité ne fait que signaler ; elle n'interrompt pas le runtime."
      }
    },
    "checkpoint": {
      "verdictTitle": "Verdict",
      "evidenceTitle": "Preuves",
      "keyChangesTitle": "Changements clés",
      "keyChangesEmpty": "Aucun changement clé capturé pour l'instant",
      "fileDetailsTitle": "Détails des fichiers",
      "risksTitle": "Risques",
      "nextActionTitle": "Action suivante",
      "sections": {
        "summary": "Résumé",
        "advisorySignals": "Signaux consultatifs",
        "evidenceTrail": "Piste de preuves",
        "policyAudit": "Audit des règles",
        "suggestedActions": "Actions suggérées"
      },
      "advisory": {
        "count": "{{count}} signal(aux) consultatif(s)"
      },
      "verdict": {
        "running": "En cours",
        "blocked": "Bloqué",
        "needs_review": "À examiner",
        "ready": "Prêt"
      },
      "headline": {
        "running": "Travail en cours",
        "blocked": "Attention requise",
        "needs_review": "Examen avant de continuer",
        "ready": "Prêt à continuer",
        "idle": "En attente de preuves"
      },
      "summary": {
        "blockedValidation": "Une validation requise a échoué et doit d'abord être corrigée.",
        "blockedCommand": "La dernière commande a échoué : {{command}}. Si le système tente encore une récupération automatique, attendez que cette exécution se stabilise avant de l'arrêter.",
        "blockedSubagent": "Une tâche déléguée s'est arrêtée en état d'erreur.",
        "runningValidation": "La validation est toujours en cours. Attendez le résultat avant de décider.",
        "runningCommand": "La dernière commande est toujours en cours : {{command}}",
        "runningAgent": "Au moins un Agent est toujours en traitement.",
        "runningTodo": "Il reste des tâches actives en cours.",
        "runningProcessing": "Le tour actuel produit encore des preuves d'exécution.",
        "readyWithFiles": "{{count}} fichier(s) modifié(s) ont passé les contrôles principaux observés.",
        "ready": "Les preuves d'exécution observées semblent stabilisées.",
        "needsValidation": "Des fichiers ont changé, mais les validations principales n'ont pas encore été exécutées.",
        "manual": "Le résultat est disponible, mais il nécessite encore une revue humaine.",
        "idle": "Aucune preuve d'exécution fiable n'a encore été observée."
      },
      "evidence": {
        "filesChanged": "Fichiers modifiés",
        "filesChangedValue": "{{count}} fichiers",
        "validations": "Validations",
        "requiredValidations": "Requises",
        "optionalValidations": "Optionnelles",
        "fileChangeSummary": "+{{additions}}/-{{deletions}} sur {{count}} fichiers",
        "runMissing": "À exécuter d'abord",
        "runMissingGeneric": "Exécutez le script de validation principale du projet",
        "tasks": "Tâches",
        "agents": "Agents",
        "inProgress": "En cours",
        "settled": "Stabilisé"
      },
      "evidenceTrail": {
        "count": "{{count}} élément(s) de preuve",
        "sourceLabel": "Source",
        "snapshotLabel": "Instantané",
        "observedLabel": "Observé",
        "artifactLabel": "Artefact",
        "hashLabel": "Hachage",
        "qualifierLabel": "Qualificatif",
        "degradedLabel": "Dégradé",
        "staleLabel": "Périmé",
        "snapshotRecorded": "Instantané enregistré",
        "hashRecorded": "Vérifié",
        "policy": {
          "buildValidationPolicy": "Validation de build",
          "costBudgetGovernancePolicy": "Budget de coût",
          "heavyTestNoiseGovernancePolicy": "Bruit de tests lourds",
          "largeFileGovernancePolicy": "Gouvernance des gros fichiers",
          "lintValidationPolicy": "Validation lint",
          "openspecGovernancePolicy": "Gouvernance OpenSpec",
          "testsValidationPolicy": "Validation des tests",
          "typecheckValidationPolicy": "Validation de vérification de types"
        },
        "sourceName": {
          "build": "Build",
          "costBudget": "Budget de coût",
          "heavyTestNoise": "Bruit de tests lourds",
          "largeFile": "Gros fichier",
          "lint": "Lint",
          "openspec": "OpenSpec",
          "tests": "Tests",
          "trellis": "Trellis",
          "typecheck": "Vérification de types"
        },
        "reason": {
          "governanceArtifactMalformed": "Le fichier de preuve a un format invalide",
          "governanceEvidenceUnavailable": "La preuve ne peut pas encore être analysée",
          "pricingUnavailable": "La tarification du modèle est inconnue",
          "stale": "La preuve est périmée"
        },
        "source": "Source : {{source}}",
        "snapshot": "Instantané : {{id}}",
        "observed": "Observé : {{time}}",
        "artifact": "Artefact : {{path}}",
        "hash": "Hachage : {{hash}}",
        "qualifier": "Qualificatif : {{qualifier}}",
        "degraded": "Dégradé : {{reason}}",
        "stale": "Périmé : {{time}}"
      },
      "suggested": {
        "validation": "Optionnel : {{command}}",
        "governance": "Vérification {{source}} optionnelle : {{command}}"
      },
      "expandToDock": "Voir tous les résultats dans le dock",
      "validations": {
        "lint": "Lint",
        "typecheck": "Vérification de types",
        "tests": "Tests",
        "build": "Build",
        "custom": "Commande",
        "status": {
          "pass": "Réussi",
          "fail": "Échec",
          "running": "En cours",
          "not_run": "Non exécuté",
          "not_observed": "Non observé"
        }
      },
      "keyChanges": {
        "files": "Fichiers touchés",
        "filesSummary": "{{count}} fichiers modifiés · +{{additions}} / -{{deletions}}",
        "tasks": "Progression des tâches",
        "tasksSummary": "{{completed}}/{{total}} tâches complétées",
        "agents": "Progression des Agents",
        "agentsSummary": "{{completed}}/{{total}} Agents complétés"
      },
      "risks": {
        "none": "Aucun risque bloquant détecté.",
        "commandFailed": "Une commande s'est terminée en erreur : {{command}}",
        "validationFailed": "Au moins une validation s'est terminée en échec.",
        "validationMissing": "Les validations principales n'ont pas été exécutées après les modifications de fichiers.",
        "subagentError": "Un Agent a signalé une erreur : {{agent}}",
        "manualReview": "Le système n'a pas encore observé assez de preuves pour déclarer un résultat.",
        "severity": {
          "high": "Élevé",
          "medium": "Moyen",
          "low": "Faible"
        }
      },
      "actions": {
        "reviewDiff": "Examiner le diff",
        "openRisk": "Inspecter les risques",
        "retry": "Réessayer l'étape en échec",
        "commit": "Commiter quand c'est prêt",
        "hint": {
          "runMissingValidation": "Exécutez la validation manquante avant de décider s'il faut continuer.",
          "running": "Attendez que les preuves d'exécution actuelles se stabilisent.",
          "blocked": "Inspectez d'abord la preuve en échec ; si la récupération est encore en cours, attendez que l'exécution se stabilise avant de décider de l'arrêter.",
          "needs_review": "Ce résultat peut encore se rétablir. Attendez que l'exécution continue de se stabiliser avant d'agir.",
          "ready": "Les preuves sont stabilisées ; effectuez la vérification finale avant commit."
        }
      },
      "commitDialog": {
        "title": "Confirmation de commit",
        "path": "Chemin :",
        "files": "Fichiers à commiter",
        "toggleAllFiles": "Basculer tous les fichiers à commiter",
        "staged": "Indexé"
      }
    }
  }
};

export default statusPanel;
