// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
const tabbar = {"tabbar":{"projects":"Projets","codex":"Codex","spec":"Spec","git":"Git","log":"Journal","primaryNavigation":"Navigation principale","workspaceNavigation":"Navigation de l'espace de travail"}};

export default tabbar;
