// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
const taskCenter = {
  "taskCenter": {
    "title": "Centre de tâches",
    "eyebrow": "Exécutions d'Agent",
    "workspaceHero": "Exécution nécessitant une attention maintenant",
    "statusFilter": "Statut",
    "engineFilter": "Moteur",
    "filterAll": "Tout",
    "empty": "Aucune exécution de tâche pour l'instant",
    "summary": "{{attention}} exécution(s) sur {{total}} nécessitent une attention",
    "openedFromProjectMap": "Exécution liée ouverte depuis la file d'attente de la carte du projet. Cette page affiche le détail réel du TaskRun ; si aucune action de conversation n'apparaît, cette exécution n'est pas encore liée à une vraie session.",
    "trigger": "Déclencheur",
    "updatedAt": "Mis à jour",
    "currentStep": "Étape actuelle",
    "latestOutput": "Dernière sortie",
    "diagnostics": "Diagnostics",
    "artifacts": "Artefacts",
    "browserEvidence": "Preuves du navigateur",
    "unavailable": "Indisponible",
    "noArtifacts": "Aucun artefact pour l'instant",
    "noBrowserEvidence": "Aucune preuve de navigateur liée",
    "browserEvidenceCandidates": "candidats",
    "source": {
      "kanban": "kanban",
      "orchestration": "orchestration"
    },
    "browserEvidenceState": {
      "available": "disponible",
      "stale": "obsolète",
      "expired": "expirée",
      "degraded": "dégradée",
      "deleted": "supprimée",
      "unsupported": "non prise en charge"
    },
    "status": {
      "queued": "En file d'attente",
      "planning": "Planification",
      "running": "En cours",
      "waiting_input": "En attente de saisie",
      "blocked": "Bloquée",
      "failed": "Échec",
      "completed": "Terminée",
      "canceled": "Annulée"
    },
    "action": {
      "openConversation": "Ouvrir la conversation",
      "openOrchestrationTask": "Ouvrir la tâche d'orchestration",
      "retry": "Réessayer",
      "resume": "Reprendre",
      "cancel": "Annuler",
      "fork": "Bifurquer l'exécution"
    },
    "nextStep": {
      "monitor": "Cette exécution progresse encore. Surveillez l'étape actuelle ou annulez si nécessaire.",
      "openConversation": "Ouvrez ensuite la conversation liée pour fournir une saisie ou inspecter la dernière sortie.",
      "resume": "Cette exécution est bloquée. Reprenez-la d'abord pour continuer sur le chemin actuel.",
      "retry": "Cette exécution a échoué. Réessayez-la ou inspectez le résumé de l'échec.",
      "wait": "Aucune action n'est nécessaire pour l'instant. Laissez d'abord l'exécution se stabiliser.",
      "review": "Examinez d'abord les diagnostics et les artefacts, puis décidez de la prochaine étape.",
      "fork": "Vous pouvez bifurquer une nouvelle exécution à partir du résultat actuel pour continuer."
    }
  }
};

export default taskCenter;
