// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {"terminal":{"newTab":"Nouvel onglet","closeTab":"Fermer l'onglet","clear":"Effacer","title":"Terminal","tabTitle":"Terminal {{number}}","claudeTuiResumeTitle":"Claude TUI","sendSelectionToComposer":"Envoyer au compositeur"}};

export default terminal;
