// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {"time":{"justNow":"à l'instant","minuteAgo":"il y a {{count}} minute","minutesAgo":"il y a {{count}} minutes","hourAgo":"il y a {{count}} heure","hoursAgo":"il y a {{count}} heures","dayAgo":"il y a {{count}} jour","daysAgo":"il y a {{count}} jours","weekAgo":"il y a {{count}} semaine","weeksAgo":"il y a {{count}} semaines","now":"maintenant","shortSecondsAgo":"il y a {{value}} s","shortSecondsIn":"dans {{value}} s","shortMinutesAgo":"il y a {{value}} min","shortMinutesIn":"dans {{value}} min","shortMinutes":"{{value}} min","shortHours":"{{value}} h","shortDays":"{{value}} j","shortWeeks":"{{value}} sem","shortMonths":"{{value}} mois","shortYears":"{{value}} an"}};

export default time;
