// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
const tools = {
  "tools": {
    "readFile": "Lire le fichier",
    "readDirectory": "Lire le répertoire",
    "editFile": "Modifier le fichier",
    "writeFile": "Écrire le fichier",
    "editNotebook": "Modifier le notebook",
    "runCommand": "Exécuter la commande",
    "executeCommand": "Exécuter la commande",
    "search": "Rechercher",
    "fileMatch": "Correspondance de fichier",
    "findFile": "Trouver le fichier",
    "webFetch": "Récupération web",
    "webSearch": "Recherche web",
    "subtask": "Sous-tâche",
    "todoList": "Liste de tâches",
    "userInputRequest": "Poser une question à l'utilisateur",
    "diffCompare": "Diff",
    "result": "Résultat",
    "claudeControlResumeFailed": "Échec de la reprise",
    "claudeControlModelChanged": "Modèle modifié",
    "claudeControlInterrupted": "Interrompu",
    "claudeControlLocalOutput": "Sortie de commande locale",
    "webRequest": "Requête web",
    "batchRun": "Exécution par lot",
    "searchMatch": "Recherche/Correspondance",
    "batchReadFile": "Lecture de fichiers par lot",
    "batchSearch": "Recherche par lot",
    "batchSearchMatch": "Recherche/Correspondance par lot",
    "batchEditFile": "Modification de fichiers par lot",
    "bashGroupBatchRun": "Exécuter les commandes par lot",
    "bashGroupCompleted": "terminée",
    "bashGroupAllCompleted": "Toutes terminées",
    "bashGroupFailed": "échouée",
    "planQuickView": "Plan",
    "openFullPlanPanel": "Ouvrir le panneau Plan complet",
    "closePlanPanel": "Fermer le panneau Plan",
    "path": "Chemin",
    "lineRange": "Ligne {{start}}-{{end}}",
    "failedCount": "{{count}} échec(s)"
  }
};

export default tools;
