// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "Mise à jour",
    "checkingForUpdates": "Recherche de mises à jour...",
    "updateAvailable": "Une nouvelle version est disponible !",
    "upToDate": "Vous êtes à jour.",
    "downloading": "Téléchargement de la mise à jour…",
    "installing": "Installation de la mise à jour…",
    "restarting": "Redémarrage…",
    "failed": "Échec de la mise à jour.",
    "downloaded": "téléchargé",
    "releaseNotesTitle": "Notes de version",
    "releaseNotesLoading": "Chargement des notes de version…",
    "releaseNotesLoadFailed": "Échec du chargement des notes de version.",
    "releaseNotesEmpty": "Aucune note de version pour l'instant.",
    "releaseNotesOpenInGitHub": "Voir sur GitHub",
    "releaseNotesPrev": "Précédent",
    "releaseNotesNext": "Suivant",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "Anglais :",
    "releaseNotesChinese": "中文："
  }
};

export default update;
