// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
const usage = {"usage":{"sessionReset":"Réinitialisations de session","weeklyReset":"Réinitialisations hebdomadaires","credits":"Crédits","used":"utilisé","remaining":"restant","unlimited":"Illimité"}};

export default usage;
