// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "版本",
    "tagline": "新世代 VibeCoding 編輯器",
    "checkForUpdates": "檢查更新",
    "releaseNotes": "版本說明",
    "reportIssue": "回報問題",
    "website": "官方網站",
    "github": "GitHub",
    "wechatGroupTitle": "掃碼加入微信群"
  }
};

export default about;
