// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
const activityPanel = {
  "activityPanel": {
    "title": "工作階段活動",
    "noRoot": "目前任務",
    "selectWorkspace": "選擇一個工作區以檢視工作階段活動。",
    "emptyIdle": "尚無工作階段活動。",
    "emptyRunning": "正在等待工作階段活動…",
    "emptyCompleted": "此任務在第一階段完成，未追蹤到任何活動。",
    "eventsCount": "{{count}} 個事件",
    "sessionsCount": "{{count}} 個工作階段",
    "liveNow": "即時",
    "command": "指令",
    "commandPendingSummary": "執行指令中",
    "commandCategories": {
      "command": "指令",
      "search": "搜尋",
      "read": "讀取",
      "list": "列出",
      "git": "Git",
      "test": "測試",
      "lint": "Lint",
      "build": "建置",
      "run": "執行"
    },
    "description": "描述",
    "cwd": "工作目錄",
    "waitingForOutput": "正在等待指令輸出…",
    "waitingForReasoning": "正在等待思考內容…",
    "rootSession": "根",
    "childSession": "子",
    "relatedSessions": "相關",
    "fallbackLinking": "備用連結",
    "liveEditPreview": "即時預覽",
    "liveEditFollowLabel": "即時跟隨",
    "liveEditPreviewTooltip": "啟用後可即時開啟 AI 正在編輯的檔案。",
    "enableLiveEditPreview": "啟用即時編輯預覽",
    "disableLiveEditPreview": "停用即時編輯預覽",
    "followCoachTitle": "試試即時跟隨",
    "followCoachBody": "開啟後可跟隨 AI 正在編輯的檔案。",
    "followCoachEnable": "立即啟用",
    "followCoachDismiss": "暫時不要",
    "followNudgeTitle": "即時跟隨",
    "followNudgeErrorTitle": "啟用失敗",
    "followNudgeBody": "AI 正在編輯檔案。要啟用即時跟隨嗎？",
    "followNudgeEnable": "啟用",
    "followNudgeLater": "稍後",
    "followNudgeRetry": "重試",
    "followToggleFailed": "切換即時跟隨失敗，請再試一次。",
    "showOutput": "顯示輸出",
    "hideOutput": "隱藏輸出",
    "expandTurnGroup": "展開回合群組",
    "collapseTurnGroup": "收合回合群組",
    "turnGroup": "回合 {{index}}",
    "turnGroupFallback": "舊版活動",
    "tabs": {
      "ariaLabel": "工作階段活動分類",
      "all": "摘要",
      "command": "指令",
      "file": "產物",
      "task": "任務",
      "subagent": "子 Agent",
      "explore": "探索",
      "reasoning": "思考"
    },
    "artifacts": {
      "kicker": "回合產物",
      "title": "產物",
      "fileCount": "{{count}} 個檔案",
      "fileCount_other": "{{count}} 個檔案",
      "turnSemanticTitle": "回合意涵",
      "tabsAriaLabel": "回合產物檢視",
      "tabs": {
        "artifacts": "產物",
        "semantic": "語意差異"
      }
    },
    "radar": {
      "modeCurrentTask": "目前任務",
      "modeWorkspaceRadar": "工作區雷達",
      "runningSection": "執行中（{{count}}）",
      "recentSection": "最近完成（{{count}}）",
      "emptyRunning": "沒有執行中的工作階段。",
      "emptyRecent": "沒有最近完成的工作階段。",
      "openSession": "開啟",
      "runningCountAria": "{{count}} 個執行中的工作階段",
      "recentCountAria": "{{count}} 個最近的工作階段",
      "startedAt": "開始：",
      "endedAt": "結束：",
      "totalDuration": "耗時：",
      "timeUnknown": "--:--:--",
      "durationUnknown": "--",
      "unreadBadge": "NEW",
      "unreadMark": "未讀",
      "readMark": "已讀",
      "deleteHistoryEntry": "刪除 {{name}}",
      "deleteDateGroupEntries": "刪除 {{date}} 的全部 {{count}} 筆項目"
    },
    "status": {
      "running": "執行中",
      "completed": "已完成",
      "failed": "失敗",
      "pending": "等待中"
    }
  }
};

export default activityPanel;
