// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
const agentOrchestration = {
  "agentOrchestration": {
    "title": "專案地圖工作佇列",
    "eyebrow": "專案地圖佇列",
    "summary": "{{workspace}} · {{total}} 項工作 · {{providers}} 個可用來源",
    "workspaceUnknown": "未知工作區",
    "loadingTitle": "正在載入編排檢視",
    "loadingDescription": "正在彙整專案地圖候選項、既有任務草稿與 TaskRun 情境。",
    "emptyTitle": "此工作區尚無編排任務",
    "emptyDescription": "此檢視目前僅顯示既有的編排情境與執行狀態。任務建立入口將於任務模組重新設計後回歸。",
    "degradedTitle": "部分來源已降級",
    "unavailable": "無法使用",
    "noRefs": "沒有來源參照",
    "noEvidenceRefs": "沒有證據參照",
    "noRisks": "沒有風險標記",
    "status": {
      "candidate": "候選",
      "planned": "已規劃",
      "ready": "就緒",
      "running": "執行中",
      "waiting_input": "等待輸入",
      "blocked": "已阻擋",
      "review_needed": "需審查",
      "completed": "已完成",
      "archived": "已封存"
    },
    "queueStatus": {
      "todo": "待辦",
      "queued": "已排入佇列",
      "running": "執行中",
      "failed": "失敗",
      "dispatched": "已派發",
      "review": "需審查",
      "done": "已完成",
      "archived": "已封存"
    },
    "action": {
      "backToProjectMap": "返回專案地圖"
    },
    "manual": {
      "open": "新增手動任務",
      "eyebrow": "手動來源",
      "title": "建立手動任務",
      "description": "手動任務不會憑空產生已驗證的證據。派發前請先補上範圍與驗收條件。",
      "fieldTitle": "標題",
      "fieldScope": "範圍",
      "fieldAcceptance": "驗收條件",
      "fieldPrompt": "提示詞",
      "cancel": "取消",
      "create": "建立任務"
    },
    "actions": {
      "label": "任務動作",
      "openSource": "開啟來源",
      "openSourceLabel": "開啟 {{title}} 的來源",
      "openRun": "在任務中心檢視執行",
      "openRunLabel": "在任務中心檢視 {{title}} 的關聯執行",
      "openSession": "開啟工作階段",
      "openSessionLabel": "開啟 {{title}} 的關聯工作階段",
      "cancelQueuedRun": "取消派發",
      "archive": "封存",
      "writeBack": "回寫來源提供者",
      "writeBackDisabled": "回寫來源提供者屬於未來的動作：必須經過獨立的確認流程。此處不會修改 OpenSpec、Trellis、spec-kit 或 Agent 規則檔案。"
    },
    "queue": {
      "taskLabel": "{{title}}，狀態 {{status}}，來源提供者 {{provider}}，{{risks}} 個風險標記",
      "riskCount": "{{count}} 個風險標記",
      "riskOverflow": "+{{count}} 項風險"
    },
    "dispatch": {
      "open": "傳送至任務中心",
      "openLabel": "將 {{title}} 傳送至任務中心",
      "eyebrow": "派發關卡",
      "title": "派發確認",
      "description": "請先設定引擎、工作區、執行緒策略與驗收範圍。確認派發後才會建立 TaskRun。",
      "engine": "引擎",
      "model": "模型",
      "defaultModel": "使用預設模型",
      "workspace": "工作區",
      "status": "狀態",
      "threadStrategy": "執行緒策略",
      "promptSummary": "提示詞摘要",
      "acceptance": "驗收條件",
      "sources": "來源",
      "disabled": "執行功能尚未接通：此處僅預覽派發參數，不會建立 TaskRun。",
      "cancel": "取消",
      "confirm": "確認派發"
    },
    "review": {
      "label": "審查動作",
      "open": "審查",
      "openLabel": "審查 {{title}}",
      "title": "審查關卡",
      "description": "關聯的執行已完成。在接受、要求變更或建立後續任務前，請先審查結果。",
      "accept": "接受結果",
      "requestChanges": "要求變更",
      "createFollowUp": "建立後續任務",
      "missingRunTitle": "缺少執行結果；無法審查",
      "missingRunDescription": "此任務已標記為待審查，但沒有關聯的執行或工作階段。請先重新派發再進行審查。",
      "feedback": {
        "accepted": "結果已接受，任務完成。",
        "changesRequested": "已要求變更，任務已移回工作佇列。",
        "followUpCreated": "已建立並選取後續任務。"
      }
    },
    "filters": {
      "label": "任務佇列篩選條件",
      "provider": "來源提供者",
      "status": "工作狀態",
      "engine": "引擎",
      "workspace": "工作區",
      "sourceKind": "來源類型",
      "risk": "風險",
      "allProviders": "所有來源提供者",
      "allStatuses": "所有工作狀態",
      "allEngines": "所有引擎",
      "allWorkspaces": "所有工作區",
      "allSourceKinds": "所有來源類型",
      "allRisks": "所有風險",
      "noEngine": "無引擎",
      "reset": "重設",
      "visibleSummary": "顯示 {{visible}} / {{total}}",
      "emptyTitle": "沒有符合目前篩選條件的任務",
      "emptyDescription": "請調整來源提供者、狀態、引擎、工作區、來源類型或風險篩選條件以繼續。"
    },
    "reviewState": {
      "not_started": "尚未開始",
      "needs_review": "需審查",
      "accepted": "已接受",
      "changes_requested": "已要求變更"
    },
    "threadStrategy": {
      "new_thread": "新執行緒",
      "reuse_active_thread": "重用使用中的執行緒",
      "choose_thread": "選擇執行緒"
    },
    "detail": {
      "scope": "範圍",
      "acceptance": "驗收條件",
      "createdAt": "建立時間",
      "updatedAt": "更新時間",
      "providerSources": "來源提供者",
      "evidence": "證據",
      "evidenceCount": "{{count}} 個證據參照",
      "risks": "風險",
      "links": "執行連結",
      "runManagement": "執行／工作階段管理",
      "linkCountsLabel": "連結數量",
      "linkCounts": "{{runs}} 次執行 · {{sessions}} 個工作階段",
      "linkedRuns": "關聯執行",
      "linkedSessions": "關聯工作階段",
      "noLinkedRuns": "沒有關聯執行",
      "noLinkedSessions": "沒有關聯工作階段",
      "missingLinkedRun": "沒有關聯執行，已移回待辦。",
      "linkedRunMissing": "找不到執行紀錄",
      "runEngine": "引擎",
      "runUpdatedAt": "更新時間",
      "runCurrentStep": "目前步驟",
      "runLatestOutput": "最新輸出",
      "activity": "活動",
      "reviewState": "審查狀態",
      "threadStrategy": "執行緒策略",
      "preferredEngine": "偏好引擎",
      "preferredModel": "偏好模型",
      "parentTask": "上層任務",
      "selectionPreservedTitle": "已保留目前節點",
      "selectionPreservedDescription": "任務狀態已變更，但詳細資訊面板仍停留在您剛操作的節點上。"
    }
  }
};

export default agentOrchestration;
