// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
const app = {"app":{"title":"ccgui","subtitle":"在你的本機專案間編排 Agent。"}};

export default app;
