// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
const approval = {
  "approval": {
    "approve": "核准",
    "deny": "拒絕",
    "approveAll": "全部核准",
    "denyAll": "全部拒絕",
    "reviewRequest": "審查請求",
    "approvalNeeded": "需要核准",
    "pendingBadge": "等待核准",
    "reviewBeforeApply": "在本機橋接執行前，請先審查此請求。",
    "inputRequested": "需要輸入",
    "fileChanges": "檔案變更",
    "commandExecution": "指令執行",
    "genericApproval": "核准",
    "toolLabel": "工具",
    "filePathLabel": "檔案路徑",
    "commandLabel": "指令",
    "noteLabel": "備註",
    "none": "無",
    "noExtraDetails": "沒有其他細節。",
    "decline": "拒絕",
    "close": "關閉",
    "approveTurnBatch": "核准此批次中的全部（{{count}}）",
    "allowCommandsStartWith": "允許以 {{prefix}} 開頭的指令",
    "alwaysAllow": "一律允許",
    "approveEnter": "核准（Enter）",
    "remainingRequests": "還有 {{count}} 個核准請求等待中",
    "applyingApprovedFileChange": "正在套用已核准的檔案變更",
    "resumingAfterApproval": "已核准。正在本機套用變更並繼續 Claude…",
    "userInputRequested": "需要使用者輸入",
    "requestOf": "第 {{current}} / {{total}} 個請求",
    "typeAnswerOptional": "輸入你的回答（選填）",
    "addNotesOptional": "新增備註（選填）",
    "noQuestionsProvided": "沒有提供問題。",
    "showSecret": "顯示",
    "hideSecret": "隱藏",
    "submitFailed": "送出失敗，請重試。",
    "submit": "送出",
    "dismiss": "關閉",
    "dismissUserInputRequest": "關閉此問題卡片",
    "collapseUserInputRequest": "收合此問題卡片而不略過",
    "collapsedUserInputRequest": "已收合的問題卡片",
    "expandUserInputRequest": "展開",
    "skipUserInputRequest": "略過此問題並繼續",
    "skipAndContinue": "略過此問題",
    "submitted": "已送出",
    "noAnswerProvided": "（未提供回答）",
    "noDisplayableAnswer": "（沒有可顯示的回答）",
    "userInputSubmittedBanner": "[已送出使用者輸入]"
  }
};

export default approval;
