// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {"askUserQuestion":{"title":"Claude 有一個問題要問你","progress":"問題 {{current}} / {{total}}","timeoutWarning":"請盡快回覆。此對話將在 {{seconds}} 秒後自動關閉","collapse":"收合","expand":"展開","clickToAnswer":"點擊以回答","questionTab":"問題 {{index}}","cancel":"取消","back":"上一步","next":"下一步","submit":"送出","otherOption":"其他","otherOptionDesc":"輸入自訂回答","customInputPlaceholder":"輸入你的回答…","multiSelectHint":"你可以選取多個選項"}};

export default askUserQuestion;
