// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
const claudeModes = {"claudeModes":{"default":{"label":"建議模式（預覽）","tooltip":"Claude Code 預覽核准模式。在完整核准橋接完成前，部分流程仍可能降級。","description":"現以預覽形式提供，用於驗證 Claude 的預設權限流程。若遇到降級路徑，介面應引導使用者回到計畫模式。"},"plan":{"label":"計畫模式","tooltip":"Claude Code 唯讀分析模式。","description":"在採取行動前，使用唯讀工具進行分析與規劃。"},"acceptEdits":{"label":"自動編輯","tooltip":"Claude Code 自動編輯模式。目前推出階段尚未啟用。","description":"在 Claude 核可語意驗證完成前，此模式維持不可用。"},"bypassPermissions":{"label":"全自動","tooltip":"略過權限檢查的 Claude Code 模式。","description":"免核可即可寫入檔案並執行指令。請謹慎使用。"}}};

export default claudeModes;
