// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
const codexModes = {"codexModes":{"default":{"label":"建議（需核可）","tooltip":"Codex approval_policy=untrusted－編輯檔案或執行 shell 指令前會先詢問。","description":"最安全的選項。每次寫入或指令都需要你核可。"},"plan":{"label":"規劃模式","tooltip":"規劃模式－唯讀分析","description":"僅使用唯讀工具，產生計畫供使用者核可"},"acceptEdits":{"label":"自動編輯","tooltip":"Codex approval_policy=auto-edit－自動套用檔案修補，執行 shell 指令前仍會詢問。","description":"透過 apply_patch 自動建立與編輯檔案，同時保留指令核可。"},"bypassPermissions":{"label":"全自動","tooltip":"Codex approval_policy=never－執行指令並寫入檔案時不詢問（工作區沙箱仍會強制執行）。","description":"免核可模式。Codex 會立即執行編輯與 shell 指令。"}}};

export default codexModes;
