// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {"debug":{"title":"偵錯","copyLogs":"複製記錄","clearLogs":"清除記錄","noLogs":"沒有偵錯記錄","copy":"複製","clear":"清除","noDebugEventsYet":"尚無偵錯事件。"}};

export default debug;
