// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/engineTaskOutput.ts; keys mirror the English source.
const engineTaskOutput = {"engineTaskOutput":{"label":"任務輸出檢視器","inspect":"檢視輸出","close":"關閉任務輸出","engine":"{{engine}} 任務","identity":"身分","telemetry":"Token","recentOutput":"近期輸出","refresh":"重新整理","refreshing":"重新整理中","pending":"待處理","telemetryPending":"尚無可信的 Token 資料","outputUnavailable":"目前尚無可用的輸出。任務可能仍在執行，或此引擎不提供即時任務輸出。","artifactLive":"已從任務輸出檔案更新。","artifactTruncated":"輸出較長；僅顯示最新的片段。","artifactUnavailable":"即時輸出無法使用。保留目前的快照。","status":{"running":"執行中","completed":"已完成","error":"錯誤","unavailable":"無法使用"},"tokens":{"input":"輸入","cached":"已快取","output":"輸出","total":"總計"},"telemetryStatus":{"live":"即時資料","estimated":"估算資料","pending":"等待資料","unavailable":"資料無法使用"}}};

export default engineTaskOutput;
