// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "連線失敗",
    "requestFailed": "請求失敗",
    "unexpectedError": "發生非預期的錯誤",
    "sessionExpired": "工作階段已過期",
    "rateLimited": "已達速率限制。請稍後再試。",
    "networkError": "網路錯誤。請檢查你的連線。",
    "failedToAddWorkspace": "無法新增工作區。",
    "failedToOpenNewWindow": "無法開啟新視窗。",
    "failedToCreateSession": "無法建立工作階段。",
    "failedToCreateSessionNoThreadId": "執行環境未傳回新的工作階段 id。",
    "failedToCreateSessionRuntimeRecovering": "建立此工作階段時執行環境正在重新啟動。應用程式已自動重試一次。請重新連線工作區後再試一次。",
    "reconnectAndRetryCreateSession": "重新連線並重試建立",
    "reconnectingAndRetryingCreateSession": "正在重新連線並重試建立…",
    "runtimeRecovered": "執行環境已復原。",
    "retryingCreateSessionAfterRecovery": "正在重試建立工作階段…",
    "cliNotFound": "找不到 Claude Code CLI 或 Codex CLI。請安裝其中之一。",
    "cliNotFoundHint": "安裝 Claude Code：npm install -g @anthropic-ai/claude-code\n安裝 Codex：npm install -g @openai/codex",
    "codexCliNotFound": "找不到 Codex CLI。請安裝 Codex 並確認 `codex` 已加入你的 PATH。",
    "couldntOpenWorkspace": "無法開啟工作區",
    "dismissError": "關閉錯誤"
  }
};

export default errors;
