// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
const home = {"home":{"welcome":"歡迎","subtitle":"今天想打造什麼？","latestActivity":"近期對話","noActivity":"沒有近期對話","latestAgents":"最新 Agent","agentReplied":"Agent 已回覆。","running":"執行中","loadingAgents":"正在載入 Agent","noAgentActivity":"尚無 Agent 活動","startThreadToSee":"開啟一個對話串，最新回應會顯示在這裡。","openProject":"新增專案","addWorkspace":"新增專案","usageSnapshot":"用量快照","refreshUsage":"重新整理用量","workspace":"工作區","allWorkspaces":"所有工作區","view":"檢視","tokens":"Token","time":"時間","last7Days":"最近 7 天","last30Days":"最近 30 天","cacheHitRate":"快取命中率","peakDay":"尖峰日","agentTime":"Agent 時間","runs":"次執行","avg":"平均","total":"總計","day":"天","noUsageData":"尚無用量資料","runCodexSession":"執行一個 Codex 工作階段以開始追蹤本機用量。","topModels":"熱門模型","noModelsYet":"尚無模型","updated":"已更新"}};

export default home;
