// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
const kanban = {
  "kanban": {
    "mode": {
      "chat": "聊天模式",
      "chatShort": "聊天",
      "kanban": "看板模式",
      "kanbanShort": "看板"
    },
    "columns": {
      "todo": "待辦",
      "inprogress": "進行中",
      "testing": "審查中",
      "done": "已完成"
    },
    "projects": {
      "title": "專案",
      "subtitle": "選取一個工作區以管理任務",
      "empty": "尚無工作區",
      "emptyHint": "新增一個工作區以開始管理任務",
      "taskCount": "{{count}} 個任務"
    },
    "board": {
      "back": "返回",
      "backActions": "返回操作",
      "backToPanels": "返回面板",
      "backToChat": "返回聊天",
      "addTask": "新增",
      "searchPlaceholder": "搜尋…",
      "toggleGitPanel": "Git 變更"
    },
    "task": {
      "createTitle": "建立任務",
      "create": "建立",
      "titlePlaceholder": "輸入任務標題",
      "descPlaceholder": "描述任務…",
      "notInstalled": "未安裝",
      "noModels": "沒有模型",
      "addImage": "新增圖片",
      "start": "開始",
      "menu": "任務選單",
      "edit": "編輯",
      "editTitle": "編輯任務",
      "update": "更新",
      "dragToStart": "請將此任務拖曳至「進行中」以開始",
      "delete": "刪除",
      "cancelSchedule": "取消排程",
      "pauseSchedule": "暫停排程",
      "resumeSchedule": "恢復排程",
      "blockTask": "標記為封鎖",
      "linked": "已連結",
      "processing": "處理中…",
      "generateTitle": "產生標題",
      "generateTitleFailed": "產生標題失敗",
      "generateTitleTimeout": "產生標題逾時，請重試",
      "schedule": {
        "modeLabel": "排程",
        "manual": "手動",
        "once": "執行一次",
        "recurring": "週期性",
        "runAt": "執行時間",
        "every": "每",
        "minutes": "分鐘",
        "hours": "小時",
        "days": "天",
        "weeks": "週",
        "executionModeLabel": "執行方式",
        "sameThread": "在同一對話串中執行",
        "newThread": "每次執行都開啟新對話串",
        "maxRounds": "回合上限（1-50）",
        "resultPassing": "結果傳遞",
        "passResult": "傳遞前一次結果",
        "blockResult": "不傳遞結果",
        "onceBadge": "一次性",
        "recurringBadge": "已排程",
        "schedulerBadge": "排程器",
        "runningBadge": "執行中",
        "scheduledBadge": "已排程",
        "onceOverdueBadge": "錯過執行"
      },
      "chain": {
        "upstreamLabel": "上游任務",
        "none": "無",
        "badge": "已串接"
      },
      "group": {
        "recurring": "週期性執行群組",
        "chain": "連結任務群組",
        "count": "{{count}} 個項目",
        "bulkComplete": "批次完成",
        "bulkCompleteConfirm": "確定要批次完成此群組中的 {{count}} 個任務嗎？",
        "loadMore": "再載入 {{count}} 個",
        "remaining": "剩餘 {{count}} 個"
      },
      "snapshot": {
        "badge": "快照就緒"
      },
      "latestRunSummary": {
        "ariaLabel": "最新執行摘要"
      },
      "blocked": "已封鎖：{{reason}}",
      "detail": {
        "runAt": "執行時間 {{time}}",
        "every": "每 {{interval}} {{unit}}",
        "countdown": "倒數 {{time}}",
        "sameThread": "同一對話串",
        "newThread": "新對話串",
        "runIndex": "第 {{index}} 次執行",
        "headCode": "#{{code}}",
        "groupCode": "#{{code}}",
        "chainOrder": "步驟 #{{order}}",
        "rounds": "回合 {{current}}/{{max}}",
        "resultPassed": "傳遞結果",
        "resultBlocked": "不傳遞結果",
        "timeRange": "{{start}} - {{end}}",
        "startedAt": "開始於 {{time}}",
        "finishedAt": "結束於 {{time}}"
      },
      "blockedReason": {
        "nonReentrant": "任務已在執行中",
        "missedOnceWindow": "錯過一次性執行時段",
        "invalidRecurringRule": "無效的週期性規則",
        "skippedMissedRecurringWindows": "已略過錯過的週期性時段",
        "maxRoundsReached": "已達回合上限並自動完成",
        "missingUpstreamSnapshot": "缺少上游結果快照",
        "downstreamNotTodo": "下游任務不是待辦狀態",
        "downstreamHasSchedule": "下游任務有獨立排程",
        "chainRequiresHeadTrigger": "串接任務必須由頭部任務觸發",
        "chainRequiresHeadTriggerWithOrder": "串接任務必須由頭部步驟（#{{headOrder}}）自動觸發；目前步驟為 #{{currentOrder}}",
        "chainRequiresExecutionCompletion": "串接任務必須先完成「進行中」執行，才能進入審查／完成",
        "chainCompletedCannotBackToTodo": "已完成的串接任務無法移回待辦",
        "chainCompletedStatusLocked": "已完成的串接任務無法移至其他狀態",
        "scheduledTriggerBlocked": "任務執行期間略過週期性觸發",
        "dragIntoChainGroupBlocked": "未連結的任務無法拖曳進已連結的群組",
        "manualBlocked": "手動封鎖",
        "manualCancelled": "已手動取消排程"
      },
      "validation": {
        "generic": "任務設定無效。請調整後重試。",
        "scheduleTodoOnly": "只有待辦任務可以設定排程。",
        "invalidOnceTime": "請選取有效的排程時間。",
        "invalidRecurringInterval": "週期性間隔必須大於 0。",
        "invalidRecurringRule": "無法計算下一次週期性時間。",
        "chainRequiresTodoTask": "只有待辦任務可以加入任務鏈。",
        "downstreamCannotBeScheduled": "下游任務不能保有獨立排程。",
        "chainSelfCycle": "任務不能以自身作為上游。",
        "chainPreviousNotFound": "找不到所選的上游任務。",
        "chainRequiresTodoUpstream": "上游任務必須維持待辦狀態。",
        "chainMultiDownstream": "所選的上游任務已有一個下游任務。",
        "chainCycleDetected": "偵測到任務鏈循環。請改選其他上游任務。"
      }
    },
    "conversation": {
      "close": "關閉"
    },
    "panel": {
      "subtitle": "選取一個面板以管理任務",
      "create": "新增面板",
      "namePlaceholder": "輸入面板名稱",
      "empty": "尚無面板。建立一個以開始使用。",
      "menu": "面板選單",
      "rename": "重新命名",
      "delete": "刪除",
      "deleteConfirmTitle": "確認刪除",
      "deleteConfirmMessage": "確定要刪除面板「{{name}}」嗎？此面板中的 {{count}} 個任務也會一併刪除。此操作無法復原。",
      "cancel": "取消",
      "confirmDelete": "刪除",
      "searchPanels": "搜尋面板…",
      "noPanelsFound": "找不到面板"
    },
    "workspace": {
      "searchWorkspaces": "搜尋工作區…",
      "noWorkspacesFound": "找不到工作區"
    },
    "composer": {
      "relatedPanels": "已連結的專案面板",
      "openPanel": "開啟已連結的面板",
      "empty": "沒有已連結的面板",
      "count": "{{count}} 個面板",
      "clear": "清除選取",
      "more": "更多",
      "collapse": "收合",
      "link": "連結",
      "contextModeLabel": "情境",
      "contextModeNew": "新對話",
      "contextModeInherit": "沿用目前"
    }
  }
};

export default kanban;
