// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {"layout":{"resizeGitHistoryPanel":"調整 Git 歷史面板大小","resizeSidebar":"調整側邊欄大小","resizeRightPanel":"調整右側面板大小","resizeEditorSplit":"調整編輯器分割大小","resizeNoteCardsSplit":"調整對話與筆記分割大小","resizePlanPanel":"調整計畫面板大小","resizeRuntimeConsole":"調整執行主控台大小","resizeProjects":"調整專案大小"}};

export default layout;
