// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
const menu = {
  "menu": {
    "about": "關於 {{appName}}",
    "checkForUpdates": "檢查更新…",
    "settings": "設定…",
    "file": "檔案",
    "newAgent": "新增 Agent",
    "newWorktreeAgent": "新增 Worktree Agent",
    "newCloneAgent": "新增複製 Agent",
    "newWindow": "新增視窗",
    "addWorkspace": "新增工作區…",
    "closeWindow": "關閉視窗",
    "quit": "結束",
    "edit": "編輯",
    "composer": "撰寫器",
    "cycleModel": "循環切換模型",
    "cycleAccessMode": "循環切換存取模式",
    "cycleReasoningMode": "循環切換推理模式",
    "cycleCollaborationMode": "循環切換協作模式",
    "view": "檢視",
    "toggleProjectsSidebar": "切換專案側邊欄",
    "toggleGitSidebar": "切換右側側邊欄",
    "toggleGlobalSearch": "切換全域搜尋",
    "toggleDebugPanel": "切換除錯面板",
    "toggleTerminal": "切換終端機",
    "toggleDevtools": "切換開發者工具",
    "nextAgent": "下一個 Agent",
    "previousAgent": "上一個 Agent",
    "nextWorkspace": "下一個工作區",
    "previousWorkspace": "上一個工作區",
    "toggleFullScreen": "切換全螢幕",
    "window": "視窗",
    "minimize": "最小化",
    "maximize": "最大化",
    "reloadWindow": "重新載入視窗",
    "help": "說明"
  }
};

export default menu;
