// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "選擇模型",
    "addModel": "新增模型",
    "refreshConfig": "重新整理設定",
    "refreshingConfig": "重新整理中…",
    "refreshConfigFailed": "重新整理失敗：{{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "最新的前沿代理式編碼模型。"
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "適合日常工作的均衡代理式編碼模型。"
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "快速又實惠的代理式編碼模型。"
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "適用於複雜編碼、研究與實際工作的前沿模型。"
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "適合日常編碼的強大模型。"
      },
      "gpt54mini": {
        "label": "gpt-5.4-mini",
        "description": "適合較簡單編碼任務的小型、快速且具成本效益的模型。"
      },
      "gpt53codex": {
        "label": "gpt-5.3-codex",
        "description": "針對編碼最佳化的模型。"
      },
      "gpt53codexSpark": {
        "label": "gpt-5.3-codex-spark",
        "description": "超快速編碼模型。"
      },
      "gpt52": {
        "label": "gpt-5.2",
        "description": "針對專業工作與長時間執行的代理最佳化。"
      }
    }
  }
};

export default models;
