// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {"modes":{"selectMode":"選擇模式","default":{"label":"預設模式","tooltip":"標準權限行為","description":"每項操作都需手動確認，適合謹慎使用"},"plan":{"label":"計畫模式","tooltip":"計畫模式 - 唯讀分析","description":"僅使用唯讀工具，產生計畫供使用者核准"},"acceptEdits":{"label":"Agent 模式","tooltip":"自動接受檔案編輯","description":"自動接受檔案建立/編輯，減少確認步驟"},"bypassPermissions":{"label":"自動模式","tooltip":"略過所有權限檢查","description":"完全自動化，略過所有權限檢查〔請謹慎使用〕"}}};

export default modes;
