// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "選擇模型",
    "addModel": "新增模型",
    "refreshConfig": "重新整理設定",
    "refreshingConfig": "重新整理中…",
    "refreshConfigFailed": "重新整理失敗：{{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "最新的前沿代理式編碼模型。"
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "適合日常工作的均衡代理式編碼模型。"
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "快速又實惠的代理式編碼模型。"
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "適用於複雜編碼、研究與實際工作的前沿模型。"
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "適合日常編碼的強大模型。"
      }
    }
  }
};

export default models;
