// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {
  "panels": {
    "radar": "雷達",
    "git": "Git",
    "files": "檔案",
    "search": "搜尋",
    "notes": "筆記",
    "memory": "記憶",
    "projectMap": "專案地圖",
    "intentCanvas": "意圖畫布",
    "activity": "活動",
    "prompts": "提示詞"
  }
};

export default panels;
