// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {"plan":{"title":"計畫","noPlan":"沒有可用的計畫","steps":"步驟","completed":"已完成","inProgress":"進行中","pending":"待處理"}};

export default plan;
