// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "提示詞增強器",
    "tooltip": "增強提示詞",
    "tooltipFull": "改寫提示詞以提供更多脈絡並改善 Agent 回應",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "正在增強提示詞…",
    "readyToEnhance": "設定提供者、模型與逾時後即可開始增強。",
    "runSettings": "增強設定",
    "provider": "提供者",
    "model": "模型",
    "noModel": "無模型",
    "timeoutSeconds": "逾時（秒）",
    "runEnhancement": "開始增強",
    "originalPrompt": "原始提示詞",
    "enhancedPrompt": "增強後提示詞",
    "useEnhanced": "使用增強版",
    "keepOriginal": "保留原始版",
    "enhanceFailed": "增強提示詞失敗",
    "emptyPrompt": "請先輸入提示詞",
    "copyEnhanced": "複製增強版"
  }
};

export default promptEnhancer;
