// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/prompts.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/prompts.ts; keys mirror the English source.
const prompts = {
  "prompts": {
    "title": "自訂提示詞",
    "noPrompts": "無提示詞",
    "filterPrompts": "篩選提示詞",
    "globalPrompts": "通用提示詞",
    "workspacePrompts": "工作區提示詞",
    "addWorkspacePrompt": "新增工作區提示詞",
    "addGeneralPrompt": "新增通用提示詞",
    "noWorkspacePrompts": "尚無工作區提示詞",
    "noGeneralPrompts": "尚無通用提示詞",
    "createOrDropWorkspace": "在此建立一個，或將 .md 檔拖曳至",
    "createOrDropGeneral": "在此建立一個，或將 .md 檔拖曳至",
    "workspacePromptsFolder": "工作區提示詞資料夾",
    "codexHomePrompts": "CODEX_HOME/prompts",
    "promptCount": "{{count}} 個提示詞",
    "promptCount_other": "{{count}} 個提示詞",
    "name": "名稱",
    "promptName": "提示詞名稱",
    "scope": "範圍",
    "workspace": "工作區",
    "general": "通用",
    "description": "描述",
    "optionalDescription": "選填描述",
    "argumentHint": "參數提示",
    "optionalArgumentHint": "選填參數提示",
    "content": "內容",
    "promptContent": "提示詞內容",
    "send": "傳送",
    "sendToCurrentAgent": "傳送至目前 Agent",
    "newAgent": "新增 Agent",
    "sendToNewAgent": "傳送至新的 Agent",
    "edit": "編輯",
    "moveTo": "移動至{{scope}}",
    "delete": "刪除",
    "promptActions": "提示詞操作",
    "deletePrompt": "刪除此提示詞？",
    "arguments": "參數",
    "argumentsFor": "{{name}} 的參數"
  }
};

export default prompts;
