// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {"reasoning":{"title":"選擇推理深度","default":"預設","claudeDefault":"預設","defaultDescription":"使用引擎預設的推理行為","low":{"label":"低","description":"以基本推理快速回應"},"medium":{"label":"中","description":"均衡思考（預設）"},"high":{"label":"高","description":"為複雜任務進行深度推理"},"xhigh":{"label":"超高","description":"超高推理深度"},"max":{"label":"最高","description":"最高推理深度"}}};

export default reasoning;
