// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
const rewind = {
  "rewind": {
    "title": "將檔案回溯至先前狀態",
    "tooltip": "回溯",
    "label": "回溯",
    "tooltipFull": "將檔案還原至此訊息時的狀態",
    "notAvailable": "此工作階段無法使用回溯",
    "noEligibleMessage": "找不到可回溯的使用者訊息。",
    "selectPrompt": "選擇回溯目標（1-{{count}}）：",
    "invalidSelection": "無效的回溯選擇。",
    "confirmPrompt": "從此訊息建立新的討論串？\n「{{preview}}」",
    "dialogTitle": "確認 {{engine}} 回溯",
    "dialogDescription": "現在點擊回溯只會先開啟此確認對話框。回溯僅在你明確確認後才會執行。",
    "targetSectionTitle": "回溯起始點",
    "targetMessageLabel": "此回溯將從這則使用者訊息開始回退",
    "impactSectionTitle": "將移除的內容",
    "impactUserMessages": "移除的使用者訊息",
    "impactAssistantMessages": "移除的助理回覆",
    "impactToolCalls": "移除的工具呼叫",
    "impactFiles": "涉及的檔案",
    "impactSummary": "確認後，目前的線性歷史將從這則使用者訊息開始回退。這包含此使用者訊息以及之後所有的助理回覆、工具呼叫與相關變更。",
    "impactFollowUp": "若下方列出檔案，代表其變更發生在將被回溯的歷史區段內。請在確認前先檢視。",
    "workspaceRestoreSectionTitle": "工作區檔案策略",
    "modeMessagesAndFilesLabel": "回溯訊息 + 檔案",
    "modeMessagesAndFilesHint": "同時回溯對話歷史並還原相關的工作區檔案變更。",
    "modeMessagesOnlyLabel": "僅訊息",
    "modeMessagesOnlyHint": "僅回溯對話歷史，保留目前工作區檔案不變。",
    "modeFilesOnlyLabel": "僅檔案",
    "modeFilesOnlyHint": "僅還原相關檔案，並保持目前對話歷史不變。",
    "filesSectionTitle": "受影響的檔案",
    "filesRailTitle": "檔案",
    "filesEmpty": "在將被回溯的歷史區段中未偵測到檔案變更。",
    "filesHint": "這是前端對偵測到的檔案變更所做的盡力摘要，讓你在繼續前確認影響範圍。",
    "diffEmpty": "此檔案沒有可用的差異預覽。你仍可檢視其他檔案或開啟主要差異面板。",
    "openDiffAction": "在差異面板中開啟",
    "storeAction": "儲存變更",
    "storeActionBusy": "正在儲存…",
    "storeUnavailable": "目前的回溯脈絡不含足以儲存變更的工作階段資訊。",
    "storeFailed": "儲存變更失敗。",
    "storeRevealFailed": "開啟已儲存的變更目錄失敗。",
    "storeRevealAction": "開啟資料夾",
    "storeSuccessTitle": "已儲存 {{count}} 個檔案，並產生可重複使用的清單快照。",
    "storeSuccessPrefix": "已儲存至：",
    "confirmAction": "確認回溯",
    "confirmActionBusy": "正在回溯…",
    "failed": "回溯對話失敗。"
  }
};

export default rewind;
