// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "搜尋檔案、看板、討論串、訊息、技能、命令…",
    "placeholderFiltered": "搜尋{{content}}…",
    "inputAria": "搜尋輸入",
    "scope": "範圍",
    "content": "內容",
    "current": "目前",
    "global": "全域",
    "currentWorkspace": "目前工作區",
    "allWorkspaces": "所有工作區",
    "noResults": "無結果",
    "noResultsHint": "試試使用檔案路徑、任務標題、討論串標題、訊息文字、技能名稱或命令名稱中的關鍵字。",
    "fileIndexLoading": "正在補齊檔案索引…",
    "fileIndexPartial": "檔案索引不完整，目前結果可能遺漏部分檔案。",
    "fileIndexError": "檔案索引載入失敗；重新開啟搜尋即可重試。",
    "navigate": "導覽",
    "open": "開啟",
    "close": "關閉",
    "projectTag": "專案",
    "typeTag": "類型",
    "sourceTag": "來源",
    "locationTag": "位置",
    "typeAction": "操作",
    "typeFile": "檔案",
    "typeKanban": "看板",
    "typeThread": "討論串",
    "typeMessage": "訊息",
    "typeHistory": "歷史",
    "typeSkill": "技能",
    "typeCommand": "命令",
    "sourceActions": "應用程式操作",
    "sourceFiles": "檔案索引",
    "sourceKanban": "看板資料",
    "sourceThreads": "討論串標題",
    "sourceMessages": "訊息內容",
    "sourceHistory": "輸入歷史",
    "sourceSkills": "技能清單",
    "sourceCommands": "命令清單",
    "contentAll": "全部",
    "contentActions": "操作",
    "contentFiles": "檔案",
    "contentKanban": "看板",
    "contentThreads": "討論串",
    "contentMessages": "訊息",
    "contentHistory": "歷史",
    "contentSkills": "技能",
    "contentCommands": "命令"
  }
};

export default searchPalette;
