// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
const statusPanel = {
  "statusPanel": {
    "tabTodos": "任務",
    "tabSubagents": "子 Agent",
    "tabAgents": "Agent",
    "tabCheckpoint": "結果",
    "tabPlan": "計畫",
    "tabCommands": "指令",
    "files": "檔案",
    "emptyTodos": "無任務",
    "emptySubagents": "無子 Agent",
    "emptyFileChanges": "無檔案變更",
    "emptyCommands": "無指令",
    "emptyPlan": "無計畫",
    "planGenerating": "正在產生計畫…",
    "planSwitchHint": "切換至計畫模式以檢視計畫",
    "expand": "展開狀態面板",
    "collapse": "收合狀態面板",
    "label": "狀態",
    "policy": {
      "title": "政策稽核",
      "count": "{{count}} 項決策",
      "noReason": "{{policy}} 未提供理由",
      "verdict": {
        "running": "執行中",
        "blocked": "受阻",
        "needs_review": "待審查",
        "ready": "就緒",
        "no_contribution": "已略過"
      },
      "corePolicy": {
        "blocked": "核心規則偵測到阻礙風險。",
        "running": "核心規則偵測到進行中的工作。",
        "ready": "核心規則認定目前佐證已就緒。",
        "needsReview": "核心規則需要審查。"
      },
      "lintValidationPolicy": {
        "pass": "Lint 通過。",
        "fail": "Lint 失敗，需要審查。",
        "running": "Lint 執行中。",
        "notRun": "Lint 尚未執行。"
      },
      "typecheckValidationPolicy": {
        "pass": "型別檢查通過。",
        "fail": "型別檢查失敗，需要審查。",
        "running": "型別檢查執行中。",
        "notRun": "型別檢查尚未執行。"
      },
      "testsValidationPolicy": {
        "pass": "測試通過。",
        "fail": "測試失敗，需要審查。",
        "running": "測試執行中。",
        "notRun": "測試尚未執行。"
      },
      "openspecGovernancePolicy": {
        "pass": "OpenSpec 治理佐證為最新。",
        "warn": "OpenSpec 治理佐證有建議性警告。",
        "fail": "OpenSpec 治理佐證需要審查。",
        "unknown": "OpenSpec 治理佐證無法取得或不完整。"
      },
      "largeFileGovernancePolicy": {
        "pass": "大型檔案治理佐證為最新。",
        "warn": "大型檔案治理佐證有建議性警告。",
        "fail": "大型檔案治理佐證需要審查。",
        "unknown": "大型檔案治理佐證無法取得或不完整。"
      },
      "heavyTestNoiseGovernancePolicy": {
        "pass": "重度測試雜訊佐證為最新。",
        "warn": "重度測試雜訊佐證有建議性警告。",
        "fail": "重度測試雜訊佐證需要審查。",
        "unknown": "重度測試雜訊佐證無法取得或不完整。"
      },
      "realtimeHarnessGovernancePolicy": {
        "pass": "即時測試框架佐證為最新。",
        "warn": "即時測試框架佐證有建議性警告。",
        "fail": "即時測試框架佐證需要審查。",
        "unknown": "即時測試框架佐證無法取得或不完整。"
      },
      "capabilityMismatchGovernancePolicy": {
        "pass": "引擎能力佐證為最新。",
        "warn": "引擎能力佐證有建議性警告。",
        "fail": "引擎能力佐證需要審查。",
        "unknown": "引擎能力佐證無法取得或不完整。"
      },
      "engineRuntimeGovernancePolicy": {
        "pass": "引擎執行階段契約佐證為最新。",
        "warn": "引擎執行階段契約佐證有建議性警告。",
        "fail": "引擎執行階段契約佐證需要審查。",
        "unknown": "引擎執行階段契約佐證無法取得或不完整。"
      },
      "costBudgetGovernancePolicy": {
        "pass": "成本預算佐證為最新。",
        "warn": "成本預算佐證有建議性警告。",
        "fail": "成本預算佐證需要審查。",
        "unknown": "成本預算佐證無法取得或不完整。"
      }
    },
    "audit": {
      "title": "決策依據",
      "expandLabel": "{{count}} 項政策決策",
      "empty": "無政策決策",
      "reasonUnavailable": "{{policy}} 未提供理由",
      "sourceUnavailable": "無來源",
      "enforcement": {
        "advisory": "建議",
        "blocking": "阻擋",
        "informational": "資訊"
      }
    },
    "governance": {
      "title": "治理佐證",
      "loading": "正在讀取佐證…",
      "empty": "無治理佐證",
      "count": "{{count}} 項佐證 · {{needsAction}} 項需處理",
      "group": {
        "needs_action": "需處理 · {{count}}",
        "watch": "觀察 · {{count}}",
        "passed": "已通過 · {{count}}"
      },
      "meta": {
        "source": "來源：{{source}}",
        "artifact": "產物：{{path}}",
        "action": "動作：解決 {{reason}}"
      },
      "status": {
        "pass": "通過",
        "warn": "警告",
        "fail": "失敗",
        "unknown": "未知"
      }
    },
    "cost": {
      "title": "成本／預算",
      "session": "工作階段",
      "engine": "引擎",
      "model": "模型",
      "sessionId": "工作階段 ID",
      "tokens": "Token",
      "tokenBreakdownLabel": "Token 用量明細",
      "known": "已比對定價",
      "partial": "部分估算",
      "unknownModel": "未知模型",
      "pricingSource": "定價來源：{{source}} · {{date}}",
      "historyDegraded": "由於 localStorage 寫入失敗，成本歷史記錄改於記憶體中延續。",
      "accumulated": {
        "session": "工作階段 {{amount}}",
        "today": "今日 {{amount}}",
        "month": "本月 {{amount}}"
      },
      "degraded": {
        "pricing-unavailable": "找不到 {{engine}}/{{model}} 可追溯的定價；成本不會被悄悄視為零。",
        "pricing-stale": "定價 fixture 已過時；此成本僅供參考。",
        "usage-unavailable": "無可用的 Token 用量以進行成本推算。",
        "block-level-cost-unsupported": "此版本不支援區塊層級成本。",
        "unknown": "成本推算已降級。"
      }
    },
    "budget": {
      "unconfigured": "尚未設定預算。這是指引，並非預算檢查失敗。",
      "unsetShort": "未設定預算",
      "barLabel": "預算使用進度",
      "progress": "{{amount}} / {{limit}}",
      "threshold": {
        "info": "已達資訊門檻：{{amount}} / {{threshold}}",
        "warn": "已達警告門檻：{{amount}} / {{threshold}}",
        "block": "已達阻擋門檻：{{amount}} / {{threshold}}。此能力僅發出訊號，不會中斷執行階段。"
      }
    },
    "checkpoint": {
      "verdictTitle": "判定",
      "evidenceTitle": "佐證",
      "keyChangesTitle": "主要變更",
      "keyChangesEmpty": "尚未擷取主要變更",
      "fileDetailsTitle": "檔案詳情",
      "risksTitle": "風險",
      "nextActionTitle": "下一步動作",
      "sections": {
        "summary": "摘要",
        "advisorySignals": "建議性訊號",
        "evidenceTrail": "佐證軌跡",
        "policyAudit": "政策稽核",
        "suggestedActions": "建議動作"
      },
      "advisory": {
        "count": "{{count}} 項建議性訊號"
      },
      "verdict": {
        "running": "執行中",
        "blocked": "受阻",
        "needs_review": "需審查",
        "ready": "就緒"
      },
      "headline": {
        "running": "工作進行中",
        "blocked": "需要注意",
        "needs_review": "繼續前請審查",
        "ready": "可繼續",
        "idle": "等待佐證"
      },
      "summary": {
        "blockedValidation": "有必要的驗證失敗，須先修復。",
        "blockedCommand": "最新指令失敗：{{command}}。若系統仍在嘗試自動復原，請等待此次執行穩定後再停止。",
        "blockedSubagent": "有委派任務以錯誤狀態停止。",
        "runningValidation": "驗證仍在執行中。請等待結果後再決定。",
        "runningCommand": "最新指令仍在執行中：{{command}}",
        "runningAgent": "至少有一個 Agent 仍在處理中。",
        "runningTodo": "仍有進行中的任務。",
        "runningProcessing": "目前回合仍在產生執行佐證。",
        "readyWithFiles": "{{count}} 個變更檔案已通過所觀察到的核心檢查。",
        "ready": "所觀察到的執行佐證看來已穩定。",
        "needsValidation": "檔案已變更，但核心驗證尚未執行。",
        "manual": "結果已產生，但仍需人工審查一遍。",
        "idle": "尚未觀察到可靠的執行佐證。"
      },
      "evidence": {
        "filesChanged": "變更的檔案",
        "filesChangedValue": "{{count}} 個檔案",
        "validations": "驗證",
        "requiredValidations": "必要",
        "optionalValidations": "選用",
        "fileChangeSummary": "+{{additions}}/-{{deletions}}，橫跨 {{count}} 個檔案",
        "runMissing": "請先執行",
        "runMissingGeneric": "執行專案的核心驗證指令碼",
        "tasks": "任務",
        "agents": "Agent",
        "inProgress": "進行中",
        "settled": "已穩定"
      },
      "evidenceTrail": {
        "count": "{{count}} 項佐證",
        "sourceLabel": "來源",
        "snapshotLabel": "快照",
        "observedLabel": "觀察到",
        "artifactLabel": "產物",
        "hashLabel": "雜湊",
        "qualifierLabel": "限定條件",
        "degradedLabel": "已降級",
        "staleLabel": "已過時",
        "snapshotRecorded": "已記錄快照",
        "hashRecorded": "已驗證",
        "policy": {
          "buildValidationPolicy": "建置驗證",
          "costBudgetGovernancePolicy": "成本預算",
          "heavyTestNoiseGovernancePolicy": "重度測試雜訊",
          "largeFileGovernancePolicy": "大型檔案治理",
          "lintValidationPolicy": "Lint 驗證",
          "openspecGovernancePolicy": "OpenSpec 治理",
          "testsValidationPolicy": "測試驗證",
          "typecheckValidationPolicy": "型別檢查驗證"
        },
        "sourceName": {
          "build": "建置",
          "costBudget": "成本預算",
          "heavyTestNoise": "重度測試雜訊",
          "largeFile": "大型檔案",
          "lint": "Lint",
          "openspec": "OpenSpec",
          "tests": "測試",
          "trellis": "Trellis",
          "typecheck": "型別檢查"
        },
        "reason": {
          "governanceArtifactMalformed": "佐證檔案格式無效",
          "governanceEvidenceUnavailable": "佐證尚無法解析",
          "pricingUnavailable": "模型定價未知",
          "stale": "佐證已過時"
        },
        "source": "來源：{{source}}",
        "snapshot": "快照：{{id}}",
        "observed": "觀察到：{{time}}",
        "artifact": "產物：{{path}}",
        "hash": "雜湊：{{hash}}",
        "qualifier": "限定條件：{{qualifier}}",
        "degraded": "已降級：{{reason}}",
        "stale": "已過時：{{time}}"
      },
      "suggested": {
        "validation": "選用：{{command}}",
        "governance": "選用 {{source}} 檢查：{{command}}"
      },
      "expandToDock": "在停靠面板中檢視完整結果",
      "validations": {
        "lint": "Lint",
        "typecheck": "型別檢查",
        "tests": "測試",
        "build": "建置",
        "custom": "指令",
        "status": {
          "pass": "通過",
          "fail": "失敗",
          "running": "執行中",
          "not_run": "未執行",
          "not_observed": "未觀察到"
        }
      },
      "keyChanges": {
        "files": "異動的檔案",
        "filesSummary": "{{count}} 個檔案變更 · +{{additions}} / -{{deletions}}",
        "tasks": "任務進度",
        "tasksSummary": "已完成 {{completed}}/{{total}} 個任務",
        "agents": "Agent 進度",
        "agentsSummary": "已完成 {{completed}}/{{total}} 個 Agent"
      },
      "risks": {
        "none": "未偵測到阻礙風險。",
        "commandFailed": "有指令以錯誤結束：{{command}}",
        "validationFailed": "至少有一項驗證以失敗結束。",
        "validationMissing": "檔案變更後核心驗證尚未執行。",
        "subagentError": "有 Agent 回報錯誤：{{agent}}",
        "manualReview": "系統尚未觀察到足夠佐證以宣告結果。",
        "severity": {
          "high": "高",
          "medium": "中",
          "low": "低"
        }
      },
      "actions": {
        "reviewDiff": "檢視差異",
        "openRisk": "檢視風險",
        "retry": "重試失敗步驟",
        "commit": "就緒時提交",
        "hint": {
          "runMissingValidation": "在決定是否繼續前，先執行缺少的驗證。",
          "running": "請等待目前的執行佐證穩定。",
          "blocked": "請先檢視失敗的佐證；若復原仍在進行中，請等待執行穩定後再決定是否停止。",
          "needs_review": "此結果或許仍會復原。請等待執行持續穩定後再採取行動。",
          "ready": "佐證已穩定；請進行最後的提交前檢查。"
        }
      },
      "commitDialog": {
        "title": "提交確認",
        "path": "路徑：",
        "files": "要提交的檔案",
        "toggleAllFiles": "切換所有提交檔案",
        "staged": "已暫存"
      }
    }
  }
};

export default statusPanel;
