// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
const tabbar = {
  "tabbar": {
    "projects": "專案",
    "codex": "Codex",
    "spec": "Spec",
    "git": "Git",
    "log": "記錄",
    "primaryNavigation": "主要導覽",
    "workspaceNavigation": "工作區導覽"
  }
};

export default tabbar;
