// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {
  "terminal": {
    "newTab": "新增分頁",
    "closeTab": "關閉分頁",
    "clear": "清除",
    "title": "終端機",
    "tabTitle": "終端機 {{number}}",
    "claudeTuiResumeTitle": "Claude TUI",
    "sendSelectionToComposer": "傳送至編輯區"
  }
};

export default terminal;
