// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
const threadCompletion = {"threadCompletion":{"title":"工作階段已完成","project":"專案","session":"工作階段"}};

export default threadCompletion;
