// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {
  "time": {
    "justNow": "剛剛",
    "minuteAgo": "{{count}} 分鐘前",
    "minutesAgo": "{{count}} 分鐘前",
    "hourAgo": "{{count}} 小時前",
    "hoursAgo": "{{count}} 小時前",
    "dayAgo": "{{count}} 天前",
    "daysAgo": "{{count}} 天前",
    "weekAgo": "{{count}} 週前",
    "weeksAgo": "{{count}} 週前",
    "now": "現在",
    "shortSecondsAgo": "{{value}} 秒前",
    "shortSecondsIn": "{{value}} 秒後",
    "shortMinutesAgo": "{{value}} 分前",
    "shortMinutesIn": "{{value}} 分後",
    "shortMinutes": "{{value}} 分",
    "shortHours": "{{value}} 時",
    "shortDays": "{{value}} 天",
    "shortWeeks": "{{value}} 週",
    "shortMonths": "{{value}} 月",
    "shortYears": "{{value}} 年"
  }
};

export default time;
