// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
const tools = {
  "tools": {
    "readFile": "讀取檔案",
    "readDirectory": "讀取目錄",
    "editFile": "編輯檔案",
    "writeFile": "寫入檔案",
    "editNotebook": "編輯筆記本",
    "runCommand": "執行指令",
    "executeCommand": "執行指令",
    "search": "搜尋",
    "fileMatch": "檔案比對",
    "findFile": "尋找檔案",
    "webFetch": "網頁擷取",
    "webSearch": "網頁搜尋",
    "subtask": "子任務",
    "todoList": "待辦清單",
    "userInputRequest": "詢問使用者問題",
    "diffCompare": "差異比對",
    "result": "結果",
    "claudeControlResumeFailed": "繼續失敗",
    "claudeControlModelChanged": "模型已變更",
    "claudeControlInterrupted": "已中斷",
    "claudeControlLocalOutput": "本機指令輸出",
    "webRequest": "網路請求",
    "batchRun": "批次執行",
    "searchMatch": "搜尋/比對",
    "batchReadFile": "批次讀取檔案",
    "batchSearch": "批次搜尋",
    "batchSearchMatch": "批次搜尋/比對",
    "batchEditFile": "批次編輯檔案",
    "bashGroupBatchRun": "批次執行指令",
    "bashGroupCompleted": "已完成",
    "bashGroupAllCompleted": "全部完成",
    "bashGroupFailed": "失敗",
    "planQuickView": "計畫",
    "openFullPlanPanel": "開啟完整計畫面板",
    "closePlanPanel": "關閉計畫面板",
    "path": "路徑",
    "lineRange": "第 {{start}}-{{end}} 行",
    "failedCount": "{{count}} 個失敗"
  }
};

export default tools;
