// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "更新",
    "checkingForUpdates": "正在檢查更新…",
    "updateAvailable": "有新版本可用！",
    "upToDate": "已是最新版本。",
    "downloading": "正在下載更新…",
    "installing": "正在安裝更新…",
    "restarting": "正在重新啟動…",
    "failed": "更新失敗。",
    "downloaded": "已下載",
    "releaseNotesTitle": "版本說明",
    "releaseNotesLoading": "正在載入版本說明…",
    "releaseNotesLoadFailed": "版本說明載入失敗。",
    "releaseNotesEmpty": "尚無版本說明。",
    "releaseNotesOpenInGitHub": "在 GitHub 上檢視",
    "releaseNotesPrev": "上一則",
    "releaseNotesNext": "下一則",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "English：",
    "releaseNotesChinese": "中文："
  }
};

export default update;
