// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
const usage = {
  "usage": {
    "sessionReset": "工作階段重設",
    "weeklyReset": "每週重設",
    "credits": "點數",
    "used": "已使用",
    "remaining": "剩餘",
    "unlimited": "無限制"
  }
};

export default usage;
