/**
 * Rebuild a translated locale from its flat translation map, mirroring the
 * English source's per-namespace folder split:
 *   src/i18n/locales/<lang>/<namespace>.ts  — one file per top-level namespace
 *   src/i18n/locales/<lang>/index.ts        — barrel, mirrors en/index.ts
 *
 * Validates BEFORE writing anything:
 *   1. every English key has a translation (no missing / no extra keys)
 *   2. each value carries the exact same {{placeholder}} multiset as English
 * Any violation aborts with a non-zero exit so a bad machine translation can
 * never land as a runtime bug.
 *
 * Usage: npx vite-node scripts/i18n/build-locale.ts <langCode>
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import en from "../../src/i18n/locales/en";

const lang = process.argv[2];
if (!lang) {
  console.error("Usage: vite-node scripts/i18n/build-locale.ts <langCode>");
  process.exit(1);
}

const flatPath = resolve(`scripts/i18n/.work/${lang}.flat.json`);
const flat: Record<string, string> = JSON.parse(readFileSync(flatPath, "utf8"));

const placeholders = (s: string): string[] =>
  (s.match(/\{\{[^}]+\}\}/g) ?? []).slice().sort();

const missing: string[] = [];
const badPlaceholders: string[] = [];
const seen = new Set<string>();

function build(node: unknown, path: string): unknown {
  if (typeof node === "string") {
    seen.add(path);
    const translated = flat[path];
    if (typeof translated !== "string") {
      missing.push(path);
      return node; // keep English so the emitted file still parses if we ignore errors
    }
    const a = placeholders(node).join("|");
    const b = placeholders(translated).join("|");
    if (a !== b) badPlaceholders.push(`${path}  en[${a}] != ${lang}[${b}]`);
    return translated;
  }
  if (node && typeof node === "object" && !Array.isArray(node)) {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
      out[k] = build(v, path ? `${path}.${k}` : k);
    }
    return out;
  }
  return node;
}

// The English bundle spreads one object per namespace file, so its own top-level
// keys ARE the namespace names (about, chat, …). Rebuild one translated object
// per namespace and mirror the en/ folder layout exactly.
const namespaces = Object.keys(en as Record<string, unknown>).sort();
const built: Record<string, unknown> = {};
for (const ns of namespaces) {
  built[ns] = build({ [ns]: (en as Record<string, unknown>)[ns] }, "");
}

const extra = Object.keys(flat).filter((k) => !seen.has(k));

const errors: string[] = [];
if (missing.length) errors.push(`Missing ${missing.length} keys, e.g.:\n  ${missing.slice(0, 15).join("\n  ")}`);
if (extra.length) errors.push(`Extra ${extra.length} keys not in English, e.g.:\n  ${extra.slice(0, 15).join("\n  ")}`);
if (badPlaceholders.length) errors.push(`Placeholder mismatch in ${badPlaceholders.length} values, e.g.:\n  ${badPlaceholders.slice(0, 15).join("\n  ")}`);

if (errors.length) {
  console.error(`[build-locale:${lang}] FAILED validation:\n\n${errors.join("\n\n")}`);
  process.exit(1);
}

const outDir = resolve(`src/i18n/locales/${lang}`);
mkdirSync(outDir, { recursive: true });

const fileBanner = (source: string): string =>
  `// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.\n` +
  `// Machine translation of ${source}; keys mirror the English source.\n`;

for (const ns of namespaces) {
  // Keep generated locale modules compact so adding languages does not trip the
  // source-file line-count guard. The translation source remains inspectable in
  // scripts/i18n/.work/<lang>.flat.json when review needs a pretty JSON shape.
  const body = `const ${ns} = ${JSON.stringify(built[ns])};\n\nexport default ${ns};\n`;
  writeFileSync(resolve(outDir, `${ns}.ts`), fileBanner(`src/i18n/locales/en/${ns}.ts`) + body);
}

// Barrel — same import + spread shape as src/i18n/locales/en/index.ts. Uses a
// neutral `locale` binding so language codes with hyphens (zh-TW, pt-BR) stay
// valid identifiers.
const importLines = namespaces.map((ns) => `import ${ns} from "./${ns}";`).join("\n");
const spreadLines = namespaces.map((ns) => `  ...${ns},`).join("\n");
const barrel =
  fileBanner("src/i18n/locales/en/index.ts") +
  `${importLines}\n\nconst locale = {\n${spreadLines}\n};\n\nexport default locale;\n`;
writeFileSync(resolve(outDir, "index.ts"), barrel);

console.log(
  `[build-locale:${lang}] OK — ${seen.size} keys across ${namespaces.length} namespaces → src/i18n/locales/${lang}/`,
);
