// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
const agentOrchestration = {
  "agentOrchestration": {
    "title": "Fila de trabalho do Mapa do Projeto",
    "eyebrow": "Fila do Mapa do Projeto",
    "summary": "{{workspace}} · {{total}} item(ns) de trabalho · {{providers}} fonte(s) disponível(is)",
    "workspaceUnknown": "Workspace desconhecido",
    "loadingTitle": "Carregando a visualização de orquestração",
    "loadingDescription": "Agregando candidatos do Mapa do Projeto, rascunhos de tarefas existentes e o contexto de TaskRun.",
    "emptyTitle": "Ainda não há tarefas de orquestração neste workspace",
    "emptyDescription": "No momento, esta visualização mostra apenas o contexto de orquestração existente e o status de execução. Os pontos de entrada para criação de tarefas retornarão após a reformulação do módulo de tarefas.",
    "degradedTitle": "Algumas fontes estão degradadas",
    "unavailable": "Indisponível",
    "noRefs": "Sem referências de fonte",
    "noEvidenceRefs": "Sem referências de evidência",
    "noRisks": "Sem marcadores de risco",
    "status": {
      "candidate": "Candidata",
      "planned": "Planejada",
      "ready": "Pronta",
      "running": "Em execução",
      "waiting_input": "Aguardando entrada",
      "blocked": "Bloqueada",
      "review_needed": "Requer revisão",
      "completed": "Concluída",
      "archived": "Arquivada"
    },
    "queueStatus": {
      "todo": "A fazer",
      "queued": "Na fila",
      "running": "Em execução",
      "failed": "Falhou",
      "dispatched": "Despachada",
      "review": "Requer revisão",
      "done": "Concluída",
      "archived": "Arquivada"
    },
    "action": {
      "backToProjectMap": "Voltar ao Mapa do Projeto"
    },
    "manual": {
      "open": "Adicionar tarefa manual",
      "eyebrow": "Fonte manual",
      "title": "Criar tarefa manual",
      "description": "Tarefas manuais não inventam evidências verificadas. Adicione escopo e critérios de aceitação antes de despachar.",
      "fieldTitle": "Título",
      "fieldScope": "Escopo",
      "fieldAcceptance": "Aceitação",
      "fieldPrompt": "Prompt",
      "cancel": "Cancelar",
      "create": "Criar tarefa"
    },
    "actions": {
      "label": "Ações da tarefa",
      "openSource": "Abrir fonte",
      "openSourceLabel": "Abrir fonte de {{title}}",
      "openRun": "Ver execução na Central de Tarefas",
      "openRunLabel": "Ver execução vinculada de {{title}} na Central de Tarefas",
      "openSession": "Abrir sessão",
      "openSessionLabel": "Abrir sessão vinculada de {{title}}",
      "cancelQueuedRun": "Cancelar despacho",
      "archive": "Arquivar",
      "writeBack": "Gravar de volta na fonte",
      "writeBackDisabled": "A gravação de volta na fonte é uma ação futura: deve passar por um fluxo de confirmação separado. Arquivos do OpenSpec, Trellis, spec-kit e regras de agentes não são modificados aqui."
    },
    "queue": {
      "taskLabel": "{{title}}, status {{status}}, fonte {{provider}}, {{risks}} marcador(es) de risco",
      "riskCount": "{{count}} marcador(es) de risco",
      "riskOverflow": "+{{count}} risco(s)"
    },
    "dispatch": {
      "open": "Enviar para a Central de Tarefas",
      "openLabel": "Enviar {{title}} para a Central de Tarefas",
      "eyebrow": "Porta de despacho",
      "title": "Confirmação de despacho",
      "description": "Configure primeiro o motor, o workspace, a estratégia de thread e o escopo de aceitação. Um TaskRun só é criado após a confirmação do despacho.",
      "engine": "Motor",
      "model": "Modelo",
      "defaultModel": "Usar o modelo padrão",
      "workspace": "Workspace",
      "status": "Status",
      "threadStrategy": "Estratégia de thread",
      "promptSummary": "Resumo do prompt",
      "acceptance": "Aceitação",
      "sources": "Fontes",
      "disabled": "A execução ainda não está conectada: isto apenas visualiza os parâmetros de despacho e não criará um TaskRun.",
      "cancel": "Cancelar",
      "confirm": "Confirmar despacho"
    },
    "review": {
      "label": "Ações de revisão",
      "open": "Revisar",
      "openLabel": "Revisar {{title}}",
      "title": "Porta de revisão",
      "description": "A execução vinculada foi concluída. Revise o resultado antes de aceitar, solicitar alterações ou criar uma tarefa de acompanhamento.",
      "accept": "Aceitar resultado",
      "requestChanges": "Solicitar alterações",
      "createFollowUp": "Criar acompanhamento",
      "missingRunTitle": "Resultado de execução ausente; a revisão está indisponível",
      "missingRunDescription": "Esta tarefa está marcada para revisão, mas não tem execução nem sessão vinculada. Despache-a novamente antes de revisar.",
      "feedback": {
        "accepted": "Resultado aceito. A tarefa está concluída.",
        "changesRequested": "Alterações solicitadas. A tarefa voltou para a fila de trabalho.",
        "followUpCreated": "Tarefa de acompanhamento criada e selecionada."
      }
    },
    "filters": {
      "label": "Filtros da fila de tarefas",
      "provider": "Fonte",
      "status": "Status do trabalho",
      "engine": "Motor",
      "workspace": "Workspace",
      "sourceKind": "Tipo de fonte",
      "risk": "Risco",
      "allProviders": "Todas as fontes",
      "allStatuses": "Todos os status de trabalho",
      "allEngines": "Todos os motores",
      "allWorkspaces": "Todos os workspaces",
      "allSourceKinds": "Todos os tipos de fonte",
      "allRisks": "Todos os riscos",
      "noEngine": "Sem motor",
      "reset": "Redefinir",
      "visibleSummary": "Mostrando {{visible}} / {{total}}",
      "emptyTitle": "Nenhuma tarefa corresponde aos filtros atuais",
      "emptyDescription": "Ajuste os filtros de fonte, status, motor, workspace, tipo de fonte ou risco para continuar."
    },
    "reviewState": {
      "not_started": "Não iniciada",
      "needs_review": "Requer revisão",
      "accepted": "Aceita",
      "changes_requested": "Alterações solicitadas"
    },
    "threadStrategy": {
      "new_thread": "Nova thread",
      "reuse_active_thread": "Reutilizar thread ativa",
      "choose_thread": "Escolher thread"
    },
    "detail": {
      "scope": "Escopo",
      "acceptance": "Aceitação",
      "createdAt": "Criada",
      "updatedAt": "Atualizada",
      "providerSources": "Fontes de origem",
      "evidence": "Evidência",
      "evidenceCount": "{{count}} referência(s) de evidência",
      "risks": "Riscos",
      "links": "Vínculos de execução",
      "runManagement": "Gerenciamento de execução / sessão",
      "linkCountsLabel": "Contagem de vínculos",
      "linkCounts": "{{runs}} execução(ões) · {{sessions}} sessão(ões)",
      "linkedRuns": "Execuções vinculadas",
      "linkedSessions": "Sessões vinculadas",
      "noLinkedRuns": "Nenhuma execução vinculada",
      "noLinkedSessions": "Nenhuma sessão vinculada",
      "missingLinkedRun": "Nenhuma execução vinculada. Voltou para a fila de a fazer.",
      "linkedRunMissing": "Registro de execução ausente",
      "runEngine": "Motor",
      "runUpdatedAt": "Atualizada",
      "runCurrentStep": "Etapa atual",
      "runLatestOutput": "Saída mais recente",
      "activity": "Atividade",
      "reviewState": "Estado da revisão",
      "threadStrategy": "Estratégia de thread",
      "preferredEngine": "Motor preferido",
      "preferredModel": "Modelo preferido",
      "parentTask": "Tarefa principal",
      "selectionPreservedTitle": "Nó atual preservado",
      "selectionPreservedDescription": "O status da tarefa mudou, mas o painel de detalhes permanece no nó em que você acabou de agir."
    }
  }
};

export default agentOrchestration;
