// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {"askUserQuestion":{"title":"O Claude tem uma pergunta para você","progress":"Pergunta {{current}} / {{total}}","timeoutWarning":"Responda em breve. Este diálogo será fechado automaticamente em {{seconds}} segundos","collapse":"Recolher","expand":"Expandir","clickToAnswer":"Clique para responder","questionTab":"Pergunta {{index}}","cancel":"Cancelar","back":"Voltar","next":"Avançar","submit":"Enviar","otherOption":"Outro","otherOptionDesc":"Insira uma resposta personalizada","customInputPlaceholder":"Digite sua resposta...","multiSelectHint":"Você pode selecionar várias opções"}};

export default askUserQuestion;
