// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
const codexModes = {
  "codexModes": {
    "default": {
      "label": "Sugerir (aprovação)",
      "tooltip": "Codex approval_policy=untrusted – solicita confirmação antes de editar arquivos ou executar comandos de shell.",
      "description": "Opção mais segura. Cada gravação ou comando exige a sua aprovação."
    },
    "plan": {
      "label": "Modo de plano",
      "tooltip": "Modo de plano - análise somente leitura",
      "description": "Usa apenas ferramentas somente leitura, gera um plano para aprovação do usuário"
    },
    "acceptEdits": {
      "label": "Edição automática",
      "tooltip": "Codex approval_policy=auto-edit – aplica patches de arquivos automaticamente, mas ainda pergunta antes de comandos de shell.",
      "description": "Cria e edita arquivos automaticamente via apply_patch, mantendo as aprovações de comandos."
    },
    "bypassPermissions": {
      "label": "Totalmente automático",
      "tooltip": "Codex approval_policy=never – executa comandos e grava arquivos sem solicitar confirmação (o sandbox do workspace ainda é aplicado).",
      "description": "Modo autônomo. O Codex executa edições e comandos de shell imediatamente."
    }
  }
};

export default codexModes;
