// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {"debug":{"title":"Depuração","copyLogs":"Copiar logs","clearLogs":"Limpar logs","noLogs":"Nenhum log de depuração","copy":"Copiar","clear":"Limpar","noDebugEventsYet":"Nenhum evento de depuração ainda."}};

export default debug;
