// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "Falha na conexão",
    "requestFailed": "Falha na solicitação",
    "unexpectedError": "Ocorreu um erro inesperado",
    "sessionExpired": "Sessão expirada",
    "rateLimited": "Limite de taxa atingido. Tente novamente mais tarde.",
    "networkError": "Erro de rede. Verifique sua conexão.",
    "failedToAddWorkspace": "Falha ao adicionar workspace.",
    "failedToOpenNewWindow": "Falha ao abrir uma nova janela.",
    "failedToCreateSession": "Falha ao criar sessão.",
    "failedToCreateSessionNoThreadId": "O runtime não retornou um novo id de sessão.",
    "failedToCreateSessionRuntimeRecovering": "O runtime estava reiniciando ao criar esta sessão. O app já tentou novamente uma vez. Reconecte o workspace e tente de novo.",
    "reconnectAndRetryCreateSession": "Reconectar e tentar criar novamente",
    "reconnectingAndRetryingCreateSession": "Reconectando e tentando criar novamente...",
    "runtimeRecovered": "Runtime recuperado.",
    "retryingCreateSessionAfterRecovery": "Tentando criar sessão novamente...",
    "cliNotFound": "Nem o Claude Code CLI nem o Codex CLI foram encontrados. Instale um deles.",
    "cliNotFoundHint": "Instale o Claude Code: curl -fsSL https://claude.ai/install.sh | bash\nInstale o Codex: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI não encontrado. Instale o Codex e certifique-se de que `codex` esteja no seu PATH.",
    "couldntOpenWorkspace": "Não foi possível abrir o workspace",
    "dismissError": "Dispensar erro"
  }
};

export default errors;
