// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {
  "layout": {
    "resizeGitHistoryPanel": "Redimensionar painel de histórico do Git",
    "resizeSidebar": "Redimensionar barra lateral",
    "resizeRightPanel": "Redimensionar painel direito",
    "resizeEditorSplit": "Redimensionar divisão do editor",
    "resizeNoteCardsSplit": "Redimensionar divisão de conversa e notas",
    "resizePlanPanel": "Redimensionar painel de plano",
    "resizeRuntimeConsole": "Redimensionar console de execução",
    "resizeProjects": "Redimensionar projetos"
  }
};

export default layout;
