// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/lockScreen.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/lockScreen.ts; keys mirror the English source.
const lockScreen = {
  "lockScreen": {
    "lock": "Bloquear tela",
    "locked": "Bloqueado",
    "brandKicker": "Codemoss Product Atlas",
    "title": "Bloqueio seguro do ccgui · Visão geral da capacidade de engenharia",
    "description": "Threads e tarefas continuam rodando em segundo plano. Use esta tela de bloqueio para revisar o ciclo completo de entrega do ccgui: planejamento, orquestração de execução, revisão e envio.",
    "tabLabel": "Navegação por abas da tela de bloqueio",
    "tabs": {
      "live": "Sessões ao vivo",
      "capabilities": "Atlas de capacidades",
      "workflow": "Fluxo de entrega",
      "elements": "Guia de elementos"
    },
    "liveTitle": "Fluxo de sessão ao vivo",
    "liveDesc": "Apenas a saída de sessões em execução é exibida, atualizada automaticamente pela atividade mais recente.",
    "liveEmpty": "Nenhuma saída de sessão em execução no momento.",
    "liveRunning": "Em execução",
    "capabilityTitle": "Atlas de capacidades",
    "capabilityDesc": "O ccgui não é apenas um shell de chat. É um espaço de trabalho de engenharia local-first projetado para o fluxo de produção.",
    "journeyTitle": "Jornada de entrega típica",
    "journeyDesc": "A maioria das mudanças passa por esta sequência no ccgui:",
    "elementsTitle": "Guia de elementos",
    "elementsDesc": "Use esta página para revisar rapidamente cada módulo principal e sua responsabilidade.",
    "unlockTitle": "Painel de desbloqueio",
    "unlockDesc": "O arquivo de senha é ~/.ccgui/client/pwd.txt. Se ausente, o desbloqueio é permitido e o arquivo é criado automaticamente com um valor padrão.",
    "passwordInput": "Digite a senha de desbloqueio",
    "passwordPlaceholder": "Digite a senha",
    "passwordHint": "Pressione Enter ou clique em Desbloquear após inserir a senha.",
    "unlock": "Desbloquear",
    "invalidPassword": "Senha incorreta. Tente novamente.",
    "storageTitle": "Armazenamento da senha",
    "storageDesc": "Para alterar a senha, edite o conteúdo deste arquivo diretamente e salve.",
    "storagePathLabel": "Caminho do arquivo",
    "facts": {
      "integrationsLabel": "Roteamento multimotor",
      "integrationsValue": "Codex / Claude / Gemini",
      "workflowLabel": "Ciclo de entrega",
      "workflowValue": "Planejar → Executar → Revisar → Enviar",
      "runtimeLabel": "Estado de execução",
      "runtimeValue": "A tela de bloqueio não interrompe execuções ativas"
    },
    "journey": {
      "planTitle": "Planeje primeiro",
      "planDesc": "Defina escopo, restrições e decomposição de tarefas antes de tocar no código.",
      "executeTitle": "Execute com contexto",
      "executeDesc": "Execute com o contexto do espaço de trabalho e do thread, com despacho de tarefas Kanban e sessões paralelas.",
      "reviewTitle": "Revise com rastreamento",
      "reviewDesc": "Mantenha rastros de ferramentas, diffs e registros de depuração visíveis para uma verificação confiável.",
      "deliverTitle": "Entregue de forma limpa",
      "deliverDesc": "Conecte commits, branches, ações de PR e etapas de arquivamento em ativos de equipe reutilizáveis."
    },
    "features": {
      "workspaceGraphTitle": "Grafo do espaço de trabalho",
      "workspaceGraphDesc": "Gerencie repositórios, worktrees, agrupamento e ordenação com troca de contexto rápida.",
      "threadOrchestrationTitle": "Orquestração de threads",
      "threadOrchestrationDesc": "Suporta reprodução de histórico, prompts em fila, interrupção, título automático e continuidade de execuções longas.",
      "engineRoutingTitle": "Roteamento de motores",
      "engineRoutingDesc": "Alterne modelo, esforço de raciocínio, modo de acesso e modo de colaboração para se adequar a cada tarefa.",
      "gitIntelligenceTitle": "Inteligência do Git",
      "gitIntelligenceDesc": "Visualizações de Diff, Log, Commit, PR e Issue em um só fluxo, sem trocar de contexto.",
      "kanbanDispatchTitle": "Despacho Kanban",
      "kanbanDispatchDesc": "Crie sessões a partir de tarefas e mantenha o status de execução sincronizado com o progresso do quadro.",
      "memoryEngineTitle": "Motor de memória",
      "memoryEngineDesc": "Persista o conhecimento e as preferências do projeto para que sessões futuras comecem com contexto.",
      "unifiedSearchTitle": "Busca unificada",
      "unifiedSearchDesc": "Uma paleta única em arquivos, threads, mensagens, skills e comandos.",
      "terminalObservabilityTitle": "Terminal + Observabilidade",
      "terminalObservabilityDesc": "O terminal integrado e os rastros de depuração tornam a solução de problemas mais rápida e auditável.",
      "composerControlTitle": "Controle do compositor",
      "composerControlDesc": "Controle centralizado para presets, atalhos, regras de fence, comportamento de colagem e ditado.",
      "promptAssetsTitle": "Ativos de prompt",
      "promptAssetsDesc": "Gerencie ativos de prompt do espaço de trabalho/globais e reutilize-os em tarefas de entrega.",
      "collaborationModeTitle": "Modos de colaboração",
      "collaborationModeDesc": "Alterne a estratégia de colaboração para as etapas de exploração, implementação e revisão.",
      "openEcosystemTitle": "Ecossistema aberto",
      "openEcosystemDesc": "Integração open-in, pontos de extensão prontos para plugins e interoperabilidade com ferramentas externas."
    },
    "elements": {
      "titlebarTitle": "Controles da barra de título",
      "titlebarDesc": "Troca de projeto, ações de branch, opções open-in, gatilho de bloqueio e cópia de thread em uma única faixa.",
      "sidebarTitle": "Barra lateral do espaço de trabalho",
      "sidebarDesc": "Gerencie grupos de espaço de trabalho/worktree, listas de threads, filtros de busca e troca rápida de contexto de projeto.",
      "composerTitle": "Espaço de trabalho do compositor",
      "composerDesc": "Entrada rica, blocos de código (fences), comandos, ditado e montagem de contexto em um único ciclo do editor.",
      "gitPanelTitle": "Central do Git",
      "gitPanelDesc": "Contexto de diff, log, commit, PR e issue em uma única superfície para reduzir a troca de ferramentas.",
      "kanbanTitle": "Despacho Kanban",
      "kanbanDesc": "Despache tarefas em sessões de IA e mantenha o status vinculado ao progresso da execução.",
      "searchTitle": "Busca unificada",
      "searchDesc": "Um único ponto de entrada em arquivos, threads, mensagens, skills e comandos.",
      "memoryTitle": "Motor de memória",
      "memoryDesc": "Persista o conhecimento de longo prazo do projeto para reduzir a configuração repetida de contexto.",
      "debugTitle": "Terminal + Depuração",
      "debugDesc": "O terminal integrado e os rastros de depuração mantêm a solução de problemas observável e auditável."
    }
  }
};

export default lockScreen;
