// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
const menu = {
  "menu": {
    "about": "Sobre o {{appName}}",
    "checkForUpdates": "Verificar atualizações…",
    "settings": "Configurações…",
    "file": "Arquivo",
    "newAgent": "Novo Agent",
    "newWorktreeAgent": "Novo Agent de Worktree",
    "newCloneAgent": "Novo Agent de Clone",
    "newWindow": "Nova janela",
    "addWorkspace": "Adicionar espaço de trabalho…",
    "closeWindow": "Fechar janela",
    "quit": "Sair",
    "edit": "Editar",
    "composer": "Compositor",
    "cycleModel": "Alternar modelo",
    "cycleAccessMode": "Alternar modo de acesso",
    "cycleReasoningMode": "Alternar modo de raciocínio",
    "cycleCollaborationMode": "Alternar modo de colaboração",
    "view": "Exibir",
    "toggleProjectsSidebar": "Alternar barra lateral de projetos",
    "toggleGitSidebar": "Alternar barra lateral direita",
    "toggleGlobalSearch": "Alternar busca global",
    "toggleDebugPanel": "Alternar painel de depuração",
    "toggleTerminal": "Alternar terminal",
    "toggleDevtools": "Alternar ferramentas de desenvolvedor",
    "nextAgent": "Próximo Agent",
    "previousAgent": "Agent anterior",
    "nextWorkspace": "Próximo espaço de trabalho",
    "previousWorkspace": "Espaço de trabalho anterior",
    "toggleFullScreen": "Alternar tela cheia",
    "window": "Janela",
    "minimize": "Minimizar",
    "maximize": "Maximizar",
    "reloadWindow": "Recarregar janela",
    "help": "Ajuda"
  }
};

export default menu;
