// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Selecionar modelo",
    "addModel": "Adicionar modelo",
    "refreshConfig": "Atualizar configuração",
    "refreshingConfig": "Atualizando...",
    "refreshConfigFailed": "Falha ao atualizar: {{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "Modelo de programação agêntica de fronteira mais recente."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Modelo de programação agêntica equilibrado para o dia a dia."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Modelo de programação agêntica rápido e acessível."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Modelo de fronteira para programação complexa, pesquisa e trabalho do mundo real."
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "Modelo robusto para programação do dia a dia."
      }
    }
  }
};

export default models;
