// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {"panels":{"radar":"Radar","git":"Git","files":"Arquivos","search":"Busca","notes":"Notas","memory":"Memória","projectMap":"Mapa do projeto","intentCanvas":"Canvas de intenção","activity":"Atividade","prompts":"Prompts"}};

export default panels;
