// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {
  "plan": {
    "title": "Plano",
    "noPlan": "Nenhum plano disponível",
    "steps": "Etapas",
    "completed": "Concluído",
    "inProgress": "Em andamento",
    "pending": "Pendente"
  }
};

export default plan;
