// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "Aprimorador de Prompt",
    "tooltip": "Aprimorar prompt",
    "tooltipFull": "Reescreve o prompt para fornecer mais contexto e melhorar as respostas do agente",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "Aprimorando prompt...",
    "readyToEnhance": "Defina o provedor, o modelo e o tempo limite e inicie o aprimoramento.",
    "runSettings": "Configurações de aprimoramento",
    "provider": "Provedor",
    "model": "Modelo",
    "noModel": "Sem modelo",
    "timeoutSeconds": "Tempo limite (segundos)",
    "runEnhancement": "Iniciar aprimoramento",
    "originalPrompt": "Prompt original",
    "enhancedPrompt": "Prompt aprimorado",
    "useEnhanced": "Usar aprimorado",
    "keepOriginal": "Manter original",
    "enhanceFailed": "Falha ao aprimorar o prompt",
    "emptyPrompt": "Digite um prompt primeiro",
    "copyEnhanced": "Copiar aprimorado"
  }
};

export default promptEnhancer;
