// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/providers.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/providers.ts; keys mirror the English source.
const providers = {
  "providers": {
    "claude": {
      "label": "Claude Code"
    },
    "codex": {
      "label": "Codex CLI"
    },
    "gemini": {
      "label": "Gemini CLI"
    },
    "kimi": {
      "label": "Kimi CLI"
    },
    "opencode": {
      "label": "OpenCode"
    }
  }
};

export default providers;
