// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {
  "reasoning": {
    "title": "Selecionar profundidade de raciocínio",
    "default": "Padrão",
    "claudeDefault": "Padrão",
    "defaultDescription": "Usar o comportamento de raciocínio padrão do motor",
    "low": {
      "label": "Baixo",
      "description": "Respostas rápidas com raciocínio básico"
    },
    "medium": {
      "label": "Médio",
      "description": "Raciocínio equilibrado (padrão)"
    },
    "high": {
      "label": "Alto",
      "description": "Raciocínio profundo para tarefas complexas"
    },
    "xhigh": {
      "label": "Extra alto",
      "description": "Profundidade de raciocínio extra alta"
    },
    "max": {
      "label": "Máximo",
      "description": "Profundidade máxima de raciocínio"
    },
    "ultra": {
      "label": "Ultra",
      "description": "Raciocínio máximo com delegação automática de tarefas"
    }
  }
};

export default reasoning;
