// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/runtimeNotice.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/runtimeNotice.ts; keys mirror the English source.
const runtimeNotice = {
  "runtimeNotice": {
    "title": "Aviso de runtime",
    "open": "Abrir avisos de runtime",
    "minimize": "Minimizar",
    "clear": "Limpar",
    "emptyTitle": "Nenhum aviso de runtime ainda",
    "emptyDescription": "O progresso da inicialização e erros importantes aparecerão aqui.",
    "statusIdle": "Ocioso",
    "statusStreaming": "Em execução",
    "statusError": "Erro",
    "severityInfo": "Informação",
    "severityWarning": "Aviso",
    "severityError": "Erro",
    "bootstrap": {
      "start": "Inicializando estado local...",
      "storageMigrationCheck": "Verificando migração de estado local...",
      "inputHistoryRestore": "Restaurando histórico de entrada...",
      "interfaceResources": "Carregando recursos da interface...",
      "mountShell": "Montando o shell do cliente...",
      "localStorageMigrationFailed": "Falha na migração de estado local. A inicialização continua em modo degradado.",
      "ready": "Inicialização do cliente concluída.",
      "failed": "Falha na inicialização do cliente. Recarregue e tente novamente."
    },
    "runtime": {
      "startupPending": "{{workspace}}: o runtime {{engine}} está conectando...",
      "resumePending": "{{workspace}}: falha na verificação de integridade do runtime. Tentando recuperação.",
      "ready": "{{workspace}}: o runtime {{engine}} está conectado",
      "suspectStale": "{{workspace}}: falha na verificação de integridade do runtime. Tentando recuperação.",
      "cooldown": "{{workspace}}: falha na recuperação do runtime. O período de espera está ativo.",
      "quarantined": "{{workspace}}: falha na recuperação do runtime, requer atenção.",
      "codexSessionStartHookSkipped": "O Codex ignorou o hook SessionStart do projeto e criou a sessão. Inspecione `.codex/hooks.json`; o contexto do projeto pode estar incompleto. ({{reason}})"
    },
    "startup": {
      "taskStarted": "Carga em segundo plano iniciada: {{task}} ({{phase}} / {{workspace}})",
      "taskCompleted": "Carga em segundo plano concluída: {{task}} ({{durationMs}}ms)",
      "taskFailed": "Falha na carga em segundo plano: {{task}}",
      "taskTimedOut": "Tempo esgotado na carga em segundo plano: {{task}}. O caminho degradado está ativo.",
      "taskDegraded": "Carga em segundo plano degradada: {{task}} ({{reason}})",
      "taskCancelled": "Carga em segundo plano cancelada: {{task}} ({{reason}})",
      "commandCompleted": "Comando interno concluído: {{command}} ({{workspace}} / {{durationMs}}ms)",
      "commandFailed": "Falha no comando interno: {{command}} ({{workspace}} / {{durationMs}}ms)",
      "shellReady": "O shell do cliente está pronto",
      "inputReady": "A entrada está interativa",
      "activeWorkspaceReady": "A primeira tela do workspace ativo está pronta"
    },
    "engine": {
      "checking": "Verificando o status do {{engine}}...",
      "ready": "{{engine}} está pronto",
      "unavailable": "{{engine}} não está instalado. Instale-o primeiro.",
      "requiresLogin": "{{engine}} requer login"
    },
    "codex": {
      "providerSelected": "{{name}} selecionado. Clique na entrada do Codex para criar uma sessão."
    },
    "claude": {
      "resumeCommandCopied": "Comando de retomada do Claude copiado. Se o seletor /resume do TUI não mostrar esta sessão da GUI, execute claude --resume {{sessionId}} ou /resume {{sessionId}} explicitamente."
    },
    "error": {
      "createSessionRecoveryRequired": "{{workspace}}: falha na criação da sessão enquanto a recuperação do runtime está em andamento",
      "threadTurnFailed": "Falha na sessão {{engine}}: {{message}}",
      "codexSessionRecoverableFailure": "Conexão do Codex interrompida: o vínculo da sessão anterior ou a conexão do runtime não é mais utilizável. Tente novamente ou reconecte."
    }
  }
};

export default runtimeNotice;
