// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "Buscar arquivos, kanban, threads, mensagens, skills, comandos...",
    "placeholderFiltered": "Buscar {{content}}...",
    "inputAria": "Campo de busca",
    "scope": "Escopo",
    "content": "Conteúdo",
    "current": "Atual",
    "global": "Global",
    "currentWorkspace": "Workspace atual",
    "allWorkspaces": "Todos os workspaces",
    "noResults": "Nenhum resultado",
    "noResultsHint": "Tente palavras-chave do caminho do arquivo, título da tarefa, título da thread, texto da mensagem, nome da skill ou nome do comando.",
    "fileIndexLoading": "Concluindo o índice de arquivos...",
    "fileIndexPartial": "O índice de arquivos está parcial; alguns arquivos podem estar ausentes.",
    "fileIndexError": "Falha ao carregar o índice. Reabra a busca para tentar novamente.",
    "navigate": "Navegar",
    "open": "Abrir",
    "close": "Fechar",
    "projectTag": "Projeto",
    "typeTag": "Tipo",
    "sourceTag": "Fonte",
    "locationTag": "Local",
    "typeAction": "Ação",
    "typeFile": "Arquivo",
    "typeKanban": "Kanban",
    "typeThread": "Thread",
    "typeMessage": "Mensagem",
    "typeHistory": "Histórico",
    "typeSkill": "Skill",
    "typeCommand": "Comando",
    "sourceActions": "Ações do aplicativo",
    "sourceFiles": "Índice de arquivos",
    "sourceKanban": "Dados do kanban",
    "sourceThreads": "Títulos das threads",
    "sourceMessages": "Conteúdo das mensagens",
    "sourceHistory": "Histórico de entrada",
    "sourceSkills": "Lista de skills",
    "sourceCommands": "Lista de comandos",
    "contentAll": "Tudo",
    "contentActions": "Ações",
    "contentFiles": "Arquivos",
    "contentKanban": "Kanban",
    "contentThreads": "Threads",
    "contentMessages": "Mensagens",
    "contentHistory": "Histórico",
    "contentSkills": "Skills",
    "contentCommands": "Comandos"
  }
};

export default searchPalette;
