// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
const taskCenter = {
  "taskCenter": {
    "title": "Central de Tarefas",
    "eyebrow": "Execuções de Agent",
    "workspaceHero": "Execução que precisa de atenção agora",
    "statusFilter": "Status",
    "engineFilter": "Motor",
    "filterAll": "Todos",
    "empty": "Nenhuma execução de tarefa ainda",
    "summary": "{{attention}} de {{total}} execuções precisam de atenção",
    "openedFromProjectMap": "Execução vinculada aberta a partir da fila de trabalho do Mapa do Projeto. Esta página mostra o detalhe real do TaskRun; se nenhuma ação de conversa aparecer, esta Execução ainda não está vinculada a uma sessão real.",
    "trigger": "Acionar",
    "updatedAt": "Atualizado",
    "currentStep": "Etapa atual",
    "latestOutput": "Saída mais recente",
    "diagnostics": "Diagnósticos",
    "artifacts": "Artefatos",
    "browserEvidence": "Evidência do navegador",
    "unavailable": "Indisponível",
    "noArtifacts": "Nenhum artefato ainda",
    "noBrowserEvidence": "Nenhuma evidência do navegador vinculada",
    "browserEvidenceCandidates": "candidatos",
    "source": {
      "kanban": "kanban",
      "orchestration": "orquestração"
    },
    "browserEvidenceState": {
      "available": "disponível",
      "stale": "desatualizada",
      "expired": "expirada",
      "degraded": "degradada",
      "deleted": "excluída",
      "unsupported": "não suportada"
    },
    "status": {
      "queued": "Na fila",
      "planning": "Planejando",
      "running": "Em execução",
      "waiting_input": "Aguardando entrada",
      "blocked": "Bloqueado",
      "failed": "Falhou",
      "completed": "Concluído",
      "canceled": "Cancelado"
    },
    "action": {
      "openConversation": "Abrir conversa",
      "openOrchestrationTask": "Abrir tarefa de orquestração",
      "retry": "Tentar novamente",
      "resume": "Retomar",
      "cancel": "Cancelar",
      "fork": "Bifurcar execução"
    },
    "nextStep": {
      "monitor": "Esta execução ainda está em andamento. Monitore a etapa atual ou cancele se necessário.",
      "openConversation": "Abra a conversa vinculada em seguida para fornecer entrada ou inspecionar a saída mais recente.",
      "resume": "Esta execução está bloqueada. Retome-a primeiro para continuar o caminho atual.",
      "retry": "Esta execução falhou. Tente novamente em seguida ou inspecione o resumo da falha.",
      "wait": "Nenhuma ação é necessária no momento. Deixe a execução estabilizar primeiro.",
      "review": "Revise os diagnósticos e artefatos primeiro e depois decida o próximo passo.",
      "fork": "Você pode bifurcar uma nova execução a partir do resultado atual para continuar."
    }
  }
};

export default taskCenter;
