// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {
  "time": {
    "justNow": "agora mesmo",
    "minuteAgo": "há {{count}} minuto",
    "minutesAgo": "há {{count}} minutos",
    "hourAgo": "há {{count}} hora",
    "hoursAgo": "há {{count}} horas",
    "dayAgo": "há {{count}} dia",
    "daysAgo": "há {{count}} dias",
    "weekAgo": "há {{count}} semana",
    "weeksAgo": "há {{count}} semanas",
    "now": "agora",
    "shortSecondsAgo": "há {{value}}s",
    "shortSecondsIn": "em {{value}}s",
    "shortMinutesAgo": "há {{value}}min",
    "shortMinutesIn": "em {{value}}min",
    "shortMinutes": "{{value}}min",
    "shortHours": "{{value}}h",
    "shortDays": "{{value}}d",
    "shortWeeks": "{{value}}sem",
    "shortMonths": "{{value}}mês",
    "shortYears": "{{value}}a"
  }
};

export default time;
