// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
const tools = {
  "tools": {
    "readFile": "Ler arquivo",
    "readDirectory": "Ler diretório",
    "editFile": "Editar arquivo",
    "writeFile": "Gravar arquivo",
    "editNotebook": "Editar notebook",
    "runCommand": "Executar comando",
    "executeCommand": "Executar comando",
    "search": "Buscar",
    "fileMatch": "Correspondência de arquivo",
    "findFile": "Localizar arquivo",
    "webFetch": "Busca na web",
    "webSearch": "Pesquisa na web",
    "subtask": "Subtarefa",
    "todoList": "Lista de tarefas",
    "userInputRequest": "Perguntar ao usuário",
    "diffCompare": "Diff",
    "result": "Resultado",
    "claudeControlResumeFailed": "Falha ao retomar",
    "claudeControlModelChanged": "Modelo alterado",
    "claudeControlInterrupted": "Interrompido",
    "claudeControlLocalOutput": "Saída do comando local",
    "webRequest": "Solicitação web",
    "batchRun": "Execução em lote",
    "searchMatch": "Buscar/Corresponder",
    "batchReadFile": "Ler arquivos em lote",
    "batchSearch": "Buscar em lote",
    "batchSearchMatch": "Buscar/corresponder em lote",
    "batchEditFile": "Editar arquivos em lote",
    "bashGroupBatchRun": "Executar comandos em lote",
    "bashGroupCompleted": "concluído",
    "bashGroupAllCompleted": "Todos concluídos",
    "bashGroupFailed": "falhou",
    "planQuickView": "Plano",
    "openFullPlanPanel": "Abrir painel de Plano completo",
    "closePlanPanel": "Fechar painel de Plano",
    "path": "Caminho",
    "lineRange": "Linha {{start}}-{{end}}",
    "failedCount": "{{count}} falharam"
  }
};

export default tools;
