// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {"update":{"title":"Atualização","checkingForUpdates":"Verificando atualizações...","updateAvailable":"Uma nova versão está disponível!","upToDate":"Você está atualizado.","downloading":"Baixando atualização…","installing":"Instalando atualização…","restarting":"Reiniciando…","failed":"A atualização falhou.","downloaded":"baixado","releaseNotesTitle":"Notas de versão","releaseNotesLoading":"Carregando notas de versão…","releaseNotesLoadFailed":"Falha ao carregar as notas de versão.","releaseNotesEmpty":"Nenhuma nota de versão ainda.","releaseNotesOpenInGitHub":"Ver no GitHub","releaseNotesPrev":"Anterior","releaseNotesNext":"Próxima","releaseNotesPage":"{{current}} / {{total}}","releaseNotesEnglish":"Inglês:","releaseNotesChinese":"中文："}};

export default update;
