// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
const activityPanel = {
  "activityPanel": {
    "title": "セッションアクティビティ",
    "noRoot": "現在のタスク",
    "selectWorkspace": "セッションアクティビティを確認するワークスペースを選択してください。",
    "emptyIdle": "セッションアクティビティはまだありません。",
    "emptyRunning": "セッションアクティビティを待機中...",
    "emptyCompleted": "このタスクはフェーズ1で追跡されたアクティビティなしで完了しました。",
    "eventsCount": "{{count}} 件のイベント",
    "sessionsCount": "{{count}} 件のセッション",
    "liveNow": "ライブ",
    "command": "コマンド",
    "commandPendingSummary": "コマンド実行中",
    "commandCategories": {
      "command": "コマンド",
      "search": "検索",
      "read": "読み取り",
      "list": "一覧",
      "git": "Git",
      "test": "テスト",
      "lint": "Lint",
      "build": "ビルド",
      "run": "実行"
    },
    "description": "説明",
    "cwd": "作業ディレクトリ",
    "waitingForOutput": "コマンド出力を待機中...",
    "waitingForReasoning": "思考内容を待機中...",
    "rootSession": "ルート",
    "childSession": "子",
    "relatedSessions": "関連",
    "fallbackLinking": "フォールバックリンク",
    "liveEditPreview": "ライブプレビュー",
    "liveEditFollowLabel": "ライブ追従",
    "liveEditPreviewTooltip": "AI が現在編集中のファイルをリアルタイムで開くには有効にします。",
    "enableLiveEditPreview": "ライブ編集プレビューを有効化",
    "disableLiveEditPreview": "ライブ編集プレビューを無効化",
    "followCoachTitle": "ライブ追従を試す",
    "followCoachBody": "オンにすると AI が編集中のファイルを追従します。",
    "followCoachEnable": "今すぐ有効化",
    "followCoachDismiss": "後で",
    "followNudgeTitle": "ライブ追従",
    "followNudgeErrorTitle": "有効化に失敗",
    "followNudgeBody": "AI がファイルを編集しています。ライブ追従を有効化しますか？",
    "followNudgeEnable": "有効化",
    "followNudgeLater": "後で",
    "followNudgeRetry": "再試行",
    "followToggleFailed": "ライブ追従の切り替えに失敗しました。もう一度お試しください。",
    "showOutput": "出力を表示",
    "hideOutput": "出力を非表示",
    "expandTurnGroup": "ターングループを展開",
    "collapseTurnGroup": "ターングループを折りたたむ",
    "turnGroup": "ターン {{index}}",
    "turnGroupFallback": "旧アクティビティ",
    "tabs": {
      "ariaLabel": "セッションアクティビティのカテゴリ",
      "all": "サマリー",
      "command": "コマンド",
      "file": "成果物",
      "task": "タスク",
      "subagent": "サブエージェント",
      "explore": "探索",
      "reasoning": "思考"
    },
    "artifacts": {
      "kicker": "ターンの成果物",
      "title": "成果物",
      "fileCount": "{{count}} ファイル",
      "fileCount_other": "{{count}} ファイル",
      "turnSemanticTitle": "ターンの意味",
      "tabsAriaLabel": "ターン成果物ビュー",
      "tabs": {
        "artifacts": "成果物",
        "semantic": "セマンティック差分"
      }
    },
    "radar": {
      "modeCurrentTask": "現在のタスク",
      "modeWorkspaceRadar": "ワークスペースレーダー",
      "runningSection": "実行中 ({{count}})",
      "recentSection": "最近完了 ({{count}})",
      "emptyRunning": "実行中のセッションはありません。",
      "emptyRecent": "最近完了したセッションはありません。",
      "openSession": "開く",
      "runningCountAria": "{{count}} 件の実行中セッション",
      "recentCountAria": "{{count}} 件の最近のセッション",
      "startedAt": "開始:",
      "endedAt": "終了:",
      "totalDuration": "所要時間:",
      "timeUnknown": "--:--:--",
      "durationUnknown": "--",
      "unreadBadge": "NEW",
      "unreadMark": "未読",
      "readMark": "既読",
      "deleteHistoryEntry": "{{name}} を削除",
      "deleteDateGroupEntries": "{{date}} の {{count}} 件すべてを削除"
    },
    "status": {
      "running": "実行中",
      "completed": "完了",
      "failed": "失敗",
      "pending": "保留中"
    }
  }
};

export default activityPanel;
