// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
const agentOrchestration = {
  "agentOrchestration": {
    "title": "プロジェクトマップ作業キュー",
    "eyebrow": "プロジェクトマップキュー",
    "summary": "{{workspace}} · {{total}} 件の作業項目 · {{providers}} 件のソースが利用可能",
    "workspaceUnknown": "不明なワークスペース",
    "loadingTitle": "オーケストレーションビューを読み込み中",
    "loadingDescription": "プロジェクトマップの候補、既存のタスクドラフト、TaskRun コンテキストを集約しています。",
    "emptyTitle": "このワークスペースにはまだオーケストレーションタスクがありません",
    "emptyDescription": "現在このビューには既存のオーケストレーションコンテキストと実行状況のみが表示されます。タスク作成のエントリーポイントはタスクモジュールの再設計後に復帰します。",
    "degradedTitle": "一部のプロバイダーが劣化しています",
    "unavailable": "利用不可",
    "noRefs": "ソース参照なし",
    "noEvidenceRefs": "エビデンス参照なし",
    "noRisks": "リスクマーカーなし",
    "status": {
      "candidate": "候補",
      "planned": "計画済み",
      "ready": "準備完了",
      "running": "実行中",
      "waiting_input": "入力待ち",
      "blocked": "ブロック中",
      "review_needed": "レビューが必要",
      "completed": "完了",
      "archived": "アーカイブ済み"
    },
    "queueStatus": {
      "todo": "未着手",
      "queued": "キュー登録済み",
      "running": "実行中",
      "failed": "失敗",
      "dispatched": "ディスパッチ済み",
      "review": "レビューが必要",
      "done": "完了",
      "archived": "アーカイブ済み"
    },
    "action": {
      "backToProjectMap": "プロジェクトマップに戻る"
    },
    "manual": {
      "open": "手動タスクを追加",
      "eyebrow": "手動ソース",
      "title": "手動タスクを作成",
      "description": "手動タスクは検証済みのエビデンスを作り出しません。ディスパッチ前にスコープと受け入れ基準を追加してください。",
      "fieldTitle": "タイトル",
      "fieldScope": "スコープ",
      "fieldAcceptance": "受け入れ基準",
      "fieldPrompt": "プロンプト",
      "cancel": "キャンセル",
      "create": "タスクを作成"
    },
    "actions": {
      "label": "タスクアクション",
      "openSource": "ソースを開く",
      "openSourceLabel": "{{title}} のソースを開く",
      "openRun": "タスクセンターで Run を表示",
      "openRunLabel": "タスクセンターで {{title}} のリンクされた Run を表示",
      "openSession": "セッションを開く",
      "openSessionLabel": "{{title}} のリンクされたセッションを開く",
      "cancelQueuedRun": "ディスパッチをキャンセル",
      "archive": "アーカイブ",
      "writeBack": "プロバイダーに書き戻す",
      "writeBackDisabled": "プロバイダーへの書き戻しは今後のアクションです。別の確認フローを経る必要があります。OpenSpec、Trellis、spec-kit、および Agent ルールファイルはここでは変更されません。"
    },
    "queue": {
      "taskLabel": "{{title}}、ステータス {{status}}、プロバイダー {{provider}}、{{risks}} 件のリスクマーカー",
      "riskCount": "{{count}} 件のリスクマーカー",
      "riskOverflow": "+{{count}} 件のリスク"
    },
    "dispatch": {
      "open": "タスクセンターに送信",
      "openLabel": "{{title}} をタスクセンターに送信",
      "eyebrow": "ディスパッチゲート",
      "title": "ディスパッチの確認",
      "description": "まずエンジン、ワークスペース、スレッド戦略、受け入れスコープを設定してください。TaskRun はディスパッチを確認した後にのみ作成されます。",
      "engine": "エンジン",
      "model": "モデル",
      "defaultModel": "デフォルトモデルを使用",
      "workspace": "ワークスペース",
      "status": "ステータス",
      "threadStrategy": "スレッド戦略",
      "promptSummary": "プロンプトの概要",
      "acceptance": "受け入れ基準",
      "sources": "ソース",
      "disabled": "実行はまだ接続されていません。これはディスパッチパラメータをプレビューするだけで、TaskRun は作成されません。",
      "cancel": "キャンセル",
      "confirm": "ディスパッチを確認"
    },
    "review": {
      "label": "レビューアクション",
      "open": "レビュー",
      "openLabel": "{{title}} をレビュー",
      "title": "レビューゲート",
      "description": "リンクされた Run が完了しました。結果を承認するか、変更を依頼するか、フォローアップタスクを作成する前にレビューしてください。",
      "accept": "結果を承認",
      "requestChanges": "変更を依頼",
      "createFollowUp": "フォローアップを作成",
      "missingRunTitle": "実行結果がありません。レビューは利用できません",
      "missingRunDescription": "このタスクはレビュー対象としてマークされていますが、リンクされた Run またはセッションがありません。レビューの前にもう一度ディスパッチしてください。",
      "feedback": {
        "accepted": "結果が承認されました。タスクは完了です。",
        "changesRequested": "変更が依頼されました。タスクは作業キューに戻されました。",
        "followUpCreated": "フォローアップタスクが作成され、選択されました。"
      }
    },
    "filters": {
      "label": "タスクキューフィルター",
      "provider": "プロバイダー",
      "status": "作業ステータス",
      "engine": "エンジン",
      "workspace": "ワークスペース",
      "sourceKind": "ソース種別",
      "risk": "リスク",
      "allProviders": "すべてのプロバイダー",
      "allStatuses": "すべての作業ステータス",
      "allEngines": "すべてのエンジン",
      "allWorkspaces": "すべてのワークスペース",
      "allSourceKinds": "すべてのソース種別",
      "allRisks": "すべてのリスク",
      "noEngine": "エンジンなし",
      "reset": "リセット",
      "visibleSummary": "{{visible}} / {{total}} を表示中",
      "emptyTitle": "現在のフィルターに一致するタスクがありません",
      "emptyDescription": "続行するにはプロバイダー、ステータス、エンジン、ワークスペース、ソース種別、リスクのフィルターを調整してください。"
    },
    "reviewState": {
      "not_started": "未開始",
      "needs_review": "レビューが必要",
      "accepted": "承認済み",
      "changes_requested": "変更依頼済み"
    },
    "threadStrategy": {
      "new_thread": "新しいスレッド",
      "reuse_active_thread": "アクティブなスレッドを再利用",
      "choose_thread": "スレッドを選択"
    },
    "detail": {
      "scope": "スコープ",
      "acceptance": "受け入れ基準",
      "createdAt": "作成日時",
      "updatedAt": "更新日時",
      "providerSources": "プロバイダーソース",
      "evidence": "エビデンス",
      "evidenceCount": "{{count}} 件のエビデンス参照",
      "risks": "リスク",
      "links": "実行リンク",
      "runManagement": "Run / セッション管理",
      "linkCountsLabel": "リンク数",
      "linkCounts": "{{runs}} 件の Run · {{sessions}} 件のセッション",
      "linkedRuns": "リンクされた Run",
      "linkedSessions": "リンクされたセッション",
      "noLinkedRuns": "リンクされた Run はありません",
      "noLinkedSessions": "リンクされたセッションはありません",
      "missingLinkedRun": "リンクされた Run がありません。未着手に戻されました。",
      "linkedRunMissing": "Run レコードがありません",
      "runEngine": "エンジン",
      "runUpdatedAt": "更新日時",
      "runCurrentStep": "現在のステップ",
      "runLatestOutput": "最新の出力",
      "activity": "アクティビティ",
      "reviewState": "レビュー状態",
      "threadStrategy": "スレッド戦略",
      "preferredEngine": "優先エンジン",
      "preferredModel": "優先モデル",
      "parentTask": "親タスク",
      "selectionPreservedTitle": "現在のノードを保持",
      "selectionPreservedDescription": "タスクのステータスは変更されましたが、詳細ペインは操作したノードのまま維持されます。"
    }
  }
};

export default agentOrchestration;
