// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
const app = {"app":{"title":"ccgui","subtitle":"ローカルプロジェクト全体で Agent をオーケストレーションします。"}};

export default app;
