// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
const approval = {
  "approval": {
    "approve": "承認",
    "deny": "拒否",
    "approveAll": "すべて承認",
    "denyAll": "すべて拒否",
    "reviewRequest": "リクエストを確認",
    "approvalNeeded": "承認が必要",
    "pendingBadge": "承認待ち",
    "reviewBeforeApply": "ローカルブリッジが実行する前に、このリクエストを確認してください。",
    "inputRequested": "入力が要求されました",
    "fileChanges": "ファイルの変更",
    "commandExecution": "コマンドの実行",
    "genericApproval": "承認",
    "toolLabel": "ツール",
    "filePathLabel": "ファイルパス",
    "commandLabel": "コマンド",
    "noteLabel": "メモ",
    "none": "なし",
    "noExtraDetails": "追加の詳細はありません。",
    "decline": "却下",
    "close": "閉じる",
    "approveTurnBatch": "このバッチ内のすべてを承認 ({{count}})",
    "allowCommandsStartWith": "{{prefix}} で始まるコマンドを許可",
    "alwaysAllow": "常に許可",
    "approveEnter": "承認 (Enter)",
    "remainingRequests": "他に {{count}} 件の承認リクエストが待機中",
    "applyingApprovedFileChange": "承認されたファイル変更を適用中",
    "resumingAfterApproval": "承認されました。変更をローカルに適用して Claude を再開しています...",
    "userInputRequested": "ユーザー入力が要求されました",
    "requestOf": "リクエスト {{current}} / {{total}}",
    "typeAnswerOptional": "回答を入力（任意）",
    "addNotesOptional": "メモを追加（任意）",
    "noQuestionsProvided": "質問はありません。",
    "showSecret": "表示",
    "hideSecret": "非表示",
    "submitFailed": "送信に失敗しました。もう一度お試しください。",
    "submit": "送信",
    "dismiss": "閉じる",
    "dismissUserInputRequest": "この質問カードを閉じる",
    "collapseUserInputRequest": "スキップせずにこの質問カードを折りたたむ",
    "collapsedUserInputRequest": "折りたたまれた質問カード",
    "expandUserInputRequest": "展開",
    "skipUserInputRequest": "この質問をスキップして続行",
    "skipAndContinue": "この質問をスキップ",
    "submitted": "送信済み",
    "noAnswerProvided": "（回答なし）",
    "noDisplayableAnswer": "（表示可能な回答なし）",
    "userInputSubmittedBanner": "[ユーザー入力が送信されました]"
  }
};

export default approval;
