// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {
  "askUserQuestion": {
    "title": "Claude から質問があります",
    "progress": "質問 {{current}} / {{total}}",
    "timeoutWarning": "早めにご回答ください。このダイアログは {{seconds}} 秒後に自動的に閉じます",
    "collapse": "折りたたむ",
    "expand": "展開",
    "clickToAnswer": "クリックして回答",
    "questionTab": "質問 {{index}}",
    "cancel": "キャンセル",
    "back": "戻る",
    "next": "次へ",
    "submit": "送信",
    "otherOption": "その他",
    "otherOptionDesc": "カスタム回答を入力",
    "customInputPlaceholder": "回答を入力...",
    "multiSelectHint": "複数のオプションを選択できます"
  }
};

export default askUserQuestion;
