// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
const browserAgent = {
  "browserAgent": {
    "dock": {
      "description": "まずページの主要な情報を読み取り、その後ナビゲーションと要素操作を段階的に有効化します。",
      "disabled": "無効",
      "statusDisconnected": "切断",
      "statusLoading": "読み込み中",
      "statusReady": "読み取り可能",
      "statusClosed": "クローズ済み",
      "statusNeedsAttention": "対応が必要",
      "statusPreparing": "準備中",
      "emptyUrl": "開くページの URL を入力してください。",
      "blockedUrl": "この URL は Browser Agent のポリシーによりブロックされています。",
      "opened": "Browser Agent がブラウザタブを開きました。",
      "closed": "Browser Agent のタブが閉じられました。",
      "busy": "処理中",
      "open": "開く",
      "enable": "有効化",
      "enabled": "Browser Agent が有効になりました。",
      "tabs": "ブラウザタブ",
      "newTab": "新しいブラウザタブ",
      "openDock": "ブラウザ",
      "panelTitle": "ブラウザドック",
      "panelKicker": "ここでページを開き、必要に応じてそのコンテキストを AI に添付します。",
      "noWorkspace": "ブラウザドックを開く前にワークスペースを選択してください。",
      "noPage": "Browser Agent ウィンドウを起動するには、許可された http/https ページを開いてください。",
      "rendering": "Browser Agent ウィンドウでページをレンダリング中...",
      "windowOpened": "ページは別の Browser Agent ウィンドウで開かれています。",
      "closePanel": "ブラウザドックを閉じる",
      "close": "Browser Agent セッションを閉じる",
      "info": "Browser Agent の詳細を表示",
      "footnote": "MVP では生の DOM、Cookie、ヘッダー、ページのシークレットを保存しません。"
    },
    "composer": {
      "attach": "ブラウザコンテキストを添付",
      "attaching": "ブラウザコンテキストを添付中...",
      "attached": "ブラウザコンテキストを添付しました",
      "visibleSnapshot": "ブラウザの表示ページスナップショット",
      "selectedElement": "選択したページ要素",
      "selectedElementCount": "{{count}} 件の選択したページ要素",
      "selectedElementFacts": "選択したページ要素の情報",
      "selectedElementMore": "他に {{count}} 件の要素",
      "selectorHint": "セレクター {{selector}}",
      "noRawApi": "API の生データではありません",
      "remove": "削除",
      "refresh": "ブラウザコンテキストを更新",
      "fresh": "準備完了",
      "stale": "更新",
      "expired": "期限切れ",
      "degraded": "劣化",
      "unsupported": "非対応",
      "showDetails": "キャプチャの詳細を表示",
      "hideDetails": "詳細を非表示",
      "countSummary": "ページ要素数",
      "headingCount": "見出し {{count}}",
      "linkCount": "リンク {{count}}",
      "buttonCount": "ボタン {{count}}",
      "formCount": "フォーム {{count}}",
      "readableBlockCount": "読み取り可能ブロック {{count}}",
      "visualEvidenceCount": "視覚的手がかり {{count}}",
      "counts": "見出し {{headings}} · リンク {{links}} · ボタン {{buttons}} · フォーム {{forms}} · 読み取り可能ブロック {{readableBlocks}} · 視覚的手がかり {{visualEvidence}} · コード候補 {{candidates}}",
      "primaryContent": "メインコンテンツ",
      "readableBlocks": "読み取り可能ブロック {{count}}",
      "visualEvidence": "視覚的手がかり {{count}}",
      "codeCandidates": "コード候補 {{count}}",
      "privacy": "{{redacted}} 種類の墨消し、{{omitted}} 種類の機密ソースを省略しました。",
      "noSession": "アクティブな Browser Agent セッションがありません。まずブラウザドックでページを開いてください。"
    }
  }
};

export default browserAgent;
