// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
const claudeModes = {"claudeModes":{"default":{"label":"提案モード（プレビュー）","tooltip":"Claude Code のプレビュー承認モード。完全な承認ブリッジが完成するまで、一部のフローは依然として劣化する場合があります。","description":"Claude のデフォルト権限フローを検証するためのプレビューとして利用可能になりました。劣化したパスに遭遇した場合、UI はユーザーをプランモードに誘導する必要があります。"},"plan":{"label":"プランモード","tooltip":"Claude Code の読み取り専用分析モード。","description":"アクションを起こす前に、読み取り専用ツールを使用して分析と計画を行います。"},"acceptEdits":{"label":"自動編集","tooltip":"Claude Code の自動編集モード。現在のロールアウト段階では有効化されていません。","description":"このモードは、Claude の承認セマンティクスが検証されるまで利用できません。"},"bypassPermissions":{"label":"フルオート","tooltip":"権限チェックをスキップする Claude Code モード。","description":"承認なしでファイル書き込みやコマンドを実行します。注意して使用してください。"}}};

export default claudeModes;
