// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
const codexModes = {
  "codexModes": {
    "default": {
      "label": "提案（承認あり）",
      "tooltip": "Codex approval_policy=untrusted – ファイル編集やシェルコマンド実行の前に確認します。",
      "description": "最も安全な選択肢。すべての書き込みやコマンドに承認が必要です。"
    },
    "plan": {
      "label": "プランモード",
      "tooltip": "プランモード - 読み取り専用の分析",
      "description": "読み取り専用ツールのみを使用し、ユーザー承認用のプランを生成します"
    },
    "acceptEdits": {
      "label": "自動編集",
      "tooltip": "Codex approval_policy=auto-edit – ファイルパッチを自動適用しますが、シェルコマンドの前には確認します。",
      "description": "apply_patch でファイルの自動作成・編集を行い、コマンドの承認は維持します。"
    },
    "bypassPermissions": {
      "label": "フルオート",
      "tooltip": "Codex approval_policy=never – 確認なしでコマンド実行とファイル書き込みを行います（ワークスペースサンドボックスは引き続き適用）。",
      "description": "ハンズオフモード。Codex が編集とシェルコマンドを即座に実行します。"
    }
  }
};

export default codexModes;
