// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {
  "debug": {
    "title": "デバッグ",
    "copyLogs": "ログをコピー",
    "clearLogs": "ログをクリア",
    "noLogs": "デバッグログがありません",
    "copy": "コピー",
    "clear": "クリア",
    "noDebugEventsYet": "まだデバッグイベントがありません。"
  }
};

export default debug;
