// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/engineTaskOutput.ts; keys mirror the English source.
const engineTaskOutput = {"engineTaskOutput":{"label":"タスク出力インスペクター","inspect":"出力を表示","close":"タスク出力を閉じる","engine":"{{engine}} タスク","identity":"識別情報","telemetry":"Token","recentOutput":"最近の出力","refresh":"更新","refreshing":"更新中","pending":"保留中","telemetryPending":"信頼できる Token データはまだありません","outputUnavailable":"まだ出力がありません。タスクがまだ実行中か、このエンジンがライブのタスク出力を公開していない可能性があります。","artifactLive":"タスク出力ファイルから更新されました。","artifactTruncated":"出力が長いため、最新のセグメントを表示しています。","artifactUnavailable":"ライブ出力を利用できません。現在のスナップショットを保持します。","status":{"running":"実行中","completed":"完了","error":"エラー","unavailable":"利用不可"},"tokens":{"input":"入力","cached":"キャッシュ済み","output":"出力","total":"合計"},"telemetryStatus":{"live":"ライブデータ","estimated":"推定データ","pending":"データ待機中","unavailable":"データ利用不可"}}};

export default engineTaskOutput;
