// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "接続に失敗しました",
    "requestFailed": "リクエストに失敗しました",
    "unexpectedError": "予期しないエラーが発生しました",
    "sessionExpired": "セッションの有効期限が切れました",
    "rateLimited": "レート制限に達しました。後でもう一度お試しください。",
    "networkError": "ネットワークエラーです。接続を確認してください。",
    "failedToAddWorkspace": "ワークスペースの追加に失敗しました。",
    "failedToOpenNewWindow": "新しいウィンドウを開けませんでした。",
    "failedToCreateSession": "セッションの作成に失敗しました。",
    "failedToCreateSessionNoThreadId": "ランタイムが新しいセッション ID を返しませんでした。",
    "failedToCreateSessionRuntimeRecovering": "このセッションの作成中にランタイムが再起動していました。アプリはすでに一度再試行しました。ワークスペースを再接続して、もう一度お試しください。",
    "reconnectAndRetryCreateSession": "再接続して作成を再試行",
    "reconnectingAndRetryingCreateSession": "再接続して作成を再試行中...",
    "runtimeRecovered": "ランタイムが復旧しました。",
    "retryingCreateSessionAfterRecovery": "セッションの作成を再試行中...",
    "cliNotFound": "Claude Code CLI と Codex CLI のどちらも見つかりませんでした。いずれかをインストールしてください。",
    "cliNotFoundHint": "Claude Code をインストール：curl -fsSL https://claude.ai/install.sh | bash\nCodex をインストール：npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI が見つかりません。Codex をインストールし、`codex` が PATH に含まれていることを確認してください。",
    "couldntOpenWorkspace": "ワークスペースを開けませんでした",
    "dismissError": "エラーを閉じる"
  }
};

export default errors;
