// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
const homeChat = {
  "homeChat": {
    "badge": "ワークスペース対応チャットホーム",
    "minimalTitle": "何でも作成",
    "announcementTag": "新機能",
    "announcementText": "ランディングテンプレート、ワークフローカード、スタータープロンプトを探索",
    "announcementAction": "見つける",
    "title": "ccgui Agent で作業をもっと簡単に",
    "titleLineOne": "Enter を押して",
    "titleLineTwo": "アプリをより速く構築",
    "subtitle": "使い慣れたコンポーザーはそのままに、その周りにより力強いランディングのリズムを加え、セットアップの手間を減らして実際の実行へ移行します。",
    "promptPlaceholder": "目標を記述してください。例: このリポジトリのリリースノートを生成し、リスクチェックを含める。",
    "pathResolving": "デフォルトのプロジェクトパスを解決中...",
    "workspaceSearchPlaceholder": "プロジェクトを検索",
    "addWorkspaceAction": "新しいプロジェクトを追加",
    "workspaceNoMatch": "プロジェクトが見つかりません",
    "loadingRecentAgents": "最近の作業を読み込み中",
    "recentConversations": "最近の会話",
    "quickActions": "クイックアクション",
    "placeholderHint": "これらのエントリポイントは現時点では視覚的なプレースホルダーです。",
    "placeholderSelected": "{{label}} は近日公開予定です。",
    "seeAll": "すべて表示",
    "navPrev": "前のカード",
    "navNext": "次のカード",
    "comingSoon": "近日公開",
    "tabs": {
      "templates": "テンプレート",
      "workflows": "ワークフロー"
    },
    "quick": {
      "plan": "概要から計画",
      "doc": "ドキュメント",
      "release": "リリースノート",
      "review": "リポジトリをレビュー",
      "spec": "仕様のドラフト"
    },
    "cards": {
      "website": {
        "title": "ウェブサイト公開キット",
        "description": "洗練された公開ページのためのヒーローレイアウト、構成、スターターコピー。"
      },
      "creator": {
        "title": "クリエイターダッシュボード",
        "description": "コンテンツ、トラフィック、プロンプトのための分析優先のコントロールルーム。"
      },
      "audio": {
        "title": "オーディオランディング",
        "description": "音楽、ポッドキャスト、メディア公開のためのソフトなグラデーションと大胆な指標。"
      },
      "editorial": {
        "title": "エディトリアルマニフェスト",
        "description": "キャンペーン、声明、ブランドショーケースのためのポスター風タイポグラフィ。"
      },
      "release": {
        "title": "リリースチェックリスト",
        "description": "変更、検証、ノート、ロールアウトのフォローアップを段階的に引き継ぎます。"
      },
      "research": {
        "title": "リサーチスプリント",
        "description": "質問を集め、情報源を調査し、次のアクションへと統合します。"
      },
      "debug": {
        "title": "デバッグデスク",
        "description": "ログのトリアージ、リグレッションの絞り込み、検証済み修正の記録。"
      },
      "content": {
        "title": "コンテンツパイプライン",
        "description": "一貫したチェックポイントで概要作成、下書き、レビュー、公開を行います。"
      }
    }
  }
};

export default homeChat;
