// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {
  "layout": {
    "resizeGitHistoryPanel": "Git 履歴パネルのサイズを変更",
    "resizeSidebar": "サイドバーのサイズを変更",
    "resizeRightPanel": "右パネルのサイズを変更",
    "resizeEditorSplit": "エディタ分割のサイズを変更",
    "resizeNoteCardsSplit": "会話とノートの分割サイズを変更",
    "resizePlanPanel": "プランパネルのサイズを変更",
    "resizeRuntimeConsole": "実行コンソールのサイズを変更",
    "resizeProjects": "プロジェクトのサイズを変更"
  }
};

export default layout;
