// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/lockScreen.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/lockScreen.ts; keys mirror the English source.
const lockScreen = {
  "lockScreen": {
    "lock": "画面をロック",
    "locked": "ロック中",
    "brandKicker": "Codemoss プロダクトアトラス",
    "title": "ccgui セキュアロック · エンジニアリング機能概要",
    "description": "スレッドとタスクはバックグラウンドで実行され続けます。このロック画面で ccgui のデリバリーループ全体（計画、実行のオーケストレーション、レビュー、出荷）を確認できます。",
    "tabLabel": "ロック画面のタブナビゲーション",
    "tabs": {
      "live": "ライブセッション",
      "capabilities": "機能アトラス",
      "workflow": "デリバリーフロー",
      "elements": "エレメントガイド"
    },
    "liveTitle": "ライブセッションストリーム",
    "liveDesc": "実行中のセッション出力のみを表示し、最新のアクティビティで自動更新されます。",
    "liveEmpty": "現在、実行中のセッション出力はありません。",
    "liveRunning": "実行中",
    "capabilityTitle": "機能アトラス",
    "capabilityDesc": "ccgui は単なるチャットシェルではありません。本番フローのために設計された、ローカルファーストのエンジニアリングワークスペースです。",
    "journeyTitle": "典型的なデリバリージャーニー",
    "journeyDesc": "ほとんどの変更は ccgui でこの流れに沿って進みます:",
    "elementsTitle": "エレメントガイド",
    "elementsDesc": "このページで各コアモジュールとその役割をすばやく確認できます。",
    "unlockTitle": "ロック解除パネル",
    "unlockDesc": "パスワードファイルは ~/.ccgui/client/pwd.txt です。存在しない場合はロック解除が許可され、デフォルト値でファイルが自動作成されます。",
    "passwordInput": "ロック解除パスワードを入力",
    "passwordPlaceholder": "パスワードを入力",
    "passwordHint": "パスワードを入力後、Enter を押すかロック解除をクリックしてください。",
    "unlock": "ロック解除",
    "invalidPassword": "パスワードが正しくありません。もう一度お試しください。",
    "storageTitle": "パスワードの保存場所",
    "storageDesc": "パスワードを変更するには、このファイルの内容を直接編集して保存してください。",
    "storagePathLabel": "ファイルパス",
    "facts": {
      "integrationsLabel": "マルチエンジンルーティング",
      "integrationsValue": "Codex / Claude / Gemini",
      "workflowLabel": "デリバリーループ",
      "workflowValue": "計画 → 実行 → レビュー → 出荷",
      "runtimeLabel": "ランタイム状態",
      "runtimeValue": "ロック画面は実行中の処理を停止しません"
    },
    "journey": {
      "planTitle": "まず計画",
      "planDesc": "コードに触れる前に、スコープ、制約、タスク分解を定義します。",
      "executeTitle": "コンテキストを伴う実行",
      "executeDesc": "ワークスペースとスレッドのコンテキストを使い、Kanban のタスク割り当てと並列セッションで実行します。",
      "reviewTitle": "トレース付きレビュー",
      "reviewDesc": "ツールのトレース、差分、デバッグ記録を可視化し、確実な検証を行います。",
      "deliverTitle": "きれいにデリバリー",
      "deliverDesc": "コミット、ブランチ、PR 操作、アーカイブの各ステップを再利用可能なチーム資産につなげます。"
    },
    "features": {
      "workspaceGraphTitle": "ワークスペースグラフ",
      "workspaceGraphDesc": "リポジトリ、Worktree、グループ化、並び順を管理し、コンテキストをすばやく切り替えます。",
      "threadOrchestrationTitle": "スレッドオーケストレーション",
      "threadOrchestrationDesc": "履歴の再生、プロンプトのキュー、中断、自動タイトル、長時間実行の継続をサポートします。",
      "engineRoutingTitle": "エンジンルーティング",
      "engineRoutingDesc": "モデル、推論の労力、アクセスモード、コラボレーションモードを切り替え、各タスクに合わせます。",
      "gitIntelligenceTitle": "Git インテリジェンス",
      "gitIntelligenceDesc": "Diff、Log、Commit、PR、Issue のビューを 1 つのワークフローにまとめ、コンテキストの切り替えを不要にします。",
      "kanbanDispatchTitle": "Kanban ディスパッチ",
      "kanbanDispatchDesc": "タスクからセッションを作成し、実行状態をボードの進捗と同期させます。",
      "memoryEngineTitle": "メモリエンジン",
      "memoryEngineDesc": "プロジェクトの知識や設定を保持し、今後のセッションをコンテキスト付きで開始できます。",
      "unifiedSearchTitle": "統合検索",
      "unifiedSearchDesc": "ファイル、スレッド、メッセージ、スキル、コマンドを横断する 1 つのパレット。",
      "terminalObservabilityTitle": "ターミナル + 可観測性",
      "terminalObservabilityDesc": "組み込みのターミナルとデバッグトレースにより、トラブルシューティングを高速かつ監査可能にします。",
      "composerControlTitle": "コンポーザーコントロール",
      "composerControlDesc": "プリセット、ショートカット、フェンスルール、貼り付け動作、音声入力を一元管理します。",
      "promptAssetsTitle": "プロンプトアセット",
      "promptAssetsDesc": "ワークスペース／グローバルのプロンプトアセットを管理し、デリバリータスク全体で再利用します。",
      "collaborationModeTitle": "コラボレーションモード",
      "collaborationModeDesc": "探索、実装、レビューの各段階に合わせてコラボレーション戦略を切り替えます。",
      "openEcosystemTitle": "オープンなエコシステム",
      "openEcosystemDesc": "外部連携（Open-in）、プラグイン対応の拡張ポイント、外部ツールとの相互運用性を提供します。"
    },
    "elements": {
      "titlebarTitle": "タイトルバーコントロール",
      "titlebarDesc": "プロジェクト切り替え、ブランチ操作、Open-in オプション、ロックトリガー、スレッドコピーを 1 つの列にまとめます。",
      "sidebarTitle": "ワークスペースサイドバー",
      "sidebarDesc": "ワークスペース／Worktree のグループ、スレッド一覧、検索フィルター、プロジェクトコンテキストのすばやい切り替えを管理します。",
      "composerTitle": "コンポーザーワークスペース",
      "composerDesc": "リッチな入力、コードフェンス、コマンド、音声入力、コンテキスト構築を 1 つのエディタループで行います。",
      "gitPanelTitle": "Git ハブ",
      "gitPanelDesc": "Diff、log、commit、PR、Issue のコンテキストを 1 つの画面にまとめ、ツールの切り替えを減らします。",
      "kanbanTitle": "Kanban ディスパッチ",
      "kanbanDesc": "タスクを AI セッションに割り当て、状態を実行の進捗にリンクさせます。",
      "searchTitle": "統合検索",
      "searchDesc": "ファイル、スレッド、メッセージ、スキル、コマンドを横断する単一の入り口。",
      "memoryTitle": "メモリエンジン",
      "memoryDesc": "プロジェクトの長期的な知識を保持し、コンテキストの再設定を減らします。",
      "debugTitle": "ターミナル + デバッグ",
      "debugDesc": "組み込みのターミナルとデバッグトレースにより、トラブルシューティングを可観測かつ監査可能に保ちます。"
    }
  }
};

export default lockScreen;
