// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
const menu = {
  "menu": {
    "about": "{{appName}} について",
    "checkForUpdates": "アップデートを確認…",
    "settings": "設定…",
    "file": "ファイル",
    "newAgent": "新規 Agent",
    "newWorktreeAgent": "新規 Worktree Agent",
    "newCloneAgent": "新規クローン Agent",
    "newWindow": "新規ウィンドウ",
    "addWorkspace": "ワークスペースを追加…",
    "closeWindow": "ウィンドウを閉じる",
    "quit": "終了",
    "edit": "編集",
    "composer": "コンポーザー",
    "cycleModel": "モデルを切り替え",
    "cycleAccessMode": "アクセスモードを切り替え",
    "cycleReasoningMode": "推論モードを切り替え",
    "cycleCollaborationMode": "コラボレーションモードを切り替え",
    "view": "表示",
    "toggleProjectsSidebar": "プロジェクトサイドバーを切り替え",
    "toggleGitSidebar": "右サイドバーを切り替え",
    "toggleGlobalSearch": "グローバル検索を切り替え",
    "toggleDebugPanel": "デバッグパネルを切り替え",
    "toggleTerminal": "ターミナルを切り替え",
    "toggleDevtools": "開発者ツールを切り替え",
    "nextAgent": "次の Agent",
    "previousAgent": "前の Agent",
    "nextWorkspace": "次のワークスペース",
    "previousWorkspace": "前のワークスペース",
    "toggleFullScreen": "フルスクリーンを切り替え",
    "window": "ウィンドウ",
    "minimize": "最小化",
    "maximize": "最大化",
    "reloadWindow": "ウィンドウを再読み込み",
    "help": "ヘルプ"
  }
};

export default menu;
