// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {
  "modes": {
    "selectMode": "モードを選択",
    "default": {
      "label": "デフォルトモード",
      "tooltip": "標準的な権限の動作",
      "description": "各操作で手動確認が必要。慎重な利用に適しています"
    },
    "plan": {
      "label": "プランモード",
      "tooltip": "プランモード - 読み取り専用の分析",
      "description": "読み取り専用ツールのみを使用し、ユーザー承認用のプランを生成します"
    },
    "acceptEdits": {
      "label": "エージェントモード",
      "tooltip": "ファイル編集を自動承認",
      "description": "ファイルの作成・編集を自動承認し、確認ステップを削減します"
    },
    "bypassPermissions": {
      "label": "オートモード",
      "tooltip": "すべての権限チェックをバイパス",
      "description": "完全自動化。すべての権限チェックをバイパスします［慎重に使用してください］"
    }
  }
};

export default modes;
