// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {"panels":{"radar":"レーダー","git":"Git","files":"ファイル","search":"検索","notes":"ノート","memory":"メモリ","projectMap":"プロジェクトマップ","intentCanvas":"インテントキャンバス","activity":"アクティビティ","prompts":"プロンプト"}};

export default panels;
