// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {"plan":{"title":"プラン","noPlan":"利用可能なプランはありません","steps":"ステップ","completed":"完了","inProgress":"進行中","pending":"保留中"}};

export default plan;
