// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "プロンプト強化",
    "tooltip": "プロンプトを強化",
    "tooltipFull": "プロンプトを書き換えて文脈を補い、Agent の応答を改善します",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "プロンプトを強化中...",
    "readyToEnhance": "プロバイダー、モデル、タイムアウトを設定してから強化を開始してください。",
    "runSettings": "強化設定",
    "provider": "プロバイダー",
    "model": "モデル",
    "noModel": "モデルなし",
    "timeoutSeconds": "タイムアウト（秒）",
    "runEnhancement": "強化を開始",
    "originalPrompt": "元のプロンプト",
    "enhancedPrompt": "強化されたプロンプト",
    "useEnhanced": "強化版を使用",
    "keepOriginal": "元のまま保持",
    "enhanceFailed": "プロンプトの強化に失敗しました",
    "emptyPrompt": "先にプロンプトを入力してください",
    "copyEnhanced": "強化版をコピー"
  }
};

export default promptEnhancer;
