// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {"reasoning":{"title":"推論の深さを選択","default":"既定","claudeDefault":"既定","defaultDescription":"エンジン既定の推論動作を使用します","low":{"label":"低","description":"基本的な推論による素早い応答"},"medium":{"label":"中","description":"バランスの取れた思考（既定）"},"high":{"label":"高","description":"複雑なタスク向けの深い推論"},"xhigh":{"label":"特高","description":"さらに高い推論の深さ"},"max":{"label":"最大","description":"最大の推論の深さ"},"ultra":{"label":"ウルトラ","description":"タスクの自動委任を伴う最大推論"}}};

export default reasoning;
