// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
const rewind = {
  "rewind": {
    "title": "ファイルを以前の状態に巻き戻す",
    "tooltip": "巻き戻し",
    "label": "巻き戻し",
    "tooltipFull": "このメッセージ時点の状態にファイルを復元します",
    "notAvailable": "このセッションでは巻き戻しを利用できません",
    "noEligibleMessage": "巻き戻し可能なユーザーメッセージが見つかりませんでした。",
    "selectPrompt": "巻き戻し対象を選択してください (1-{{count}}):",
    "invalidSelection": "無効な巻き戻し選択です。",
    "confirmPrompt": "このメッセージから新しいスレッドを作成しますか？\n\"{{preview}}\"",
    "dialogTitle": "{{engine}} の巻き戻しを確認",
    "dialogDescription": "巻き戻しをクリックすると、まずこの確認ダイアログが開くだけです。巻き戻しは明示的に確認した後にのみ実行されます。",
    "targetSectionTitle": "巻き戻しの開始点",
    "targetMessageLabel": "この巻き戻しはこのユーザーメッセージからロールバックします",
    "impactSectionTitle": "削除される内容",
    "impactUserMessages": "削除されるユーザーメッセージ",
    "impactAssistantMessages": "削除されるアシスタントの返信",
    "impactToolCalls": "削除される Tool 呼び出し",
    "impactFiles": "関係するファイル",
    "impactSummary": "確認後、現在の線形履歴はこのユーザーメッセージからロールバックされます。これにはこのユーザーメッセージと、それ以降のすべてのアシスタントの返信、Tool 呼び出し、関連する変更が含まれます。",
    "impactFollowUp": "以下にファイルが表示されている場合、その変更は巻き戻される履歴区間の中で発生したものです。確認する前に内容を確認してください。",
    "workspaceRestoreSectionTitle": "ワークスペースファイルの方針",
    "modeMessagesAndFilesLabel": "メッセージ + ファイルを巻き戻す",
    "modeMessagesAndFilesHint": "会話履歴を巻き戻し、関連するワークスペースファイルの変更もまとめて復元します。",
    "modeMessagesOnlyLabel": "メッセージのみ",
    "modeMessagesOnlyHint": "会話履歴のみを巻き戻し、現在のワークスペースファイルはそのままにします。",
    "modeFilesOnlyLabel": "ファイルのみ",
    "modeFilesOnlyHint": "関連するファイルのみを復元し、現在の会話履歴は変更しません。",
    "filesSectionTitle": "影響を受けるファイル",
    "filesRailTitle": "ファイル",
    "filesEmpty": "巻き戻される履歴区間でファイルの変更は検出されませんでした。",
    "filesHint": "これは検出されたファイル変更のベストエフォートなフロントエンド要約であり、続行前に影響範囲を確認できます。",
    "diffEmpty": "このファイルの差分プレビューは利用できません。他のファイルを確認するか、メインの差分パネルを開くことができます。",
    "openDiffAction": "差分パネルで開く",
    "storeAction": "変更を保存",
    "storeActionBusy": "保存中...",
    "storeUnavailable": "現在の巻き戻しコンテキストには、変更を保存するのに十分なセッション情報が含まれていません。",
    "storeFailed": "変更の保存に失敗しました。",
    "storeRevealFailed": "保存された変更のディレクトリを開けませんでした。",
    "storeRevealAction": "フォルダを開く",
    "storeSuccessTitle": "{{count}} 個のファイルを保存し、再利用可能なマニフェストスナップショットを生成しました。",
    "storeSuccessPrefix": "保存先: ",
    "confirmAction": "巻き戻しを確認",
    "confirmActionBusy": "巻き戻し中...",
    "failed": "会話の巻き戻しに失敗しました。"
  }
};

export default rewind;
