// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "ファイル、カンバン、スレッド、メッセージ、Skill、コマンドを検索...",
    "placeholderFiltered": "{{content}}を検索...",
    "inputAria": "検索入力",
    "scope": "範囲",
    "content": "内容",
    "current": "現在",
    "global": "グローバル",
    "currentWorkspace": "現在のワークスペース",
    "allWorkspaces": "すべてのワークスペース",
    "noResults": "結果なし",
    "noResultsHint": "ファイルパス、タスクタイトル、スレッドタイトル、メッセージ本文、Skill 名、コマンド名のキーワードで試してください。",
    "fileIndexLoading": "ファイルインデックスを補完しています…",
    "fileIndexPartial": "ファイルインデックスが不完全なため、一部のファイルが見つからない可能性があります。",
    "fileIndexError": "ファイルインデックスを読み込めませんでした。検索を開き直して再試行してください。",
    "navigate": "移動",
    "open": "開く",
    "close": "閉じる",
    "projectTag": "プロジェクト",
    "typeTag": "種類",
    "sourceTag": "ソース",
    "locationTag": "場所",
    "typeAction": "操作",
    "typeFile": "ファイル",
    "typeKanban": "カンバン",
    "typeThread": "スレッド",
    "typeMessage": "メッセージ",
    "typeHistory": "履歴",
    "typeSkill": "Skill",
    "typeCommand": "コマンド",
    "sourceActions": "アプリ操作",
    "sourceFiles": "ファイルインデックス",
    "sourceKanban": "カンバンデータ",
    "sourceThreads": "スレッドタイトル",
    "sourceMessages": "メッセージ内容",
    "sourceHistory": "入力履歴",
    "sourceSkills": "Skill 一覧",
    "sourceCommands": "コマンド一覧",
    "contentAll": "すべて",
    "contentActions": "操作",
    "contentFiles": "ファイル",
    "contentKanban": "カンバン",
    "contentThreads": "スレッド",
    "contentMessages": "メッセージ",
    "contentHistory": "履歴",
    "contentSkills": "Skill",
    "contentCommands": "コマンド"
  }
};

export default searchPalette;
