// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
const statusPanel = {
  "statusPanel": {
    "tabTodos": "タスク",
    "tabSubagents": "サブエージェント",
    "tabAgents": "エージェント",
    "tabCheckpoint": "結果",
    "tabPlan": "プラン",
    "tabCommands": "コマンド",
    "files": "ファイル",
    "emptyTodos": "タスクなし",
    "emptySubagents": "サブエージェントなし",
    "emptyFileChanges": "ファイル変更なし",
    "emptyCommands": "コマンドなし",
    "emptyPlan": "プランなし",
    "planGenerating": "プランを生成中...",
    "planSwitchHint": "プランを表示するには Plan モードに切り替えてください",
    "expand": "ステータスパネルを展開",
    "collapse": "ステータスパネルを折りたたむ",
    "label": "ステータス",
    "policy": {
      "title": "ポリシー監査",
      "count": "{{count}} 件の判定",
      "noReason": "{{policy}} は理由を提供しませんでした",
      "verdict": {
        "running": "実行中",
        "blocked": "ブロック中",
        "needs_review": "レビュー",
        "ready": "準備完了",
        "no_contribution": "スキップ"
      },
      "corePolicy": {
        "blocked": "コアルールがブロッキングリスクを検出しました。",
        "running": "コアルールが進行中の作業を検出しました。",
        "ready": "コアルールは現在の証跡が準備完了であると判断しました。",
        "needsReview": "コアルールがレビューを必要としています。"
      },
      "lintValidationPolicy": {
        "pass": "Lint に合格しました。",
        "fail": "Lint が失敗し、レビューが必要です。",
        "running": "Lint を実行中です。",
        "notRun": "Lint は実行されていません。"
      },
      "typecheckValidationPolicy": {
        "pass": "型チェックに合格しました。",
        "fail": "型チェックが失敗し、レビューが必要です。",
        "running": "型チェックを実行中です。",
        "notRun": "型チェックは実行されていません。"
      },
      "testsValidationPolicy": {
        "pass": "テストに合格しました。",
        "fail": "テストが失敗し、レビューが必要です。",
        "running": "テストを実行中です。",
        "notRun": "テストは実行されていません。"
      },
      "openspecGovernancePolicy": {
        "pass": "OpenSpec ガバナンスの証跡は最新です。",
        "warn": "OpenSpec ガバナンスの証跡に助言的な警告があります。",
        "fail": "OpenSpec ガバナンスの証跡にレビューが必要です。",
        "unknown": "OpenSpec ガバナンスの証跡が利用できないか、不完全です。"
      },
      "largeFileGovernancePolicy": {
        "pass": "大容量ファイルのガバナンス証跡は最新です。",
        "warn": "大容量ファイルのガバナンス証跡に助言的な警告があります。",
        "fail": "大容量ファイルのガバナンス証跡にレビューが必要です。",
        "unknown": "大容量ファイルのガバナンス証跡が利用できないか、不完全です。"
      },
      "heavyTestNoiseGovernancePolicy": {
        "pass": "重いテストノイズの証跡は最新です。",
        "warn": "重いテストノイズの証跡に助言的な警告があります。",
        "fail": "重いテストノイズの証跡にレビューが必要です。",
        "unknown": "重いテストノイズの証跡が利用できないか、不完全です。"
      },
      "realtimeHarnessGovernancePolicy": {
        "pass": "リアルタイムハーネスの証跡は最新です。",
        "warn": "リアルタイムハーネスの証跡に助言的な警告があります。",
        "fail": "リアルタイムハーネスの証跡にレビューが必要です。",
        "unknown": "リアルタイムハーネスの証跡が利用できないか、不完全です。"
      },
      "capabilityMismatchGovernancePolicy": {
        "pass": "エンジン機能の証跡は最新です。",
        "warn": "エンジン機能の証跡に助言的な警告があります。",
        "fail": "エンジン機能の証跡にレビューが必要です。",
        "unknown": "エンジン機能の証跡が利用できないか、不完全です。"
      },
      "engineRuntimeGovernancePolicy": {
        "pass": "エンジンランタイム契約の証跡は最新です。",
        "warn": "エンジンランタイム契約の証跡に助言的な警告があります。",
        "fail": "エンジンランタイム契約の証跡にレビューが必要です。",
        "unknown": "エンジンランタイム契約の証跡が利用できないか、不完全です。"
      },
      "costBudgetGovernancePolicy": {
        "pass": "コスト予算の証跡は最新です。",
        "warn": "コスト予算の証跡に助言的な警告があります。",
        "fail": "コスト予算の証跡にレビューが必要です。",
        "unknown": "コスト予算の証跡が利用できないか、不完全です。"
      }
    },
    "audit": {
      "title": "判定の根拠",
      "expandLabel": "{{count}} 件のポリシー判定",
      "empty": "ポリシー判定なし",
      "reasonUnavailable": "{{policy}} は理由を提供しませんでした",
      "sourceUnavailable": "ソースなし",
      "enforcement": {
        "advisory": "助言",
        "blocking": "ブロッキング",
        "informational": "情報"
      }
    },
    "governance": {
      "title": "ガバナンス証跡",
      "loading": "証跡を読み込み中...",
      "empty": "ガバナンス証跡なし",
      "count": "{{count}} 件の証跡 · {{needsAction}} 件が対応必要",
      "group": {
        "needs_action": "対応必要 · {{count}}",
        "watch": "監視 · {{count}}",
        "passed": "合格 · {{count}}"
      },
      "meta": {
        "source": "ソース: {{source}}",
        "artifact": "成果物: {{path}}",
        "action": "アクション: {{reason}} を解決"
      },
      "status": {
        "pass": "合格",
        "warn": "警告",
        "fail": "失敗",
        "unknown": "不明"
      }
    },
    "cost": {
      "title": "コスト / 予算",
      "session": "セッション",
      "engine": "エンジン",
      "model": "モデル",
      "sessionId": "セッション ID",
      "tokens": "Token",
      "tokenBreakdownLabel": "Token 使用量の内訳",
      "known": "料金が一致",
      "partial": "部分的な見積もり",
      "unknownModel": "不明なモデル",
      "pricingSource": "料金ソース: {{source}} · {{date}}",
      "historyDegraded": "localStorage への書き込みに失敗したため、コスト履歴はメモリ内で継続しています。",
      "accumulated": {
        "session": "セッション {{amount}}",
        "today": "本日 {{amount}}",
        "month": "今月 {{amount}}"
      },
      "degraded": {
        "pricing-unavailable": "{{engine}}/{{model}} の追跡可能な料金がありません。コストが暗黙的にゼロとして扱われることはありません。",
        "pricing-stale": "料金フィクスチャが古くなっています。このコストは参考情報のみです。",
        "usage-unavailable": "コスト予測に利用できる Token 使用量がありません。",
        "block-level-cost-unsupported": "このバージョンではブロック単位のコストはサポートされていません。",
        "unknown": "コスト予測が劣化しています。"
      }
    },
    "budget": {
      "unconfigured": "予算が未設定です。これはガイダンスであり、予算チェックの失敗ではありません。",
      "unsetShort": "予算未設定",
      "barLabel": "予算使用の進捗",
      "progress": "{{amount}} / {{limit}}",
      "threshold": {
        "info": "情報しきい値に到達: {{amount}} / {{threshold}}",
        "warn": "警告しきい値に到達: {{amount}} / {{threshold}}",
        "block": "ブロックしきい値に到達: {{amount}} / {{threshold}}。この機能はシグナルを発するのみで、ランタイムを中断しません。"
      }
    },
    "checkpoint": {
      "verdictTitle": "判定",
      "evidenceTitle": "証跡",
      "keyChangesTitle": "主な変更",
      "keyChangesEmpty": "まだ主な変更は取得されていません",
      "fileDetailsTitle": "ファイルの詳細",
      "risksTitle": "リスク",
      "nextActionTitle": "次のアクション",
      "sections": {
        "summary": "サマリー",
        "advisorySignals": "助言シグナル",
        "evidenceTrail": "証跡トレイル",
        "policyAudit": "ポリシー監査",
        "suggestedActions": "推奨アクション"
      },
      "advisory": {
        "count": "{{count}} 件の助言シグナル"
      },
      "verdict": {
        "running": "実行中",
        "blocked": "ブロック中",
        "needs_review": "レビューが必要",
        "ready": "準備完了"
      },
      "headline": {
        "running": "作業進行中",
        "blocked": "対応が必要です",
        "needs_review": "続行前にレビュー",
        "ready": "続行の準備完了",
        "idle": "証跡を待機中"
      },
      "summary": {
        "blockedValidation": "必須の検証が失敗したため、先に修正する必要があります。",
        "blockedCommand": "最新のコマンドが失敗しました: {{command}}。システムがまだ自動復旧を試みている場合は、停止する前にこの実行が落ち着くのを待ってください。",
        "blockedSubagent": "委任されたタスクがエラー状態で停止しました。",
        "runningValidation": "検証がまだ実行中です。判断する前に結果を待ってください。",
        "runningCommand": "最新のコマンドがまだ実行中です: {{command}}",
        "runningAgent": "少なくとも 1 つの Agent がまだ処理中です。",
        "runningTodo": "まだ進行中のアクティブなタスクがあります。",
        "runningProcessing": "現在のターンはまだ実行の証跡を生成中です。",
        "readyWithFiles": "{{count}} 件の変更ファイルが観測されたコアチェックに合格しました。",
        "ready": "観測された実行の証跡は落ち着いているように見えます。",
        "needsValidation": "ファイルは変更されましたが、コア検証はまだ実行されていません。",
        "manual": "結果は利用可能ですが、まだ人間によるレビューが必要です。",
        "idle": "まだ信頼できる実行の証跡は観測されていません。"
      },
      "evidence": {
        "filesChanged": "変更されたファイル",
        "filesChangedValue": "{{count}} ファイル",
        "validations": "検証",
        "requiredValidations": "必須",
        "optionalValidations": "オプション",
        "fileChangeSummary": "{{count}} ファイルにわたって +{{additions}}/-{{deletions}}",
        "runMissing": "先に実行",
        "runMissingGeneric": "プロジェクトのコア検証スクリプトを実行",
        "tasks": "タスク",
        "agents": "エージェント",
        "inProgress": "進行中",
        "settled": "確定"
      },
      "evidenceTrail": {
        "count": "{{count}} 件の証跡",
        "sourceLabel": "ソース",
        "snapshotLabel": "スナップショット",
        "observedLabel": "観測",
        "artifactLabel": "成果物",
        "hashLabel": "ハッシュ",
        "qualifierLabel": "修飾子",
        "degradedLabel": "劣化",
        "staleLabel": "古い",
        "snapshotRecorded": "スナップショット記録済み",
        "hashRecorded": "検証済み",
        "policy": {
          "buildValidationPolicy": "ビルド検証",
          "costBudgetGovernancePolicy": "コスト予算",
          "heavyTestNoiseGovernancePolicy": "重いテストノイズ",
          "largeFileGovernancePolicy": "大容量ファイルガバナンス",
          "lintValidationPolicy": "Lint 検証",
          "openspecGovernancePolicy": "OpenSpec ガバナンス",
          "testsValidationPolicy": "テスト検証",
          "typecheckValidationPolicy": "型チェック検証"
        },
        "sourceName": {
          "build": "ビルド",
          "costBudget": "コスト予算",
          "heavyTestNoise": "重いテストノイズ",
          "largeFile": "大容量ファイル",
          "lint": "Lint",
          "openspec": "OpenSpec",
          "tests": "テスト",
          "trellis": "Trellis",
          "typecheck": "型チェック"
        },
        "reason": {
          "governanceArtifactMalformed": "証跡ファイルの形式が無効です",
          "governanceEvidenceUnavailable": "証跡をまだ解析できません",
          "pricingUnavailable": "モデルの料金が不明です",
          "stale": "証跡が古くなっています"
        },
        "source": "ソース: {{source}}",
        "snapshot": "スナップショット: {{id}}",
        "observed": "観測: {{time}}",
        "artifact": "成果物: {{path}}",
        "hash": "ハッシュ: {{hash}}",
        "qualifier": "修飾子: {{qualifier}}",
        "degraded": "劣化: {{reason}}",
        "stale": "古い: {{time}}"
      },
      "suggested": {
        "validation": "オプション: {{command}}",
        "governance": "オプションの {{source}} チェック: {{command}}"
      },
      "expandToDock": "ドックで完全な結果を表示",
      "validations": {
        "lint": "Lint",
        "typecheck": "型チェック",
        "tests": "テスト",
        "build": "ビルド",
        "custom": "コマンド",
        "status": {
          "pass": "合格",
          "fail": "失敗",
          "running": "実行中",
          "not_run": "未実行",
          "not_observed": "未観測"
        }
      },
      "keyChanges": {
        "files": "変更されたファイル",
        "filesSummary": "{{count}} ファイル変更 · +{{additions}} / -{{deletions}}",
        "tasks": "タスクの進捗",
        "tasksSummary": "{{total}} 件中 {{completed}} 件のタスクが完了",
        "agents": "Agent の進捗",
        "agentsSummary": "{{total}} 件中 {{completed}} 件の Agent が完了"
      },
      "risks": {
        "none": "ブロッキングリスクは検出されませんでした。",
        "commandFailed": "コマンドがエラーで終了しました: {{command}}",
        "validationFailed": "少なくとも 1 つの検証が失敗で終了しました。",
        "validationMissing": "ファイル変更後にコア検証が実行されていません。",
        "subagentError": "Agent がエラーを報告しました: {{agent}}",
        "manualReview": "システムはまだ結果を宣言するのに十分な証跡を観測していません。",
        "severity": {
          "high": "高",
          "medium": "中",
          "low": "低"
        }
      },
      "actions": {
        "reviewDiff": "差分をレビュー",
        "openRisk": "リスクを確認",
        "retry": "失敗したステップを再試行",
        "commit": "準備ができたらコミット",
        "hint": {
          "runMissingValidation": "続行するかどうかを判断する前に、欠落している検証を実行してください。",
          "running": "現在の実行の証跡が落ち着くのを待ってください。",
          "blocked": "まず失敗した証跡を確認してください。復旧がまだ進行中の場合は、停止を判断する前に実行が落ち着くのを待ってください。",
          "needs_review": "この結果はまだ回復する可能性があります。アクションを起こす前に、実行が落ち着き続けるのを待ってください。",
          "ready": "証跡は確定しています。コミット前の最終チェックを行ってください。"
        }
      },
      "commitDialog": {
        "title": "コミットの確認",
        "path": "パス:",
        "files": "コミットするファイル",
        "toggleAllFiles": "すべてのコミットファイルを切り替え",
        "staged": "ステージ済み"
      }
    }
  }
};

export default statusPanel;
