// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
const tabbar = {
  "tabbar": {
    "projects": "プロジェクト",
    "codex": "Codex",
    "spec": "Spec",
    "git": "Git",
    "log": "ログ",
    "primaryNavigation": "メインナビゲーション",
    "workspaceNavigation": "ワークスペースナビゲーション"
  }
};

export default tabbar;
