// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {"terminal":{"newTab":"新しいタブ","closeTab":"タブを閉じる","clear":"クリア","title":"ターミナル","tabTitle":"ターミナル {{number}}","claudeTuiResumeTitle":"Claude TUI","sendSelectionToComposer":"コンポーザーに送信"}};

export default terminal;
