// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
const threadCompletion = {
  "threadCompletion": {
    "title": "セッション完了",
    "project": "プロジェクト",
    "session": "セッション"
  }
};

export default threadCompletion;
