// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {
  "time": {
    "justNow": "たった今",
    "minuteAgo": "{{count}}分前",
    "minutesAgo": "{{count}}分前",
    "hourAgo": "{{count}}時間前",
    "hoursAgo": "{{count}}時間前",
    "dayAgo": "{{count}}日前",
    "daysAgo": "{{count}}日前",
    "weekAgo": "{{count}}週間前",
    "weeksAgo": "{{count}}週間前",
    "now": "今",
    "shortSecondsAgo": "{{value}}秒前",
    "shortSecondsIn": "{{value}}秒後",
    "shortMinutesAgo": "{{value}}分前",
    "shortMinutesIn": "{{value}}分後",
    "shortMinutes": "{{value}}分",
    "shortHours": "{{value}}時間",
    "shortDays": "{{value}}日",
    "shortWeeks": "{{value}}週間",
    "shortMonths": "{{value}}か月",
    "shortYears": "{{value}}年"
  }
};

export default time;
