// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
const tools = {
  "tools": {
    "readFile": "ファイルを読み取り",
    "readDirectory": "ディレクトリを読み取り",
    "editFile": "ファイルを編集",
    "writeFile": "ファイルを書き込み",
    "editNotebook": "ノートブックを編集",
    "runCommand": "コマンドを実行",
    "executeCommand": "コマンドを実行",
    "search": "検索",
    "fileMatch": "ファイルマッチ",
    "findFile": "ファイルを検索",
    "webFetch": "Web取得",
    "webSearch": "Web検索",
    "subtask": "サブタスク",
    "todoList": "ToDoリスト",
    "userInputRequest": "ユーザーに質問",
    "diffCompare": "差分",
    "result": "結果",
    "claudeControlResumeFailed": "再開に失敗しました",
    "claudeControlModelChanged": "モデルが変更されました",
    "claudeControlInterrupted": "中断されました",
    "claudeControlLocalOutput": "ローカルコマンドの出力",
    "webRequest": "Webリクエスト",
    "batchRun": "バッチ実行",
    "searchMatch": "検索/マッチ",
    "batchReadFile": "ファイルを一括読み取り",
    "batchSearch": "一括検索",
    "batchSearchMatch": "一括検索/マッチ",
    "batchEditFile": "ファイルを一括編集",
    "bashGroupBatchRun": "コマンドを一括実行",
    "bashGroupCompleted": "完了",
    "bashGroupAllCompleted": "すべて完了",
    "bashGroupFailed": "失敗",
    "planQuickView": "プラン",
    "openFullPlanPanel": "プランパネル全体を開く",
    "closePlanPanel": "プランパネルを閉じる",
    "path": "パス",
    "lineRange": "行 {{start}}-{{end}}",
    "failedCount": "{{count}}件失敗"
  }
};

export default tools;
