// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "アップデート",
    "checkingForUpdates": "アップデートを確認中...",
    "updateAvailable": "新しいバージョンが利用可能です！",
    "upToDate": "最新の状態です。",
    "downloading": "アップデートをダウンロード中…",
    "installing": "アップデートをインストール中…",
    "restarting": "再起動中…",
    "failed": "アップデートに失敗しました。",
    "downloaded": "ダウンロード済み",
    "releaseNotesTitle": "リリースノート",
    "releaseNotesLoading": "リリースノートを読み込み中…",
    "releaseNotesLoadFailed": "リリースノートの読み込みに失敗しました。",
    "releaseNotesEmpty": "リリースノートはまだありません。",
    "releaseNotesOpenInGitHub": "GitHubで表示",
    "releaseNotesPrev": "前へ",
    "releaseNotesNext": "次へ",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "英語:",
    "releaseNotesChinese": "中文："
  }
};

export default update;
