// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
const usage = {"usage":{"sessionReset":"セッションのリセット","weeklyReset":"週次のリセット","credits":"クレジット","used":"使用済み","remaining":"残り","unlimited":"無制限"}};

export default usage;
