// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {"about":{"version":"Versión","tagline":"Editor VibeCoding de nueva generación","checkForUpdates":"Buscar actualizaciones","releaseNotes":"Notas de la versión","reportIssue":"Informar de un problema","website":"Sitio web","github":"GitHub","wechatGroupTitle":"Escanea para unirte al grupo de WeChat"}};

export default about;
