// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
const activityPanel = {
  "activityPanel": {
    "title": "Actividad de la sesión",
    "noRoot": "Tarea actual",
    "selectWorkspace": "Selecciona un espacio de trabajo para inspeccionar la actividad de la sesión.",
    "emptyIdle": "Aún no hay actividad en la sesión.",
    "emptyRunning": "Esperando actividad de la sesión...",
    "emptyCompleted": "Esta tarea finalizó sin actividad registrada en la fase uno.",
    "eventsCount": "{{count}} eventos",
    "sessionsCount": "{{count}} sesiones",
    "liveNow": "en vivo",
    "command": "Comando",
    "commandPendingSummary": "Ejecutando comando",
    "commandCategories": {
      "command": "Comando",
      "search": "Búsqueda",
      "read": "Lectura",
      "list": "Lista",
      "git": "Git",
      "test": "Prueba",
      "lint": "Lint",
      "build": "Compilación",
      "run": "Ejecución"
    },
    "description": "Descripción",
    "cwd": "CWD",
    "waitingForOutput": "Esperando la salida del comando...",
    "waitingForReasoning": "Esperando el contenido del razonamiento...",
    "rootSession": "raíz",
    "childSession": "hija",
    "relatedSessions": "Relacionadas",
    "fallbackLinking": "enlace de reserva",
    "liveEditPreview": "Vista previa en vivo",
    "liveEditFollowLabel": "Seguimiento en vivo",
    "liveEditPreviewTooltip": "Actívalo para abrir en tiempo real los archivos que la IA está editando.",
    "enableLiveEditPreview": "Activar la vista previa de edición en vivo",
    "disableLiveEditPreview": "Desactivar la vista previa de edición en vivo",
    "followCoachTitle": "Prueba el seguimiento en vivo",
    "followCoachBody": "Actívalo para seguir los archivos que la IA está editando.",
    "followCoachEnable": "Activar ahora",
    "followCoachDismiss": "Ahora no",
    "followNudgeTitle": "Seguimiento en vivo",
    "followNudgeErrorTitle": "Error al activar",
    "followNudgeBody": "La IA está editando archivos. ¿Activar el seguimiento en vivo?",
    "followNudgeEnable": "Activar",
    "followNudgeLater": "Más tarde",
    "followNudgeRetry": "Reintentar",
    "followToggleFailed": "No se pudo cambiar el seguimiento en vivo. Inténtalo de nuevo.",
    "showOutput": "Mostrar salida",
    "hideOutput": "Ocultar salida",
    "expandTurnGroup": "Expandir grupo de turnos",
    "collapseTurnGroup": "Contraer grupo de turnos",
    "turnGroup": "Turno {{index}}",
    "turnGroupFallback": "Actividad heredada",
    "tabs": {
      "ariaLabel": "Categorías de actividad de la sesión",
      "all": "Resumen",
      "command": "Comando",
      "file": "Artefactos",
      "task": "Tarea",
      "subagent": "Subagente",
      "explore": "Explorar",
      "reasoning": "Razonamiento"
    },
    "artifacts": {
      "kicker": "Artefactos del turno",
      "title": "Artefactos",
      "fileCount": "{{count}} archivo",
      "fileCount_other": "{{count}} archivos",
      "turnSemanticTitle": "Significado del turno",
      "tabsAriaLabel": "Vista de artefactos del turno",
      "tabs": {
        "artifacts": "Artefactos",
        "semantic": "Diff semántico"
      }
    },
    "radar": {
      "modeCurrentTask": "Tarea actual",
      "modeWorkspaceRadar": "Radar del espacio de trabajo",
      "runningSection": "En ejecución ({{count}})",
      "recentSection": "Completadas recientemente ({{count}})",
      "emptyRunning": "No hay sesiones en ejecución.",
      "emptyRecent": "No hay sesiones completadas recientemente.",
      "openSession": "Abrir",
      "runningCountAria": "{{count}} sesiones en ejecución",
      "recentCountAria": "{{count}} sesiones recientes",
      "startedAt": "Iniciada:",
      "endedAt": "Finalizada:",
      "totalDuration": "Duración:",
      "timeUnknown": "--:--:--",
      "durationUnknown": "--",
      "unreadBadge": "NUEVO",
      "unreadMark": "Sin leer",
      "readMark": "Leído",
      "deleteHistoryEntry": "Eliminar {{name}}",
      "deleteDateGroupEntries": "Eliminar las {{count}} entradas de {{date}}"
    },
    "status": {
      "running": "en ejecución",
      "completed": "completada",
      "failed": "fallida",
      "pending": "pendiente"
    }
  }
};

export default activityPanel;
