// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/agentOrchestration.ts; keys mirror the English source.
const agentOrchestration = {
  "agentOrchestration": {
    "title": "Cola de trabajo del mapa del proyecto",
    "eyebrow": "Cola del mapa del proyecto",
    "summary": "{{workspace}} · {{total}} elemento(s) de trabajo · {{providers}} fuente(s) disponible(s)",
    "workspaceUnknown": "Espacio de trabajo desconocido",
    "loadingTitle": "Cargando la vista de orquestación",
    "loadingDescription": "Agregando candidatos del mapa del proyecto, borradores de tareas existentes y contexto de TaskRun.",
    "emptyTitle": "Aún no hay tareas de orquestación en este espacio de trabajo",
    "emptyDescription": "Esta vista solo muestra por ahora el contexto de orquestación existente y el estado de ejecución. Los puntos de entrada para crear tareas volverán tras el rediseño del módulo de tareas.",
    "degradedTitle": "Algunas fuentes están degradadas",
    "unavailable": "No disponible",
    "noRefs": "Sin referencias de fuente",
    "noEvidenceRefs": "Sin referencias de evidencia",
    "noRisks": "Sin marcadores de riesgo",
    "status": {
      "candidate": "Candidata",
      "planned": "Planificada",
      "ready": "Lista",
      "running": "En ejecución",
      "waiting_input": "Esperando entrada",
      "blocked": "Bloqueada",
      "review_needed": "Requiere revisión",
      "completed": "Completada",
      "archived": "Archivada"
    },
    "queueStatus": {
      "todo": "Por hacer",
      "queued": "En cola",
      "running": "En ejecución",
      "failed": "Fallida",
      "dispatched": "Despachada",
      "review": "Requiere revisión",
      "done": "Hecha",
      "archived": "Archivada"
    },
    "action": {
      "backToProjectMap": "Volver al mapa del proyecto"
    },
    "manual": {
      "open": "Añadir tarea manual",
      "eyebrow": "Fuente manual",
      "title": "Crear tarea manual",
      "description": "Las tareas manuales no inventan evidencia verificada. Añade alcance y aceptación antes de despacharla.",
      "fieldTitle": "Título",
      "fieldScope": "Alcance",
      "fieldAcceptance": "Aceptación",
      "fieldPrompt": "Prompt",
      "cancel": "Cancelar",
      "create": "Crear tarea"
    },
    "actions": {
      "label": "Acciones de la tarea",
      "openSource": "Abrir fuente",
      "openSourceLabel": "Abrir la fuente de {{title}}",
      "openRun": "Ver la ejecución en el Centro de tareas",
      "openRunLabel": "Ver la ejecución vinculada de {{title}} en el Centro de tareas",
      "openSession": "Abrir sesión",
      "openSessionLabel": "Abrir la sesión vinculada de {{title}}",
      "cancelQueuedRun": "Cancelar despacho",
      "archive": "Archivar",
      "writeBack": "Escribir de vuelta al proveedor",
      "writeBackDisabled": "La escritura de vuelta al proveedor es una acción futura: debe pasar por un flujo de confirmación aparte. Aquí no se modifican los archivos de OpenSpec, Trellis, spec-kit ni las reglas del agente."
    },
    "queue": {
      "taskLabel": "{{title}}, estado {{status}}, proveedor {{provider}}, {{risks}} marcador(es) de riesgo",
      "riskCount": "{{count}} marcador(es) de riesgo",
      "riskOverflow": "+{{count}} riesgo(s)"
    },
    "dispatch": {
      "open": "Enviar al Centro de tareas",
      "openLabel": "Enviar {{title}} al Centro de tareas",
      "eyebrow": "Puerta de despacho",
      "title": "Confirmación de despacho",
      "description": "Configura primero el motor, el espacio de trabajo, la estrategia de hilos y el alcance de aceptación. Solo se crea un TaskRun tras confirmar el despacho.",
      "engine": "Motor",
      "model": "Modelo",
      "defaultModel": "Usar el modelo predeterminado",
      "workspace": "Espacio de trabajo",
      "status": "Estado",
      "threadStrategy": "Estrategia de hilos",
      "promptSummary": "Resumen del prompt",
      "acceptance": "Aceptación",
      "sources": "Fuentes",
      "disabled": "La ejecución aún no está conectada: esto solo muestra una vista previa de los parámetros de despacho y no creará un TaskRun.",
      "cancel": "Cancelar",
      "confirm": "Confirmar despacho"
    },
    "review": {
      "label": "Acciones de revisión",
      "open": "Revisar",
      "openLabel": "Revisar {{title}}",
      "title": "Puerta de revisión",
      "description": "La ejecución vinculada ha finalizado. Revisa el resultado antes de aceptarlo, solicitar cambios o crear una tarea de seguimiento.",
      "accept": "Aceptar resultado",
      "requestChanges": "Solicitar cambios",
      "createFollowUp": "Crear seguimiento",
      "missingRunTitle": "Falta el resultado de ejecución; la revisión no está disponible",
      "missingRunDescription": "Esta tarea está marcada para revisión, pero no tiene ninguna ejecución ni sesión vinculada. Despáchala de nuevo antes de revisarla.",
      "feedback": {
        "accepted": "Resultado aceptado. La tarea está completa.",
        "changesRequested": "Cambios solicitados. La tarea volvió a la cola de trabajo.",
        "followUpCreated": "Tarea de seguimiento creada y seleccionada."
      }
    },
    "filters": {
      "label": "Filtros de la cola de tareas",
      "provider": "Proveedor",
      "status": "Estado del trabajo",
      "engine": "Motor",
      "workspace": "Espacio de trabajo",
      "sourceKind": "Tipo de fuente",
      "risk": "Riesgo",
      "allProviders": "Todos los proveedores",
      "allStatuses": "Todos los estados de trabajo",
      "allEngines": "Todos los motores",
      "allWorkspaces": "Todos los espacios de trabajo",
      "allSourceKinds": "Todos los tipos de fuente",
      "allRisks": "Todos los riesgos",
      "noEngine": "Sin motor",
      "reset": "Restablecer",
      "visibleSummary": "Mostrando {{visible}} / {{total}}",
      "emptyTitle": "Ninguna tarea coincide con los filtros actuales",
      "emptyDescription": "Ajusta los filtros de proveedor, estado, motor, espacio de trabajo, tipo de fuente o riesgo para continuar."
    },
    "reviewState": {
      "not_started": "No iniciada",
      "needs_review": "Requiere revisión",
      "accepted": "Aceptada",
      "changes_requested": "Cambios solicitados"
    },
    "threadStrategy": {
      "new_thread": "Hilo nuevo",
      "reuse_active_thread": "Reutilizar el hilo activo",
      "choose_thread": "Elegir hilo"
    },
    "detail": {
      "scope": "Alcance",
      "acceptance": "Aceptación",
      "createdAt": "Creada",
      "updatedAt": "Actualizada",
      "providerSources": "Fuentes del proveedor",
      "evidence": "Evidencia",
      "evidenceCount": "{{count}} referencia(s) de evidencia",
      "risks": "Riesgos",
      "links": "Enlaces de ejecución",
      "runManagement": "Gestión de ejecuciones / sesiones",
      "linkCountsLabel": "Recuento de enlaces",
      "linkCounts": "{{runs}} ejecución(es) · {{sessions}} sesión(es)",
      "linkedRuns": "Ejecuciones vinculadas",
      "linkedSessions": "Sesiones vinculadas",
      "noLinkedRuns": "Sin ejecuciones vinculadas",
      "noLinkedSessions": "Sin sesiones vinculadas",
      "missingLinkedRun": "Sin ejecución vinculada. Devuelta a por hacer.",
      "linkedRunMissing": "Falta el registro de ejecución",
      "runEngine": "Motor",
      "runUpdatedAt": "Actualizada",
      "runCurrentStep": "Paso actual",
      "runLatestOutput": "Última salida",
      "activity": "Actividad",
      "reviewState": "Estado de revisión",
      "threadStrategy": "Estrategia de hilos",
      "preferredEngine": "Motor preferido",
      "preferredModel": "Modelo preferido",
      "parentTask": "Tarea principal",
      "selectionPreservedTitle": "Nodo actual conservado",
      "selectionPreservedDescription": "El estado de la tarea cambió, pero el panel de detalles permanece en el nodo sobre el que acabas de actuar."
    }
  }
};

export default agentOrchestration;
