// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {
  "askUserQuestion": {
    "title": "Claude tiene una pregunta para ti",
    "progress": "Pregunta {{current}} / {{total}}",
    "timeoutWarning": "Por favor, responde pronto. Este diálogo se cerrará automáticamente en {{seconds}} segundos",
    "collapse": "Contraer",
    "expand": "Expandir",
    "clickToAnswer": "Haz clic para responder",
    "questionTab": "Pregunta {{index}}",
    "cancel": "Cancelar",
    "back": "Atrás",
    "next": "Siguiente",
    "submit": "Enviar",
    "otherOption": "Otra",
    "otherOptionDesc": "Introduce una respuesta personalizada",
    "customInputPlaceholder": "Escribe tu respuesta...",
    "multiSelectHint": "Puedes seleccionar varias opciones"
  }
};

export default askUserQuestion;
