// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
const browserAgent = {
  "browserAgent": {
    "dock": {
      "description": "Lee primero los datos clave de la página y luego habilita progresivamente la navegación y las acciones sobre elementos.",
      "disabled": "Desactivado",
      "statusDisconnected": "Desconectado",
      "statusLoading": "Cargando",
      "statusReady": "Legible",
      "statusClosed": "Cerrado",
      "statusNeedsAttention": "Requiere atención",
      "statusPreparing": "Preparando",
      "emptyUrl": "Introduce la URL de una página para abrirla.",
      "blockedUrl": "Esta URL está bloqueada por la política de Browser Agent.",
      "opened": "Browser Agent abrió una pestaña del navegador.",
      "closed": "Pestaña de Browser Agent cerrada.",
      "busy": "Trabajando",
      "open": "Abrir",
      "enable": "Activar",
      "enabled": "Browser Agent activado.",
      "tabs": "Pestañas del navegador",
      "newTab": "Nueva pestaña del navegador",
      "openDock": "Navegador",
      "panelTitle": "Panel del navegador",
      "panelKicker": "Abre una página aquí y luego adjunta su contexto a la IA cuando lo necesites.",
      "noWorkspace": "Selecciona un espacio de trabajo antes de abrir el panel del navegador.",
      "noPage": "Abre una página http/https permitida para lanzar la ventana de Browser Agent.",
      "rendering": "Renderizando la página en la ventana de Browser Agent...",
      "windowOpened": "La página está abierta en una ventana aparte de Browser Agent.",
      "closePanel": "Cerrar el panel del navegador",
      "close": "Cerrar la sesión de Browser Agent",
      "info": "Mostrar los detalles de Browser Agent",
      "footnote": "El MVP no almacena el DOM en bruto, cookies, cabeceras ni secretos de la página."
    },
    "composer": {
      "attach": "Adjuntar contexto del navegador",
      "attaching": "Adjuntando contexto del navegador...",
      "attached": "Contexto del navegador adjuntado",
      "visibleSnapshot": "Instantánea de la página visible del navegador",
      "selectedElement": "Elemento de página seleccionado",
      "selectedElementCount": "{{count}} elementos de página seleccionados",
      "selectedElementFacts": "Datos del elemento de página seleccionado",
      "selectedElementMore": "{{count}} elementos más",
      "selectorHint": "Selector {{selector}}",
      "noRawApi": "No son datos en bruto de la API",
      "remove": "Quitar",
      "refresh": "Actualizar el contexto del navegador",
      "fresh": "listo",
      "stale": "actualizar",
      "expired": "caducado",
      "degraded": "degradado",
      "unsupported": "no compatible",
      "showDetails": "Mostrar detalles de la captura",
      "hideDetails": "Ocultar detalles",
      "countSummary": "Recuento de elementos de la página",
      "headingCount": "Encabezados {{count}}",
      "linkCount": "Enlaces {{count}}",
      "buttonCount": "Botones {{count}}",
      "formCount": "Formularios {{count}}",
      "readableBlockCount": "Bloques legibles {{count}}",
      "visualEvidenceCount": "Pistas visuales {{count}}",
      "counts": "Encabezados {{headings}} · enlaces {{links}} · botones {{buttons}} · formularios {{forms}} · bloques legibles {{readableBlocks}} · pistas visuales {{visualEvidence}} · candidatos de código {{candidates}}",
      "primaryContent": "Contenido principal",
      "readableBlocks": "Bloques legibles {{count}}",
      "visualEvidence": "Pistas visuales {{count}}",
      "codeCandidates": "Candidatos de código {{count}}",
      "privacy": "{{redacted}} tipo(s) de redacción, {{omitted}} tipo(s) de fuente sensible omitida(s).",
      "noSession": "No hay ninguna sesión activa de Browser Agent. Abre primero una página en el panel del navegador."
    }
  }
};

export default browserAgent;
