// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
const claudeModes = {
  "claudeModes": {
    "default": {
      "label": "Modo Sugerencia (Vista previa)",
      "tooltip": "Modo de aprobación de vista previa de Claude Code. Algunos flujos aún pueden degradarse mientras se completa el puente de aprobación completo.",
      "description": "Ahora disponible como vista previa para validar el flujo de permisos predeterminado de Claude. Si se alcanza una ruta degradada, la interfaz debería guiar al usuario de vuelta al modo Plan."
    },
    "plan": {
      "label": "Modo Plan",
      "tooltip": "Modo de análisis de solo lectura de Claude Code.",
      "description": "Usa herramientas de solo lectura para el análisis y la planificación antes de actuar."
    },
    "acceptEdits": {
      "label": "Edición automática",
      "tooltip": "Modo de edición automática de Claude Code. No está habilitado en la fase de despliegue actual.",
      "description": "Este modo permanece no disponible hasta que se verifique la semántica de aprobación de Claude."
    },
    "bypassPermissions": {
      "label": "Totalmente automático",
      "tooltip": "Modo de Claude Code que omite las comprobaciones de permisos.",
      "description": "Ejecución sin intervención para escrituras de archivos y comandos sin aprobaciones. Úsalo con cuidado."
    }
  }
};

export default claudeModes;
