// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/config.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/config.ts; keys mirror the English source.
const config = {
  "config": {
    "switchProvider": "Cambiar de proveedor"
  }
};

export default config;
