// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {"debug":{"title":"Depuración","copyLogs":"Copiar registros","clearLogs":"Borrar registros","noLogs":"Sin registros de depuración","copy":"Copiar","clear":"Borrar","noDebugEventsYet":"Aún no hay eventos de depuración."}};

export default debug;
