// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "Fallo de conexión",
    "requestFailed": "La solicitud falló",
    "unexpectedError": "Ocurrió un error inesperado",
    "sessionExpired": "La sesión expiró",
    "rateLimited": "Límite de solicitudes alcanzado. Inténtalo de nuevo más tarde.",
    "networkError": "Error de red. Comprueba tu conexión.",
    "failedToAddWorkspace": "No se pudo añadir el espacio de trabajo.",
    "failedToOpenNewWindow": "No se pudo abrir una nueva ventana.",
    "failedToCreateSession": "No se pudo crear la sesión.",
    "failedToCreateSessionNoThreadId": "El runtime no devolvió un nuevo id de sesión.",
    "failedToCreateSessionRuntimeRecovering": "El runtime se estaba reiniciando al crear esta sesión. La app ya reintentó una vez. Reconecta el espacio de trabajo e inténtalo de nuevo.",
    "reconnectAndRetryCreateSession": "Reconectar y reintentar la creación",
    "reconnectingAndRetryingCreateSession": "Reconectando y reintentando la creación...",
    "runtimeRecovered": "Runtime recuperado.",
    "retryingCreateSessionAfterRecovery": "Reintentando la creación de la sesión...",
    "cliNotFound": "No se encontró ni la CLI de Claude Code ni la CLI de Codex. Instala una de ellas.",
    "cliNotFoundHint": "Instalar Claude Code: npm install -g @anthropic-ai/claude-code\nInstalar Codex: npm install -g @openai/codex",
    "codexCliNotFound": "No se encontró la CLI de Codex. Instala Codex y asegúrate de que `codex` esté en tu PATH.",
    "couldntOpenWorkspace": "No se pudo abrir el espacio de trabajo",
    "dismissError": "Descartar error"
  }
};

export default errors;
