// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
const home = {
  "home": {
    "welcome": "Bienvenido",
    "subtitle": "¿Qué te gustaría crear hoy?",
    "latestActivity": "Conversaciones recientes",
    "noActivity": "No hay conversaciones recientes",
    "latestAgents": "Últimos agentes",
    "agentReplied": "El agente respondió.",
    "running": "En ejecución",
    "loadingAgents": "Cargando agentes",
    "noAgentActivity": "Todavía no hay actividad de agentes",
    "startThreadToSee": "Inicia un hilo para ver aquí las respuestas más recientes.",
    "openProject": "Añadir proyecto",
    "addWorkspace": "Añadir proyecto",
    "usageSnapshot": "Instantánea de uso",
    "refreshUsage": "Actualizar uso",
    "workspace": "Espacio de trabajo",
    "allWorkspaces": "Todos los espacios de trabajo",
    "view": "Ver",
    "tokens": "Tokens",
    "time": "Tiempo",
    "last7Days": "Últimos 7 días",
    "last30Days": "Últimos 30 días",
    "cacheHitRate": "Tasa de aciertos de caché",
    "peakDay": "Día pico",
    "agentTime": "tiempo de agente",
    "runs": "ejecuciones",
    "avg": "Prom.",
    "total": "Total",
    "day": "día",
    "noUsageData": "Todavía no hay datos de uso",
    "runCodexSession": "Ejecuta una sesión de Codex para empezar a registrar el uso local.",
    "topModels": "Modelos principales",
    "noModelsYet": "Todavía no hay modelos",
    "updated": "Actualizado"
  }
};

export default home;
