// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
const kanban = {
  "kanban": {
    "mode": {
      "chat": "Modo chat",
      "chatShort": "Chat",
      "kanban": "Modo kanban",
      "kanbanShort": "Tablero"
    },
    "columns": {
      "todo": "Por hacer",
      "inprogress": "En progreso",
      "testing": "En revisión",
      "done": "Hecho"
    },
    "projects": {
      "title": "Proyectos",
      "subtitle": "Selecciona un espacio de trabajo para gestionar tareas",
      "empty": "Todavía no hay espacios de trabajo",
      "emptyHint": "Añade un espacio de trabajo para empezar a gestionar tareas",
      "taskCount": "{{count}} tareas"
    },
    "board": {
      "back": "Atrás",
      "backActions": "Acciones de retroceso",
      "backToPanels": "Volver a los paneles",
      "backToChat": "Volver al chat",
      "addTask": "Añadir",
      "searchPlaceholder": "Buscar...",
      "toggleGitPanel": "Cambios de Git"
    },
    "task": {
      "createTitle": "Crear tarea",
      "create": "Crear",
      "titlePlaceholder": "Introduce el título de la tarea",
      "descPlaceholder": "Describe la tarea...",
      "notInstalled": "No instalado",
      "noModels": "Sin modelos",
      "addImage": "Añadir imagen",
      "start": "Iniciar",
      "menu": "Menú de la tarea",
      "edit": "Editar",
      "editTitle": "Editar tarea",
      "update": "Actualizar",
      "dragToStart": "Arrastra esta tarea a «En progreso» para iniciarla",
      "delete": "Eliminar",
      "cancelSchedule": "Cancelar programación",
      "pauseSchedule": "Pausar programación",
      "resumeSchedule": "Reanudar programación",
      "blockTask": "Marcar como bloqueada",
      "linked": "Vinculada",
      "processing": "Procesando...",
      "generateTitle": "Generar título",
      "generateTitleFailed": "No se pudo generar el título",
      "generateTitleTimeout": "Se agotó el tiempo de generación del título, inténtalo de nuevo",
      "schedule": {
        "modeLabel": "Programación",
        "manual": "Manual",
        "once": "Ejecutar una vez",
        "recurring": "Recurrente",
        "runAt": "Ejecutar a las",
        "every": "Cada",
        "minutes": "minutos",
        "hours": "horas",
        "days": "días",
        "weeks": "semanas",
        "executionModeLabel": "Ejecución",
        "sameThread": "Ejecutar en el mismo hilo",
        "newThread": "Iniciar un nuevo hilo en cada ejecución",
        "maxRounds": "Límite de rondas (1-50)",
        "resultPassing": "Paso de resultado",
        "passResult": "Pasar el resultado anterior",
        "blockResult": "No pasar el resultado",
        "onceBadge": "Una vez",
        "recurringBadge": "Programada",
        "schedulerBadge": "Programador",
        "runningBadge": "En ejecución",
        "scheduledBadge": "Programada",
        "onceOverdueBadge": "Ejecución perdida"
      },
      "chain": {
        "upstreamLabel": "Tarea previa",
        "none": "Ninguna",
        "badge": "Encadenada"
      },
      "group": {
        "recurring": "Grupo de ejecución recurrente",
        "chain": "Grupo de tareas vinculadas",
        "count": "{{count}} elementos",
        "bulkComplete": "Completar en masa",
        "bulkCompleteConfirm": "¿Confirmar el completado masivo de {{count}} tareas de este grupo?",
        "loadMore": "Cargar {{count}} más",
        "remaining": "{{count}} restantes"
      },
      "snapshot": {
        "badge": "Instantánea lista"
      },
      "latestRunSummary": {
        "ariaLabel": "Resumen de la última ejecución"
      },
      "blocked": "Bloqueada: {{reason}}",
      "detail": {
        "runAt": "Ejecutar a las {{time}}",
        "every": "Cada {{interval}} {{unit}}",
        "countdown": "Cuenta regresiva {{time}}",
        "sameThread": "Mismo hilo",
        "newThread": "Nuevo hilo",
        "runIndex": "Ejecución n.º {{index}}",
        "headCode": "#{{code}}",
        "groupCode": "#{{code}}",
        "chainOrder": "Paso n.º {{order}}",
        "rounds": "Rondas {{current}}/{{max}}",
        "resultPassed": "Paso a través",
        "resultBlocked": "Sin paso a través",
        "timeRange": "{{start}} - {{end}}",
        "startedAt": "Iniciada {{time}}",
        "finishedAt": "Finalizada {{time}}"
      },
      "blockedReason": {
        "nonReentrant": "La tarea ya se está ejecutando",
        "missedOnceWindow": "Se perdió la ventana de ejecución única",
        "invalidRecurringRule": "Regla recurrente no válida",
        "skippedMissedRecurringWindows": "Se omitieron las ventanas recurrentes perdidas",
        "maxRoundsReached": "Se alcanzó el límite de rondas y se completó automáticamente",
        "missingUpstreamSnapshot": "Falta la instantánea de resultado previa",
        "downstreamNotTodo": "La tarea posterior no está en «Por hacer»",
        "downstreamHasSchedule": "La tarea posterior tiene una programación independiente",
        "chainRequiresHeadTrigger": "La tarea encadenada debe activarse desde la tarea inicial",
        "chainRequiresHeadTriggerWithOrder": "La tarea encadenada debe activarse automáticamente por el paso inicial (n.º {{headOrder}}); el paso actual es el n.º {{currentOrder}}",
        "chainRequiresExecutionCompletion": "La tarea encadenada debe completar la ejecución en «En progreso» antes de pasar a «En revisión»/«Hecho»",
        "chainCompletedCannotBackToTodo": "Las tareas encadenadas completadas no se pueden mover de nuevo a «Por hacer»",
        "chainCompletedStatusLocked": "Las tareas encadenadas completadas no se pueden mover a otros estados",
        "scheduledTriggerBlocked": "Se omitió el activador recurrente mientras la tarea se ejecuta",
        "dragIntoChainGroupBlocked": "Las tareas no vinculadas no se pueden arrastrar a grupos vinculados",
        "manualBlocked": "Bloqueada manualmente",
        "manualCancelled": "Programación cancelada manualmente"
      },
      "validation": {
        "generic": "Configuración de tarea no válida. Ajústala y reintenta.",
        "scheduleTodoOnly": "Solo las tareas en «Por hacer» pueden configurar programación.",
        "invalidOnceTime": "Selecciona una hora de programación válida.",
        "invalidRecurringInterval": "El intervalo recurrente debe ser mayor que 0.",
        "invalidRecurringRule": "No se puede calcular el próximo momento recurrente.",
        "chainRequiresTodoTask": "Solo las tareas en «Por hacer» pueden unirse a una cadena de tareas.",
        "downstreamCannotBeScheduled": "Las tareas posteriores no pueden mantener programaciones independientes.",
        "chainSelfCycle": "Una tarea no puede usarse a sí misma como tarea previa.",
        "chainPreviousNotFound": "No se encontró la tarea previa seleccionada.",
        "chainRequiresTodoUpstream": "La tarea previa debe permanecer en estado «Por hacer».",
        "chainMultiDownstream": "La tarea previa seleccionada ya tiene una tarea posterior.",
        "chainCycleDetected": "Se detectó un ciclo en la cadena. Elige otra tarea previa."
      }
    },
    "conversation": {
      "close": "Cerrar"
    },
    "panel": {
      "subtitle": "Selecciona un panel para gestionar tareas",
      "create": "Nuevo panel",
      "namePlaceholder": "Introduce el nombre del panel",
      "empty": "Todavía no hay paneles. Crea uno para empezar.",
      "menu": "Menú del panel",
      "rename": "Renombrar",
      "delete": "Eliminar",
      "deleteConfirmTitle": "Confirmar eliminación",
      "deleteConfirmMessage": "¿Seguro que quieres eliminar el panel «{{name}}»? También se eliminarán {{count}} tareas de este panel. Esta acción no se puede deshacer.",
      "cancel": "Cancelar",
      "confirmDelete": "Eliminar",
      "searchPanels": "Buscar paneles...",
      "noPanelsFound": "No se encontraron paneles"
    },
    "workspace": {
      "searchWorkspaces": "Buscar espacios de trabajo...",
      "noWorkspacesFound": "No se encontraron espacios de trabajo"
    },
    "composer": {
      "relatedPanels": "Paneles de proyecto vinculados",
      "openPanel": "Abrir panel vinculado",
      "empty": "No hay paneles vinculados",
      "count": "{{count}} paneles",
      "clear": "Borrar selección",
      "more": "Más",
      "collapse": "Contraer",
      "link": "enlazar",
      "contextModeLabel": "Contexto",
      "contextModeNew": "Nuevo hilo",
      "contextModeInherit": "Heredar actual"
    }
  }
};

export default kanban;
