// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {
  "layout": {
    "resizeGitHistoryPanel": "Redimensionar panel de historial Git",
    "resizeSidebar": "Redimensionar barra lateral",
    "resizeRightPanel": "Redimensionar panel derecho",
    "resizeEditorSplit": "Redimensionar división del editor",
    "resizeNoteCardsSplit": "Redimensionar división de conversación y notas",
    "resizePlanPanel": "Redimensionar panel del plan",
    "resizeRuntimeConsole": "Redimensionar consola de ejecución",
    "resizeProjects": "Redimensionar proyectos"
  }
};

export default layout;
