// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/menu.ts; keys mirror the English source.
const menu = {
  "menu": {
    "about": "Acerca de {{appName}}",
    "checkForUpdates": "Buscar actualizaciones…",
    "settings": "Ajustes…",
    "file": "Archivo",
    "newAgent": "Nuevo Agent",
    "newWorktreeAgent": "Nuevo Agent de Worktree",
    "newCloneAgent": "Nuevo Agent de clonación",
    "newWindow": "Nueva ventana",
    "addWorkspace": "Añadir espacio de trabajo…",
    "closeWindow": "Cerrar ventana",
    "quit": "Salir",
    "edit": "Editar",
    "composer": "Composer",
    "cycleModel": "Cambiar modelo",
    "cycleAccessMode": "Cambiar modo de acceso",
    "cycleReasoningMode": "Cambiar modo de razonamiento",
    "cycleCollaborationMode": "Cambiar modo de colaboración",
    "view": "Ver",
    "toggleProjectsSidebar": "Alternar barra lateral de proyectos",
    "toggleGitSidebar": "Alternar barra lateral derecha",
    "toggleGlobalSearch": "Alternar búsqueda global",
    "toggleDebugPanel": "Alternar panel de depuración",
    "toggleTerminal": "Alternar terminal",
    "toggleDevtools": "Alternar herramientas de desarrollador",
    "nextAgent": "Siguiente Agent",
    "previousAgent": "Agent anterior",
    "nextWorkspace": "Siguiente espacio de trabajo",
    "previousWorkspace": "Espacio de trabajo anterior",
    "toggleFullScreen": "Alternar pantalla completa",
    "window": "Ventana",
    "minimize": "Minimizar",
    "maximize": "Maximizar",
    "reloadWindow": "Recargar ventana",
    "help": "Ayuda"
  }
};

export default menu;
