// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {
  "modes": {
    "selectMode": "Seleccionar modo",
    "default": {
      "label": "Modo predeterminado",
      "tooltip": "Comportamiento de permisos estándar",
      "description": "Requiere confirmación manual para cada operación, adecuado para un uso cauteloso"
    },
    "plan": {
      "label": "Modo de planificación",
      "tooltip": "Modo de planificación: análisis de solo lectura",
      "description": "Usa solo herramientas de solo lectura, genera un plan para la aprobación del usuario"
    },
    "acceptEdits": {
      "label": "Modo agente",
      "tooltip": "Aceptar automáticamente las ediciones de archivos",
      "description": "Acepta automáticamente la creación/edición de archivos, reduciendo los pasos de confirmación"
    },
    "bypassPermissions": {
      "label": "Modo automático",
      "tooltip": "Omitir todas las comprobaciones de permisos",
      "description": "Totalmente automatizado, omitiendo todas las comprobaciones de permisos [Usar con precaución]"
    }
  }
};

export default modes;
