// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "Seleccionar modelo",
    "addModel": "Añadir modelo",
    "refreshConfig": "Actualizar configuración",
    "refreshingConfig": "Actualizando...",
    "refreshConfigFailed": "Error al actualizar: {{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "El modelo de codificación agéntica de frontera más reciente."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "Modelo de codificación agéntica equilibrado para el trabajo diario."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "Modelo de codificación agéntica rápido y asequible."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "Modelo de frontera para codificación compleja, investigación y trabajo del mundo real."
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "Modelo potente para la codificación diaria."
      }
    }
  }
};

export default models;
