// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {
  "panels": {
    "radar": "Radar",
    "git": "Git",
    "files": "Archivos",
    "search": "Buscar",
    "notes": "Notas",
    "memory": "Memoria",
    "projectMap": "Mapa del proyecto",
    "intentCanvas": "Lienzo de intención",
    "activity": "Actividad",
    "prompts": "Prompts"
  }
};

export default panels;
