// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {
  "plan": {
    "title": "Plan",
    "noPlan": "No hay ningún plan disponible",
    "steps": "Pasos",
    "completed": "Completado",
    "inProgress": "En curso",
    "pending": "Pendiente"
  }
};

export default plan;
