// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/prompts.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/prompts.ts; keys mirror the English source.
const prompts = {
  "prompts": {
    "title": "Prompts personalizados",
    "noPrompts": "Sin prompts",
    "filterPrompts": "Filtrar prompts",
    "globalPrompts": "Prompts generales",
    "workspacePrompts": "Prompts del espacio de trabajo",
    "addWorkspacePrompt": "Añadir prompt del espacio de trabajo",
    "addGeneralPrompt": "Añadir prompt general",
    "noWorkspacePrompts": "Aún no hay prompts del espacio de trabajo",
    "noGeneralPrompts": "Aún no hay prompts generales",
    "createOrDropWorkspace": "Crea uno aquí o suelta un archivo .md en la",
    "createOrDropGeneral": "Crea uno aquí o suelta un archivo .md en",
    "workspacePromptsFolder": "carpeta de prompts del espacio de trabajo",
    "codexHomePrompts": "CODEX_HOME/prompts",
    "promptCount": "{{count}} prompt",
    "promptCount_other": "{{count}} prompts",
    "name": "Nombre",
    "promptName": "Nombre del prompt",
    "scope": "Alcance",
    "workspace": "Espacio de trabajo",
    "general": "General",
    "description": "Descripción",
    "optionalDescription": "Descripción opcional",
    "argumentHint": "Sugerencia de argumento",
    "optionalArgumentHint": "Sugerencia de argumento opcional",
    "content": "Contenido",
    "promptContent": "Contenido del prompt",
    "send": "Enviar",
    "sendToCurrentAgent": "Enviar al agente actual",
    "newAgent": "Nuevo agente",
    "sendToNewAgent": "Enviar a un nuevo agente",
    "edit": "Editar",
    "moveTo": "Mover a {{scope}}",
    "delete": "Eliminar",
    "promptActions": "Acciones del prompt",
    "deletePrompt": "¿Eliminar este prompt?",
    "arguments": "Argumentos",
    "argumentsFor": "Argumentos para {{name}}"
  }
};

export default prompts;
