// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {"reasoning":{"title":"Seleccionar profundidad de razonamiento","default":"Predeterminado","claudeDefault":"Predeterminado","defaultDescription":"Usar el comportamiento de razonamiento predeterminado del motor","low":{"label":"Bajo","description":"Respuestas rápidas con razonamiento básico"},"medium":{"label":"Medio","description":"Razonamiento equilibrado (predeterminado)"},"high":{"label":"Alto","description":"Razonamiento profundo para tareas complejas"},"xhigh":{"label":"Muy alto","description":"Profundidad de razonamiento muy alta"},"max":{"label":"Máximo","description":"Profundidad de razonamiento máxima"},"ultra":{"label":"Ultra","description":"Razonamiento máximo con delegación automática de tareas"}}};

export default reasoning;
