// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/runtimeNotice.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/runtimeNotice.ts; keys mirror the English source.
const runtimeNotice = {
  "runtimeNotice": {
    "title": "Aviso de tiempo de ejecución",
    "open": "Abrir avisos de tiempo de ejecución",
    "minimize": "Minimizar",
    "clear": "Limpiar",
    "emptyTitle": "Aún no hay avisos de tiempo de ejecución",
    "emptyDescription": "El progreso de la inicialización y los errores clave aparecerán aquí.",
    "statusIdle": "Inactivo",
    "statusStreaming": "En ejecución",
    "statusError": "Error",
    "severityInfo": "Información",
    "severityWarning": "Advertencia",
    "severityError": "Error",
    "bootstrap": {
      "start": "Inicializando estado local...",
      "storageMigrationCheck": "Comprobando la migración del estado local...",
      "inputHistoryRestore": "Restaurando el historial de entrada...",
      "interfaceResources": "Cargando recursos de la interfaz...",
      "mountShell": "Montando el shell del cliente...",
      "localStorageMigrationFailed": "Falló la migración del estado local. El arranque continúa en modo degradado.",
      "ready": "Se completó la inicialización del cliente.",
      "failed": "Falló la inicialización del cliente. Recarga e inténtalo de nuevo."
    },
    "runtime": {
      "startupPending": "{{workspace}}: el tiempo de ejecución de {{engine}} se está conectando...",
      "resumePending": "{{workspace}}: falló la comprobación de estado del tiempo de ejecución. Intentando recuperación.",
      "ready": "{{workspace}}: el tiempo de ejecución de {{engine}} está conectado",
      "suspectStale": "{{workspace}}: falló la comprobación de estado del tiempo de ejecución. Intentando recuperación.",
      "cooldown": "{{workspace}}: falló la recuperación del tiempo de ejecución. El periodo de enfriamiento está activo.",
      "quarantined": "{{workspace}}: falló la recuperación del tiempo de ejecución y requiere atención.",
      "codexSessionStartHookSkipped": "Codex omitió el hook SessionStart del proyecto y creó la sesión. Inspecciona `.codex/hooks.json`; el contexto del proyecto puede estar incompleto. ({{reason}})"
    },
    "startup": {
      "taskStarted": "Carga en segundo plano iniciada: {{task}} ({{phase}} / {{workspace}})",
      "taskCompleted": "Carga en segundo plano completada: {{task}} ({{durationMs}}ms)",
      "taskFailed": "Falló la carga en segundo plano: {{task}}",
      "taskTimedOut": "Se agotó el tiempo de la carga en segundo plano: {{task}}. La ruta degradada está activa.",
      "taskDegraded": "Carga en segundo plano degradada: {{task}} ({{reason}})",
      "taskCancelled": "Carga en segundo plano cancelada: {{task}} ({{reason}})",
      "commandCompleted": "Comando interno completado: {{command}} ({{workspace}} / {{durationMs}}ms)",
      "commandFailed": "Falló el comando interno: {{command}} ({{workspace}} / {{durationMs}}ms)",
      "shellReady": "El shell del cliente está listo",
      "inputReady": "La entrada es interactiva",
      "activeWorkspaceReady": "La primera pantalla del espacio de trabajo activo está lista"
    },
    "engine": {
      "checking": "Comprobando el estado de {{engine}}...",
      "ready": "{{engine}} está listo",
      "unavailable": "{{engine}} no está instalado. Instálalo primero.",
      "requiresLogin": "{{engine}} requiere iniciar sesión"
    },
    "codex": {
      "providerSelected": "{{name}} seleccionado. Haz clic en la entrada de Codex para crear una sesión."
    },
    "claude": {
      "resumeCommandCopied": "Comando de reanudación de Claude copiado. Si el selector /resume del TUI no muestra esta sesión de la GUI, ejecuta claude --resume {{sessionId}} o /resume {{sessionId}} explícitamente."
    },
    "error": {
      "createSessionRecoveryRequired": "{{workspace}}: falló la creación de la sesión mientras la recuperación del tiempo de ejecución está en curso",
      "threadTurnFailed": "Falló la sesión de {{engine}}: {{message}}",
      "codexSessionRecoverableFailure": "Conexión de Codex interrumpida: el enlace de sesión anterior o la conexión del tiempo de ejecución ya no se pueden usar. Reintenta o vuelve a conectar."
    }
  }
};

export default runtimeNotice;
