// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "Buscar archivos, kanban, hilos, mensajes, skills, comandos...",
    "placeholderFiltered": "Buscar {{content}}...",
    "inputAria": "Campo de búsqueda",
    "scope": "Alcance",
    "content": "Contenido",
    "current": "Actual",
    "global": "Global",
    "currentWorkspace": "Espacio de trabajo actual",
    "allWorkspaces": "Todos los espacios de trabajo",
    "noResults": "Sin resultados",
    "noResultsHint": "Prueba con palabras clave de la ruta del archivo, el título de la tarea, el título del hilo, el texto del mensaje, el nombre de la skill o el nombre del comando.",
    "fileIndexLoading": "Completando el índice de archivos...",
    "fileIndexPartial": "El índice de archivos está incompleto; pueden faltar algunos archivos.",
    "fileIndexError": "No se pudo cargar el índice de archivos. Vuelve a abrir la búsqueda para reintentarlo.",
    "navigate": "Navegar",
    "open": "Abrir",
    "close": "Cerrar",
    "projectTag": "Proyecto",
    "typeTag": "Tipo",
    "sourceTag": "Fuente",
    "locationTag": "Ubicación",
    "typeAction": "Acción",
    "typeFile": "Archivo",
    "typeKanban": "Kanban",
    "typeThread": "Hilo",
    "typeMessage": "Mensaje",
    "typeHistory": "Historial",
    "typeSkill": "Skill",
    "typeCommand": "Comando",
    "sourceActions": "Acciones de la aplicación",
    "sourceFiles": "Índice de archivos",
    "sourceKanban": "Datos de kanban",
    "sourceThreads": "Títulos de hilos",
    "sourceMessages": "Contenido de mensajes",
    "sourceHistory": "Historial de entrada",
    "sourceSkills": "Lista de skills",
    "sourceCommands": "Lista de comandos",
    "contentAll": "Todo",
    "contentActions": "Acciones",
    "contentFiles": "Archivos",
    "contentKanban": "Kanban",
    "contentThreads": "Hilos",
    "contentMessages": "Mensajes",
    "contentHistory": "Historial",
    "contentSkills": "Skills",
    "contentCommands": "Comandos"
  }
};

export default searchPalette;
