// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
const statusPanel = {
  "statusPanel": {
    "tabTodos": "Tareas",
    "tabSubagents": "Subagentes",
    "tabAgents": "Agentes",
    "tabCheckpoint": "Resultado",
    "tabPlan": "Plan",
    "tabCommands": "Comandos",
    "files": "archivos",
    "emptyTodos": "Sin tareas",
    "emptySubagents": "Sin subagentes",
    "emptyFileChanges": "Sin cambios en archivos",
    "emptyCommands": "Sin comandos",
    "emptyPlan": "Sin plan",
    "planGenerating": "Generando plan...",
    "planSwitchHint": "Cambia al modo Plan para ver el plan",
    "expand": "Expandir panel de estado",
    "collapse": "Contraer panel de estado",
    "label": "Estado",
    "policy": {
      "title": "Auditoría de políticas",
      "count": "{{count}} decisión(es)",
      "noReason": "{{policy}} no proporcionó ningún motivo",
      "verdict": {
        "running": "En ejecución",
        "blocked": "Bloqueado",
        "needs_review": "Revisar",
        "ready": "Listo",
        "no_contribution": "Omitido"
      },
      "corePolicy": {
        "blocked": "Las reglas principales detectaron un riesgo bloqueante.",
        "running": "Las reglas principales detectaron trabajo en curso.",
        "ready": "Las reglas principales encontraron lista la evidencia actual.",
        "needsReview": "Las reglas principales requieren revisión."
      },
      "lintValidationPolicy": {
        "pass": "Lint pasó.",
        "fail": "Lint falló y necesita revisión.",
        "running": "Lint está en ejecución.",
        "notRun": "Lint no se ha ejecutado."
      },
      "typecheckValidationPolicy": {
        "pass": "La verificación de tipos pasó.",
        "fail": "La verificación de tipos falló y necesita revisión.",
        "running": "La verificación de tipos está en ejecución.",
        "notRun": "La verificación de tipos no se ha ejecutado."
      },
      "testsValidationPolicy": {
        "pass": "Las pruebas pasaron.",
        "fail": "Las pruebas fallaron y necesitan revisión.",
        "running": "Las pruebas están en ejecución.",
        "notRun": "Las pruebas no se han ejecutado."
      },
      "openspecGovernancePolicy": {
        "pass": "La evidencia de gobernanza de OpenSpec está actualizada.",
        "warn": "La evidencia de gobernanza de OpenSpec tiene advertencias informativas.",
        "fail": "La evidencia de gobernanza de OpenSpec necesita revisión.",
        "unknown": "La evidencia de gobernanza de OpenSpec no está disponible o está incompleta."
      },
      "largeFileGovernancePolicy": {
        "pass": "La evidencia de gobernanza de archivos grandes está actualizada.",
        "warn": "La evidencia de gobernanza de archivos grandes tiene advertencias informativas.",
        "fail": "La evidencia de gobernanza de archivos grandes necesita revisión.",
        "unknown": "La evidencia de gobernanza de archivos grandes no está disponible o está incompleta."
      },
      "heavyTestNoiseGovernancePolicy": {
        "pass": "La evidencia de ruido de pruebas pesadas está actualizada.",
        "warn": "La evidencia de ruido de pruebas pesadas tiene advertencias informativas.",
        "fail": "La evidencia de ruido de pruebas pesadas necesita revisión.",
        "unknown": "La evidencia de ruido de pruebas pesadas no está disponible o está incompleta."
      },
      "realtimeHarnessGovernancePolicy": {
        "pass": "La evidencia del arnés en tiempo real está actualizada.",
        "warn": "La evidencia del arnés en tiempo real tiene advertencias informativas.",
        "fail": "La evidencia del arnés en tiempo real necesita revisión.",
        "unknown": "La evidencia del arnés en tiempo real no está disponible o está incompleta."
      },
      "capabilityMismatchGovernancePolicy": {
        "pass": "La evidencia de capacidad del motor está actualizada.",
        "warn": "La evidencia de capacidad del motor tiene advertencias informativas.",
        "fail": "La evidencia de capacidad del motor necesita revisión.",
        "unknown": "La evidencia de capacidad del motor no está disponible o está incompleta."
      },
      "engineRuntimeGovernancePolicy": {
        "pass": "La evidencia del contrato de tiempo de ejecución del motor está actualizada.",
        "warn": "La evidencia del contrato de tiempo de ejecución del motor tiene advertencias informativas.",
        "fail": "La evidencia del contrato de tiempo de ejecución del motor necesita revisión.",
        "unknown": "La evidencia del contrato de tiempo de ejecución del motor no está disponible o está incompleta."
      },
      "costBudgetGovernancePolicy": {
        "pass": "La evidencia del presupuesto de costos está actualizada.",
        "warn": "La evidencia del presupuesto de costos tiene advertencias informativas.",
        "fail": "La evidencia del presupuesto de costos necesita revisión.",
        "unknown": "La evidencia del presupuesto de costos no está disponible o está incompleta."
      }
    },
    "audit": {
      "title": "Justificación de la decisión",
      "expandLabel": "{{count}} decisión(es) de política",
      "empty": "Sin decisiones de política",
      "reasonUnavailable": "{{policy}} no proporcionó ningún motivo",
      "sourceUnavailable": "Sin fuente",
      "enforcement": {
        "advisory": "Informativo",
        "blocking": "Bloqueante",
        "informational": "Info"
      }
    },
    "governance": {
      "title": "Evidencia de gobernanza",
      "loading": "Leyendo evidencia...",
      "empty": "Sin evidencia de gobernanza",
      "count": "{{count}} elemento(s) de evidencia · {{needsAction}} requieren acción",
      "group": {
        "needs_action": "Requiere acción · {{count}}",
        "watch": "Observar · {{count}}",
        "passed": "Pasado · {{count}}"
      },
      "meta": {
        "source": "Fuente: {{source}}",
        "artifact": "Artefacto: {{path}}",
        "action": "Acción: resolver {{reason}}"
      },
      "status": {
        "pass": "Aprobado",
        "warn": "Advertencia",
        "fail": "Fallo",
        "unknown": "Desconocido"
      }
    },
    "cost": {
      "title": "Costo / Presupuesto",
      "session": "Sesión",
      "engine": "Motor",
      "model": "Modelo",
      "sessionId": "ID de sesión",
      "tokens": "Tokens",
      "tokenBreakdownLabel": "Desglose del uso de Tokens",
      "known": "Precio coincidente",
      "partial": "Estimación parcial",
      "unknownModel": "Modelo desconocido",
      "pricingSource": "Fuente de precios: {{source}} · {{date}}",
      "historyDegraded": "El historial de costos continúa en memoria porque las escrituras en localStorage fallaron.",
      "accumulated": {
        "session": "Sesión {{amount}}",
        "today": "Hoy {{amount}}",
        "month": "Mes {{amount}}"
      },
      "degraded": {
        "pricing-unavailable": "No hay precios rastreables disponibles para {{engine}}/{{model}}; el costo no se trata silenciosamente como cero.",
        "pricing-stale": "El fixture de precios está desactualizado; este costo es solo informativo.",
        "usage-unavailable": "No hay uso de tokens disponible para la proyección de costos.",
        "block-level-cost-unsupported": "El costo a nivel de bloque no es compatible en esta versión.",
        "unknown": "La proyección de costos está degradada."
      }
    },
    "budget": {
      "unconfigured": "El presupuesto no está configurado. Esto es una orientación, no una comprobación de presupuesto fallida.",
      "unsetShort": "Presupuesto sin definir",
      "barLabel": "Progreso del uso del presupuesto",
      "progress": "{{amount}} / {{limit}}",
      "threshold": {
        "info": "Umbral informativo alcanzado: {{amount}} / {{threshold}}",
        "warn": "Umbral de advertencia alcanzado: {{amount}} / {{threshold}}",
        "block": "Umbral de bloqueo alcanzado: {{amount}} / {{threshold}}. Esta capacidad solo emite señales; no interrumpe el tiempo de ejecución."
      }
    },
    "checkpoint": {
      "verdictTitle": "Veredicto",
      "evidenceTitle": "Evidencia",
      "keyChangesTitle": "Cambios clave",
      "keyChangesEmpty": "Aún no se han capturado cambios clave",
      "fileDetailsTitle": "Detalles del archivo",
      "risksTitle": "Riesgos",
      "nextActionTitle": "Siguiente acción",
      "sections": {
        "summary": "Resumen",
        "advisorySignals": "Señales informativas",
        "evidenceTrail": "Rastro de evidencia",
        "policyAudit": "Auditoría de políticas",
        "suggestedActions": "Acciones sugeridas"
      },
      "advisory": {
        "count": "{{count}} señal(es) informativa(s)"
      },
      "verdict": {
        "running": "En ejecución",
        "blocked": "Bloqueado",
        "needs_review": "Necesita revisión",
        "ready": "Listo"
      },
      "headline": {
        "running": "Trabajo en curso",
        "blocked": "Se requiere atención",
        "needs_review": "Revisar antes de continuar",
        "ready": "Listo para continuar",
        "idle": "Esperando evidencia"
      },
      "summary": {
        "blockedValidation": "Una validación obligatoria falló y debe corregirse primero.",
        "blockedCommand": "El último comando falló: {{command}}. Si el sistema aún está intentando una recuperación automática, espera a que esta ejecución se estabilice antes de detenerla.",
        "blockedSubagent": "Una tarea delegada se detuvo en estado de error.",
        "runningValidation": "La validación aún está en ejecución. Espera el resultado antes de decidir.",
        "runningCommand": "El último comando aún está en ejecución: {{command}}",
        "runningAgent": "Al menos un agente aún está procesando.",
        "runningTodo": "Todavía hay tareas activas en curso.",
        "runningProcessing": "El turno actual todavía está produciendo evidencia de ejecución.",
        "readyWithFiles": "{{count}} archivo(s) modificado(s) pasaron las comprobaciones principales observadas.",
        "ready": "La evidencia de ejecución observada parece estabilizada.",
        "needsValidation": "Los archivos cambiaron, pero las validaciones principales aún no se han ejecutado.",
        "manual": "El resultado está disponible, pero aún necesita una revisión humana.",
        "idle": "Aún no se ha observado evidencia de ejecución fiable."
      },
      "evidence": {
        "filesChanged": "Archivos modificados",
        "filesChangedValue": "{{count}} archivos",
        "validations": "Validaciones",
        "requiredValidations": "Obligatorias",
        "optionalValidations": "Opcionales",
        "fileChangeSummary": "+{{additions}}/-{{deletions}} en {{count}} archivos",
        "runMissing": "Ejecuta primero",
        "runMissingGeneric": "Ejecuta el script de validación principal del proyecto",
        "tasks": "Tareas",
        "agents": "Agentes",
        "inProgress": "En progreso",
        "settled": "Estabilizado"
      },
      "evidenceTrail": {
        "count": "{{count}} elemento(s) de evidencia",
        "sourceLabel": "Fuente",
        "snapshotLabel": "Instantánea",
        "observedLabel": "Observado",
        "artifactLabel": "Artefacto",
        "hashLabel": "Hash",
        "qualifierLabel": "Calificador",
        "degradedLabel": "Degradado",
        "staleLabel": "Desactualizado",
        "snapshotRecorded": "Instantánea registrada",
        "hashRecorded": "Verificado",
        "policy": {
          "buildValidationPolicy": "Validación de compilación",
          "costBudgetGovernancePolicy": "Presupuesto de costos",
          "heavyTestNoiseGovernancePolicy": "Ruido de pruebas pesadas",
          "largeFileGovernancePolicy": "Gobernanza de archivos grandes",
          "lintValidationPolicy": "Validación de lint",
          "openspecGovernancePolicy": "Gobernanza de OpenSpec",
          "testsValidationPolicy": "Validación de pruebas",
          "typecheckValidationPolicy": "Validación de verificación de tipos"
        },
        "sourceName": {
          "build": "Compilación",
          "costBudget": "Presupuesto de costos",
          "heavyTestNoise": "Ruido de pruebas pesadas",
          "largeFile": "Archivo grande",
          "lint": "Lint",
          "openspec": "OpenSpec",
          "tests": "Pruebas",
          "trellis": "Trellis",
          "typecheck": "Verificación de tipos"
        },
        "reason": {
          "governanceArtifactMalformed": "El archivo de evidencia tiene un formato inválido",
          "governanceEvidenceUnavailable": "La evidencia aún no se puede analizar",
          "pricingUnavailable": "El precio del modelo es desconocido",
          "stale": "La evidencia está desactualizada"
        },
        "source": "Fuente: {{source}}",
        "snapshot": "Instantánea: {{id}}",
        "observed": "Observado: {{time}}",
        "artifact": "Artefacto: {{path}}",
        "hash": "Hash: {{hash}}",
        "qualifier": "Calificador: {{qualifier}}",
        "degraded": "Degradado: {{reason}}",
        "stale": "Desactualizado: {{time}}"
      },
      "suggested": {
        "validation": "Opcional: {{command}}",
        "governance": "Comprobación opcional de {{source}}: {{command}}"
      },
      "expandToDock": "Ver los resultados completos en el dock",
      "validations": {
        "lint": "Lint",
        "typecheck": "Verificación de tipos",
        "tests": "Pruebas",
        "build": "Compilación",
        "custom": "Comando",
        "status": {
          "pass": "Aprobado",
          "fail": "Fallo",
          "running": "En ejecución",
          "not_run": "No ejecutado",
          "not_observed": "No observado"
        }
      },
      "keyChanges": {
        "files": "Archivos tocados",
        "filesSummary": "{{count}} archivos modificados · +{{additions}} / -{{deletions}}",
        "tasks": "Progreso de tareas",
        "tasksSummary": "{{completed}}/{{total}} tareas completadas",
        "agents": "Progreso de agentes",
        "agentsSummary": "{{completed}}/{{total}} agentes completados"
      },
      "risks": {
        "none": "No se detectaron riesgos bloqueantes.",
        "commandFailed": "Un comando terminó en error: {{command}}",
        "validationFailed": "Al menos una validación terminó en fallo.",
        "validationMissing": "Las validaciones principales no se han ejecutado tras los cambios en archivos.",
        "subagentError": "Un agente reportó un error: {{agent}}",
        "manualReview": "El sistema aún no ha observado suficiente evidencia para declarar un resultado.",
        "severity": {
          "high": "Alto",
          "medium": "Medio",
          "low": "Bajo"
        }
      },
      "actions": {
        "reviewDiff": "Revisar diff",
        "openRisk": "Inspeccionar riesgos",
        "retry": "Reintentar el paso fallido",
        "commit": "Confirmar cuando esté listo",
        "hint": {
          "runMissingValidation": "Ejecuta la validación faltante antes de decidir si continuar.",
          "running": "Espera a que la evidencia de ejecución actual se estabilice.",
          "blocked": "Inspecciona primero la evidencia fallida; si la recuperación aún está en curso, espera a que la ejecución se estabilice antes de decidir detenerla.",
          "needs_review": "Este resultado aún puede recuperarse. Espera a que la ejecución siga estabilizándose antes de actuar.",
          "ready": "La evidencia está estabilizada; haz la comprobación final previa a la confirmación."
        }
      },
      "commitDialog": {
        "title": "Confirmación del commit",
        "path": "Ruta:",
        "files": "Archivos para confirmar",
        "toggleAllFiles": "Alternar todos los archivos del commit",
        "staged": "Preparado"
      }
    }
  }
};

export default statusPanel;
