// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
const tabbar = {"tabbar":{"projects":"Proyectos","codex":"Codex","spec":"Spec","git":"Git","log":"Registro","primaryNavigation":"Navegación principal","workspaceNavigation":"Navegación del espacio de trabajo"}};

export default tabbar;
