// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
const taskCenter = {
  "taskCenter": {
    "title": "Centro de tareas",
    "eyebrow": "Ejecuciones de Agent",
    "workspaceHero": "Ejecución que necesita atención ahora",
    "statusFilter": "Estado",
    "engineFilter": "Motor",
    "filterAll": "Todos",
    "empty": "Aún no hay ejecuciones de tareas",
    "summary": "{{attention}} de {{total}} ejecuciones necesitan atención",
    "openedFromProjectMap": "Se abrió la ejecución vinculada desde la cola de trabajo del Mapa del proyecto. Esta página muestra el detalle real de TaskRun; si no aparece ninguna acción de conversación, esta ejecución aún no está vinculada a una sesión real.",
    "trigger": "Disparador",
    "updatedAt": "Actualizado",
    "currentStep": "Paso actual",
    "latestOutput": "Última salida",
    "diagnostics": "Diagnósticos",
    "artifacts": "Artefactos",
    "browserEvidence": "Evidencia del navegador",
    "unavailable": "No disponible",
    "noArtifacts": "Aún no hay artefactos",
    "noBrowserEvidence": "No hay evidencia del navegador vinculada",
    "browserEvidenceCandidates": "candidatos",
    "source": {
      "kanban": "kanban",
      "orchestration": "orquestación"
    },
    "browserEvidenceState": {
      "available": "disponible",
      "stale": "obsoleta",
      "expired": "caducada",
      "degraded": "degradada",
      "deleted": "eliminada",
      "unsupported": "no compatible"
    },
    "status": {
      "queued": "En cola",
      "planning": "Planificando",
      "running": "En ejecución",
      "waiting_input": "Esperando entrada",
      "blocked": "Bloqueado",
      "failed": "Fallido",
      "completed": "Completado",
      "canceled": "Cancelado"
    },
    "action": {
      "openConversation": "Abrir conversación",
      "openOrchestrationTask": "Abrir tarea de orquestación",
      "retry": "Reintentar",
      "resume": "Reanudar",
      "cancel": "Cancelar",
      "fork": "Bifurcar ejecución"
    },
    "nextStep": {
      "monitor": "Esta ejecución sigue avanzando. Supervisa el paso actual o cancélala si es necesario.",
      "openConversation": "Abre a continuación la conversación vinculada para proporcionar entrada o inspeccionar la última salida.",
      "resume": "Esta ejecución está bloqueada. Reanúdala primero para continuar por la ruta actual.",
      "retry": "Esta ejecución falló. Reinténtala a continuación o inspecciona el resumen del fallo.",
      "wait": "No se necesita ninguna acción por ahora. Deja primero que la ejecución se estabilice.",
      "review": "Revisa primero los diagnósticos y los artefactos, luego decide el siguiente paso.",
      "fork": "Puedes bifurcar una nueva ejecución a partir del resultado actual para continuar."
    }
  }
};

export default taskCenter;
