// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {
  "terminal": {
    "newTab": "Nueva pestaña",
    "closeTab": "Cerrar pestaña",
    "clear": "Limpiar",
    "title": "Terminal",
    "tabTitle": "Terminal {{number}}",
    "claudeTuiResumeTitle": "Claude TUI",
    "sendSelectionToComposer": "Enviar al redactor"
  }
};

export default terminal;
