// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {
  "time": {
    "justNow": "ahora mismo",
    "minuteAgo": "hace {{count}} minuto",
    "minutesAgo": "hace {{count}} minutos",
    "hourAgo": "hace {{count}} hora",
    "hoursAgo": "hace {{count}} horas",
    "dayAgo": "hace {{count}} día",
    "daysAgo": "hace {{count}} días",
    "weekAgo": "hace {{count}} semana",
    "weeksAgo": "hace {{count}} semanas",
    "now": "ahora",
    "shortSecondsAgo": "hace {{value}}s",
    "shortSecondsIn": "en {{value}}s",
    "shortMinutesAgo": "hace {{value}}min",
    "shortMinutesIn": "en {{value}}min",
    "shortMinutes": "{{value}}min",
    "shortHours": "{{value}}h",
    "shortDays": "{{value}}d",
    "shortWeeks": "{{value}}sem",
    "shortMonths": "{{value}}mes",
    "shortYears": "{{value}}a"
  }
};

export default time;
