// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tools.ts; keys mirror the English source.
const tools = {
  "tools": {
    "readFile": "Leer archivo",
    "readDirectory": "Leer directorio",
    "editFile": "Editar archivo",
    "writeFile": "Escribir archivo",
    "editNotebook": "Editar notebook",
    "runCommand": "Ejecutar comando",
    "executeCommand": "Ejecutar comando",
    "search": "Buscar",
    "fileMatch": "Coincidencia de archivo",
    "findFile": "Encontrar archivo",
    "webFetch": "Obtención web",
    "webSearch": "Búsqueda web",
    "subtask": "Subtarea",
    "todoList": "Lista de tareas",
    "userInputRequest": "Preguntar al usuario",
    "diffCompare": "Diff",
    "result": "Resultado",
    "claudeControlResumeFailed": "La reanudación falló",
    "claudeControlModelChanged": "Modelo cambiado",
    "claudeControlInterrupted": "Interrumpido",
    "claudeControlLocalOutput": "Salida del comando local",
    "webRequest": "Solicitud web",
    "batchRun": "Ejecución por lotes",
    "searchMatch": "Búsqueda/Coincidencia",
    "batchReadFile": "Leer archivos por lotes",
    "batchSearch": "Búsqueda por lotes",
    "batchSearchMatch": "Búsqueda/coincidencia por lotes",
    "batchEditFile": "Editar archivos por lotes",
    "bashGroupBatchRun": "Ejecutar comandos por lotes",
    "bashGroupCompleted": "completado",
    "bashGroupAllCompleted": "Todos completados",
    "bashGroupFailed": "fallido",
    "planQuickView": "Plan",
    "openFullPlanPanel": "Abrir el panel completo del Plan",
    "closePlanPanel": "Cerrar el panel del Plan",
    "path": "Ruta",
    "lineRange": "Línea {{start}}-{{end}}",
    "failedCount": "{{count}} fallidos"
  }
};

export default tools;
