// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "Actualizar",
    "checkingForUpdates": "Buscando actualizaciones...",
    "updateAvailable": "¡Hay una nueva versión disponible!",
    "upToDate": "Estás al día.",
    "downloading": "Descargando actualización…",
    "installing": "Instalando actualización…",
    "restarting": "Reiniciando…",
    "failed": "La actualización falló.",
    "downloaded": "descargado",
    "releaseNotesTitle": "Notas de la versión",
    "releaseNotesLoading": "Cargando notas de la versión…",
    "releaseNotesLoadFailed": "No se pudieron cargar las notas de la versión.",
    "releaseNotesEmpty": "Aún no hay notas de la versión.",
    "releaseNotesOpenInGitHub": "Ver en GitHub",
    "releaseNotesPrev": "Anterior",
    "releaseNotesNext": "Siguiente",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "Inglés:",
    "releaseNotesChinese": "中文："
  }
};

export default update;
