// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
const usage = {
  "usage": {
    "sessionReset": "Reinicios de sesión",
    "weeklyReset": "Reinicios semanales",
    "credits": "Créditos",
    "used": "usado",
    "remaining": "restante",
    "unlimited": "Ilimitado"
  }
};

export default usage;
