// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {"about":{"version":"संस्करण","tagline":"अगली पीढ़ी का VibeCoding एडिटर","checkForUpdates":"अपडेट जांचें","releaseNotes":"रिलीज़ नोट्स","reportIssue":"समस्या रिपोर्ट करें","website":"वेबसाइट","github":"GitHub","wechatGroupTitle":"WeChat ग्रुप में शामिल होने के लिए स्कैन करें"}};

export default about;
