// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
const activityPanel = {
  "activityPanel": {
    "title": "सत्र गतिविधि",
    "noRoot": "वर्तमान कार्य",
    "selectWorkspace": "सत्र गतिविधि देखने के लिए एक वर्कस्पेस चुनें।",
    "emptyIdle": "अभी तक कोई सत्र गतिविधि नहीं।",
    "emptyRunning": "सत्र गतिविधि की प्रतीक्षा है...",
    "emptyCompleted": "यह कार्य पहले चरण में ट्रैक की गई गतिविधि के बिना पूरा हुआ।",
    "eventsCount": "{{count}} इवेंट",
    "sessionsCount": "{{count}} सत्र",
    "liveNow": "लाइव",
    "command": "कमांड",
    "commandPendingSummary": "कमांड चल रही है",
    "commandCategories": {
      "command": "कमांड",
      "search": "खोज",
      "read": "पढ़ें",
      "list": "सूची",
      "git": "Git",
      "test": "टेस्ट",
      "lint": "Lint",
      "build": "बिल्ड",
      "run": "रन"
    },
    "description": "विवरण",
    "cwd": "CWD",
    "waitingForOutput": "कमांड आउटपुट की प्रतीक्षा है...",
    "waitingForReasoning": "सोच सामग्री की प्रतीक्षा है...",
    "rootSession": "रूट",
    "childSession": "चाइल्ड",
    "relatedSessions": "संबंधित",
    "fallbackLinking": "फ़ॉलबैक लिंक",
    "liveEditPreview": "लाइव पूर्वावलोकन",
    "liveEditFollowLabel": "लाइव फ़ॉलो",
    "liveEditPreviewTooltip": "AI जिन फ़ाइलों को वर्तमान में संपादित कर रहा है, उन्हें रीयल टाइम में खोलने के लिए सक्षम करें।",
    "enableLiveEditPreview": "लाइव एडिट पूर्वावलोकन सक्षम करें",
    "disableLiveEditPreview": "लाइव एडिट पूर्वावलोकन अक्षम करें",
    "followCoachTitle": "लाइव फ़ॉलो आज़माएं",
    "followCoachBody": "AI द्वारा संपादित की जा रही फ़ाइलों को फ़ॉलो करने के लिए चालू करें।",
    "followCoachEnable": "अभी सक्षम करें",
    "followCoachDismiss": "अभी नहीं",
    "followNudgeTitle": "लाइव फ़ॉलो",
    "followNudgeErrorTitle": "सक्षम करना विफल",
    "followNudgeBody": "AI फ़ाइलें संपादित कर रहा है। लाइव फ़ॉलो सक्षम करें?",
    "followNudgeEnable": "सक्षम करें",
    "followNudgeLater": "बाद में",
    "followNudgeRetry": "पुनः प्रयास करें",
    "followToggleFailed": "लाइव फ़ॉलो स्विच करने में विफल। कृपया पुनः प्रयास करें।",
    "showOutput": "आउटपुट दिखाएं",
    "hideOutput": "आउटपुट छिपाएं",
    "expandTurnGroup": "टर्न समूह विस्तृत करें",
    "collapseTurnGroup": "टर्न समूह संक्षिप्त करें",
    "turnGroup": "टर्न {{index}}",
    "turnGroupFallback": "लीगेसी गतिविधि",
    "tabs": {
      "ariaLabel": "सत्र गतिविधि श्रेणियां",
      "all": "सारांश",
      "command": "कमांड",
      "file": "आर्टिफैक्ट",
      "task": "कार्य",
      "subagent": "सबएजेंट",
      "explore": "एक्सप्लोर",
      "reasoning": "सोच"
    },
    "artifacts": {
      "kicker": "टर्न आर्टिफैक्ट",
      "title": "आर्टिफैक्ट",
      "fileCount": "{{count}} फ़ाइल",
      "fileCount_other": "{{count}} फ़ाइलें",
      "turnSemanticTitle": "टर्न अर्थ",
      "tabsAriaLabel": "टर्न आर्टिफैक्ट व्यू",
      "tabs": {
        "artifacts": "आर्टिफैक्ट",
        "semantic": "सिमेंटिक डिफ़"
      }
    },
    "radar": {
      "modeCurrentTask": "वर्तमान कार्य",
      "modeWorkspaceRadar": "वर्कस्पेस रडार",
      "runningSection": "चल रहे ({{count}})",
      "recentSection": "हाल ही में पूर्ण ({{count}})",
      "emptyRunning": "कोई चल रहा सत्र नहीं।",
      "emptyRecent": "हाल ही में कोई पूर्ण सत्र नहीं।",
      "openSession": "खोलें",
      "runningCountAria": "{{count}} चल रहे सत्र",
      "recentCountAria": "{{count}} हालिया सत्र",
      "startedAt": "शुरू हुआ:",
      "endedAt": "समाप्त हुआ:",
      "totalDuration": "अवधि:",
      "timeUnknown": "--:--:--",
      "durationUnknown": "--",
      "unreadBadge": "नया",
      "unreadMark": "अपठित",
      "readMark": "पठित",
      "deleteHistoryEntry": "{{name}} हटाएं",
      "deleteDateGroupEntries": "{{date}} की सभी {{count}} प्रविष्टियां हटाएं"
    },
    "status": {
      "running": "चल रहा",
      "completed": "पूर्ण",
      "failed": "विफल",
      "pending": "लंबित"
    }
  }
};

export default activityPanel;
