// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
const app = {
  "app": {
    "title": "ccgui",
    "subtitle": "अपने स्थानीय प्रोजेक्ट्स में agents को ऑर्केस्ट्रेट करें।"
  }
};

export default app;
