// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/approval.ts; keys mirror the English source.
const approval = {
  "approval": {
    "approve": "स्वीकृत करें",
    "deny": "अस्वीकार करें",
    "approveAll": "सभी स्वीकृत करें",
    "denyAll": "सभी अस्वीकार करें",
    "reviewRequest": "अनुरोध की समीक्षा करें",
    "approvalNeeded": "स्वीकृति आवश्यक",
    "pendingBadge": "स्वीकृति लंबित",
    "reviewBeforeApply": "स्थानीय ब्रिज द्वारा इसे निष्पादित करने से पहले इस अनुरोध की समीक्षा करें।",
    "inputRequested": "इनपुट का अनुरोध किया गया",
    "fileChanges": "फ़ाइल बदलाव",
    "commandExecution": "कमांड निष्पादन",
    "genericApproval": "स्वीकृति",
    "toolLabel": "टूल",
    "filePathLabel": "फ़ाइल पथ",
    "commandLabel": "कमांड",
    "noteLabel": "नोट",
    "none": "कोई नहीं",
    "noExtraDetails": "कोई अतिरिक्त विवरण नहीं।",
    "decline": "अस्वीकार करें",
    "close": "बंद करें",
    "approveTurnBatch": "इस बैच में सभी स्वीकृत करें ({{count}})",
    "allowCommandsStartWith": "{{prefix}} से शुरू होने वाली कमांड की अनुमति दें",
    "alwaysAllow": "हमेशा अनुमति दें",
    "approveEnter": "स्वीकृत करें (Enter)",
    "remainingRequests": "{{count}} और स्वीकृति अनुरोध प्रतीक्षा में",
    "applyingApprovedFileChange": "स्वीकृत फ़ाइल बदलाव लागू किया जा रहा है",
    "resumingAfterApproval": "स्वीकृत। बदलाव स्थानीय रूप से लागू किया जा रहा है और Claude फिर से शुरू हो रहा है...",
    "userInputRequested": "उपयोगकर्ता इनपुट का अनुरोध किया गया",
    "requestOf": "{{total}} में से अनुरोध {{current}}",
    "typeAnswerOptional": "अपना उत्तर टाइप करें (वैकल्पिक)",
    "addNotesOptional": "नोट्स जोड़ें (वैकल्पिक)",
    "noQuestionsProvided": "कोई प्रश्न प्रदान नहीं किया गया।",
    "showSecret": "दिखाएं",
    "hideSecret": "छिपाएं",
    "submitFailed": "सबमिट विफल। कृपया पुनः प्रयास करें।",
    "submit": "सबमिट करें",
    "dismiss": "बंद करें",
    "dismissUserInputRequest": "इस प्रश्न कार्ड को बंद करें",
    "collapseUserInputRequest": "इस प्रश्न कार्ड को छोड़े बिना संक्षिप्त करें",
    "collapsedUserInputRequest": "संक्षिप्त प्रश्न कार्ड",
    "expandUserInputRequest": "विस्तृत करें",
    "skipUserInputRequest": "इस प्रश्न को छोड़ें और जारी रखें",
    "skipAndContinue": "इस प्रश्न को छोड़ें",
    "submitted": "सबमिट किया गया",
    "noAnswerProvided": "(कोई उत्तर प्रदान नहीं किया गया)",
    "noDisplayableAnswer": "(कोई प्रदर्शन योग्य उत्तर नहीं)",
    "userInputSubmittedBanner": "[उपयोगकर्ता इनपुट सबमिट किया गया]"
  }
};

export default approval;
