// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {"askUserQuestion":{"title":"Claude का आपके लिए एक प्रश्न है","progress":"प्रश्न {{current}} / {{total}}","timeoutWarning":"कृपया जल्दी जवाब दें। यह डायलॉग {{seconds}} सेकंड में स्वतः बंद हो जाएगा","collapse":"संक्षिप्त करें","expand":"विस्तृत करें","clickToAnswer":"उत्तर देने के लिए क्लिक करें","questionTab":"प्रश्न {{index}}","cancel":"रद्द करें","back":"पीछे","next":"आगे","submit":"सबमिट करें","otherOption":"अन्य","otherOptionDesc":"एक कस्टम उत्तर दर्ज करें","customInputPlaceholder":"अपना उत्तर टाइप करें...","multiSelectHint":"आप कई विकल्प चुन सकते हैं"}};

export default askUserQuestion;
