// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
const codexModes = {
  "codexModes": {
    "default": {
      "label": "सुझाव (स्वीकृति)",
      "tooltip": "Codex approval_policy=untrusted – फ़ाइलें संपादित करने या शेल कमांड चलाने से पहले पूछता है।",
      "description": "सबसे सुरक्षित विकल्प। हर राइट या कमांड के लिए आपकी स्वीकृति आवश्यक है।"
    },
    "plan": {
      "label": "प्लान मोड",
      "tooltip": "प्लान मोड - केवल-पढ़ने वाला विश्लेषण",
      "description": "केवल रीड-ओनली टूल का उपयोग करता है, उपयोगकर्ता की स्वीकृति के लिए प्लान बनाता है"
    },
    "acceptEdits": {
      "label": "ऑटो एडिट",
      "tooltip": "Codex approval_policy=auto-edit – फ़ाइल पैच स्वचालित रूप से लागू करता है, फिर भी शेल कमांड से पहले पूछता है।",
      "description": "कमांड स्वीकृतियाँ बनाए रखते हुए apply_patch के ज़रिए फ़ाइलें स्वतः बनाएँ और संपादित करें।"
    },
    "bypassPermissions": {
      "label": "पूर्ण स्वचालित",
      "tooltip": "Codex approval_policy=never – बिना पूछे कमांड चलाता है और फ़ाइलें लिखता है (वर्कस्पेस सैंडबॉक्स फिर भी लागू रहता है)।",
      "description": "हैंड्स-ऑफ़ मोड। Codex संपादन और शेल कमांड तुरंत निष्पादित करता है।"
    }
  }
};

export default codexModes;
