// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {
  "debug": {
    "title": "डिबग",
    "copyLogs": "लॉग कॉपी करें",
    "clearLogs": "लॉग साफ़ करें",
    "noLogs": "कोई डिबग लॉग नहीं",
    "copy": "कॉपी करें",
    "clear": "साफ़ करें",
    "noDebugEventsYet": "अभी तक कोई डिबग इवेंट नहीं।"
  }
};

export default debug;
