// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "कनेक्शन विफल",
    "requestFailed": "अनुरोध विफल",
    "unexpectedError": "एक अप्रत्याशित त्रुटि हुई",
    "sessionExpired": "सत्र समाप्त हो गया",
    "rateLimited": "दर सीमित। कृपया बाद में पुनः प्रयास करें।",
    "networkError": "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जाँचें।",
    "failedToAddWorkspace": "वर्कस्पेस जोड़ने में विफल।",
    "failedToOpenNewWindow": "नई विंडो खोलने में विफल।",
    "failedToCreateSession": "सत्र बनाने में विफल।",
    "failedToCreateSessionNoThreadId": "रनटाइम ने कोई नई सत्र आईडी नहीं लौटाई।",
    "failedToCreateSessionRuntimeRecovering": "इस सत्र को बनाते समय रनटाइम पुनः आरंभ हो रहा था। ऐप पहले ही एक बार पुनः प्रयास कर चुका है। वर्कस्पेस को पुनः कनेक्ट करें और फिर प्रयास करें।",
    "reconnectAndRetryCreateSession": "पुनः कनेक्ट करें और निर्माण पुनः प्रयास करें",
    "reconnectingAndRetryingCreateSession": "पुनः कनेक्ट और निर्माण पुनः प्रयास हो रहा है...",
    "runtimeRecovered": "रनटाइम पुनर्प्राप्त हुआ।",
    "retryingCreateSessionAfterRecovery": "सत्र निर्माण पुनः प्रयास हो रहा है...",
    "cliNotFound": "न तो Claude Code CLI और न ही Codex CLI मिला। कृपया इनमें से एक इंस्टॉल करें।",
    "cliNotFoundHint": "Claude Code इंस्टॉल करें: npm install -g @anthropic-ai/claude-code\nCodex इंस्टॉल करें: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI नहीं मिला। Codex इंस्टॉल करें और सुनिश्चित करें कि `codex` आपके PATH पर है।",
    "couldntOpenWorkspace": "वर्कस्पेस नहीं खुल सका",
    "dismissError": "त्रुटि खारिज करें"
  }
};

export default errors;
