// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
const home = {
  "home": {
    "welcome": "स्वागत है",
    "subtitle": "आज आप क्या बनाना चाहेंगे?",
    "latestActivity": "हाल की बातचीत",
    "noActivity": "कोई हाल की बातचीत नहीं",
    "latestAgents": "नवीनतम Agent",
    "agentReplied": "Agent ने उत्तर दिया।",
    "running": "चल रहा है",
    "loadingAgents": "Agent लोड हो रहे हैं",
    "noAgentActivity": "अभी तक कोई Agent गतिविधि नहीं",
    "startThreadToSee": "यहाँ नवीनतम उत्तर देखने के लिए एक thread शुरू करें।",
    "openProject": "प्रोजेक्ट जोड़ें",
    "addWorkspace": "प्रोजेक्ट जोड़ें",
    "usageSnapshot": "उपयोग snapshot",
    "refreshUsage": "उपयोग रिफ्रेश करें",
    "workspace": "Workspace",
    "allWorkspaces": "सभी workspaces",
    "view": "देखें",
    "tokens": "Token",
    "time": "समय",
    "last7Days": "पिछले 7 दिन",
    "last30Days": "पिछले 30 दिन",
    "cacheHitRate": "Cache hit दर",
    "peakDay": "शीर्ष दिन",
    "agentTime": "agent समय",
    "runs": "रन",
    "avg": "औसत",
    "total": "कुल",
    "day": "दिन",
    "noUsageData": "अभी तक कोई उपयोग डेटा नहीं",
    "runCodexSession": "लोकल उपयोग ट्रैक करना शुरू करने के लिए एक Codex सत्र चलाएँ।",
    "topModels": "शीर्ष मॉडल",
    "noModelsYet": "अभी तक कोई मॉडल नहीं",
    "updated": "अपडेट किया गया"
  }
};

export default home;
