// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
const homeChat = {
  "homeChat": {
    "badge": "Workspace-जागरूक चैट होम",
    "minimalTitle": "कुछ भी बनाएँ",
    "announcementTag": "नया",
    "announcementText": "लैंडिंग टेम्पलेट, वर्कफ़्लो कार्ड और स्टार्टर prompts एक्सप्लोर करें",
    "announcementAction": "खोजें",
    "title": "ccgui Agent, काम को आसान बनाएँ",
    "titleLineOne": "Enter दबाएँ",
    "titleLineTwo": "ऐप्स तेज़ी से बनाएँ",
    "subtitle": "जिस composer को आप पहले से जानते हैं उसे बनाए रखें, उसके चारों ओर एक मजबूत लैंडिंग लय जोड़ें, और कम सेटअप बाधा के साथ वास्तविक निष्पादन में आगे बढ़ें।",
    "promptPlaceholder": "अपना लक्ष्य बताएँ, उदाहरण के लिए: इस repository के लिए release notes बनाएँ और जोखिम जाँच शामिल करें।",
    "pathResolving": "डिफ़ॉल्ट प्रोजेक्ट पथ हल हो रहा है...",
    "workspaceSearchPlaceholder": "प्रोजेक्ट खोजें",
    "addWorkspaceAction": "नया प्रोजेक्ट जोड़ें",
    "workspaceNoMatch": "कोई प्रोजेक्ट नहीं मिला",
    "loadingRecentAgents": "हाल का काम लोड हो रहा है",
    "recentConversations": "हाल की बातचीत",
    "quickActions": "त्वरित कार्रवाइयाँ",
    "placeholderHint": "ये प्रवेश बिंदु अभी के लिए दृश्य placeholders हैं।",
    "placeholderSelected": "{{label}} जल्द आ रहा है।",
    "seeAll": "सभी देखें",
    "navPrev": "पिछले कार्ड",
    "navNext": "अगले कार्ड",
    "comingSoon": "जल्द आ रहा है",
    "tabs": {
      "templates": "टेम्पलेट",
      "workflows": "वर्कफ़्लो"
    },
    "quick": {
      "plan": "brief से योजना",
      "doc": "दस्तावेज़",
      "release": "रिलीज़ नोट्स",
      "review": "repository की समीक्षा करें",
      "spec": "spec का मसौदा"
    },
    "cards": {
      "website": {
        "title": "वेबसाइट लॉन्च किट",
        "description": "एक परिष्कृत लॉन्च पेज के लिए hero लेआउट, संरचना और स्टार्टर कॉपी।"
      },
      "creator": {
        "title": "क्रिएटर डैशबोर्ड",
        "description": "सामग्री, ट्रैफ़िक और prompts के लिए एक analytics-प्रथम नियंत्रण कक्ष।"
      },
      "audio": {
        "title": "ऑडियो लैंडिंग",
        "description": "संगीत, podcasts या मीडिया लॉन्च के लिए मुलायम gradients और बोल्ड मेट्रिक्स।"
      },
      "editorial": {
        "title": "संपादकीय घोषणापत्र",
        "description": "अभियानों, वक्तव्यों और ब्रांडेड showcases के लिए पोस्टर जैसी टाइपोग्राफी।"
      },
      "release": {
        "title": "रिलीज़ चेकलिस्ट",
        "description": "बदलावों, सत्यापन, नोट्स और rollout फ़ॉलो-अप के लिए एक चरणबद्ध handoff।"
      },
      "research": {
        "title": "रिसर्च स्प्रिंट",
        "description": "प्रश्न एकत्र करें, निष्कर्षों का स्रोत खोजें, और उन्हें अगली कार्रवाइयों में संश्लेषित करें।"
      },
      "debug": {
        "title": "डिबग डेस्क",
        "description": "logs की छँटाई, regressions को सीमित करना, और सत्यापित सुधारों का दस्तावेज़ीकरण।"
      },
      "content": {
        "title": "सामग्री पाइपलाइन",
        "description": "सुसंगत checkpoints के साथ brief, मसौदा, समीक्षा और प्रकाशित करें।"
      }
    }
  }
};

export default homeChat;
