// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
const kanban = {
  "kanban": {
    "mode": {
      "chat": "चैट मोड",
      "chatShort": "चैट",
      "kanban": "Kanban मोड",
      "kanbanShort": "बोर्ड"
    },
    "columns": {
      "todo": "करना है",
      "inprogress": "प्रगति में",
      "testing": "समीक्षा में",
      "done": "पूर्ण"
    },
    "projects": {
      "title": "प्रोजेक्ट",
      "subtitle": "कार्य प्रबंधित करने के लिए एक workspace चुनें",
      "empty": "अभी तक कोई workspace नहीं",
      "emptyHint": "कार्य प्रबंधन शुरू करने के लिए एक workspace जोड़ें",
      "taskCount": "{{count}} कार्य"
    },
    "board": {
      "back": "वापस",
      "backActions": "वापस कार्रवाइयाँ",
      "backToPanels": "पैनल पर वापस",
      "backToChat": "चैट पर वापस",
      "addTask": "जोड़ें",
      "searchPlaceholder": "खोजें...",
      "toggleGitPanel": "Git बदलाव"
    },
    "task": {
      "createTitle": "कार्य बनाएँ",
      "create": "बनाएँ",
      "titlePlaceholder": "कार्य शीर्षक दर्ज करें",
      "descPlaceholder": "कार्य का वर्णन करें...",
      "notInstalled": "इंस्टॉल नहीं है",
      "noModels": "कोई मॉडल नहीं",
      "addImage": "छवि जोड़ें",
      "start": "शुरू करें",
      "menu": "कार्य मेनू",
      "edit": "संपादित करें",
      "editTitle": "कार्य संपादित करें",
      "update": "अपडेट करें",
      "dragToStart": "शुरू करने के लिए कृपया इस कार्य को \"प्रगति में\" पर खींचें",
      "delete": "हटाएँ",
      "cancelSchedule": "शेड्यूल रद्द करें",
      "pauseSchedule": "शेड्यूल रोकें",
      "resumeSchedule": "शेड्यूल फिर से शुरू करें",
      "blockTask": "अवरुद्ध चिह्नित करें",
      "linked": "लिंक किया गया",
      "processing": "प्रोसेस हो रहा है...",
      "generateTitle": "शीर्षक बनाएँ",
      "generateTitleFailed": "शीर्षक बनाने में विफल",
      "generateTitleTimeout": "शीर्षक बनाने का समय समाप्त हुआ, कृपया पुनः प्रयास करें",
      "schedule": {
        "modeLabel": "शेड्यूल",
        "manual": "मैन्युअल",
        "once": "एक बार चलाएँ",
        "recurring": "आवर्ती",
        "runAt": "इस समय चलाएँ",
        "every": "प्रत्येक",
        "minutes": "मिनट",
        "hours": "घंटे",
        "days": "दिन",
        "weeks": "सप्ताह",
        "executionModeLabel": "निष्पादन",
        "sameThread": "उसी thread में चलाएँ",
        "newThread": "हर बार नया thread शुरू करें",
        "maxRounds": "राउंड सीमा (1-50)",
        "resultPassing": "परिणाम पास करना",
        "passResult": "पिछला परिणाम पास करें",
        "blockResult": "परिणाम पास न करें",
        "onceBadge": "एक-बार",
        "recurringBadge": "शेड्यूल किया गया",
        "schedulerBadge": "शेड्यूलर",
        "runningBadge": "चल रहा है",
        "scheduledBadge": "शेड्यूल किया गया",
        "onceOverdueBadge": "छूटा हुआ रन"
      },
      "chain": {
        "upstreamLabel": "अपस्ट्रीम कार्य",
        "none": "कोई नहीं",
        "badge": "चेन किया गया"
      },
      "group": {
        "recurring": "आवर्ती रन समूह",
        "chain": "लिंक किया गया कार्य समूह",
        "count": "{{count}} आइटम",
        "bulkComplete": "एक साथ पूर्ण करें",
        "bulkCompleteConfirm": "इस समूह के {{count}} कार्यों को एक साथ पूर्ण करने की पुष्टि करें?",
        "loadMore": "{{count}} और लोड करें",
        "remaining": "{{count}} शेष"
      },
      "snapshot": {
        "badge": "Snapshot तैयार"
      },
      "latestRunSummary": {
        "ariaLabel": "नवीनतम रन सारांश"
      },
      "blocked": "अवरुद्ध: {{reason}}",
      "detail": {
        "runAt": "{{time}} पर चलाएँ",
        "every": "प्रत्येक {{interval}} {{unit}}",
        "countdown": "काउंटडाउन {{time}}",
        "sameThread": "समान thread",
        "newThread": "नया thread",
        "runIndex": "रन #{{index}}",
        "headCode": "#{{code}}",
        "groupCode": "#{{code}}",
        "chainOrder": "चरण #{{order}}",
        "rounds": "राउंड {{current}}/{{max}}",
        "resultPassed": "पास-थ्रू",
        "resultBlocked": "कोई पास-थ्रू नहीं",
        "timeRange": "{{start}} - {{end}}",
        "startedAt": "शुरू हुआ {{time}}",
        "finishedAt": "समाप्त हुआ {{time}}"
      },
      "blockedReason": {
        "nonReentrant": "कार्य पहले से चल रहा है",
        "missedOnceWindow": "एक-बार का रन विंडो छूट गया",
        "invalidRecurringRule": "अमान्य आवर्ती नियम",
        "skippedMissedRecurringWindows": "छूटे हुए आवर्ती विंडो छोड़े गए",
        "maxRoundsReached": "राउंड सीमा पर पहुँचा और स्वतः पूर्ण हुआ",
        "missingUpstreamSnapshot": "अपस्ट्रीम परिणाम snapshot अनुपलब्ध",
        "downstreamNotTodo": "डाउनस्ट्रीम कार्य todo नहीं है",
        "downstreamHasSchedule": "डाउनस्ट्रीम कार्य का स्वतंत्र शेड्यूल है",
        "chainRequiresHeadTrigger": "चेन किए गए कार्य को head कार्य द्वारा ट्रिगर किया जाना चाहिए",
        "chainRequiresHeadTriggerWithOrder": "चेन किए गए कार्य को head चरण (#{{headOrder}}) द्वारा स्वतः ट्रिगर किया जाना चाहिए; वर्तमान चरण #{{currentOrder}} है",
        "chainRequiresExecutionCompletion": "चेन किए गए कार्य को Review/Done में प्रवेश करने से पहले प्रगति में निष्पादन पूरा करना होगा",
        "chainCompletedCannotBackToTodo": "पूर्ण किए गए चेन कार्यों को वापस Todo में नहीं ले जाया जा सकता",
        "chainCompletedStatusLocked": "पूर्ण किए गए चेन कार्यों को अन्य स्थितियों में नहीं ले जाया जा सकता",
        "scheduledTriggerBlocked": "कार्य चलने के दौरान आवर्ती ट्रिगर छोड़ा गया",
        "dragIntoChainGroupBlocked": "बिना लिंक किए कार्यों को लिंक किए गए समूहों में नहीं खींचा जा सकता",
        "manualBlocked": "मैन्युअल रूप से अवरुद्ध",
        "manualCancelled": "शेड्यूल मैन्युअल रूप से रद्द किया गया"
      },
      "validation": {
        "generic": "अमान्य कार्य कॉन्फ़िगरेशन। कृपया समायोजित करें और पुनः प्रयास करें।",
        "scheduleTodoOnly": "केवल todo कार्य ही शेड्यूलिंग कॉन्फ़िगर कर सकते हैं।",
        "invalidOnceTime": "कृपया एक मान्य शेड्यूल समय चुनें।",
        "invalidRecurringInterval": "आवर्ती अंतराल 0 से अधिक होना चाहिए।",
        "invalidRecurringRule": "अगला आवर्ती समय गणना करने में असमर्थ।",
        "chainRequiresTodoTask": "केवल todo कार्य ही किसी कार्य चेन में शामिल हो सकते हैं।",
        "downstreamCannotBeScheduled": "डाउनस्ट्रीम कार्य स्वतंत्र शेड्यूल नहीं रख सकते।",
        "chainSelfCycle": "कोई कार्य स्वयं को अपस्ट्रीम के रूप में उपयोग नहीं कर सकता।",
        "chainPreviousNotFound": "चयनित अपस्ट्रीम कार्य नहीं मिला।",
        "chainRequiresTodoUpstream": "अपस्ट्रीम कार्य को todo स्थिति में रहना चाहिए।",
        "chainMultiDownstream": "चयनित अपस्ट्रीम कार्य में पहले से एक डाउनस्ट्रीम कार्य है।",
        "chainCycleDetected": "चेन चक्र पाया गया। कृपया कोई अन्य अपस्ट्रीम कार्य चुनें।"
      }
    },
    "conversation": {
      "close": "बंद करें"
    },
    "panel": {
      "subtitle": "कार्य प्रबंधित करने के लिए एक पैनल चुनें",
      "create": "नया पैनल",
      "namePlaceholder": "पैनल नाम दर्ज करें",
      "empty": "अभी तक कोई पैनल नहीं। शुरू करने के लिए एक बनाएँ।",
      "menu": "पैनल मेनू",
      "rename": "नाम बदलें",
      "delete": "हटाएँ",
      "deleteConfirmTitle": "हटाने की पुष्टि करें",
      "deleteConfirmMessage": "क्या आप वाकई पैनल \"{{name}}\" हटाना चाहते हैं? इस पैनल के {{count}} कार्य भी हट जाएँगे। यह कार्रवाई पूर्ववत नहीं की जा सकती।",
      "cancel": "रद्द करें",
      "confirmDelete": "हटाएँ",
      "searchPanels": "पैनल खोजें...",
      "noPanelsFound": "कोई पैनल नहीं मिला"
    },
    "workspace": {
      "searchWorkspaces": "workspaces खोजें...",
      "noWorkspacesFound": "कोई workspace नहीं मिला"
    },
    "composer": {
      "relatedPanels": "जुड़े हुए प्रोजेक्ट पैनल",
      "openPanel": "जुड़ा हुआ पैनल खोलें",
      "empty": "कोई जुड़ा हुआ पैनल नहीं",
      "count": "{{count}} पैनल",
      "clear": "चयन साफ़ करें",
      "more": "और",
      "collapse": "संक्षिप्त करें",
      "link": "लिंक",
      "contextModeLabel": "संदर्भ",
      "contextModeNew": "नया Thread",
      "contextModeInherit": "वर्तमान को इनहेरिट करें"
    }
  }
};

export default kanban;
