// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {"layout":{"resizeGitHistoryPanel":"git history पैनल का आकार बदलें","resizeSidebar":"साइडबार का आकार बदलें","resizeRightPanel":"दायाँ पैनल का आकार बदलें","resizeEditorSplit":"एडिटर स्प्लिट का आकार बदलें","resizeNoteCardsSplit":"बातचीत और नोट्स स्प्लिट का आकार बदलें","resizePlanPanel":"प्लान पैनल का आकार बदलें","resizeRuntimeConsole":"रन कंसोल का आकार बदलें","resizeProjects":"प्रोजेक्ट्स का आकार बदलें"}};

export default layout;
