// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/lockScreen.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/lockScreen.ts; keys mirror the English source.
const lockScreen = {
  "lockScreen": {
    "lock": "स्क्रीन लॉक करें",
    "locked": "लॉक किया गया",
    "brandKicker": "Codemoss Product Atlas",
    "title": "ccgui सुरक्षित लॉक · इंजीनियरिंग क्षमता अवलोकन",
    "description": "Threads और कार्य पृष्ठभूमि में चलते रहते हैं। पूरे ccgui डिलीवरी लूप की समीक्षा के लिए इस लॉक स्क्रीन का उपयोग करें: योजना, निष्पादन ऑर्केस्ट्रेशन, समीक्षा और शिपिंग।",
    "tabLabel": "लॉक स्क्रीन टैब नेविगेशन",
    "tabs": {
      "live": "लाइव सत्र",
      "capabilities": "क्षमता एटलस",
      "workflow": "डिलीवरी फ़्लो",
      "elements": "एलिमेंट गाइड"
    },
    "liveTitle": "लाइव सत्र स्ट्रीम",
    "liveDesc": "केवल चल रहे सत्र का आउटपुट दिखाया गया है, नवीनतम गतिविधि द्वारा स्वतः-अपडेट होता है।",
    "liveEmpty": "अभी कोई चल रहे सत्र का आउटपुट नहीं है।",
    "liveRunning": "चल रहा है",
    "capabilityTitle": "क्षमता एटलस",
    "capabilityDesc": "ccgui केवल एक चैट शेल नहीं है। यह प्रोडक्शन फ़्लो के लिए डिज़ाइन किया गया एक local-first इंजीनियरिंग workspace है।",
    "journeyTitle": "सामान्य डिलीवरी यात्रा",
    "journeyDesc": "अधिकांश बदलाव ccgui में इस क्रम से गुज़रते हैं:",
    "elementsTitle": "एलिमेंट गाइड",
    "elementsDesc": "प्रत्येक कोर मॉड्यूल और उसकी ज़िम्मेदारी की त्वरित समीक्षा के लिए इस पेज का उपयोग करें।",
    "unlockTitle": "अनलॉक पैनल",
    "unlockDesc": "पासवर्ड फ़ाइल ~/.ccgui/client/pwd.txt है। यदि यह मौजूद नहीं है, तो अनलॉक की अनुमति है और फ़ाइल एक डिफ़ॉल्ट मान के साथ स्वतः बन जाती है।",
    "passwordInput": "अनलॉक पासवर्ड दर्ज करें",
    "passwordPlaceholder": "पासवर्ड टाइप करें",
    "passwordHint": "पासवर्ड दर्ज करने के बाद Enter दबाएँ या Unlock पर क्लिक करें।",
    "unlock": "अनलॉक करें",
    "invalidPassword": "गलत पासवर्ड। फिर से प्रयास करें।",
    "storageTitle": "पासवर्ड संग्रहण",
    "storageDesc": "पासवर्ड बदलने के लिए, इस फ़ाइल की सामग्री को सीधे संपादित करें और सहेजें।",
    "storagePathLabel": "फ़ाइल पथ",
    "facts": {
      "integrationsLabel": "मल्टी-इंजन रूटिंग",
      "integrationsValue": "Codex / Claude / Gemini",
      "workflowLabel": "डिलीवरी लूप",
      "workflowValue": "योजना → निष्पादन → समीक्षा → शिप",
      "runtimeLabel": "रनटाइम स्थिति",
      "runtimeValue": "लॉक स्क्रीन सक्रिय रन को नहीं रोकती"
    },
    "journey": {
      "planTitle": "पहले योजना बनाएँ",
      "planDesc": "कोड को छूने से पहले दायरा, बाधाएँ और कार्य विभाजन परिभाषित करें।",
      "executeTitle": "संदर्भ के साथ निष्पादित करें",
      "executeDesc": "Kanban कार्य प्रेषण और समानांतर सत्रों के साथ, workspace और thread संदर्भ के साथ चलाएँ।",
      "reviewTitle": "ट्रेस के साथ समीक्षा करें",
      "reviewDesc": "विश्वसनीय सत्यापन के लिए tool ट्रेस, diff और डिबग रिकॉर्ड दृश्यमान रखें।",
      "deliverTitle": "साफ़-सुथरी डिलीवरी करें",
      "deliverDesc": "commits, ब्रांच, PR क्रियाओं और आर्काइव चरणों को पुन: प्रयोज्य टीम संपत्तियों में जोड़ें।"
    },
    "features": {
      "workspaceGraphTitle": "Workspace ग्राफ़",
      "workspaceGraphDesc": "तेज़ संदर्भ स्विचिंग के साथ रिपॉज़िटरी, worktrees, समूहन और क्रमबद्धता प्रबंधित करें।",
      "threadOrchestrationTitle": "Thread ऑर्केस्ट्रेशन",
      "threadOrchestrationDesc": "history रिप्ले, कतारबद्ध प्रॉम्प्ट, रुकावट, स्वतः-शीर्षक और लंबे रन की निरंतरता का समर्थन करता है।",
      "engineRoutingTitle": "इंजन रूटिंग",
      "engineRoutingDesc": "प्रत्येक कार्य के अनुरूप मॉडल, रीज़निंग प्रयास, एक्सेस मोड और सहयोग मोड बदलें।",
      "gitIntelligenceTitle": "Git इंटेलिजेंस",
      "gitIntelligenceDesc": "संदर्भ बदले बिना एक ही वर्कफ़्लो में Diff, Log, Commit, PR और Issue व्यू।",
      "kanbanDispatchTitle": "Kanban प्रेषण",
      "kanbanDispatchDesc": "कार्यों से सत्र बनाएँ और निष्पादन स्थिति को बोर्ड की प्रगति के साथ समन्वयित रखें।",
      "memoryEngineTitle": "मेमोरी इंजन",
      "memoryEngineDesc": "प्रोजेक्ट ज्ञान और प्राथमिकताएँ बनाए रखें ताकि भविष्य के सत्र संदर्भ के साथ शुरू हों।",
      "unifiedSearchTitle": "एकीकृत खोज",
      "unifiedSearchDesc": "फ़ाइलों, threads, संदेशों, स्किल्स और कमांड में एक ही पैलेट।",
      "terminalObservabilityTitle": "टर्मिनल + अवलोकनीयता",
      "terminalObservabilityDesc": "अंतर्निहित टर्मिनल और डिबग ट्रेस समस्या निवारण को तेज़ और ऑडिट-योग्य बनाते हैं।",
      "composerControlTitle": "Composer नियंत्रण",
      "composerControlDesc": "प्रीसेट, शॉर्टकट, fence नियम, पेस्ट व्यवहार और डिक्टेशन के लिए केंद्रीकृत नियंत्रण।",
      "promptAssetsTitle": "प्रॉम्प्ट संपत्तियाँ",
      "promptAssetsDesc": "workspace/ग्लोबल प्रॉम्प्ट संपत्तियों को प्रबंधित करें और डिलीवरी कार्यों में उनका पुन: उपयोग करें।",
      "collaborationModeTitle": "सहयोग मोड",
      "collaborationModeDesc": "अन्वेषण, कार्यान्वयन और समीक्षा चरणों के लिए सहयोग रणनीति बदलें।",
      "openEcosystemTitle": "ओपन इकोसिस्टम",
      "openEcosystemDesc": "Open-in एकीकरण, plugin-ready एक्सटेंशन बिंदु और बाहरी tool अंतरसंचालनीयता।"
    },
    "elements": {
      "titlebarTitle": "शीर्षक-पट्टी नियंत्रण",
      "titlebarDesc": "प्रोजेक्ट स्विच, ब्रांच क्रियाएँ, open-in विकल्प, लॉक ट्रिगर और thread कॉपी एक ही स्ट्रिप में।",
      "sidebarTitle": "Workspace साइडबार",
      "sidebarDesc": "workspace/worktree समूह, thread सूचियाँ, खोज फ़िल्टर और त्वरित प्रोजेक्ट संदर्भ स्विचिंग प्रबंधित करें।",
      "composerTitle": "Composer Workspace",
      "composerDesc": "एक ही एडिटर लूप में समृद्ध इनपुट, कोड fences, कमांड, डिक्टेशन और संदर्भ असेंबली।",
      "gitPanelTitle": "Git Hub",
      "gitPanelDesc": "tool बदलाव कम करने के लिए एक ही सतह पर Diff, log, commit, PR और issue संदर्भ।",
      "kanbanTitle": "Kanban प्रेषण",
      "kanbanDesc": "कार्यों को AI सत्रों में प्रेषित करें और स्थिति को निष्पादन प्रगति से जुड़ा रखें।",
      "searchTitle": "एकीकृत खोज",
      "searchDesc": "फ़ाइलों, threads, संदेशों, स्किल्स और कमांड में एक ही प्रवेश बिंदु।",
      "memoryTitle": "मेमोरी इंजन",
      "memoryDesc": "बार-बार संदर्भ सेटअप कम करने के लिए दीर्घकालिक प्रोजेक्ट ज्ञान बनाए रखें।",
      "debugTitle": "टर्मिनल + डिबग",
      "debugDesc": "अंतर्निहित टर्मिनल और डिबग ट्रेस समस्या निवारण को अवलोकनीय और ऑडिट-योग्य रखते हैं।"
    }
  }
};

export default lockScreen;
