// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "मॉडल चुनें",
    "addModel": "मॉडल जोड़ें",
    "refreshConfig": "कॉन्फ़िग रीफ़्रेश करें",
    "refreshingConfig": "रीफ़्रेश हो रहा है...",
    "refreshConfigFailed": "रीफ़्रेश विफल: {{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "नवीनतम फ्रंटियर एजेंटिक कोडिंग मॉडल।"
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "रोज़मर्रा के काम के लिए संतुलित एजेंटिक कोडिंग मॉडल।"
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "तेज़ और किफ़ायती एजेंटिक कोडिंग मॉडल।"
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "जटिल कोडिंग, अनुसंधान और वास्तविक कार्य के लिए फ्रंटियर मॉडल।"
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "रोज़मर्रा की कोडिंग के लिए सशक्त मॉडल।"
      },
      "gpt54mini": {
        "label": "gpt-5.4-mini",
        "description": "सरल कोडिंग कार्यों के लिए छोटा, तेज़ और लागत-कुशल मॉडल।"
      },
      "gpt53codex": {
        "label": "gpt-5.3-codex",
        "description": "कोडिंग-अनुकूलित मॉडल।"
      },
      "gpt53codexSpark": {
        "label": "gpt-5.3-codex-spark",
        "description": "अति-तेज़ कोडिंग मॉडल।"
      },
      "gpt52": {
        "label": "gpt-5.2",
        "description": "पेशेवर कार्य और लंबे समय तक चलने वाले Agent के लिए अनुकूलित।"
      }
    }
  }
};

export default models;
