// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {
  "modes": {
    "selectMode": "मोड चुनें",
    "default": {
      "label": "डिफ़ॉल्ट मोड",
      "tooltip": "मानक अनुमति व्यवहार",
      "description": "हर संचालन के लिए मैन्युअल पुष्टि आवश्यक है, सतर्क उपयोग के लिए उपयुक्त"
    },
    "plan": {
      "label": "योजना मोड",
      "tooltip": "योजना मोड - केवल-पढ़ने योग्य विश्लेषण",
      "description": "केवल केवल-पढ़ने योग्य टूल का उपयोग करता है, उपयोगकर्ता अनुमोदन के लिए योजना बनाता है"
    },
    "acceptEdits": {
      "label": "Agent मोड",
      "tooltip": "फ़ाइल संपादन स्वतः स्वीकार करें",
      "description": "फ़ाइल निर्माण/संपादन स्वतः स्वीकार करता है, पुष्टि चरणों को कम करता है"
    },
    "bypassPermissions": {
      "label": "स्वतः मोड",
      "tooltip": "सभी अनुमति जाँचों को बायपास करें",
      "description": "पूरी तरह स्वचालित, सभी अनुमति जाँचों को बायपास करता है [सावधानी से उपयोग करें]"
    }
  }
};

export default modes;
