// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {
  "panels": {
    "radar": "रडार",
    "git": "Git",
    "files": "फ़ाइलें",
    "search": "खोज",
    "notes": "नोट",
    "memory": "मेमोरी",
    "projectMap": "प्रोजेक्ट मैप",
    "intentCanvas": "इंटेंट Canvas",
    "activity": "गतिविधि",
    "prompts": "प्रॉम्प्ट"
  }
};

export default panels;
