// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {
  "plan": {
    "title": "योजना",
    "noPlan": "कोई योजना उपलब्ध नहीं",
    "steps": "चरण",
    "completed": "पूर्ण",
    "inProgress": "प्रगति में",
    "pending": "लंबित"
  }
};

export default plan;
