// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {
  "reasoning": {
    "title": "तर्क की गहराई चुनें",
    "default": "डिफ़ॉल्ट",
    "claudeDefault": "डिफ़ॉल्ट",
    "defaultDescription": "इंजन के डिफ़ॉल्ट तर्क व्यवहार का उपयोग करें",
    "low": {
      "label": "कम",
      "description": "बुनियादी तर्क के साथ त्वरित प्रतिक्रियाएँ"
    },
    "medium": {
      "label": "मध्यम",
      "description": "संतुलित सोच (डिफ़ॉल्ट)"
    },
    "high": {
      "label": "उच्च",
      "description": "जटिल कार्यों के लिए गहरा तर्क"
    },
    "xhigh": {
      "label": "अतिरिक्त उच्च",
      "description": "अतिरिक्त उच्च तर्क गहराई"
    },
    "max": {
      "label": "अधिकतम",
      "description": "अधिकतम तर्क गहराई"
    },
    "ultra": {
      "label": "अल्ट्रा",
      "description": "स्वचालित कार्य सौंपने के साथ अधिकतम तर्क"
    }
  }
};

export default reasoning;
