// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/rewind.ts; keys mirror the English source.
const rewind = {
  "rewind": {
    "title": "फ़ाइलों को पिछली स्थिति में वापस ले जाएँ",
    "tooltip": "वापस ले जाएँ",
    "label": "वापस ले जाएँ",
    "tooltipFull": "फ़ाइलों को इस संदेश की स्थिति में पुनर्स्थापित करें",
    "notAvailable": "इस सत्र में रिवाइंड उपलब्ध नहीं है",
    "noEligibleMessage": "कोई रिवाइंड योग्य उपयोगकर्ता संदेश नहीं मिला।",
    "selectPrompt": "एक रिवाइंड लक्ष्य चुनें (1-{{count}}):",
    "invalidSelection": "अमान्य रिवाइंड चयन।",
    "confirmPrompt": "इस संदेश से एक नया थ्रेड बनाएँ?\n\"{{preview}}\"",
    "dialogTitle": "{{engine}} रिवाइंड की पुष्टि करें",
    "dialogDescription": "अब रिवाइंड पर क्लिक करने से पहले केवल यह पुष्टिकरण डायलॉग खुलता है। रिवाइंड केवल तभी चलता है जब आप स्पष्ट रूप से पुष्टि करते हैं।",
    "targetSectionTitle": "रिवाइंड प्रारंभ बिंदु",
    "targetMessageLabel": "यह रिवाइंड इस उपयोगकर्ता संदेश से वापस रोल करेगा",
    "impactSectionTitle": "क्या हटाया जाएगा",
    "impactUserMessages": "हटाए गए उपयोगकर्ता संदेश",
    "impactAssistantMessages": "हटाए गए सहायक उत्तर",
    "impactToolCalls": "हटाए गए टूल कॉल",
    "impactFiles": "शामिल फ़ाइलें",
    "impactSummary": "पुष्टि के बाद, वर्तमान रैखिक इतिहास इस उपयोगकर्ता संदेश से वापस रोल होगा। इसमें यह उपयोगकर्ता संदेश और सभी बाद के सहायक उत्तर, टूल कॉल और संबंधित बदलाव शामिल हैं।",
    "impactFollowUp": "यदि नीचे फ़ाइलें सूचीबद्ध हैं, तो उनके बदलाव उस इतिहास खंड के अंदर हुए जिसे रिवाइंड किया जाएगा। पुष्टि करने से पहले उनकी समीक्षा करें।",
    "workspaceRestoreSectionTitle": "वर्कस्पेस फ़ाइल रणनीति",
    "modeMessagesAndFilesLabel": "संदेश + फ़ाइलें रिवाइंड करें",
    "modeMessagesAndFilesHint": "संवाद इतिहास को रिवाइंड करें और संबंधित वर्कस्पेस फ़ाइल बदलावों को एक साथ पुनर्स्थापित करें।",
    "modeMessagesOnlyLabel": "केवल संदेश",
    "modeMessagesOnlyHint": "केवल संवाद इतिहास को रिवाइंड करें और वर्तमान वर्कस्पेस फ़ाइलों को अछूता छोड़ दें।",
    "modeFilesOnlyLabel": "केवल फ़ाइलें",
    "modeFilesOnlyHint": "केवल संबंधित फ़ाइलों को पुनर्स्थापित करें और वर्तमान संवाद इतिहास को अपरिवर्तित रखें।",
    "filesSectionTitle": "प्रभावित फ़ाइलें",
    "filesRailTitle": "फ़ाइलें",
    "filesEmpty": "रिवाइंड किए जा रहे इतिहास खंड में कोई फ़ाइल बदलाव नहीं पाया गया।",
    "filesHint": "यह पता लगाए गए फ़ाइल बदलावों का एक सर्वोत्तम-प्रयास फ्रंटएंड सारांश है ताकि आप आगे बढ़ने से पहले प्रभाव क्षेत्र की पुष्टि कर सकें।",
    "diffEmpty": "इस फ़ाइल के लिए कोई डिफ़ पूर्वावलोकन उपलब्ध नहीं है। आप फिर भी अन्य फ़ाइलों की समीक्षा कर सकते हैं या मुख्य डिफ़ पैनल खोल सकते हैं।",
    "openDiffAction": "डिफ़ पैनल में खोलें",
    "storeAction": "बदलाव संग्रहीत करें",
    "storeActionBusy": "संग्रहीत किया जा रहा है...",
    "storeUnavailable": "वर्तमान रिवाइंड संदर्भ में बदलावों को संग्रहीत करने के लिए पर्याप्त सत्र जानकारी शामिल नहीं है।",
    "storeFailed": "बदलाव संग्रहीत करने में विफल।",
    "storeRevealFailed": "संग्रहीत बदलाव डायरेक्टरी खोलने में विफल।",
    "storeRevealAction": "फ़ोल्डर खोलें",
    "storeSuccessTitle": "{{count}} फ़ाइल संग्रहीत की और एक पुन: उपयोग योग्य मेनिफ़ेस्ट स्नैपशॉट बनाया।",
    "storeSuccessPrefix": "यहाँ सहेजा गया: ",
    "confirmAction": "रिवाइंड की पुष्टि करें",
    "confirmActionBusy": "रिवाइंड किया जा रहा है...",
    "failed": "संवाद रिवाइंड करने में विफल।"
  }
};

export default rewind;
