// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "फ़ाइलें, kanban, थ्रेड, संदेश, स्किल, कमांड खोजें...",
    "placeholderFiltered": "{{content}} खोजें...",
    "inputAria": "खोज इनपुट",
    "scope": "दायरा",
    "content": "सामग्री",
    "current": "वर्तमान",
    "global": "ग्लोबल",
    "currentWorkspace": "वर्तमान वर्कस्पेस",
    "allWorkspaces": "सभी वर्कस्पेस",
    "noResults": "कोई परिणाम नहीं",
    "noResultsHint": "फ़ाइल पथ, टास्क शीर्षक, थ्रेड शीर्षक, संदेश टेक्स्ट, स्किल नाम, या कमांड नाम से कीवर्ड आज़माएँ।",
    "fileIndexLoading": "फ़ाइल इंडेक्स पूरा किया जा रहा है...",
    "fileIndexPartial": "फ़ाइल इंडेक्स अधूरा है, इसलिए कुछ फ़ाइलें छूट सकती हैं।",
    "fileIndexError": "फ़ाइल इंडेक्स लोड नहीं हुआ। फिर प्रयास करने के लिए खोज दोबारा खोलें।",
    "navigate": "नेविगेट करें",
    "open": "खोलें",
    "close": "बंद करें",
    "projectTag": "प्रोजेक्ट",
    "typeTag": "प्रकार",
    "sourceTag": "स्रोत",
    "locationTag": "स्थान",
    "typeAction": "क्रिया",
    "typeFile": "फ़ाइल",
    "typeKanban": "Kanban",
    "typeThread": "थ्रेड",
    "typeMessage": "संदेश",
    "typeHistory": "इतिहास",
    "typeSkill": "स्किल",
    "typeCommand": "कमांड",
    "sourceActions": "ऐप क्रियाएँ",
    "sourceFiles": "फ़ाइल इंडेक्स",
    "sourceKanban": "Kanban डेटा",
    "sourceThreads": "थ्रेड शीर्षक",
    "sourceMessages": "संदेश सामग्री",
    "sourceHistory": "इनपुट इतिहास",
    "sourceSkills": "स्किल सूची",
    "sourceCommands": "कमांड सूची",
    "contentAll": "सभी",
    "contentActions": "क्रियाएँ",
    "contentFiles": "फ़ाइलें",
    "contentKanban": "Kanban",
    "contentThreads": "थ्रेड",
    "contentMessages": "संदेश",
    "contentHistory": "इतिहास",
    "contentSkills": "स्किल",
    "contentCommands": "कमांड"
  }
};

export default searchPalette;
