// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
const statusPanel = {
  "statusPanel": {
    "tabTodos": "कार्य",
    "tabSubagents": "सबएजेंट",
    "tabAgents": "Agents",
    "tabCheckpoint": "परिणाम",
    "tabPlan": "योजना",
    "tabCommands": "कमांड",
    "files": "फ़ाइलें",
    "emptyTodos": "कोई कार्य नहीं",
    "emptySubagents": "कोई सबएजेंट नहीं",
    "emptyFileChanges": "कोई फ़ाइल बदलाव नहीं",
    "emptyCommands": "कोई कमांड नहीं",
    "emptyPlan": "कोई योजना नहीं",
    "planGenerating": "योजना उत्पन्न की जा रही है...",
    "planSwitchHint": "योजना देखने के लिए योजना मोड पर स्विच करें",
    "expand": "स्थिति पैनल विस्तृत करें",
    "collapse": "स्थिति पैनल संक्षिप्त करें",
    "label": "स्थिति",
    "policy": {
      "title": "नीति ऑडिट",
      "count": "{{count}} निर्णय",
      "noReason": "{{policy}} ने कोई कारण नहीं दिया",
      "verdict": {
        "running": "चल रहा है",
        "blocked": "अवरुद्ध",
        "needs_review": "समीक्षा",
        "ready": "तैयार",
        "no_contribution": "छोड़ा गया"
      },
      "corePolicy": {
        "blocked": "कोर नियमों ने एक अवरोधक जोखिम का पता लगाया।",
        "running": "कोर नियमों ने चल रहा काम पाया।",
        "ready": "कोर नियमों ने वर्तमान साक्ष्य तैयार पाया।",
        "needsReview": "कोर नियमों को समीक्षा की आवश्यकता है।"
      },
      "lintValidationPolicy": {
        "pass": "Lint पास हुआ।",
        "fail": "Lint विफल हुआ और समीक्षा की आवश्यकता है।",
        "running": "Lint चल रहा है।",
        "notRun": "Lint नहीं चला।"
      },
      "typecheckValidationPolicy": {
        "pass": "Typecheck पास हुआ।",
        "fail": "Typecheck विफल हुआ और समीक्षा की आवश्यकता है।",
        "running": "Typecheck चल रहा है।",
        "notRun": "Typecheck नहीं चला।"
      },
      "testsValidationPolicy": {
        "pass": "Tests पास हुए।",
        "fail": "Tests विफल हुए और समीक्षा की आवश्यकता है।",
        "running": "Tests चल रहे हैं।",
        "notRun": "Tests नहीं चले।"
      },
      "openspecGovernancePolicy": {
        "pass": "OpenSpec गवर्नेंस साक्ष्य वर्तमान है।",
        "warn": "OpenSpec गवर्नेंस साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "OpenSpec गवर्नेंस साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "OpenSpec गवर्नेंस साक्ष्य अनुपलब्ध या अधूरा है।"
      },
      "largeFileGovernancePolicy": {
        "pass": "बड़ी-फ़ाइल गवर्नेंस साक्ष्य वर्तमान है।",
        "warn": "बड़ी-फ़ाइल गवर्नेंस साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "बड़ी-फ़ाइल गवर्नेंस साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "बड़ी-फ़ाइल गवर्नेंस साक्ष्य अनुपलब्ध या अधूरा है।"
      },
      "heavyTestNoiseGovernancePolicy": {
        "pass": "हैवी-टेस्ट-नॉइज़ साक्ष्य वर्तमान है।",
        "warn": "हैवी-टेस्ट-नॉइज़ साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "हैवी-टेस्ट-नॉइज़ साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "हैवी-टेस्ट-नॉइज़ साक्ष्य अनुपलब्ध या अधूरा है।"
      },
      "realtimeHarnessGovernancePolicy": {
        "pass": "रियलटाइम हार्नेस साक्ष्य वर्तमान है।",
        "warn": "रियलटाइम हार्नेस साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "रियलटाइम हार्नेस साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "रियलटाइम हार्नेस साक्ष्य अनुपलब्ध या अधूरा है।"
      },
      "capabilityMismatchGovernancePolicy": {
        "pass": "इंजन क्षमता साक्ष्य वर्तमान है।",
        "warn": "इंजन क्षमता साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "इंजन क्षमता साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "इंजन क्षमता साक्ष्य अनुपलब्ध या अधूरा है।"
      },
      "engineRuntimeGovernancePolicy": {
        "pass": "इंजन रनटाइम अनुबंध साक्ष्य वर्तमान है।",
        "warn": "इंजन रनटाइम अनुबंध साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "इंजन रनटाइम अनुबंध साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "इंजन रनटाइम अनुबंध साक्ष्य अनुपलब्ध या अधूरा है।"
      },
      "costBudgetGovernancePolicy": {
        "pass": "लागत बजट साक्ष्य वर्तमान है।",
        "warn": "लागत बजट साक्ष्य में सलाहकारी चेतावनियाँ हैं।",
        "fail": "लागत बजट साक्ष्य को समीक्षा की आवश्यकता है।",
        "unknown": "लागत बजट साक्ष्य अनुपलब्ध या अधूरा है।"
      }
    },
    "audit": {
      "title": "निर्णय तर्क",
      "expandLabel": "{{count}} नीति निर्णय",
      "empty": "कोई नीति निर्णय नहीं",
      "reasonUnavailable": "{{policy}} ने कोई कारण नहीं दिया",
      "sourceUnavailable": "कोई स्रोत नहीं",
      "enforcement": {
        "advisory": "सलाहकारी",
        "blocking": "अवरोधक",
        "informational": "जानकारी"
      }
    },
    "governance": {
      "title": "गवर्नेंस साक्ष्य",
      "loading": "साक्ष्य पढ़ा जा रहा है...",
      "empty": "कोई गवर्नेंस साक्ष्य नहीं",
      "count": "{{count}} साक्ष्य आइटम · {{needsAction}} को कार्रवाई चाहिए",
      "group": {
        "needs_action": "कार्रवाई चाहिए · {{count}}",
        "watch": "निगरानी · {{count}}",
        "passed": "पास हुआ · {{count}}"
      },
      "meta": {
        "source": "स्रोत: {{source}}",
        "artifact": "आर्टिफ़ैक्ट: {{path}}",
        "action": "कार्रवाई: {{reason}} हल करें"
      },
      "status": {
        "pass": "पास",
        "warn": "चेतावनी",
        "fail": "विफल",
        "unknown": "अज्ञात"
      }
    },
    "cost": {
      "title": "लागत / बजट",
      "session": "सत्र",
      "engine": "इंजन",
      "model": "मॉडल",
      "sessionId": "सत्र ID",
      "tokens": "Tokens",
      "tokenBreakdownLabel": "Token उपयोग विवरण",
      "known": "मूल्य मिलान हुआ",
      "partial": "आंशिक अनुमान",
      "unknownModel": "अज्ञात मॉडल",
      "pricingSource": "मूल्य स्रोत: {{source}} · {{date}}",
      "historyDegraded": "localStorage लेखन विफल होने के कारण लागत इतिहास मेमोरी में जारी है।",
      "accumulated": {
        "session": "सत्र {{amount}}",
        "today": "आज {{amount}}",
        "month": "माह {{amount}}"
      },
      "degraded": {
        "pricing-unavailable": "{{engine}}/{{model}} के लिए कोई पता योग्य मूल्य उपलब्ध नहीं; लागत को चुपचाप शून्य नहीं माना जाता।",
        "pricing-stale": "मूल्य फ़िक्सचर पुराना है; यह लागत केवल सूचनात्मक है।",
        "usage-unavailable": "लागत प्रक्षेपण के लिए कोई token उपयोग उपलब्ध नहीं।",
        "block-level-cost-unsupported": "इस संस्करण में ब्लॉक-स्तरीय लागत समर्थित नहीं है।",
        "unknown": "लागत प्रक्षेपण अवनत है।"
      }
    },
    "budget": {
      "unconfigured": "बजट कॉन्फ़िगर नहीं है। यह मार्गदर्शन है, विफल बजट जाँच नहीं।",
      "unsetShort": "बजट अनसेट",
      "barLabel": "बजट उपयोग प्रगति",
      "progress": "{{amount}} / {{limit}}",
      "threshold": {
        "info": "सूचना सीमा पहुँची: {{amount}} / {{threshold}}",
        "warn": "चेतावनी सीमा पहुँची: {{amount}} / {{threshold}}",
        "block": "अवरोधक सीमा पहुँची: {{amount}} / {{threshold}}। यह क्षमता केवल संकेत देती है; यह रनटाइम को बाधित नहीं करती।"
      }
    },
    "checkpoint": {
      "verdictTitle": "फ़ैसला",
      "evidenceTitle": "साक्ष्य",
      "keyChangesTitle": "मुख्य बदलाव",
      "keyChangesEmpty": "अभी तक कोई मुख्य बदलाव कैप्चर नहीं हुआ",
      "fileDetailsTitle": "फ़ाइल विवरण",
      "risksTitle": "जोखिम",
      "nextActionTitle": "अगली क्रिया",
      "sections": {
        "summary": "सारांश",
        "advisorySignals": "सलाहकारी संकेत",
        "evidenceTrail": "साक्ष्य ट्रेल",
        "policyAudit": "नीति ऑडिट",
        "suggestedActions": "सुझाई गई क्रियाएँ"
      },
      "advisory": {
        "count": "{{count}} सलाहकारी संकेत"
      },
      "verdict": {
        "running": "चल रहा है",
        "blocked": "अवरुद्ध",
        "needs_review": "समीक्षा आवश्यक",
        "ready": "तैयार"
      },
      "headline": {
        "running": "काम प्रगति में",
        "blocked": "ध्यान आवश्यक",
        "needs_review": "जारी रखने से पहले समीक्षा करें",
        "ready": "जारी रखने के लिए तैयार",
        "idle": "साक्ष्य की प्रतीक्षा है"
      },
      "summary": {
        "blockedValidation": "एक आवश्यक सत्यापन विफल हुआ और पहले ठीक करना आवश्यक है।",
        "blockedCommand": "नवीनतम कमांड विफल हुआ: {{command}}। यदि सिस्टम अभी भी स्वतः पुनर्प्राप्ति का प्रयास कर रहा है, तो इसे रोकने से पहले इस रन के स्थिर होने की प्रतीक्षा करें।",
        "blockedSubagent": "एक प्रत्यायोजित कार्य त्रुटि स्थिति में रुक गया।",
        "runningValidation": "सत्यापन अभी भी चल रहा है। निर्णय लेने से पहले परिणाम की प्रतीक्षा करें।",
        "runningCommand": "नवीनतम कमांड अभी भी चल रहा है: {{command}}",
        "runningAgent": "कम से कम एक agent अभी भी प्रोसेस कर रहा है।",
        "runningTodo": "अभी भी कुछ सक्रिय कार्य प्रगति में हैं।",
        "runningProcessing": "वर्तमान टर्न अभी भी निष्पादन साक्ष्य उत्पन्न कर रहा है।",
        "readyWithFiles": "{{count}} बदली गई फ़ाइल(ों) ने देखी गई कोर जाँचें पास कीं।",
        "ready": "देखा गया निष्पादन साक्ष्य स्थिर लगता है।",
        "needsValidation": "फ़ाइलें बदलीं, पर कोर सत्यापन अभी तक नहीं चले हैं।",
        "manual": "परिणाम उपलब्ध है, पर इसे अभी भी मानव समीक्षा पास की आवश्यकता है।",
        "idle": "अभी तक कोई विश्वसनीय निष्पादन साक्ष्य नहीं देखा गया।"
      },
      "evidence": {
        "filesChanged": "बदली गई फ़ाइलें",
        "filesChangedValue": "{{count}} फ़ाइलें",
        "validations": "सत्यापन",
        "requiredValidations": "आवश्यक",
        "optionalValidations": "वैकल्पिक",
        "fileChangeSummary": "{{count}} फ़ाइलों में +{{additions}}/-{{deletions}}",
        "runMissing": "पहले चलाएँ",
        "runMissingGeneric": "प्रोजेक्ट की कोर सत्यापन स्क्रिप्ट चलाएँ",
        "tasks": "कार्य",
        "agents": "Agents",
        "inProgress": "प्रगति में",
        "settled": "स्थिर"
      },
      "evidenceTrail": {
        "count": "{{count}} साक्ष्य आइटम",
        "sourceLabel": "स्रोत",
        "snapshotLabel": "स्नैपशॉट",
        "observedLabel": "देखा गया",
        "artifactLabel": "आर्टिफ़ैक्ट",
        "hashLabel": "हैश",
        "qualifierLabel": "क्वालिफ़ायर",
        "degradedLabel": "अवनत",
        "staleLabel": "पुराना",
        "snapshotRecorded": "स्नैपशॉट रिकॉर्ड हुआ",
        "hashRecorded": "सत्यापित",
        "policy": {
          "buildValidationPolicy": "बिल्ड सत्यापन",
          "costBudgetGovernancePolicy": "लागत बजट",
          "heavyTestNoiseGovernancePolicy": "हैवी टेस्ट नॉइज़",
          "largeFileGovernancePolicy": "बड़ी-फ़ाइल गवर्नेंस",
          "lintValidationPolicy": "Lint सत्यापन",
          "openspecGovernancePolicy": "OpenSpec गवर्नेंस",
          "testsValidationPolicy": "Tests सत्यापन",
          "typecheckValidationPolicy": "Typecheck सत्यापन"
        },
        "sourceName": {
          "build": "बिल्ड",
          "costBudget": "लागत बजट",
          "heavyTestNoise": "हैवी टेस्ट नॉइज़",
          "largeFile": "बड़ी फ़ाइल",
          "lint": "Lint",
          "openspec": "OpenSpec",
          "tests": "Tests",
          "trellis": "Trellis",
          "typecheck": "Typecheck"
        },
        "reason": {
          "governanceArtifactMalformed": "साक्ष्य फ़ाइल का प्रारूप अमान्य है",
          "governanceEvidenceUnavailable": "साक्ष्य अभी तक पार्स नहीं हो सकता",
          "pricingUnavailable": "मॉडल मूल्य अज्ञात है",
          "stale": "साक्ष्य पुराना है"
        },
        "source": "स्रोत: {{source}}",
        "snapshot": "स्नैपशॉट: {{id}}",
        "observed": "देखा गया: {{time}}",
        "artifact": "आर्टिफ़ैक्ट: {{path}}",
        "hash": "हैश: {{hash}}",
        "qualifier": "क्वालिफ़ायर: {{qualifier}}",
        "degraded": "अवनत: {{reason}}",
        "stale": "पुराना: {{time}}"
      },
      "suggested": {
        "validation": "वैकल्पिक: {{command}}",
        "governance": "वैकल्पिक {{source}} जाँच: {{command}}"
      },
      "expandToDock": "डॉक में पूर्ण परिणाम देखें",
      "validations": {
        "lint": "Lint",
        "typecheck": "Typecheck",
        "tests": "Tests",
        "build": "बिल्ड",
        "custom": "कमांड",
        "status": {
          "pass": "पास",
          "fail": "विफल",
          "running": "चल रहा है",
          "not_run": "नहीं चला",
          "not_observed": "नहीं देखा गया"
        }
      },
      "keyChanges": {
        "files": "छुई गई फ़ाइलें",
        "filesSummary": "{{count}} फ़ाइलें बदलीं · +{{additions}} / -{{deletions}}",
        "tasks": "कार्य प्रगति",
        "tasksSummary": "{{completed}}/{{total}} कार्य पूर्ण हुए",
        "agents": "Agent प्रगति",
        "agentsSummary": "{{completed}}/{{total}} agents पूर्ण हुए"
      },
      "risks": {
        "none": "कोई अवरोधक जोखिम नहीं मिला।",
        "commandFailed": "एक कमांड त्रुटि में समाप्त हुआ: {{command}}",
        "validationFailed": "कम से कम एक सत्यापन विफलता में समाप्त हुआ।",
        "validationMissing": "फ़ाइल बदलावों के बाद कोर सत्यापन नहीं चले हैं।",
        "subagentError": "एक agent ने त्रुटि की सूचना दी: {{agent}}",
        "manualReview": "सिस्टम ने अभी तक परिणाम घोषित करने के लिए पर्याप्त साक्ष्य नहीं देखा है।",
        "severity": {
          "high": "उच्च",
          "medium": "मध्यम",
          "low": "निम्न"
        }
      },
      "actions": {
        "reviewDiff": "डिफ़ समीक्षा करें",
        "openRisk": "जोखिम जाँचें",
        "retry": "विफल चरण पुनः प्रयास करें",
        "commit": "तैयार होने पर कमिट करें",
        "hint": {
          "runMissingValidation": "जारी रखने का निर्णय लेने से पहले लापता सत्यापन चलाएँ।",
          "running": "वर्तमान निष्पादन साक्ष्य के स्थिर होने की प्रतीक्षा करें।",
          "blocked": "पहले विफल साक्ष्य जाँचें; यदि पुनर्प्राप्ति अभी भी प्रगति में है, तो इसे रोकने का निर्णय लेने से पहले रन के स्थिर होने की प्रतीक्षा करें।",
          "needs_review": "यह परिणाम अभी भी उबर सकता है। कोई कार्रवाई करने से पहले निष्पादन के स्थिर होते रहने की प्रतीक्षा करें।",
          "ready": "साक्ष्य स्थिर है; अंतिम प्री-कमिट जाँच करें।"
        }
      },
      "commitDialog": {
        "title": "कमिट पुष्टि",
        "path": "पथ:",
        "files": "कमिट करने योग्य फ़ाइलें",
        "toggleAllFiles": "सभी कमिट फ़ाइलें टॉगल करें",
        "staged": "स्टेज्ड"
      }
    }
  }
};

export default statusPanel;
