// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
const tabbar = {
  "tabbar": {
    "projects": "प्रोजेक्ट",
    "codex": "Codex",
    "spec": "Spec",
    "git": "Git",
    "log": "लॉग",
    "primaryNavigation": "प्राथमिक नेविगेशन",
    "workspaceNavigation": "कार्यक्षेत्र नेविगेशन"
  }
};

export default tabbar;
