// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
const taskCenter = {
  "taskCenter": {
    "title": "कार्य केंद्र",
    "eyebrow": "Agent रन",
    "workspaceHero": "अभी ध्यान चाहने वाला रन",
    "statusFilter": "स्थिति",
    "engineFilter": "इंजन",
    "filterAll": "सभी",
    "empty": "अभी तक कोई कार्य रन नहीं",
    "summary": "{{total}} में से {{attention}} रन को ध्यान चाहिए",
    "openedFromProjectMap": "प्रोजेक्ट मैप कार्य कतार से लिंक किया गया रन खोला गया। यह पेज वास्तविक TaskRun विवरण दिखाता है; यदि कोई वार्तालाप क्रिया प्रकट नहीं होती, तो यह रन अभी तक किसी वास्तविक सत्र से लिंक नहीं है।",
    "trigger": "ट्रिगर",
    "updatedAt": "अपडेट किया गया",
    "currentStep": "वर्तमान चरण",
    "latestOutput": "नवीनतम आउटपुट",
    "diagnostics": "डायग्नोस्टिक्स",
    "artifacts": "आर्टिफैक्ट्स",
    "browserEvidence": "ब्राउज़र साक्ष्य",
    "unavailable": "अनुपलब्ध",
    "noArtifacts": "अभी तक कोई आर्टिफैक्ट नहीं",
    "noBrowserEvidence": "कोई ब्राउज़र साक्ष्य लिंक नहीं किया गया",
    "browserEvidenceCandidates": "उम्मीदवार",
    "source": {
      "kanban": "kanban",
      "orchestration": "ऑर्केस्ट्रेशन"
    },
    "browserEvidenceState": {
      "available": "उपलब्ध",
      "stale": "पुराना",
      "expired": "समाप्त",
      "degraded": "क्षीण",
      "deleted": "हटाया गया",
      "unsupported": "असमर्थित"
    },
    "status": {
      "queued": "कतार में",
      "planning": "योजना बना रहे हैं",
      "running": "चल रहा है",
      "waiting_input": "इनपुट की प्रतीक्षा में",
      "blocked": "अवरुद्ध",
      "failed": "विफल",
      "completed": "पूर्ण",
      "canceled": "रद्द किया गया"
    },
    "action": {
      "openConversation": "बातचीत खोलें",
      "openOrchestrationTask": "ऑर्केस्ट्रेशन कार्य खोलें",
      "retry": "पुनः प्रयास करें",
      "resume": "फिर से शुरू करें",
      "cancel": "रद्द करें",
      "fork": "रन फ़ोर्क करें"
    },
    "nextStep": {
      "monitor": "यह रन अभी भी आगे बढ़ रहा है। वर्तमान चरण की निगरानी करें या ज़रूरत होने पर रद्द करें।",
      "openConversation": "इनपुट देने या नवीनतम आउटपुट देखने के लिए आगे लिंक की गई बातचीत खोलें।",
      "resume": "यह रन अवरुद्ध है। वर्तमान पथ जारी रखने के लिए इसे पहले फिर से शुरू करें।",
      "retry": "यह रन विफल हो गया। आगे इसे पुनः प्रयास करें या विफलता सारांश देखें।",
      "wait": "अभी कोई कार्रवाई आवश्यक नहीं है। रन को पहले स्थिर होने दें।",
      "review": "पहले डायग्नोस्टिक्स और आर्टिफैक्ट्स की समीक्षा करें, फिर अगला कदम तय करें।",
      "fork": "जारी रखने के लिए आप वर्तमान परिणाम से एक नया रन फ़ोर्क कर सकते हैं।"
    }
  }
};

export default taskCenter;
