// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {
  "terminal": {
    "newTab": "नया टैब",
    "closeTab": "टैब बंद करें",
    "clear": "साफ़ करें",
    "title": "टर्मिनल",
    "tabTitle": "टर्मिनल {{number}}",
    "claudeTuiResumeTitle": "Claude TUI",
    "sendSelectionToComposer": "कंपोज़र को भेजें"
  }
};

export default terminal;
