// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
const threadCompletion = {
  "threadCompletion": {
    "title": "सत्र पूर्ण हुआ",
    "project": "प्रोजेक्ट",
    "session": "सत्र"
  }
};

export default threadCompletion;
