// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {"time":{"justNow":"अभी-अभी","minuteAgo":"{{count}} मिनट पहले","minutesAgo":"{{count}} मिनट पहले","hourAgo":"{{count}} घंटा पहले","hoursAgo":"{{count}} घंटे पहले","dayAgo":"{{count}} दिन पहले","daysAgo":"{{count}} दिन पहले","weekAgo":"{{count}} सप्ताह पहले","weeksAgo":"{{count}} सप्ताह पहले","now":"अभी","shortSecondsAgo":"{{value}}s पहले","shortSecondsIn":"{{value}}s में","shortMinutesAgo":"{{value}}m पहले","shortMinutesIn":"{{value}}m में","shortMinutes":"{{value}}m","shortHours":"{{value}}h","shortDays":"{{value}}d","shortWeeks":"{{value}}w","shortMonths":"{{value}}mo","shortYears":"{{value}}y"}};

export default time;
