// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "अपडेट",
    "checkingForUpdates": "अपडेट की जांच कर रहे हैं...",
    "updateAvailable": "एक नया संस्करण उपलब्ध है!",
    "upToDate": "आप अद्यतित हैं।",
    "downloading": "अपडेट डाउनलोड हो रहा है…",
    "installing": "अपडेट इंस्टॉल हो रहा है…",
    "restarting": "पुनः आरंभ हो रहा है…",
    "failed": "अपडेट विफल हुआ।",
    "downloaded": "डाउनलोड किया गया",
    "releaseNotesTitle": "रिलीज़ नोट्स",
    "releaseNotesLoading": "रिलीज़ नोट्स लोड हो रहे हैं…",
    "releaseNotesLoadFailed": "रिलीज़ नोट्स लोड करने में विफल।",
    "releaseNotesEmpty": "अभी तक कोई रिलीज़ नोट्स नहीं।",
    "releaseNotesOpenInGitHub": "GitHub पर देखें",
    "releaseNotesPrev": "पिछला",
    "releaseNotesNext": "अगला",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "English:",
    "releaseNotesChinese": "中文："
  }
};

export default update;
