// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
const usage = {"usage":{"sessionReset":"सत्र रीसेट","weeklyReset":"साप्ताहिक रीसेट","credits":"क्रेडिट","used":"उपयोग किया गया","remaining":"शेष","unlimited":"असीमित"}};

export default usage;
