// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {
  "about": {
    "version": "Версия",
    "tagline": "Редактор VibeCoding нового поколения",
    "checkForUpdates": "Проверить обновления",
    "releaseNotes": "Примечания к выпуску",
    "reportIssue": "Сообщить о проблеме",
    "website": "Веб-сайт",
    "github": "GitHub",
    "wechatGroupTitle": "Сканируйте, чтобы вступить в группу WeChat"
  }
};

export default about;
