// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {"askUserQuestion":{"title":"У Claude есть вопрос к вам","progress":"Вопрос {{current}} / {{total}}","timeoutWarning":"Пожалуйста, ответьте в ближайшее время. Этот диалог автоматически закроется через {{seconds}} секунд","collapse":"Свернуть","expand":"Развернуть","clickToAnswer":"Нажмите, чтобы ответить","questionTab":"Вопрос {{index}}","cancel":"Отмена","back":"Назад","next":"Далее","submit":"Отправить","otherOption":"Другое","otherOptionDesc":"Введите свой ответ","customInputPlaceholder":"Введите ваш ответ...","multiSelectHint":"Вы можете выбрать несколько вариантов"}};

export default askUserQuestion;
