// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
const browserAgent = {
  "browserAgent": {
    "dock": {
      "description": "Сначала прочитайте ключевые факты страницы, затем постепенно включайте навигацию и действия с элементами.",
      "disabled": "Отключено",
      "statusDisconnected": "Отключено",
      "statusLoading": "Загрузка",
      "statusReady": "Читаемо",
      "statusClosed": "Закрыто",
      "statusNeedsAttention": "Требует внимания",
      "statusPreparing": "Подготовка",
      "emptyUrl": "Введите URL страницы, чтобы открыть.",
      "blockedUrl": "Этот URL заблокирован политикой Browser Agent.",
      "opened": "Browser Agent открыл вкладку браузера.",
      "closed": "Вкладка Browser Agent закрыта.",
      "busy": "Работает",
      "open": "Открыть",
      "enable": "Включить",
      "enabled": "Browser Agent включён.",
      "tabs": "Вкладки браузера",
      "newTab": "Новая вкладка браузера",
      "openDock": "Браузер",
      "panelTitle": "Панель браузера",
      "panelKicker": "Откройте страницу здесь, затем при необходимости прикрепите её контекст к AI.",
      "noWorkspace": "Выберите рабочее пространство перед открытием панели браузера.",
      "noPage": "Откройте разрешённую страницу http/https, чтобы запустить окно Browser Agent.",
      "rendering": "Отрисовка страницы в окне Browser Agent...",
      "windowOpened": "Страница открыта в отдельном окне Browser Agent.",
      "closePanel": "Закрыть панель браузера",
      "close": "Закрыть сессию Browser Agent",
      "info": "Показать детали Browser Agent",
      "footnote": "MVP не хранит необработанный DOM, cookie, заголовки или секреты страниц."
    },
    "composer": {
      "attach": "Прикрепить контекст браузера",
      "attaching": "Прикрепление контекста браузера...",
      "attached": "Контекст браузера прикреплён",
      "visibleSnapshot": "Снимок видимой страницы браузера",
      "selectedElement": "Выбранный элемент страницы",
      "selectedElementCount": "{{count}} выбранных элементов страницы",
      "selectedElementFacts": "Факты о выбранном элементе страницы",
      "selectedElementMore": "ещё {{count}} элементов",
      "selectorHint": "Селектор {{selector}}",
      "noRawApi": "Не необработанные данные API",
      "remove": "Удалить",
      "refresh": "Обновить контекст браузера",
      "fresh": "готово",
      "stale": "обновить",
      "expired": "истекло",
      "degraded": "деградация",
      "unsupported": "не поддерживается",
      "showDetails": "Показать детали захвата",
      "hideDetails": "Скрыть детали",
      "countSummary": "Количество элементов страницы",
      "headingCount": "Заголовки {{count}}",
      "linkCount": "Ссылки {{count}}",
      "buttonCount": "Кнопки {{count}}",
      "formCount": "Формы {{count}}",
      "readableBlockCount": "Читаемые блоки {{count}}",
      "visualEvidenceCount": "Визуальные признаки {{count}}",
      "counts": "Заголовки {{headings}} · ссылки {{links}} · кнопки {{buttons}} · формы {{forms}} · читаемые блоки {{readableBlocks}} · визуальные признаки {{visualEvidence}} · кандидаты кода {{candidates}}",
      "primaryContent": "Основное содержимое",
      "readableBlocks": "Читаемые блоки {{count}}",
      "visualEvidence": "Визуальные признаки {{count}}",
      "codeCandidates": "Кандидаты кода {{count}}",
      "privacy": "{{redacted}} тип(ов) редактирования, {{omitted}} пропущенных типов чувствительных источников.",
      "noSession": "Нет активной сессии Browser Agent. Сначала откройте страницу в панели браузера."
    }
  }
};

export default browserAgent;
