// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
const claudeModes = {
  "claudeModes": {
    "default": {
      "label": "Режим подсказок (предпросмотр)",
      "tooltip": "Режим одобрения предпросмотра Claude Code. Некоторые процессы могут по-прежнему работать со сбоями, пока завершается полный мост одобрения.",
      "description": "Теперь доступен как предпросмотр для проверки стандартного процесса разрешений Claude. При попадании на деградированный путь интерфейс должен направить пользователей обратно в режим планирования."
    },
    "plan": {
      "label": "Режим планирования",
      "tooltip": "Режим анализа Claude Code только для чтения.",
      "description": "Использует инструменты только для чтения для анализа и планирования перед выполнением действий."
    },
    "acceptEdits": {
      "label": "Автоправка",
      "tooltip": "Режим автоправок Claude Code. Недоступен на текущем этапе развёртывания.",
      "description": "Этот режим остаётся недоступным, пока не проверена семантика подтверждений Claude."
    },
    "bypassPermissions": {
      "label": "Полный автомат",
      "tooltip": "Режим Claude Code, пропускающий проверки разрешений.",
      "description": "Автономное выполнение записи файлов и команд без подтверждений. Используйте осторожно."
    }
  }
};

export default claudeModes;
