// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/clientDocumentation.ts; keys mirror the English source.
const clientDocumentation = {"clientDocumentation":{"open":"Документация клиента"}};

export default clientDocumentation;
