// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
const codexModes = {
  "codexModes": {
    "default": {
      "label": "Предлагать (подтверждение)",
      "tooltip": "Codex approval_policy=untrusted — запрашивает подтверждение перед изменением файлов или запуском команд оболочки.",
      "description": "Самый безопасный вариант. Каждая запись или команда требует вашего подтверждения."
    },
    "plan": {
      "label": "Режим планирования",
      "tooltip": "Режим планирования — анализ только для чтения",
      "description": "Использует только инструменты для чтения, формирует план для подтверждения пользователем"
    },
    "acceptEdits": {
      "label": "Автоправки",
      "tooltip": "Codex approval_policy=auto-edit — автоматически применяет патчи файлов, но запрашивает подтверждение перед командами оболочки.",
      "description": "Автоматическое создание и изменение файлов через apply_patch с сохранением подтверждения команд."
    },
    "bypassPermissions": {
      "label": "Полный автомат",
      "tooltip": "Codex approval_policy=never — выполняет команды и пишет файлы без запросов (изоляция рабочей области всё равно действует).",
      "description": "Автономный режим. Codex немедленно выполняет правки и команды оболочки."
    }
  }
};

export default codexModes;
