// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {"debug":{"title":"Отладка","copyLogs":"Скопировать логи","clearLogs":"Очистить логи","noLogs":"Нет логов отладки","copy":"Копировать","clear":"Очистить","noDebugEventsYet":"Пока нет событий отладки."}};

export default debug;
