// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/engineTaskOutput.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/engineTaskOutput.ts; keys mirror the English source.
const engineTaskOutput = {
  "engineTaskOutput": {
    "label": "Инспектор вывода задачи",
    "inspect": "Показать вывод",
    "close": "Закрыть вывод задачи",
    "engine": "Задача {{engine}}",
    "identity": "Идентичность",
    "telemetry": "Токены",
    "recentOutput": "Недавний вывод",
    "refresh": "Обновить",
    "refreshing": "Обновление",
    "pending": "Ожидание",
    "telemetryPending": "Пока нет надёжных данных о токенах",
    "outputUnavailable": "Вывод пока недоступен. Задача может ещё выполняться, или этот движок не предоставляет вывод задачи в реальном времени.",
    "artifactLive": "Обновлено из файла вывода задачи.",
    "artifactTruncated": "Вывод длинный; показан самый недавний сегмент.",
    "artifactUnavailable": "Вывод в реальном времени недоступен. Сохраняется текущий снимок.",
    "status": {
      "running": "Выполняется",
      "completed": "Завершено",
      "error": "Ошибка",
      "unavailable": "Недоступно"
    },
    "tokens": {
      "input": "Входные",
      "cached": "Кэшированные",
      "output": "Выходные",
      "total": "Всего"
    },
    "telemetryStatus": {
      "live": "Данные в реальном времени",
      "estimated": "Оценочные данные",
      "pending": "Ожидание данных",
      "unavailable": "Данные недоступны"
    }
  }
};

export default engineTaskOutput;
