// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
const homeChat = {
  "homeChat": {
    "badge": "Главная чата с учётом рабочего пространства",
    "minimalTitle": "Создавайте что угодно",
    "announcementTag": "Новое",
    "announcementText": "Изучите шаблоны лендингов, карточки рабочих процессов и стартовые запросы",
    "announcementAction": "Открыть",
    "title": "ccgui Agent, упрощает работу",
    "titleLineOne": "Нажмите Enter",
    "titleLineTwo": "Создавайте приложения быстрее",
    "subtitle": "Сохраните привычный редактор, добавьте вокруг него более выразительный ритм лендинга и переходите к реальной работе с меньшими усилиями на настройку.",
    "promptPlaceholder": "Опишите вашу цель, например: Сгенерировать заметки о релизе для этого репозитория и включить проверки рисков.",
    "pathResolving": "Определение пути проекта по умолчанию...",
    "workspaceSearchPlaceholder": "Поиск проектов",
    "addWorkspaceAction": "Добавить новый проект",
    "workspaceNoMatch": "Проекты не найдены",
    "loadingRecentAgents": "Загрузка недавней работы",
    "recentConversations": "Недавние беседы",
    "quickActions": "Быстрые действия",
    "placeholderHint": "Пока эти точки входа — визуальные заглушки.",
    "placeholderSelected": "{{label}} скоро появится.",
    "seeAll": "Показать все",
    "navPrev": "Предыдущие карточки",
    "navNext": "Следующие карточки",
    "comingSoon": "Скоро",
    "tabs": {
      "templates": "Шаблоны",
      "workflows": "Рабочие процессы"
    },
    "quick": {
      "plan": "План из брифа",
      "doc": "Документация",
      "release": "Заметки о релизе",
      "review": "Обзор репозитория",
      "spec": "Черновик спецификации"
    },
    "cards": {
      "website": {
        "title": "Набор для запуска сайта",
        "description": "Макет героя, структура и стартовые тексты для эффектной страницы запуска."
      },
      "creator": {
        "title": "Панель автора",
        "description": "Аналитический пульт управления для контента, трафика и запросов."
      },
      "audio": {
        "title": "Аудиолендинг",
        "description": "Мягкие градиенты и яркие метрики для музыки, подкастов или медиа-запусков."
      },
      "editorial": {
        "title": "Редакционный манифест",
        "description": "Плакатная типографика для кампаний, заявлений и брендовых витрин."
      },
      "release": {
        "title": "Чек-лист релиза",
        "description": "Поэтапная передача изменений, проверки, заметок и последующего развёртывания."
      },
      "research": {
        "title": "Исследовательский спринт",
        "description": "Соберите вопросы, найдите источники и синтезируйте их в следующие действия."
      },
      "debug": {
        "title": "Стол отладки",
        "description": "Разбор логов, локализация регрессий и документирование проверенных исправлений."
      },
      "content": {
        "title": "Контент-конвейер",
        "description": "Бриф, черновик, обзор и публикация с единообразными контрольными точками."
      }
    }
  }
};

export default homeChat;
