// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {
  "layout": {
    "resizeGitHistoryPanel": "Изменить размер панели истории Git",
    "resizeSidebar": "Изменить размер боковой панели",
    "resizeRightPanel": "Изменить размер правой панели",
    "resizeEditorSplit": "Изменить размер разделения редактора",
    "resizeNoteCardsSplit": "Изменить размер разделения беседы и заметок",
    "resizePlanPanel": "Изменить размер панели плана",
    "resizeRuntimeConsole": "Изменить размер консоли выполнения",
    "resizeProjects": "Изменить размер проектов"
  }
};

export default layout;
