// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {
  "modes": {
    "selectMode": "Выбрать режим",
    "default": {
      "label": "Стандартный режим",
      "tooltip": "Стандартное поведение разрешений",
      "description": "Требует ручного подтверждения каждой операции, подходит для осторожного использования"
    },
    "plan": {
      "label": "Режим планирования",
      "tooltip": "Режим планирования — анализ только для чтения",
      "description": "Использует только инструменты чтения, формирует план для утверждения пользователем"
    },
    "acceptEdits": {
      "label": "Режим Agent",
      "tooltip": "Автоматически принимать изменения файлов",
      "description": "Автоматически принимать создание/редактирование файлов, сокращая число подтверждений"
    },
    "bypassPermissions": {
      "label": "Автоматический режим",
      "tooltip": "Обходить все проверки разрешений",
      "description": "Полностью автоматический режим, обходящий все проверки разрешений [Используйте с осторожностью]"
    }
  }
};

export default modes;
