// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {"panels":{"radar":"Радар","git":"Git","files":"Файлы","search":"Поиск","notes":"Заметки","memory":"Память","projectMap":"Карта проекта","intentCanvas":"Холст замысла","activity":"Активность","prompts":"Промпты"}};

export default panels;
