// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {
  "plan": {
    "title": "План",
    "noPlan": "План недоступен",
    "steps": "Шаги",
    "completed": "Завершено",
    "inProgress": "В процессе",
    "pending": "Ожидает"
  }
};

export default plan;
