// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/prompts.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/prompts.ts; keys mirror the English source.
const prompts = {
  "prompts": {
    "title": "Пользовательские промпты",
    "noPrompts": "Нет промптов",
    "filterPrompts": "Фильтровать промпты",
    "globalPrompts": "Общие промпты",
    "workspacePrompts": "Промпты рабочей области",
    "addWorkspacePrompt": "Добавить промпт рабочей области",
    "addGeneralPrompt": "Добавить общий промпт",
    "noWorkspacePrompts": "Промптов рабочей области пока нет",
    "noGeneralPrompts": "Общих промптов пока нет",
    "createOrDropWorkspace": "Создайте здесь или перетащите файл .md в",
    "createOrDropGeneral": "Создайте здесь или перетащите файл .md в",
    "workspacePromptsFolder": "папку промптов рабочей области",
    "codexHomePrompts": "CODEX_HOME/prompts",
    "promptCount": "{{count}} промпт",
    "promptCount_other": "{{count}} промптов",
    "name": "Имя",
    "promptName": "Имя промпта",
    "scope": "Область",
    "workspace": "Рабочая область",
    "general": "Общий",
    "description": "Описание",
    "optionalDescription": "Необязательное описание",
    "argumentHint": "Подсказка аргумента",
    "optionalArgumentHint": "Необязательная подсказка аргумента",
    "content": "Содержимое",
    "promptContent": "Содержимое промпта",
    "send": "Отправить",
    "sendToCurrentAgent": "Отправить текущему Agent",
    "newAgent": "Новый Agent",
    "sendToNewAgent": "Отправить новому Agent",
    "edit": "Изменить",
    "moveTo": "Переместить в {{scope}}",
    "delete": "Удалить",
    "promptActions": "Действия с промптом",
    "deletePrompt": "Удалить этот промпт?",
    "arguments": "Аргументы",
    "argumentsFor": "Аргументы для {{name}}"
  }
};

export default prompts;
