// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "Улучшение промпта",
    "tooltip": "Улучшить промпт",
    "tooltipFull": "Переписать промпт, чтобы дать больше контекста и улучшить ответы Agent",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "Улучшение промпта…",
    "readyToEnhance": "Задайте провайдера, модель и таймаут, затем запустите улучшение.",
    "runSettings": "Настройки улучшения",
    "provider": "Провайдер",
    "model": "Модель",
    "noModel": "Нет модели",
    "timeoutSeconds": "Таймаут (секунды)",
    "runEnhancement": "Запустить улучшение",
    "originalPrompt": "Исходный промпт",
    "enhancedPrompt": "Улучшенный промпт",
    "useEnhanced": "Использовать улучшенный",
    "keepOriginal": "Оставить исходный",
    "enhanceFailed": "Не удалось улучшить промпт",
    "emptyPrompt": "Сначала введите промпт",
    "copyEnhanced": "Копировать улучшенный"
  }
};

export default promptEnhancer;
