// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {
  "reasoning": {
    "title": "Выберите глубину рассуждений",
    "default": "По умолчанию",
    "claudeDefault": "По умолчанию",
    "defaultDescription": "Использовать поведение рассуждений движка по умолчанию",
    "low": {
      "label": "Низкая",
      "description": "Быстрые ответы с базовыми рассуждениями"
    },
    "medium": {
      "label": "Средняя",
      "description": "Сбалансированное мышление (по умолчанию)"
    },
    "high": {
      "label": "Высокая",
      "description": "Глубокие рассуждения для сложных задач"
    },
    "xhigh": {
      "label": "Очень высокая",
      "description": "Очень высокая глубина рассуждений"
    },
    "max": {
      "label": "Максимум",
      "description": "Максимальная глубина рассуждений"
    },
    "ultra": {
      "label": "Ультра",
      "description": "Максимальное рассуждение с автоматическим делегированием задач"
    }
  }
};

export default reasoning;
