// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "Поиск файлов, канбана, тредов, сообщений, навыков, команд…",
    "placeholderFiltered": "Поиск {{content}}…",
    "inputAria": "Поле поиска",
    "scope": "Область",
    "content": "Содержимое",
    "current": "Текущий",
    "global": "Глобально",
    "currentWorkspace": "Текущая рабочая область",
    "allWorkspaces": "Все рабочие области",
    "noResults": "Нет результатов",
    "noResultsHint": "Попробуйте ключевые слова из пути к файлу, названия задачи, названия треда, текста сообщения, имени навыка или имени команды.",
    "fileIndexLoading": "Дополняется индекс файлов...",
    "fileIndexPartial": "Индекс файлов неполный, поэтому некоторые файлы могут отсутствовать.",
    "fileIndexError": "Не удалось загрузить индекс. Откройте поиск снова, чтобы повторить попытку.",
    "navigate": "Навигация",
    "open": "Открыть",
    "close": "Закрыть",
    "projectTag": "Проект",
    "typeTag": "Тип",
    "sourceTag": "Источник",
    "locationTag": "Расположение",
    "typeAction": "Действие",
    "typeFile": "Файл",
    "typeKanban": "Канбан",
    "typeThread": "Тред",
    "typeMessage": "Сообщение",
    "typeHistory": "История",
    "typeSkill": "Навык",
    "typeCommand": "Команда",
    "sourceActions": "Действия приложения",
    "sourceFiles": "Индекс файлов",
    "sourceKanban": "Данные канбана",
    "sourceThreads": "Названия тредов",
    "sourceMessages": "Содержимое сообщений",
    "sourceHistory": "История ввода",
    "sourceSkills": "Список навыков",
    "sourceCommands": "Список команд",
    "contentAll": "Все",
    "contentActions": "Действия",
    "contentFiles": "Файлы",
    "contentKanban": "Канбан",
    "contentThreads": "Треды",
    "contentMessages": "Сообщения",
    "contentHistory": "История",
    "contentSkills": "Навыки",
    "contentCommands": "Команды"
  }
};

export default searchPalette;
