// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/statusPanel.ts; keys mirror the English source.
const statusPanel = {
  "statusPanel": {
    "tabTodos": "Задачи",
    "tabSubagents": "Субагенты",
    "tabAgents": "Агенты",
    "tabCheckpoint": "Результат",
    "tabPlan": "План",
    "tabCommands": "Команды",
    "files": "файлов",
    "emptyTodos": "Нет задач",
    "emptySubagents": "Нет субагентов",
    "emptyFileChanges": "Нет изменений файлов",
    "emptyCommands": "Нет команд",
    "emptyPlan": "Нет плана",
    "planGenerating": "Генерация плана...",
    "planSwitchHint": "Переключитесь в режим Plan, чтобы просмотреть план",
    "expand": "Развернуть панель статуса",
    "collapse": "Свернуть панель статуса",
    "label": "Статус",
    "policy": {
      "title": "Аудит политик",
      "count": "Решений: {{count}}",
      "noReason": "{{policy}} не предоставила причину",
      "verdict": {
        "running": "Выполняется",
        "blocked": "Заблокировано",
        "needs_review": "Проверка",
        "ready": "Готово",
        "no_contribution": "Пропущено"
      },
      "corePolicy": {
        "blocked": "Основные правила обнаружили блокирующий риск.",
        "running": "Основные правила обнаружили выполняющуюся работу.",
        "ready": "Основные правила сочли текущие свидетельства готовыми.",
        "needsReview": "Основные правила требуют проверки."
      },
      "lintValidationPolicy": {
        "pass": "Линтинг пройден.",
        "fail": "Линтинг не пройден и требует проверки.",
        "running": "Линтинг выполняется.",
        "notRun": "Линтинг не запускался."
      },
      "typecheckValidationPolicy": {
        "pass": "Проверка типов пройдена.",
        "fail": "Проверка типов не пройдена и требует проверки.",
        "running": "Проверка типов выполняется.",
        "notRun": "Проверка типов не запускалась."
      },
      "testsValidationPolicy": {
        "pass": "Тесты пройдены.",
        "fail": "Тесты не пройдены и требуют проверки.",
        "running": "Тесты выполняются.",
        "notRun": "Тесты не запускались."
      },
      "openspecGovernancePolicy": {
        "pass": "Свидетельства управления OpenSpec актуальны.",
        "warn": "Свидетельства управления OpenSpec содержат рекомендательные предупреждения.",
        "fail": "Свидетельства управления OpenSpec требуют проверки.",
        "unknown": "Свидетельства управления OpenSpec недоступны или неполны."
      },
      "largeFileGovernancePolicy": {
        "pass": "Свидетельства управления большими файлами актуальны.",
        "warn": "Свидетельства управления большими файлами содержат рекомендательные предупреждения.",
        "fail": "Свидетельства управления большими файлами требуют проверки.",
        "unknown": "Свидетельства управления большими файлами недоступны или неполны."
      },
      "heavyTestNoiseGovernancePolicy": {
        "pass": "Свидетельства шумных тяжёлых тестов актуальны.",
        "warn": "Свидетельства шумных тяжёлых тестов содержат рекомендательные предупреждения.",
        "fail": "Свидетельства шумных тяжёлых тестов требуют проверки.",
        "unknown": "Свидетельства шумных тяжёлых тестов недоступны или неполны."
      },
      "realtimeHarnessGovernancePolicy": {
        "pass": "Свидетельства среды реального времени актуальны.",
        "warn": "Свидетельства среды реального времени содержат рекомендательные предупреждения.",
        "fail": "Свидетельства среды реального времени требуют проверки.",
        "unknown": "Свидетельства среды реального времени недоступны или неполны."
      },
      "capabilityMismatchGovernancePolicy": {
        "pass": "Свидетельства возможностей движка актуальны.",
        "warn": "Свидетельства возможностей движка содержат рекомендательные предупреждения.",
        "fail": "Свидетельства возможностей движка требуют проверки.",
        "unknown": "Свидетельства возможностей движка недоступны или неполны."
      },
      "engineRuntimeGovernancePolicy": {
        "pass": "Свидетельства контракта среды выполнения движка актуальны.",
        "warn": "Свидетельства контракта среды выполнения движка содержат рекомендательные предупреждения.",
        "fail": "Свидетельства контракта среды выполнения движка требуют проверки.",
        "unknown": "Свидетельства контракта среды выполнения движка недоступны или неполны."
      },
      "costBudgetGovernancePolicy": {
        "pass": "Свидетельства бюджета затрат актуальны.",
        "warn": "Свидетельства бюджета затрат содержат рекомендательные предупреждения.",
        "fail": "Свидетельства бюджета затрат требуют проверки.",
        "unknown": "Свидетельства бюджета затрат недоступны или неполны."
      }
    },
    "audit": {
      "title": "Обоснование решения",
      "expandLabel": "Решений политик: {{count}}",
      "empty": "Нет решений политик",
      "reasonUnavailable": "{{policy}} не предоставила причину",
      "sourceUnavailable": "Нет источника",
      "enforcement": {
        "advisory": "Рекомендательное",
        "blocking": "Блокирующее",
        "informational": "Инфо"
      }
    },
    "governance": {
      "title": "Свидетельства управления",
      "loading": "Чтение свидетельств...",
      "empty": "Нет свидетельств управления",
      "count": "Элементов свидетельств: {{count}} · требуют действия: {{needsAction}}",
      "group": {
        "needs_action": "Требуют действия · {{count}}",
        "watch": "Наблюдение · {{count}}",
        "passed": "Пройдено · {{count}}"
      },
      "meta": {
        "source": "Источник: {{source}}",
        "artifact": "Артефакт: {{path}}",
        "action": "Действие: устранить {{reason}}"
      },
      "status": {
        "pass": "Пройдено",
        "warn": "Предупреждение",
        "fail": "Не пройдено",
        "unknown": "Неизвестно"
      }
    },
    "cost": {
      "title": "Затраты / Бюджет",
      "session": "Сессия",
      "engine": "Движок",
      "model": "Модель",
      "sessionId": "ID сессии",
      "tokens": "Токены",
      "tokenBreakdownLabel": "Разбивка использования токенов",
      "known": "Тариф сопоставлен",
      "partial": "Частичная оценка",
      "unknownModel": "Неизвестная модель",
      "pricingSource": "Источник тарифов: {{source}} · {{date}}",
      "historyDegraded": "История затрат продолжается в памяти, так как запись в localStorage не удалась.",
      "accumulated": {
        "session": "Сессия {{amount}}",
        "today": "Сегодня {{amount}}",
        "month": "Месяц {{amount}}"
      },
      "degraded": {
        "pricing-unavailable": "Для {{engine}}/{{model}} нет прослеживаемых тарифов; затраты не считаются молча нулевыми.",
        "pricing-stale": "Фикстура тарифов устарела; эти затраты только для информации.",
        "usage-unavailable": "Нет данных об использовании токенов для оценки затрат.",
        "block-level-cost-unsupported": "Затраты на уровне блоков не поддерживаются в этой версии.",
        "unknown": "Оценка затрат ухудшена."
      }
    },
    "budget": {
      "unconfigured": "Бюджет не настроен. Это рекомендация, а не неудачная проверка бюджета.",
      "unsetShort": "Бюджет не задан",
      "barLabel": "Прогресс использования бюджета",
      "progress": "{{amount}} / {{limit}}",
      "threshold": {
        "info": "Достигнут информационный порог: {{amount}} / {{threshold}}",
        "warn": "Достигнут порог предупреждения: {{amount}} / {{threshold}}",
        "block": "Достигнут блокирующий порог: {{amount}} / {{threshold}}. Эта возможность только сигнализирует; она не прерывает выполнение."
      }
    },
    "checkpoint": {
      "verdictTitle": "Вердикт",
      "evidenceTitle": "Свидетельства",
      "keyChangesTitle": "Ключевые изменения",
      "keyChangesEmpty": "Пока не зафиксировано ключевых изменений",
      "fileDetailsTitle": "Детали файлов",
      "risksTitle": "Риски",
      "nextActionTitle": "Следующее действие",
      "sections": {
        "summary": "Сводка",
        "advisorySignals": "Рекомендательные сигналы",
        "evidenceTrail": "Цепочка свидетельств",
        "policyAudit": "Аудит политик",
        "suggestedActions": "Рекомендуемые действия"
      },
      "advisory": {
        "count": "Рекомендательных сигналов: {{count}}"
      },
      "verdict": {
        "running": "Выполняется",
        "blocked": "Заблокировано",
        "needs_review": "Требует проверки",
        "ready": "Готово"
      },
      "headline": {
        "running": "Работа в процессе",
        "blocked": "Требуется внимание",
        "needs_review": "Проверьте перед продолжением",
        "ready": "Готово к продолжению",
        "idle": "Ожидание свидетельств"
      },
      "summary": {
        "blockedValidation": "Обязательная проверка не пройдена и должна быть исправлена в первую очередь.",
        "blockedCommand": "Последняя команда завершилась ошибкой: {{command}}. Если система всё ещё пытается автоматически восстановиться, дождитесь стабилизации этого запуска, прежде чем останавливать его.",
        "blockedSubagent": "Делегированная задача остановилась в состоянии ошибки.",
        "runningValidation": "Проверка ещё выполняется. Дождитесь результата перед принятием решения.",
        "runningCommand": "Последняя команда всё ещё выполняется: {{command}}",
        "runningAgent": "Как минимум один агент всё ещё работает.",
        "runningTodo": "Есть ещё активные задачи в процессе.",
        "runningProcessing": "Текущий ход всё ещё производит свидетельства выполнения.",
        "readyWithFiles": "{{count}} изменённых файлов прошли наблюдаемые основные проверки.",
        "ready": "Наблюдаемые свидетельства выполнения выглядят стабильными.",
        "needsValidation": "Файлы изменены, но основные проверки ещё не запускались.",
        "manual": "Результат доступен, но всё ещё требует проверки человеком.",
        "idle": "Пока не наблюдалось надёжных свидетельств выполнения."
      },
      "evidence": {
        "filesChanged": "Изменено файлов",
        "filesChangedValue": "{{count}} файлов",
        "validations": "Проверки",
        "requiredValidations": "Обязательные",
        "optionalValidations": "Необязательные",
        "fileChangeSummary": "+{{additions}}/-{{deletions}} в {{count}} файлах",
        "runMissing": "Сначала запустите",
        "runMissingGeneric": "Запустите основной скрипт проверки проекта",
        "tasks": "Задачи",
        "agents": "Агенты",
        "inProgress": "В процессе",
        "settled": "Стабилизировано"
      },
      "evidenceTrail": {
        "count": "Элементов свидетельств: {{count}}",
        "sourceLabel": "Источник",
        "snapshotLabel": "Снимок",
        "observedLabel": "Зафиксировано",
        "artifactLabel": "Артефакт",
        "hashLabel": "Хэш",
        "qualifierLabel": "Квалификатор",
        "degradedLabel": "Ухудшено",
        "staleLabel": "Устарело",
        "snapshotRecorded": "Снимок записан",
        "hashRecorded": "Проверено",
        "policy": {
          "buildValidationPolicy": "Проверка сборки",
          "costBudgetGovernancePolicy": "Бюджет затрат",
          "heavyTestNoiseGovernancePolicy": "Шум тяжёлых тестов",
          "largeFileGovernancePolicy": "Управление большими файлами",
          "lintValidationPolicy": "Проверка линтинга",
          "openspecGovernancePolicy": "Управление OpenSpec",
          "testsValidationPolicy": "Проверка тестов",
          "typecheckValidationPolicy": "Проверка типов"
        },
        "sourceName": {
          "build": "Сборка",
          "costBudget": "Бюджет затрат",
          "heavyTestNoise": "Шум тяжёлых тестов",
          "largeFile": "Большой файл",
          "lint": "Линтинг",
          "openspec": "OpenSpec",
          "tests": "Тесты",
          "trellis": "Trellis",
          "typecheck": "Проверка типов"
        },
        "reason": {
          "governanceArtifactMalformed": "Файл свидетельств имеет неверный формат",
          "governanceEvidenceUnavailable": "Свидетельства пока не удаётся разобрать",
          "pricingUnavailable": "Тариф модели неизвестен",
          "stale": "Свидетельства устарели"
        },
        "source": "Источник: {{source}}",
        "snapshot": "Снимок: {{id}}",
        "observed": "Зафиксировано: {{time}}",
        "artifact": "Артефакт: {{path}}",
        "hash": "Хэш: {{hash}}",
        "qualifier": "Квалификатор: {{qualifier}}",
        "degraded": "Ухудшено: {{reason}}",
        "stale": "Устарело: {{time}}"
      },
      "suggested": {
        "validation": "Необязательно: {{command}}",
        "governance": "Необязательная проверка {{source}}: {{command}}"
      },
      "expandToDock": "Смотреть полные результаты в доке",
      "validations": {
        "lint": "Линтинг",
        "typecheck": "Проверка типов",
        "tests": "Тесты",
        "build": "Сборка",
        "custom": "Команда",
        "status": {
          "pass": "Пройдено",
          "fail": "Не пройдено",
          "running": "Выполняется",
          "not_run": "Не запускалось",
          "not_observed": "Не наблюдалось"
        }
      },
      "keyChanges": {
        "files": "Затронутые файлы",
        "filesSummary": "Изменено файлов: {{count}} · +{{additions}} / -{{deletions}}",
        "tasks": "Прогресс задач",
        "tasksSummary": "Завершено задач: {{completed}}/{{total}}",
        "agents": "Прогресс агентов",
        "agentsSummary": "Завершено агентов: {{completed}}/{{total}}"
      },
      "risks": {
        "none": "Блокирующих рисков не обнаружено.",
        "commandFailed": "Команда завершилась ошибкой: {{command}}",
        "validationFailed": "Как минимум одна проверка завершилась неудачей.",
        "validationMissing": "Основные проверки не запускались после изменения файлов.",
        "subagentError": "Агент сообщил об ошибке: {{agent}}",
        "manualReview": "Система пока не наблюдала достаточно свидетельств, чтобы объявить результат.",
        "severity": {
          "high": "Высокий",
          "medium": "Средний",
          "low": "Низкий"
        }
      },
      "actions": {
        "reviewDiff": "Просмотреть diff",
        "openRisk": "Изучить риски",
        "retry": "Повторить неудавшийся шаг",
        "commit": "Зафиксировать по готовности",
        "hint": {
          "runMissingValidation": "Запустите недостающую проверку, прежде чем решать, продолжать ли.",
          "running": "Дождитесь стабилизации текущих свидетельств выполнения.",
          "blocked": "Сначала изучите неудавшиеся свидетельства; если восстановление ещё идёт, дождитесь стабилизации запуска, прежде чем решать остановить его.",
          "needs_review": "Этот результат ещё может восстановиться. Дождитесь дальнейшей стабилизации выполнения, прежде чем действовать.",
          "ready": "Свидетельства стабильны; выполните финальную проверку перед фиксацией."
        }
      },
      "commitDialog": {
        "title": "Подтверждение фиксации",
        "path": "Путь:",
        "files": "Файлы для фиксации",
        "toggleAllFiles": "Переключить все файлы фиксации",
        "staged": "Проиндексировано"
      }
    }
  }
};

export default statusPanel;
