// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
const taskCenter = {
  "taskCenter": {
    "title": "Центр задач",
    "eyebrow": "Запуски агентов",
    "workspaceHero": "Запуск, требующий внимания сейчас",
    "statusFilter": "Статус",
    "engineFilter": "Движок",
    "filterAll": "Все",
    "empty": "Пока нет запусков задач",
    "summary": "{{attention}} из {{total}} запусков требуют внимания",
    "openedFromProjectMap": "Связанный запуск открыт из очереди работ Карты проекта. На этой странице показаны реальные детали TaskRun; если не появляется действие с диалогом, этот запуск ещё не связан с реальной сессией.",
    "trigger": "Триггер",
    "updatedAt": "Обновлено",
    "currentStep": "Текущий шаг",
    "latestOutput": "Последний вывод",
    "diagnostics": "Диагностика",
    "artifacts": "Артефакты",
    "browserEvidence": "Данные браузера",
    "unavailable": "Недоступно",
    "noArtifacts": "Пока нет артефактов",
    "noBrowserEvidence": "Данные браузера не привязаны",
    "browserEvidenceCandidates": "кандидаты",
    "source": {
      "kanban": "канбан",
      "orchestration": "оркестрация"
    },
    "browserEvidenceState": {
      "available": "доступно",
      "stale": "устарело",
      "expired": "истекло",
      "degraded": "ограничено",
      "deleted": "удалено",
      "unsupported": "не поддерживается"
    },
    "status": {
      "queued": "В очереди",
      "planning": "Планирование",
      "running": "Выполняется",
      "waiting_input": "Ожидание ввода",
      "blocked": "Заблокировано",
      "failed": "Ошибка",
      "completed": "Завершено",
      "canceled": "Отменено"
    },
    "action": {
      "openConversation": "Открыть беседу",
      "openOrchestrationTask": "Открыть задачу оркестрации",
      "retry": "Повторить",
      "resume": "Возобновить",
      "cancel": "Отменить",
      "fork": "Ответвить запуск"
    },
    "nextStep": {
      "monitor": "Этот запуск ещё выполняется. Следите за текущим шагом или отмените при необходимости.",
      "openConversation": "Откройте связанную беседу, чтобы дать ввод или просмотреть последний вывод.",
      "resume": "Этот запуск заблокирован. Сначала возобновите его, чтобы продолжить текущий путь.",
      "retry": "Этот запуск завершился с ошибкой. Повторите его или просмотрите сводку сбоя.",
      "wait": "Сейчас никаких действий не требуется. Дайте запуску сначала стабилизироваться.",
      "review": "Сначала просмотрите диагностику и артефакты, затем решите, что делать дальше.",
      "fork": "Вы можете ответвить новый запуск из текущего результата, чтобы продолжить."
    }
  }
};

export default taskCenter;
