// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {"terminal":{"newTab":"Новая вкладка","closeTab":"Закрыть вкладку","clear":"Очистить","title":"Терминал","tabTitle":"Терминал {{number}}","claudeTuiResumeTitle":"Claude TUI","sendSelectionToComposer":"Отправить в редактор"}};

export default terminal;
