// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
const threadCompletion = {"threadCompletion":{"title":"Сессия завершена","project":"Проект","session":"Сессия"}};

export default threadCompletion;
