// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {
  "time": {
    "justNow": "только что",
    "minuteAgo": "{{count}} минуту назад",
    "minutesAgo": "{{count}} мин назад",
    "hourAgo": "{{count}} час назад",
    "hoursAgo": "{{count}} ч назад",
    "dayAgo": "{{count}} день назад",
    "daysAgo": "{{count}} дн назад",
    "weekAgo": "{{count}} неделю назад",
    "weeksAgo": "{{count}} нед назад",
    "now": "сейчас",
    "shortSecondsAgo": "{{value}} с назад",
    "shortSecondsIn": "через {{value}} с",
    "shortMinutesAgo": "{{value}} мин назад",
    "shortMinutesIn": "через {{value}} мин",
    "shortMinutes": "{{value}} мин",
    "shortHours": "{{value}} ч",
    "shortDays": "{{value}} д",
    "shortWeeks": "{{value}} нед",
    "shortMonths": "{{value}} мес",
    "shortYears": "{{value}} г"
  }
};

export default time;
