// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "Обновление",
    "checkingForUpdates": "Проверка обновлений...",
    "updateAvailable": "Доступна новая версия!",
    "upToDate": "У вас последняя версия.",
    "downloading": "Загрузка обновления…",
    "installing": "Установка обновления…",
    "restarting": "Перезапуск…",
    "failed": "Не удалось обновить.",
    "downloaded": "загружено",
    "releaseNotesTitle": "Примечания к выпуску",
    "releaseNotesLoading": "Загрузка примечаний к выпуску…",
    "releaseNotesLoadFailed": "Не удалось загрузить примечания к выпуску.",
    "releaseNotesEmpty": "Пока нет примечаний к выпуску.",
    "releaseNotesOpenInGitHub": "Смотреть на GitHub",
    "releaseNotesPrev": "Назад",
    "releaseNotesNext": "Вперёд",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "English:",
    "releaseNotesChinese": "中文："
  }
};

export default update;
