// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/about.ts; keys mirror the English source.
const about = {"about":{"version":"버전","tagline":"차세대 VibeCoding 에디터","checkForUpdates":"업데이트 확인","releaseNotes":"릴리스 노트","reportIssue":"이슈 신고","website":"웹사이트","github":"GitHub","wechatGroupTitle":"스캔하여 WeChat 그룹 참여"}};

export default about;
