// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/activityPanel.ts; keys mirror the English source.
const activityPanel = {
  "activityPanel": {
    "title": "세션 활동",
    "noRoot": "현재 작업",
    "selectWorkspace": "세션 활동을 확인할 워크스페이스를 선택하세요.",
    "emptyIdle": "아직 세션 활동이 없습니다.",
    "emptyRunning": "세션 활동을 기다리는 중...",
    "emptyCompleted": "이 작업은 1단계에서 추적된 활동 없이 완료되었습니다.",
    "eventsCount": "이벤트 {{count}}개",
    "sessionsCount": "세션 {{count}}개",
    "liveNow": "실시간",
    "command": "명령",
    "commandPendingSummary": "명령 실행 중",
    "commandCategories": {
      "command": "명령",
      "search": "검색",
      "read": "읽기",
      "list": "목록",
      "git": "Git",
      "test": "테스트",
      "lint": "린트",
      "build": "빌드",
      "run": "실행"
    },
    "description": "설명",
    "cwd": "작업 디렉터리",
    "waitingForOutput": "명령 출력을 기다리는 중...",
    "waitingForReasoning": "사고 내용을 기다리는 중...",
    "rootSession": "루트",
    "childSession": "자식",
    "relatedSessions": "관련",
    "fallbackLinking": "폴백 링크",
    "liveEditPreview": "실시간 미리보기",
    "liveEditFollowLabel": "실시간 팔로우",
    "liveEditPreviewTooltip": "AI가 현재 편집 중인 파일을 실시간으로 열려면 활성화하세요.",
    "enableLiveEditPreview": "실시간 편집 미리보기 활성화",
    "disableLiveEditPreview": "실시간 편집 미리보기 비활성화",
    "followCoachTitle": "실시간 팔로우 사용해 보기",
    "followCoachBody": "AI가 편집 중인 파일을 따라가려면 켜세요.",
    "followCoachEnable": "지금 활성화",
    "followCoachDismiss": "나중에",
    "followNudgeTitle": "실시간 팔로우",
    "followNudgeErrorTitle": "활성화 실패",
    "followNudgeBody": "AI가 파일을 편집하고 있습니다. 실시간 팔로우를 활성화할까요?",
    "followNudgeEnable": "활성화",
    "followNudgeLater": "나중에",
    "followNudgeRetry": "다시 시도",
    "followToggleFailed": "실시간 팔로우 전환에 실패했습니다. 다시 시도해 주세요.",
    "showOutput": "출력 표시",
    "hideOutput": "출력 숨기기",
    "expandTurnGroup": "턴 그룹 펼치기",
    "collapseTurnGroup": "턴 그룹 접기",
    "turnGroup": "턴 {{index}}",
    "turnGroupFallback": "레거시 활동",
    "tabs": {
      "ariaLabel": "세션 활동 카테고리",
      "all": "요약",
      "command": "명령",
      "file": "산출물",
      "task": "작업",
      "subagent": "서브에이전트",
      "explore": "탐색",
      "reasoning": "사고"
    },
    "artifacts": {
      "kicker": "턴 산출물",
      "title": "산출물",
      "fileCount": "파일 {{count}}개",
      "fileCount_other": "파일 {{count}}개",
      "turnSemanticTitle": "턴 의미",
      "tabsAriaLabel": "턴 산출물 보기",
      "tabs": {
        "artifacts": "산출물",
        "semantic": "시맨틱 차이"
      }
    },
    "radar": {
      "modeCurrentTask": "현재 작업",
      "modeWorkspaceRadar": "워크스페이스 레이더",
      "runningSection": "실행 중 ({{count}})",
      "recentSection": "최근 완료됨 ({{count}})",
      "emptyRunning": "실행 중인 세션이 없습니다.",
      "emptyRecent": "최근 완료된 세션이 없습니다.",
      "openSession": "열기",
      "runningCountAria": "실행 중인 세션 {{count}}개",
      "recentCountAria": "최근 세션 {{count}}개",
      "startedAt": "시작:",
      "endedAt": "종료:",
      "totalDuration": "소요 시간:",
      "timeUnknown": "--:--:--",
      "durationUnknown": "--",
      "unreadBadge": "신규",
      "unreadMark": "읽지 않음",
      "readMark": "읽음",
      "deleteHistoryEntry": "{{name}} 삭제",
      "deleteDateGroupEntries": "{{date}}의 항목 {{count}}개 모두 삭제"
    },
    "status": {
      "running": "실행 중",
      "completed": "완료됨",
      "failed": "실패",
      "pending": "대기 중"
    }
  }
};

export default activityPanel;
