// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/app.ts; keys mirror the English source.
const app = {
  "app": {
    "title": "ccgui",
    "subtitle": "로컬 프로젝트 전반에 걸쳐 에이전트를 오케스트레이션하세요."
  }
};

export default app;
