// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/askUserQuestion.ts; keys mirror the English source.
const askUserQuestion = {"askUserQuestion":{"title":"Claude가 질문이 있습니다","progress":"질문 {{current}} / {{total}}","timeoutWarning":"곧 응답해 주세요. 이 대화 상자는 {{seconds}}초 후에 자동으로 닫힙니다","collapse":"접기","expand":"펼치기","clickToAnswer":"클릭하여 답변","questionTab":"질문 {{index}}","cancel":"취소","back":"뒤로","next":"다음","submit":"제출","otherOption":"기타","otherOptionDesc":"직접 답변 입력","customInputPlaceholder":"답변을 입력하세요...","multiSelectHint":"여러 옵션을 선택할 수 있습니다"}};

export default askUserQuestion;
