// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/browserAgent.ts; keys mirror the English source.
const browserAgent = {
  "browserAgent": {
    "dock": {
      "description": "먼저 주요 페이지 정보를 읽은 다음 탐색과 요소 동작을 점진적으로 활성화하세요.",
      "disabled": "비활성화됨",
      "statusDisconnected": "연결 끊김",
      "statusLoading": "로딩 중",
      "statusReady": "읽기 가능",
      "statusClosed": "닫힘",
      "statusNeedsAttention": "주의 필요",
      "statusPreparing": "준비 중",
      "emptyUrl": "열 페이지 URL을 입력하세요.",
      "blockedUrl": "이 URL은 Browser Agent 정책에 의해 차단되었습니다.",
      "opened": "Browser Agent가 브라우저 탭을 열었습니다.",
      "closed": "Browser Agent 탭이 닫혔습니다.",
      "busy": "작업 중",
      "open": "열기",
      "enable": "활성화",
      "enabled": "Browser Agent가 활성화되었습니다.",
      "tabs": "브라우저 탭",
      "newTab": "새 브라우저 탭",
      "openDock": "브라우저",
      "panelTitle": "브라우저 독",
      "panelKicker": "여기서 페이지를 연 다음 필요할 때 그 컨텍스트를 AI에 첨부하세요.",
      "noWorkspace": "브라우저 독을 열기 전에 워크스페이스를 선택하세요.",
      "noPage": "Browser Agent 창을 실행하려면 허용된 http/https 페이지를 여세요.",
      "rendering": "Browser Agent 창에서 페이지를 렌더링하는 중...",
      "windowOpened": "페이지가 별도의 Browser Agent 창에서 열려 있습니다.",
      "closePanel": "브라우저 독 닫기",
      "close": "Browser Agent 세션 닫기",
      "info": "Browser Agent 세부 정보 표시",
      "footnote": "MVP는 원시 DOM, 쿠키, 헤더 또는 페이지 시크릿을 저장하지 않습니다."
    },
    "composer": {
      "attach": "브라우저 컨텍스트 첨부",
      "attaching": "브라우저 컨텍스트 첨부 중...",
      "attached": "브라우저 컨텍스트가 첨부됨",
      "visibleSnapshot": "브라우저 보이는 페이지 스냅샷",
      "selectedElement": "선택된 페이지 요소",
      "selectedElementCount": "선택된 페이지 요소 {{count}}개",
      "selectedElementFacts": "선택된 페이지 요소 정보",
      "selectedElementMore": "요소 {{count}}개 더",
      "selectorHint": "선택자 {{selector}}",
      "noRawApi": "API 원시 데이터 아님",
      "remove": "제거",
      "refresh": "브라우저 컨텍스트 새로 고침",
      "fresh": "준비됨",
      "stale": "새로 고침",
      "expired": "만료됨",
      "degraded": "저하됨",
      "unsupported": "지원 안 됨",
      "showDetails": "캡처 세부 정보 표시",
      "hideDetails": "세부 정보 숨기기",
      "countSummary": "페이지 요소 수",
      "headingCount": "제목 {{count}}",
      "linkCount": "링크 {{count}}",
      "buttonCount": "버튼 {{count}}",
      "formCount": "폼 {{count}}",
      "readableBlockCount": "읽기 가능 블록 {{count}}",
      "visualEvidenceCount": "시각적 단서 {{count}}",
      "counts": "제목 {{headings}} · 링크 {{links}} · 버튼 {{buttons}} · 폼 {{forms}} · 읽기 가능 블록 {{readableBlocks}} · 시각적 단서 {{visualEvidence}} · 코드 후보 {{candidates}}",
      "primaryContent": "주요 콘텐츠",
      "readableBlocks": "읽기 가능 블록 {{count}}",
      "visualEvidence": "시각적 단서 {{count}}",
      "codeCandidates": "코드 후보 {{count}}",
      "privacy": "편집 종류 {{redacted}}개, 생략된 민감 소스 종류 {{omitted}}개.",
      "noSession": "활성 Browser Agent 세션이 없습니다. 먼저 브라우저 독에서 페이지를 여세요."
    }
  }
};

export default browserAgent;
