// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/claudeModes.ts; keys mirror the English source.
const claudeModes = {"claudeModes":{"default":{"label":"제안 모드 (미리보기)","tooltip":"Claude Code 미리보기 승인 모드입니다. 전체 승인 브리지가 완성되는 동안 일부 흐름은 여전히 저하될 수 있습니다.","description":"Claude의 기본 권한 흐름을 검증하기 위한 미리보기로 이제 사용할 수 있습니다. 저하된 경로에 도달하면 UI가 사용자를 계획 모드로 다시 안내합니다."},"plan":{"label":"계획 모드","tooltip":"Claude Code 읽기 전용 분석 모드입니다.","description":"동작하기 전에 읽기 전용 도구를 사용하여 분석하고 계획합니다."},"acceptEdits":{"label":"자동 편집","tooltip":"Claude Code 자동 편집 모드. 현재 롤아웃 단계에서는 활성화되지 않습니다.","description":"Claude 승인 방식이 검증될 때까지 이 모드는 사용할 수 없습니다."},"bypassPermissions":{"label":"완전 자동","tooltip":"권한 확인을 건너뛰는 Claude Code 모드.","description":"승인 없이 파일 쓰기와 명령을 실행합니다. 신중하게 사용하세요."}}};

export default claudeModes;
