// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/codexModes.ts; keys mirror the English source.
const codexModes = {"codexModes":{"default":{"label":"제안 (승인)","tooltip":"Codex approval_policy=untrusted – 파일 편집이나 셸 명령 실행 전에 확인을 요청합니다.","description":"가장 안전한 옵션. 모든 쓰기와 명령에 승인이 필요합니다."},"plan":{"label":"계획 모드","tooltip":"계획 모드 - 읽기 전용 분석","description":"읽기 전용 도구만 사용하며, 사용자 승인을 위한 계획을 생성합니다"},"acceptEdits":{"label":"자동 편집","tooltip":"Codex approval_policy=auto-edit – 파일 패치를 자동으로 적용하지만 셸 명령은 여전히 확인을 요청합니다.","description":"apply_patch로 파일을 자동 생성 및 편집하되 명령 승인은 유지합니다."},"bypassPermissions":{"label":"완전 자동","tooltip":"Codex approval_policy=never – 확인 없이 명령을 실행하고 파일을 씁니다 (작업 공간 샌드박스는 여전히 적용됨).","description":"완전 자동 모드. Codex가 편집과 셸 명령을 즉시 실행합니다."}}};

export default codexModes;
