// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/debug.ts; keys mirror the English source.
const debug = {"debug":{"title":"디버그","copyLogs":"로그 복사","clearLogs":"로그 지우기","noLogs":"디버그 로그 없음","copy":"복사","clear":"지우기","noDebugEventsYet":"아직 디버그 이벤트가 없습니다."}};

export default debug;
