// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/engineTaskOutput.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/engineTaskOutput.ts; keys mirror the English source.
const engineTaskOutput = {
  "engineTaskOutput": {
    "label": "작업 출력 검사기",
    "inspect": "출력 보기",
    "close": "작업 출력 닫기",
    "engine": "{{engine}} 작업",
    "identity": "식별 정보",
    "telemetry": "Token",
    "recentOutput": "최근 출력",
    "refresh": "새로 고침",
    "refreshing": "새로 고침 중",
    "pending": "대기 중",
    "telemetryPending": "아직 신뢰할 수 있는 Token 데이터가 없습니다",
    "outputUnavailable": "아직 사용 가능한 출력이 없습니다. 작업이 아직 실행 중이거나, 이 엔진이 실시간 작업 출력을 제공하지 않을 수 있습니다.",
    "artifactLive": "작업 출력 파일에서 업데이트됨.",
    "artifactTruncated": "출력이 길어 가장 최근 부분만 표시합니다.",
    "artifactUnavailable": "실시간 출력을 사용할 수 없습니다. 현재 스냅샷을 유지합니다.",
    "status": {
      "running": "실행 중",
      "completed": "완료됨",
      "error": "오류",
      "unavailable": "사용 불가"
    },
    "tokens": {
      "input": "입력",
      "cached": "캐시됨",
      "output": "출력",
      "total": "합계"
    },
    "telemetryStatus": {
      "live": "실시간 데이터",
      "estimated": "추정 데이터",
      "pending": "데이터 대기 중",
      "unavailable": "데이터 사용 불가"
    }
  }
};

export default engineTaskOutput;
