// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/errors.ts; keys mirror the English source.
const errors = {
  "errors": {
    "connectionFailed": "연결 실패",
    "requestFailed": "요청 실패",
    "unexpectedError": "예기치 않은 오류가 발생했습니다",
    "sessionExpired": "세션이 만료되었습니다",
    "rateLimited": "요청 한도를 초과했습니다. 나중에 다시 시도하세요.",
    "networkError": "네트워크 오류. 연결을 확인하세요.",
    "failedToAddWorkspace": "작업 공간을 추가하지 못했습니다.",
    "failedToOpenNewWindow": "새 창을 열지 못했습니다.",
    "failedToCreateSession": "세션을 생성하지 못했습니다.",
    "failedToCreateSessionNoThreadId": "런타임이 새 세션 id를 반환하지 않았습니다.",
    "failedToCreateSessionRuntimeRecovering": "이 세션을 생성하는 동안 런타임이 재시작 중이었습니다. 앱이 이미 한 번 재시도했습니다. 작업 공간을 재연결하고 다시 시도하세요.",
    "reconnectAndRetryCreateSession": "재연결 후 생성 재시도",
    "reconnectingAndRetryingCreateSession": "재연결하여 생성을 재시도하는 중...",
    "runtimeRecovered": "런타임이 복구되었습니다.",
    "retryingCreateSessionAfterRecovery": "세션 생성을 재시도하는 중...",
    "cliNotFound": "Claude Code CLI와 Codex CLI를 모두 찾을 수 없습니다. 둘 중 하나를 설치하세요.",
    "cliNotFoundHint": "Claude Code 설치: curl -fsSL https://claude.ai/install.sh | bash\nCodex 설치: npm install -g @openai/codex",
    "codexCliNotFound": "Codex CLI를 찾을 수 없습니다. Codex를 설치하고 `codex`가 PATH에 있는지 확인하세요.",
    "couldntOpenWorkspace": "작업 공간을 열 수 없습니다",
    "dismissError": "오류 닫기"
  }
};

export default errors;
