// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/homeChat.ts; keys mirror the English source.
const homeChat = {
  "homeChat": {
    "badge": "워크스페이스 연동 채팅 홈",
    "minimalTitle": "무엇이든 만들기",
    "announcementTag": "새 소식",
    "announcementText": "랜딩 템플릿, 워크플로 카드, 시작 프롬프트를 살펴보세요",
    "announcementAction": "둘러보기",
    "title": "ccgui Agent로 일을 더 쉽게",
    "titleLineOne": "Enter를 누르세요",
    "titleLineTwo": "앱을 더 빠르게 만드세요",
    "subtitle": "익숙한 작성기를 그대로 유지하면서 더 강력한 랜딩 리듬을 더하고, 준비 과정의 마찰을 줄여 실제 실행으로 넘어가세요.",
    "promptPlaceholder": "목표를 설명하세요. 예: 이 저장소의 릴리스 노트를 생성하고 리스크 점검을 포함하세요.",
    "pathResolving": "기본 프로젝트 경로를 확인하는 중...",
    "workspaceSearchPlaceholder": "프로젝트 검색",
    "addWorkspaceAction": "새 프로젝트 추가",
    "workspaceNoMatch": "프로젝트를 찾을 수 없습니다",
    "loadingRecentAgents": "최근 작업 불러오는 중",
    "recentConversations": "최근 대화",
    "quickActions": "빠른 작업",
    "placeholderHint": "이 진입점들은 현재 시각적 자리 표시자입니다.",
    "placeholderSelected": "{{label}}은(는) 곧 제공될 예정입니다.",
    "seeAll": "모두 보기",
    "navPrev": "이전 카드",
    "navNext": "다음 카드",
    "comingSoon": "곧 제공 예정",
    "tabs": {
      "templates": "템플릿",
      "workflows": "워크플로"
    },
    "quick": {
      "plan": "브리프로 계획하기",
      "doc": "문서",
      "release": "릴리스 노트",
      "review": "저장소 검토",
      "spec": "사양 초안"
    },
    "cards": {
      "website": {
        "title": "웹사이트 출시 키트",
        "description": "완성도 높은 출시 페이지를 위한 히어로 레이아웃, 구조, 시작 문구."
      },
      "creator": {
        "title": "크리에이터 대시보드",
        "description": "콘텐츠, 트래픽, 프롬프트를 위한 분석 중심 관제실."
      },
      "audio": {
        "title": "오디오 랜딩",
        "description": "음악, 팟캐스트, 미디어 출시를 위한 부드러운 그라데이션과 강렬한 지표."
      },
      "editorial": {
        "title": "에디토리얼 매니페스토",
        "description": "캠페인, 선언문, 브랜드 쇼케이스를 위한 포스터 같은 타이포그래피."
      },
      "release": {
        "title": "릴리스 체크리스트",
        "description": "변경, 검증, 노트, 롤아웃 후속 조치를 위한 단계별 인수인계."
      },
      "research": {
        "title": "리서치 스프린트",
        "description": "질문을 모으고 자료를 조사하여 다음 행동으로 종합하세요."
      },
      "debug": {
        "title": "디버그 데스크",
        "description": "로그를 분류하고 회귀를 좁히며 검증된 수정을 문서화하세요."
      },
      "content": {
        "title": "콘텐츠 파이프라인",
        "description": "일관된 체크포인트로 브리프, 초안, 검토, 게시를 진행하세요."
      }
    }
  }
};

export default homeChat;
