// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/home.ts; keys mirror the English source.
const home = {"home":{"welcome":"환영합니다","subtitle":"오늘은 무엇을 만들어 볼까요?","latestActivity":"최근 대화","noActivity":"최근 대화 없음","latestAgents":"최근 Agent","agentReplied":"Agent가 응답했습니다.","running":"실행 중","loadingAgents":"Agent 불러오는 중","noAgentActivity":"아직 Agent 활동이 없습니다","startThreadToSee":"스레드를 시작하면 최신 응답이 여기에 표시됩니다.","openProject":"프로젝트 추가","addWorkspace":"프로젝트 추가","usageSnapshot":"사용량 스냅샷","refreshUsage":"사용량 새로고침","workspace":"워크스페이스","allWorkspaces":"모든 워크스페이스","view":"보기","tokens":"Token","time":"시간","last7Days":"지난 7일","last30Days":"지난 30일","cacheHitRate":"캐시 적중률","peakDay":"최고 사용일","agentTime":"Agent 시간","runs":"실행","avg":"평균","total":"합계","day":"일","noUsageData":"아직 사용량 데이터가 없습니다","runCodexSession":"Codex 세션을 실행하면 로컬 사용량 추적이 시작됩니다.","topModels":"상위 모델","noModelsYet":"아직 모델이 없습니다","updated":"업데이트됨"}};

export default home;
