// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/kanban.ts; keys mirror the English source.
const kanban = {
  "kanban": {
    "mode": {
      "chat": "채팅 모드",
      "chatShort": "채팅",
      "kanban": "칸반 모드",
      "kanbanShort": "보드"
    },
    "columns": {
      "todo": "할 일",
      "inprogress": "진행 중",
      "testing": "검토 중",
      "done": "완료"
    },
    "projects": {
      "title": "프로젝트",
      "subtitle": "작업을 관리할 워크스페이스를 선택하세요",
      "empty": "아직 워크스페이스가 없습니다",
      "emptyHint": "워크스페이스를 추가하여 작업 관리를 시작하세요",
      "taskCount": "작업 {{count}}개"
    },
    "board": {
      "back": "뒤로",
      "backActions": "뒤로 가기 작업",
      "backToPanels": "패널로 돌아가기",
      "backToChat": "채팅으로 돌아가기",
      "addTask": "추가",
      "searchPlaceholder": "검색...",
      "toggleGitPanel": "Git 변경"
    },
    "task": {
      "createTitle": "작업 생성",
      "create": "생성",
      "titlePlaceholder": "작업 제목 입력",
      "descPlaceholder": "작업을 설명하세요...",
      "notInstalled": "설치되지 않음",
      "noModels": "모델 없음",
      "addImage": "이미지 추가",
      "start": "시작",
      "menu": "작업 메뉴",
      "edit": "편집",
      "editTitle": "작업 편집",
      "update": "업데이트",
      "dragToStart": "시작하려면 이 작업을 \"진행 중\"으로 끌어다 놓으세요",
      "delete": "삭제",
      "cancelSchedule": "일정 취소",
      "pauseSchedule": "일정 일시정지",
      "resumeSchedule": "일정 재개",
      "blockTask": "차단됨으로 표시",
      "linked": "연결됨",
      "processing": "처리 중...",
      "generateTitle": "제목 생성",
      "generateTitleFailed": "제목 생성에 실패했습니다",
      "generateTitleTimeout": "제목 생성이 시간 초과되었습니다. 다시 시도하세요",
      "schedule": {
        "modeLabel": "일정",
        "manual": "수동",
        "once": "한 번 실행",
        "recurring": "반복",
        "runAt": "실행 시각",
        "every": "매",
        "minutes": "분",
        "hours": "시간",
        "days": "일",
        "weeks": "주",
        "executionModeLabel": "실행",
        "sameThread": "같은 스레드에서 실행",
        "newThread": "실행마다 새 스레드 시작",
        "maxRounds": "라운드 제한 (1-50)",
        "resultPassing": "결과 전달",
        "passResult": "이전 결과 전달",
        "blockResult": "결과 전달 안 함",
        "onceBadge": "일회성",
        "recurringBadge": "예약됨",
        "schedulerBadge": "스케줄러",
        "runningBadge": "실행 중",
        "scheduledBadge": "예약됨",
        "onceOverdueBadge": "실행 놓침"
      },
      "chain": {
        "upstreamLabel": "상위 작업",
        "none": "없음",
        "badge": "연결됨"
      },
      "group": {
        "recurring": "반복 실행 그룹",
        "chain": "연결된 작업 그룹",
        "count": "{{count}}개 항목",
        "bulkComplete": "일괄 완료",
        "bulkCompleteConfirm": "이 그룹의 작업 {{count}}개를 일괄 완료할까요?",
        "loadMore": "{{count}}개 더 불러오기",
        "remaining": "{{count}}개 남음"
      },
      "snapshot": {
        "badge": "스냅샷 준비됨"
      },
      "latestRunSummary": {
        "ariaLabel": "최근 실행 요약"
      },
      "blocked": "차단됨: {{reason}}",
      "detail": {
        "runAt": "{{time}}에 실행",
        "every": "매 {{interval}} {{unit}}마다",
        "countdown": "남은 시간 {{time}}",
        "sameThread": "같은 스레드",
        "newThread": "새 스레드",
        "runIndex": "실행 #{{index}}",
        "headCode": "#{{code}}",
        "groupCode": "#{{code}}",
        "chainOrder": "단계 #{{order}}",
        "rounds": "라운드 {{current}}/{{max}}",
        "resultPassed": "전달됨",
        "resultBlocked": "전달 안 됨",
        "timeRange": "{{start}} - {{end}}",
        "startedAt": "시작 {{time}}",
        "finishedAt": "완료 {{time}}"
      },
      "blockedReason": {
        "nonReentrant": "작업이 이미 실행 중입니다",
        "missedOnceWindow": "일회성 실행 시간대를 놓쳤습니다",
        "invalidRecurringRule": "잘못된 반복 규칙",
        "skippedMissedRecurringWindows": "놓친 반복 실행 시간대를 건너뛰었습니다",
        "maxRoundsReached": "라운드 제한에 도달하여 자동 완료되었습니다",
        "missingUpstreamSnapshot": "상위 결과 스냅샷이 없습니다",
        "downstreamNotTodo": "하위 작업이 할 일 상태가 아닙니다",
        "downstreamHasSchedule": "하위 작업에 독립 일정이 있습니다",
        "chainRequiresHeadTrigger": "연결된 작업은 헤드 작업에 의해 트리거되어야 합니다",
        "chainRequiresHeadTriggerWithOrder": "연결된 작업은 헤드 단계(#{{headOrder}})에 의해 자동 트리거되어야 합니다. 현재 단계는 #{{currentOrder}}입니다",
        "chainRequiresExecutionCompletion": "연결된 작업은 검토/완료로 넘어가기 전에 진행 중 실행을 완료해야 합니다",
        "chainCompletedCannotBackToTodo": "완료된 연결 작업은 할 일로 되돌릴 수 없습니다",
        "chainCompletedStatusLocked": "완료된 연결 작업은 다른 상태로 이동할 수 없습니다",
        "scheduledTriggerBlocked": "작업 실행 중에는 반복 트리거를 건너뜁니다",
        "dragIntoChainGroupBlocked": "연결되지 않은 작업은 연결된 그룹으로 끌어다 놓을 수 없습니다",
        "manualBlocked": "수동으로 차단됨",
        "manualCancelled": "일정이 수동으로 취소되었습니다"
      },
      "validation": {
        "generic": "잘못된 작업 구성입니다. 수정한 후 다시 시도하세요.",
        "scheduleTodoOnly": "할 일 상태의 작업만 일정을 설정할 수 있습니다.",
        "invalidOnceTime": "유효한 일정 시간을 선택하세요.",
        "invalidRecurringInterval": "반복 간격은 0보다 커야 합니다.",
        "invalidRecurringRule": "다음 반복 시간을 계산할 수 없습니다.",
        "chainRequiresTodoTask": "할 일 상태의 작업만 작업 체인에 참여할 수 있습니다.",
        "downstreamCannotBeScheduled": "하위 작업은 독립 일정을 유지할 수 없습니다.",
        "chainSelfCycle": "작업은 자기 자신을 상위로 사용할 수 없습니다.",
        "chainPreviousNotFound": "선택한 상위 작업을 찾을 수 없습니다.",
        "chainRequiresTodoUpstream": "상위 작업은 할 일 상태를 유지해야 합니다.",
        "chainMultiDownstream": "선택한 상위 작업에는 이미 하위 작업이 있습니다.",
        "chainCycleDetected": "체인 순환이 감지되었습니다. 다른 상위 작업을 선택하세요."
      }
    },
    "conversation": {
      "close": "닫기"
    },
    "panel": {
      "subtitle": "작업을 관리할 패널을 선택하세요",
      "create": "새 패널",
      "namePlaceholder": "패널 이름 입력",
      "empty": "아직 패널이 없습니다. 하나 만들어 시작하세요.",
      "menu": "패널 메뉴",
      "rename": "이름 변경",
      "delete": "삭제",
      "deleteConfirmTitle": "삭제 확인",
      "deleteConfirmMessage": "패널 \"{{name}}\"을(를) 삭제하시겠어요? 이 패널의 작업 {{count}}개도 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.",
      "cancel": "취소",
      "confirmDelete": "삭제",
      "searchPanels": "패널 검색...",
      "noPanelsFound": "패널을 찾을 수 없습니다"
    },
    "workspace": {
      "searchWorkspaces": "워크스페이스 검색...",
      "noWorkspacesFound": "워크스페이스를 찾을 수 없습니다"
    },
    "composer": {
      "relatedPanels": "연결된 프로젝트 패널",
      "openPanel": "연결된 패널 열기",
      "empty": "연결된 패널 없음",
      "count": "{{count}}개 패널",
      "clear": "선택 해제",
      "more": "더 보기",
      "collapse": "접기",
      "link": "연결",
      "contextModeLabel": "컨텍스트",
      "contextModeNew": "새 스레드",
      "contextModeInherit": "현재 상속"
    }
  }
};

export default kanban;
