// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/layout.ts; keys mirror the English source.
const layout = {"layout":{"resizeGitHistoryPanel":"Git 히스토리 패널 크기 조정","resizeSidebar":"사이드바 크기 조정","resizeRightPanel":"오른쪽 패널 크기 조정","resizeEditorSplit":"에디터 분할 크기 조정","resizeNoteCardsSplit":"대화 및 노트 분할 크기 조정","resizePlanPanel":"플랜 패널 크기 조정","resizeRuntimeConsole":"실행 콘솔 크기 조정","resizeProjects":"프로젝트 크기 조정"}};

export default layout;
