// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/models.ts; keys mirror the English source.
const models = {
  "models": {
    "selectModel": "모델 선택",
    "addModel": "모델 추가",
    "refreshConfig": "설정 새로고침",
    "refreshingConfig": "새로고침 중...",
    "refreshConfigFailed": "새로고침 실패: {{message}}",
    "claude": {},
    "codex": {
      "gpt56sol": {
        "label": "gpt-5.6-sol",
        "description": "최신 프론티어 에이전트 코딩 모델."
      },
      "gpt56terra": {
        "label": "gpt-5.6-terra",
        "description": "일상 작업을 위한 균형 잡힌 에이전트 코딩 모델."
      },
      "gpt56luna": {
        "label": "gpt-5.6-luna",
        "description": "빠르고 경제적인 에이전트 코딩 모델."
      },
      "gpt55": {
        "label": "gpt-5.5",
        "description": "복잡한 코딩, 연구, 실무 작업을 위한 프론티어 모델."
      },
      "gpt54": {
        "label": "gpt-5.4",
        "description": "일상 코딩에 강력한 모델."
      },
      "gpt54mini": {
        "label": "gpt-5.4-mini",
        "description": "간단한 코딩 작업을 위한 작고 빠르며 비용 효율적인 모델."
      },
      "gpt53codex": {
        "label": "gpt-5.3-codex",
        "description": "코딩에 최적화된 모델."
      },
      "gpt53codexSpark": {
        "label": "gpt-5.3-codex-spark",
        "description": "초고속 코딩 모델."
      },
      "gpt52": {
        "label": "gpt-5.2",
        "description": "전문 작업과 장기 실행 에이전트에 최적화됨."
      }
    }
  }
};

export default models;
