// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/modes.ts; keys mirror the English source.
const modes = {
  "modes": {
    "selectMode": "모드 선택",
    "default": {
      "label": "기본 모드",
      "tooltip": "표준 권한 동작",
      "description": "각 작업에 대해 수동 확인이 필요하며, 신중한 사용에 적합합니다"
    },
    "plan": {
      "label": "계획 모드",
      "tooltip": "계획 모드 - 읽기 전용 분석",
      "description": "읽기 전용 도구만 사용하며, 사용자 승인을 위한 계획을 생성합니다"
    },
    "acceptEdits": {
      "label": "에이전트 모드",
      "tooltip": "파일 편집 자동 수락",
      "description": "파일 생성/편집을 자동으로 수락하여 확인 단계를 줄입니다"
    },
    "bypassPermissions": {
      "label": "자동 모드",
      "tooltip": "모든 권한 검사 우회",
      "description": "완전 자동화되어 모든 권한 검사를 우회합니다 [주의해서 사용]"
    }
  }
};

export default modes;
