// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/panels.ts; keys mirror the English source.
const panels = {
  "panels": {
    "radar": "레이더",
    "git": "Git",
    "files": "파일",
    "search": "검색",
    "notes": "노트",
    "memory": "메모리",
    "projectMap": "프로젝트 맵",
    "intentCanvas": "인텐트 캔버스",
    "activity": "활동",
    "prompts": "프롬프트"
  }
};

export default panels;
