// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/plan.ts; keys mirror the English source.
const plan = {"plan":{"title":"계획","noPlan":"사용 가능한 계획이 없습니다","steps":"단계","completed":"완료됨","inProgress":"진행 중","pending":"대기 중"}};

export default plan;
