// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "프롬프트 개선 도구",
    "tooltip": "프롬프트 개선",
    "tooltipFull": "더 많은 컨텍스트를 제공하고 Agent 응답을 개선하도록 프롬프트를 다시 작성합니다",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "프롬프트 개선 중...",
    "readyToEnhance": "제공자, 모델, 시간 초과를 설정한 다음 개선을 시작하세요.",
    "runSettings": "개선 설정",
    "provider": "제공자",
    "model": "모델",
    "noModel": "모델 없음",
    "timeoutSeconds": "시간 초과 (초)",
    "runEnhancement": "개선 시작",
    "originalPrompt": "원본 프롬프트",
    "enhancedPrompt": "개선된 프롬프트",
    "useEnhanced": "개선본 사용",
    "keepOriginal": "원본 유지",
    "enhanceFailed": "프롬프트 개선에 실패했습니다",
    "emptyPrompt": "먼저 프롬프트를 입력하세요",
    "copyEnhanced": "개선본 복사"
  }
};

export default promptEnhancer;
