// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {"reasoning":{"title":"추론 깊이 선택","default":"기본값","claudeDefault":"기본값","defaultDescription":"엔진 기본 추론 동작 사용","low":{"label":"낮음","description":"기본 추론으로 빠른 응답"},"medium":{"label":"중간","description":"균형 잡힌 사고 (기본값)"},"high":{"label":"높음","description":"복잡한 작업을 위한 심층 추론"},"xhigh":{"label":"매우 높음","description":"매우 높은 추론 깊이"},"max":{"label":"최대","description":"최대 추론 깊이"},"ultra":{"label":"울트라","description":"자동 작업 위임을 포함한 최대 추론"}}};

export default reasoning;
