// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/searchPalette.ts; keys mirror the English source.
const searchPalette = {
  "searchPalette": {
    "placeholder": "파일, 칸반, 스레드, 메시지, 스킬, 명령 검색...",
    "placeholderFiltered": "{{content}} 검색...",
    "inputAria": "검색 입력",
    "scope": "범위",
    "content": "내용",
    "current": "현재",
    "global": "전역",
    "currentWorkspace": "현재 워크스페이스",
    "allWorkspaces": "모든 워크스페이스",
    "noResults": "결과 없음",
    "noResultsHint": "파일 경로, 작업 제목, 스레드 제목, 메시지 텍스트, 스킬 이름 또는 명령 이름의 키워드로 시도해 보세요.",
    "fileIndexLoading": "파일 인덱스를 완성하는 중...",
    "fileIndexPartial": "파일 인덱스가 불완전하여 일부 파일이 누락될 수 있습니다.",
    "fileIndexError": "파일 인덱스를 불러오지 못했습니다. 검색을 다시 열어 재시도하세요.",
    "navigate": "이동",
    "open": "열기",
    "close": "닫기",
    "projectTag": "프로젝트",
    "typeTag": "유형",
    "sourceTag": "소스",
    "locationTag": "위치",
    "typeAction": "작업",
    "typeFile": "파일",
    "typeKanban": "칸반",
    "typeThread": "스레드",
    "typeMessage": "메시지",
    "typeHistory": "히스토리",
    "typeSkill": "스킬",
    "typeCommand": "명령",
    "sourceActions": "앱 작업",
    "sourceFiles": "파일 인덱스",
    "sourceKanban": "칸반 데이터",
    "sourceThreads": "스레드 제목",
    "sourceMessages": "메시지 내용",
    "sourceHistory": "입력 히스토리",
    "sourceSkills": "스킬 목록",
    "sourceCommands": "명령 목록",
    "contentAll": "전체",
    "contentActions": "작업",
    "contentFiles": "파일",
    "contentKanban": "칸반",
    "contentThreads": "스레드",
    "contentMessages": "메시지",
    "contentHistory": "히스토리",
    "contentSkills": "스킬",
    "contentCommands": "명령"
  }
};

export default searchPalette;
