// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/tabbar.ts; keys mirror the English source.
const tabbar = {
  "tabbar": {
    "projects": "프로젝트",
    "codex": "Codex",
    "spec": "Spec",
    "git": "Git",
    "log": "로그",
    "primaryNavigation": "기본 탐색",
    "workspaceNavigation": "워크스페이스 탐색"
  }
};

export default tabbar;
