// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/taskCenter.ts; keys mirror the English source.
const taskCenter = {
  "taskCenter": {
    "title": "작업 센터",
    "eyebrow": "Agent 실행",
    "workspaceHero": "지금 주의가 필요한 실행",
    "statusFilter": "상태",
    "engineFilter": "엔진",
    "filterAll": "전체",
    "empty": "아직 작업 실행이 없습니다",
    "summary": "전체 {{total}}개 실행 중 {{attention}}개가 주의를 요합니다",
    "openedFromProjectMap": "프로젝트 맵 작업 대기열에서 연결된 실행을 열었습니다. 이 페이지는 실제 TaskRun 세부 정보를 보여줍니다. 대화 작업이 나타나지 않으면 이 실행은 아직 실제 세션에 연결되지 않은 것입니다.",
    "trigger": "트리거",
    "updatedAt": "업데이트됨",
    "currentStep": "현재 단계",
    "latestOutput": "최신 출력",
    "diagnostics": "진단",
    "artifacts": "아티팩트",
    "browserEvidence": "브라우저 증거",
    "unavailable": "사용 불가",
    "noArtifacts": "아직 아티팩트 없음",
    "noBrowserEvidence": "연결된 브라우저 증거 없음",
    "browserEvidenceCandidates": "후보",
    "source": {
      "kanban": "칸반",
      "orchestration": "오케스트레이션"
    },
    "browserEvidenceState": {
      "available": "사용 가능",
      "stale": "오래됨",
      "expired": "만료됨",
      "degraded": "성능 저하",
      "deleted": "삭제됨",
      "unsupported": "지원 안 됨"
    },
    "status": {
      "queued": "대기 중",
      "planning": "계획 중",
      "running": "실행 중",
      "waiting_input": "입력 대기 중",
      "blocked": "차단됨",
      "failed": "실패",
      "completed": "완료됨",
      "canceled": "취소됨"
    },
    "action": {
      "openConversation": "대화 열기",
      "openOrchestrationTask": "오케스트레이션 작업 열기",
      "retry": "다시 시도",
      "resume": "재개",
      "cancel": "취소",
      "fork": "실행 분기"
    },
    "nextStep": {
      "monitor": "이 실행은 아직 진행 중입니다. 현재 단계를 모니터링하거나 필요 시 취소하세요.",
      "openConversation": "다음으로 연결된 대화를 열어 입력을 제공하거나 최신 출력을 확인하세요.",
      "resume": "이 실행이 차단되었습니다. 현재 경로를 계속하려면 먼저 재개하세요.",
      "retry": "이 실행이 실패했습니다. 다음으로 다시 시도하거나 실패 요약을 확인하세요.",
      "wait": "지금은 조치가 필요 없습니다. 실행이 안정될 때까지 기다리세요.",
      "review": "먼저 진단과 아티팩트를 검토한 다음 다음 단계를 결정하세요.",
      "fork": "현재 결과에서 새 실행을 분기하여 계속할 수 있습니다."
    }
  }
};

export default taskCenter;
