// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/terminal.ts; keys mirror the English source.
const terminal = {"terminal":{"newTab":"새 탭","closeTab":"탭 닫기","clear":"지우기","title":"터미널","tabTitle":"터미널 {{number}}","claudeTuiResumeTitle":"Claude TUI","sendSelectionToComposer":"작성기로 보내기"}};

export default terminal;
