// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/threadCompletion.ts; keys mirror the English source.
const threadCompletion = {"threadCompletion":{"title":"세션 완료됨","project":"프로젝트","session":"세션"}};

export default threadCompletion;
