// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/time.ts; keys mirror the English source.
const time = {
  "time": {
    "justNow": "방금",
    "minuteAgo": "{{count}}분 전",
    "minutesAgo": "{{count}}분 전",
    "hourAgo": "{{count}}시간 전",
    "hoursAgo": "{{count}}시간 전",
    "dayAgo": "{{count}}일 전",
    "daysAgo": "{{count}}일 전",
    "weekAgo": "{{count}}주 전",
    "weeksAgo": "{{count}}주 전",
    "now": "지금",
    "shortSecondsAgo": "{{value}}초 전",
    "shortSecondsIn": "{{value}}초 후",
    "shortMinutesAgo": "{{value}}분 전",
    "shortMinutesIn": "{{value}}분 후",
    "shortMinutes": "{{value}}분",
    "shortHours": "{{value}}시간",
    "shortDays": "{{value}}일",
    "shortWeeks": "{{value}}주",
    "shortMonths": "{{value}}개월",
    "shortYears": "{{value}}년"
  }
};

export default time;
