// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/update.ts; keys mirror the English source.
const update = {
  "update": {
    "title": "업데이트",
    "checkingForUpdates": "업데이트 확인 중...",
    "updateAvailable": "새 버전을 사용할 수 있습니다!",
    "upToDate": "최신 상태입니다.",
    "downloading": "업데이트 다운로드 중…",
    "installing": "업데이트 설치 중…",
    "restarting": "다시 시작 중…",
    "failed": "업데이트에 실패했습니다.",
    "downloaded": "다운로드됨",
    "releaseNotesTitle": "릴리스 노트",
    "releaseNotesLoading": "릴리스 노트 불러오는 중…",
    "releaseNotesLoadFailed": "릴리스 노트를 불러오지 못했습니다.",
    "releaseNotesEmpty": "아직 릴리스 노트가 없습니다.",
    "releaseNotesOpenInGitHub": "GitHub에서 보기",
    "releaseNotesPrev": "이전",
    "releaseNotesNext": "다음",
    "releaseNotesPage": "{{current}} / {{total}}",
    "releaseNotesEnglish": "English:",
    "releaseNotesChinese": "中文："
  }
};

export default update;
