// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/usage.ts; keys mirror the English source.
const usage = {
  "usage": {
    "sessionReset": "세션 재설정",
    "weeklyReset": "주간 재설정",
    "credits": "크레딧",
    "used": "사용됨",
    "remaining": "남음",
    "unlimited": "무제한"
  }
};

export default usage;
